### ISSUE TITLE
Where would I find the "Business Central administration shell"

### ISSUE THREAD

**Issue by DaveBoehmPBSI** [MicrosoftDocs/dynamics365smb-docs#10]
I just read through this section concerning the use of a cmdlet.  I'm guessing this pertains strictly to the "on-premises" version of Business Central (i.e. "NAV").  Somehow this page made it into the Business Central online documentation.  I'm guessing it doesn't belong here.  If I am wrong, please kindly tell me where I would find the "Business Central administration shell".  I have a subscription to Business Central (formerly known as "Dynamics 365 for Finance and Operations--Business Edition").  I'm not aware of an "administration shell" or access to any "cmdlets".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afd26be7-3f4f-3899-9b97-b711391ef190
* Version Independent ID: 76af726b-a591-678e-0264-25424a7ea2fd
* Content: [How to Configure New Companies using a Cmdlet - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/admin-how-to-configure-new-companies-using-a-cmdlet)
* Content Source: [business-central/admin-how-to-configure-new-companies-using-a-cmdlet.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-how-to-configure-new-companies-using-a-cmdlet.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback - True. This is not possible in Business Central. I have removed the topic and involved references.
