### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-docs#100]
Inventory Posting Groups
"Define balance sheet inventory accounts". Where, exactly, on the Inventory Posting Groups setup page, would the balance sheet inventory accounts be defined?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae49cb5f-62a1-2c2c-455c-5062fb5f9ae1
* Version Independent ID: 9229c603-465e-a779-4b4b-1cd60cfb20b7
* Content: [Posting Group Setup - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-posting-groups)
* Content Source: [business-central/finance-posting-groups.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-posting-groups.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by SorenGP** [comment]
Thank you for the feedback. The paragraph has been updated as follows:
"Define inventory posting groups that you then assign to the relevant item accounts on the Inventory Posting Setup page. This way, when you post entries concerning an item, the system will post to the G/L account that is set up for the combination of inventory posting group and location that is linked to the item. Inventory posting groups also provide a good way to organize your inventory, so you can separate items by their posting group when you generate reports. Set these up on the Inventory Posting Groups page."
The update will be available within one week.
