### ISSUE TITLE
Übersetzung

### ISSUE THREAD

**Issue by m3koenig** [MicrosoftDocs/dynamics365smb-docs#102]
Hat das hier mal jemand auf Deutsch gelesen? Tut mir Leid aber das geht gar nicht. 
Die Seite auf English zu laden ist anscheinend auch nicht per Knopfdruck möglich.
Schade, ich hoffe das https://github.com/OpenLocalizationService da noch besser wird aber bis dahin wäre es toll wenn dies hier jemand überarbeiten könnte :)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 806624da-261d-1922-c480-1cc0ca9787f3
* Version Independent ID: 115d509c-f3b8-588b-aff8-a41b8877cbf7
* Content: [Intelligente Cloud - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/about-intelligent-cloud)
* Content Source: [business-central/about-intelligent-cloud.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/about-intelligent-cloud.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bmeier94
* Microsoft Alias: **bmeier**

**Comment by edupont04** [comment]
Hallo m3koenig,

Bitte vezeihen Sie, dass ich in English antworte.
Your feedback can been sent to the translation supplier, and they are processing it accordingly.
