### ISSUE TITLE
Description Fixed Share

### ISSUE THREAD

**Issue by TinaSchneider90** [MicrosoftDocs/dynamics365smb-docs#104]
How can the position "Fixed Share" be used in the cost type card? I couldn't find any description therefore. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd43a98a-aef8-c77d-d1da-ef559fa95d81
* Version Independent ID: 1de459ae-e9df-49fd-8980-5c804dff3f43
* Content: [Setting Up Cost Accounting - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-set-up-cost-accounting)
* Content Source: [business-central/finance-set-up-cost-accounting.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-set-up-cost-accounting.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback. Fixed Share is a free-text field where the user can enter own info about the selected cost classification. It is a misleading name, so I will request to Development that it is renamed to "Classification Note".
