### ISSUE TITLE
Business Central License Guide Link

### ISSUE THREAD

**Issue by christianjroach** [MicrosoftDocs/dynamics365smb-docs#108]
Hello, I believe the related link to the Business Central Licensing Guide is showing an older version (July) rather than the latest version.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5acaac44-d784-aa74-0111-1b40a58ef4f2
* Version Independent ID: 7fda754a-773d-4ac2-8db4-7b55e57f2534
* Content: [Choosing the User Experience to Show or Hide Advanced Features - Business Central](https://docs.microsoft.com/en-ca/dynamics365/business-central/ui-experiences)
* Content Source: [business-central/ui-experiences.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-experiences.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Christian,

Oops, you're right! We're working on getting a new link and will get that updated on this page later today. This is the direct link: https://mbs.microsoft.com/Files/public/365/Dynamics365BusinessCentralLicensingGuide.pdf

**Comment by edupont04** [comment]
Updated: https://docs.microsoft.com/en-us/dynamics365/business-central/ui-experiences
