### ISSUE TITLE
Doc describes config functionality, missing in the product

### ISSUE THREAD

**Issue by reiniroosh** [MicrosoftDocs/dynamics365smb-docs#11]
"The administrator configures the user interface for multiple users by customizing the user interface for a profile that the users are assigned to."
Based on giving it a try and communicating with a MSFT rep it doesn't sound like this is true.
You may want to update the doc to remove that or clarify.
How can an admin customize the user interface that users are assigned to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbc54780-19ba-4d44-cd54-3435966b1293
* Version Independent ID: 1417b68c-68fd-9f06-fafa-854edc3c1e75
* Content: [Manage users and roles - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-users-profiles-roles)
* Content Source: [business-central/admin-users-profiles-roles.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-users-profiles-roles.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for your feedback! And yes, it's a mistake that we left that sentence in there since even administrators cannot currently create or edit profiles. We'll update the article in our next update within a day or two.

**Comment by edupont04** [comment]
The article has been updated, so I'm closing the issue. Feel free to resubmit if you're not happy with the changes. Once again, thank you for your feedback!
