### ISSUE TITLE
Explications ne correspondent pas à l'interface

### ISSUE THREAD

**Issue by Deeptnt** [MicrosoftDocs/dynamics365smb-docs#111]
Choisissez l'icône Page ou rapport pour la recherche, entrez Bons de commande, puis sélectionnez le lien associé dans Traitement des commandes.
Traitement des commandes n'existe pas comme lien.

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour docs.microsoft.com ➟ problème de liaison GitHub.*

* ID: 80f08e4f-318e-f833-dc53-b2ed2ee2faa9
* Version Independent ID: e3f5ed9b-7910-da4d-e99b-b8ed6e22eb23
* Content: [Procédure : configurer la taxe de service et la taxe d'achat - Business Central](https://docs.microsoft.com/fr-ca/dynamics365/business-central/localfunctionality/canada/how-to-set-up-use-tax-and-purchase-tax)
* Content Source: [business-central/LocalFunctionality/Canada/how-to-set-up-use-tax-and-purchase-tax.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Canada/how-to-set-up-use-tax-and-purchase-tax.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback. This has been fixed. The update will be available within one week.
