### ISSUE TITLE
Hard to understand

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-docs#112]
Hi Soren,
This page is quite hard to understand in the Spanish version.
In order to understand it correctly, I copied it into Word to fix it.
If you'd like a copy of my version, let me know,
Eyrún

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 8bff99ce-0eb4-dc83-651a-4264149482a8
* Version Independent ID: c0734280-1a93-336d-5132-5708492fd9ce
* Content: [Información general de los movimientos del grupo dimensiones - Business Central](https://docs.microsoft.com/es-es/dynamics365/business-central/design-details-dimension-set-entries-overview)
* Content Source: [business-central/design-details-dimension-set-entries-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-dimension-set-entries-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
I have forwarded this to MBSI (Business Central translation coordinators). 

Going forward, please report translation issues directly to MBSI as agreed (Private Conversation on Yammer). Do not report them through this documentation feedback mechanism.
