### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-docs#113]
"However, to preserve the ability of Business Central to rename a dimension and dimension value, table 348 Dimension Value is extended with an integer field of Dimension Value ID. This table converts the field pair Dimension and Dimension Value to an integer value. When you rename the dimension and dimension value, the integer value is not changed."

Table 348 = Dimension
Table 349 = Dimension Value
Both have a new field

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fa1c60c-f467-229b-7f28-c3b50a1c1287
* Version Independent ID: 631c9844-2971-824c-5b56-09e45d361121
* Content: [Design Details - Searching for Dimension Combinations - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-searching-for-dimension-combinations)
* Content Source: [business-central/design-details-searching-for-dimension-combinations.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-searching-for-dimension-combinations.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback - Changed to "table 349". The fix is available within one week.

**Comment by Bleika** [comment]
I would have understood that BOTH tables are affected:
If you rename a Dimension: T348
If you rename a Dimension Value: T349

Therefore I believe the phrase is incomplete

**Comment by SorenGP** [comment]
Only T349 has the **Dimension Value ID** field, which is used when renaming both a dimension (in T348) and a dimension value (in T349). 

The only error in the topic was that it said "table 348". This is changed to "table 349".
