### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-docs#114]
"Table 480 Dimension Set Entry is a new table. You cannot change this table. After data has been written to the table, you cannot delete or edit it. Deleting data requires that you check against all occurrences of the dimension set ID in the entire database, including partner solutions."
Conclusion: Can you or can't you delete data from this table??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec29b075-9cb9-9f87-c3d8-01d62a645b62
* Version Independent ID: 6be392af-271e-7b31-2e0a-f5c2493dc9b5
* Content: [Design Details - Table Structure - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-table-structure)
* Content Source: [business-central/design-details-table-structure.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-table-structure.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by Bleika** [comment]
"Table 482 Reclas. Dimension Set Buffer
Table 482 Reclas. Dimension Set Buffer is a new table. The table is used to edit a dimension set ID. It is required when you edit a dimension value code and a new dimension value code, for example, in the Item Reclas. Journal table."
Please correct me if I'm wrong, but as far as I understand, you cannot edit a dimension value code. Instead, you assign a new dimension value code.

**Comment by SorenGP** [comment]
Thank you for the feedback. The mentioned wording has been changed. The change will be available within one week.
