### ISSUE TITLE
What (version) is this document about???

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-docs#115]
Please revise this topic as it provides no help whatsoever for Business Central:

The "Modified Functions" part basically explains that the function CheckDimSetIDComb has taken over many tasks that were performed by several functions in the past:
Function Name	              Modification Description
CheckDimSetIDComb	      New function that substitutes the other check functions and takes a Dimension Set ID as an argument instead of a dimension table.

CheckDimSetIDComb           Delete. All usage should be changed to CheckDimSetIDComb.

A part from the obvious confusion about modified, new, delete and which function substitutes which, the most surrealist error is that "new function" CheckDimSetIDComb does not exist in COD408 in Business Central.
All the contrary, from reading this, one would expect CheckDimComb to have been deleted, but that one is found in COD408.

Limiting this topic to a list of what has been deleted is not a primary issue... the compiler will warn the developer anyhow. 
The reader expects to gain some insight into  the new version of COD408 as well as getting an idea of how to use the existing (new/modified) functions to upgrade/design code that deals with dimension management.

If this document is supposed to help developers I'd find it more logical to say:
Codeunit 408 has been completely redesigned so you must familiarize yourself with the most important functions (upgrading code from older versions will cause compilation errors):

Function Name       Function Purpose/Role/Use

Some have logical names that explain their purpose, like the following:

CheckBlockedDimAndValues
CheckDimIDComb
CheckDimIDConsistency
CheckDimValueAllowed
CheckDimValuePosting
CopyDimBufToDimSetEntry
CreateDimSetEntryFromDimValue
CreateDimSetIDFromDimBuf
CreateDimSetIDFromICDocDim
CreateDimSetIDFromICJnlLineDim
DefaultDimOnDelete
DefaultDimOnInsert
DefaultDimOnModify
GetCombinedDimensionSetID
GetDefaultDimID
GetDeltaDimSetID
GetDimensionSet
GetDimensionSetID
GetDimSetEntryDefaultDim
GetRecDefaultDimID
RenameDefaultDim
ShowDimensionSet

It would be helpful if there was some degree of explanation of the following (anything that starts with Add*,Create*,Edit*,Get*,Insert*,Update* is likely to be used in extension code):
AddDimSetIDtoTempEntry
AddFirstToTableIdArray
AddLastToTableIdArray
AddTempDimValueFromTotaling
ClearDimSetFilter
CreateDimForJobJournalLineWithHigherPriorities
CreateDimForPurchLineWithHigherPriorities
CreateDimForSalesLineWithHigherPriorities
DefaultDimInsertTempObject
DefaultDimObjectNoList
DefaultDimObjectNoWithGlobalDimsList
DefaultDimObjectNoWithoutGlobalDimsList
EditDimensionSet
EditDimensionSet2
EditReclasDimensionSet2
FillNormalFieldBuffer
FilterIncludesBlank
FindDimFieldInTable
GetConsolidatedDimFilterByDimFilter
GetDimSetFilter
GetDimSetIDsForBlank
GetDimSetIDsForFilter
GetDimValuesWithTotalings
GetShortcutDimensions
GetTableIDsForHigherPriorities
GetTempDimSetEntry
GlobalDimObjectNoList
InsertObject
IsDefaultDimTable
IsObsolete
KeyContainsOneCodeField
ParseDimParam
ResolveDimValueFilter
UpdateCostType
UpdateGenJnlLineDim
UpdateGenJnlLineDimFromCustLedgEntry
UpdateGenJnlLineDimFromVendLedgEntry
UpdateGlobalDimFromDimSetID
ValidateShortcutDimValues

The purpose/use of these new functions should definitely be explained:
CreateDimForJobJournalLineWithHigherPriorities
CreateDimForPurchLineWithHigherPriorities
CreateDimForSalesLineWithHigherPriorities
DefaultDimObjectNoWithGlobalDimsList
DefaultDimObjectNoWithoutGlobalDimsList
FillNormalFieldBuffer
FilterIncludesBlank
FindDimFieldInTable
GetConsolidatedDimFilterByDimFilter
GetDeltaDimSetID
GetTableIDsForHigherPriorities
InsertObject
IsDefaultDimTable
IsObsolete
KeyContainsOneCodeField
UpdateCostType
UpdateGenJnlLineDimFromCustLedgEntry
UpdateGenJnlLineDimFromVendLedgEntry

I'm sorry for ranting, but instead of a 2 minutes useful read I ended up spending 2 hours reading the new code itself to get a clue... Obviously, at some point, that must be done anyhow, but it would help if this topic highlighted which of the 115 library functions really deserve your attention...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d84352a-0e53-83d7-037e-1be40b475d10
* Version Independent ID: 9d2d17f8-f9c2-cc98-a2a8-ff3bd1a58286
* Content: [Design Details - Codeunit 408 Dimension Management - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-codeunit-408-dimension-management)
* Content Source: [business-central/design-details-codeunit-408-dimension-management.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-codeunit-408-dimension-management.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback. "Design Details: Dimension Set Entries" has been changed to describe the design in Business Central today as opposed to be a before-and-after account of a redesign that was made on Dynamics NAV 2013 R2 many years ago. The update will be available within one week.
