### ISSUE TITLE
Cannot find "Print Receipt on Giro" on the Document tab "Sales & Receivables Setup"

### ISSUE THREAD

**Issue by cghasvi** [MicrosoftDocs/dynamics365smb-docs#116]
Depreciated?
https://docs.microsoft.com/gl-es/dynamics-nav/deprecated-features-no?view=dynamicsnav-ps-2018

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c64c217e-3dfa-cc25-672d-080d46e9f2f8
* Version Independent ID: ff78d303-58b3-eac8-e4ab-fd435f2d9fbc
* Content: [How to Set Up KID Numbers on Sales Documents - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/norway/how-to-set-up-kid-numbers-on-sales-documents)
* Content Source: [business-central/LocalFunctionality/Norway/how-to-set-up-kid-numbers-on-sales-documents.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Norway/how-to-set-up-kid-numbers-on-sales-documents.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback. The description of Print Receipt on Giro field has been removed. The update will be available within one week.
