### ISSUE TITLE
Documentation is poor

### ISSUE THREAD

**Issue by AndyWorth** [MicrosoftDocs/dynamics365smb-docs#117]
So I am on the Bank Account Card of Dynamics 365 BC. and the field prompt is Bank Acc. Posting Grou .. And I hover to get a better explanation, click on Learn More and I don't learn anything more

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44d97463-2335-1845-83ac-c2e0fce738cc
* Version Independent ID: 5eb8c4ab-0bb7-27f8-9ac6-d8b25ebd45d5
* Content: [Set Up Bank Accounts - Business Central](https://docs.microsoft.com/en-GB/dynamics365/business-central/bank-how-setup-bank-accounts)
* Content Source: [business-central/bank-how-setup-bank-accounts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/bank-how-setup-bank-accounts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
The tooltip for the Bank Acc. Posting Group field will be improved to say: "Specifies a code for the G/L account that transactions for this bank account are posted to."

In addition, in the discussed topic, a link has been added to https://docs.microsoft.com/en-us/dynamics365/business-central/finance-posting-groups.
