### ISSUE TITLE
Please update documentation for OIOUBL extension

### ISSUE THREAD

**Issue by MortenRa** [MicrosoftDocs/dynamics365smb-docs#118]
Hi,

Seems like you are refering to field EAN No. but that field do not exist in BC according to your source code this is the GLN field, please update you documentation to reflect this correctly for both previous and new version of NAV/BC 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e58ae01-70dc-bd0c-4399-fb07a351f3dc
* Version Independent ID: d2233332-b696-c633-9765-503db1e3700f
* Content: [How to Set Up Customers for OIOUBL - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/denmark/how-to-set-up-customers-for-oioubl)
* Content Source: [business-central/LocalFunctionality/Denmark/how-to-set-up-customers-for-oioubl.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Denmark/how-to-set-up-customers-for-oioubl.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback. This has been fixed. The update will be available within one week.
