### ISSUE TITLE
Income Stmt. Bal. Acc. does not exist on General Fast Tab in Business Central

### ISSUE THREAD

**Issue by hldavids** [MicrosoftDocs/dynamics365smb-docs#12]
Are you then not allowed to have multiple retained earnings accounts in Business Central?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ce81758-a039-ef6d-5f39-c0a4c6f58b08
* Version Independent ID: 911e4550-454d-101f-99f7-24eec4cc88b9
* Content: [How to Set Up and Close Income Statement Balances - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/spain/how-to-set-up-and-close-income-statement-balances)
* Content Source: [business-central/LocalFunctionality/Spain/how-to-set-up-and-close-income-statement-balances.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Spain/how-to-set-up-and-close-income-statement-balances.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Sorry for the delay in getting back to you. I hope you found an answer to your question in the Business Central community (https://community.dynamics.com/business/f/758) or suggested it as a feature in Ideas (https://experience.dynamics.com/ideas/list/?forum=e288ef32-82ed-e611-8101-5065f38b21f1)
