### ISSUE TITLE
Minor inconsistencies

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/dynamics365smb-docs#120]
In section "Setting Options and Filters":

"For example, in the illustration above, there is a single filter that will create report for the customer whose No. is equal to 01121212."
&gt;&gt; The value "01121212" is not visible in the illustration.

"You can add more filters by setting the Add boxes."
&gt;&gt; Either the text should say "And", or the illustration should show "Add"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05dc91a6-3e9f-fde9-01f2-355fe8ca862d
* Version Independent ID: 71a37002-4f2e-d42e-b21f-eb3cc6cf23e8
* Content: [Scheduling a Report to Run at a Specific Date and Time - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-work-report)
* Content Source: [business-central/ui-work-report.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-work-report.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SorenGP** [comment]
Thank you for the feedback. The inconsistencies have been fixed. The update will be available within one week.
