### ISSUE TITLE
Page title

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/dynamics365smb-docs#121]
The page title (as displayed in the browser tab),
it should be "Working with Reports" instead of "Scheduling a Report to Run..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05dc91a6-3e9f-fde9-01f2-355fe8ca862d
* Version Independent ID: 71a37002-4f2e-d42e-b21f-eb3cc6cf23e8
* Content: [Scheduling a Report to Run at a Specific Date and Time - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-work-report)
* Content Source: [business-central/ui-work-report.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-work-report.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SorenGP** [comment]
Thank you for the feedback. The topic title has been changed. The update will be available within one week.
