### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/dynamics365smb-docs#122]
In section "Previewing a report" / "Select text" :

"You can the paste the selected text where ever you want it."

&gt;&gt; Should be "You can then paste the selected text wherever you want it."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05dc91a6-3e9f-fde9-01f2-355fe8ca862d
* Version Independent ID: 71a37002-4f2e-d42e-b21f-eb3cc6cf23e8
* Content: [Scheduling a Report to Run at a Specific Date and Time - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-work-report)
* Content Source: [business-central/ui-work-report.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-work-report.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SorenGP** [comment]
Thank you for the feedback. The typo has been fixed. The update will be available within one week.
