### ISSUE TITLE
Minor flaw

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/dynamics365smb-docs#123]
In introduction, paragraph 3 :

"A Business Central can be set up with multiple report layouts,"

&gt;&gt; The word "report" is missing
it should be "A Business Central report can be set up with multiple report layouts,"
or simply "A report can be set up with multiple report layouts,"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dca07c4-0ff2-adb9-51a3-38bd2d7b4b68
* Version Independent ID: eca5e5c6-7bb8-14bd-25e9-aa41d303e861
* Content: [Custom and Built-In Layouts for Reports and Documents - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-manage-report-layouts)
* Content Source: [business-central/ui-manage-report-layouts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-manage-report-layouts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SorenGP** [comment]
Thank you for the feedback. The wording has been changed. The update will be available within one week.
