### ISSUE TITLE
Typo (trivial / picky / low importance)

### ISSUE THREAD

**Issue by a-zaf** [MicrosoftDocs/dynamics365smb-docs#124]
In section "To test custom report layout updates" :
"Chnages to the report layouts..."
&gt;&gt; "Changes"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0d297c0-1f45-f2cd-e74f-d2ded77e5cd7
* Version Independent ID: a4092919-2da0-ba4c-c62b-69de3b08534e
* Content: [Keeping a Report Layout Up-to-date - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-update-report-layouts)
* Content Source: [business-central/ui-update-report-layouts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-update-report-layouts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, the typo has been fixed and the updated article will be published soon. Thanks for the feedback!
