### ISSUE TITLE
Ambiguity in references

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-docs#126]
Your company regularly meets prospective companies that usually develop into future business relationships. When a new contact is made [the doc says we meet "prospective Companies". Now we are talking about "when a new Contact is made". These are distinct entities in NAV], this information needs to be recorded [what information, and where is it recorded?] so that communication can continue.

Assigning as much data as possible about a specific company [again--Company, or Contact?] ensures efficient communication. For example, assigning the relevant industry group, ensures that specific companies are included in any relevant communication. You can also define the business relationship that you have with a contact [because we were just talking about "assigning...data...about a specific Company. But the relationship is with a Contact?]. For example, a contact could be a prospect, bank, or contractor [this is the fundamental ambiguity. A contact can also be a Person. And Person Contacts have relationships to Company Contacts].

This doc language smears concepts together in a way that sounds plausible in English but is not helpful as a description of the product, especially to someone trying to map data relationships properly. Rigorous adherence to the realities of the actual product relationships would yield more useable documentation. IMHO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c7058a5-84a4-97e0-8bbd-cba40a0a2c88
* Version Independent ID: 2b299373-73fb-0d62-5cab-4044e15b4e60
* Content: [Create Contact Companies - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/marketing-create-contact-companies)
* Content Source: [business-central/marketing-create-contact-companies.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/marketing-create-contact-companies.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback. The ambiguity has been resolved. The update will be available within one week.
