### ISSUE TITLE
German Translation horrible

### ISSUE THREAD

**Issue by dNsl9r** [MicrosoftDocs/dynamics365smb-docs#127]
The german Translation for the docs regarding the intelligent cloud is horrible.
I just tried to rewrite the german text for a better understanding.
Maybe your translation service can check this again and can change the docs.

> Ihr Zugang zur intelligenten Cloud mit Dynamics 365 Business Central
> 
> Als Benutzer von Business Central online haben Sie Vollzugriff auf die Szenarien, 
> die auf der intelligente Cloud basieren, wie z.B. Daten in Excel bearbeiten und Änderungen zurück in 
> Business Central zu laden, oder Daten in Power BI anzeigen. 
> 
> Während Business Central ein cloud-first Service ist, können auch Kunden, 
> die ihre Arbeit vollständig on-premises oder in Verbindung mit Intelligent Edge mit der Cloud erledigen, die intelligente Cloud nutzen.
> 
> Wenn Sie Interesse an Business Central haben, können Sie eine kostenlose Testversion der Cloudbereitstellungslösung anfordern, 
> oder Sie arbeiten mit einem Partner zusammen, um Business Central lokal auf Ihrer Hardware bereitzustellen. 
> 
> Sie können sich dann entscheiden, sich mit der Cloud über Ihren Tenant zu verbinden. 
> Als Ergebnis werden die Daten aus der Cloud lokal in Business Central bereitgestellt und für die intelligenten Cloudszenarien repliziert.
> 
> Die Verbindung mit der intelligenten Cloud von einer lokalen Lösung benötigt Ihren Administrator, um Informationen über Ihre Datenbank zu enthalten. Weitere Informationen finden Sie unter "Schließen Sie die intelligente Cloud an" im ITPro-Inhalt für Business Central.
> 
> Sehen Sie sich Ihre Insights aus der intelligenten Cloud in Business Central online an
> In Ihrem Business Central online Mandanten wird die intelligente Cloud Insights vier zentrale Punkte für Zinsen für die meisten Unternehmen anzeigen:
> 
> Liquiditätslage
> Verkaufsrentabilität
> Nettoeinnahmen
> Lagerwert
> 
> Neben den KPI-Diagrammen werden Sie Einblicke in Problemfelder erhalten, einschließlich überfälliger Zahlungen. Für jeden Insight können Sie einen detaillierten Einblick in die Daten vornehmen.
> 
> Insights aus der intelligenten Cloud
> 
> Die Seite verbindet sich auch mit Power BI für noch mehr Insights.
> 
> Sehen Sie sich Ihre Insights aus der intelligenten Cloud lokal an
> Wenn Ihr wiederverkaufender Partner von Dynamics 365 die richtige Lizenz für Ihre lokale Lösung angefordert hat, um die Verbidnung mit Business Central herzustellen, kann Ihr Administrator die Verbindung herstellen. 
> Sobald das getan wurde, können Sie die gleichen Insights aus der Cloud in der lokalen Anwendung anzeigen. Abhängig von der lokalen Lösung können Insights aus der intelligenten Cloud in die Homepage oder in eine einzelne Seite in Business Central online und lokal eingebettet werden.
> 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 806624da-261d-1922-c480-1cc0ca9787f3
* Version Independent ID: 115d509c-f3b8-588b-aff8-a41b8877cbf7
* Content: [Intelligente Cloud - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/about-intelligent-cloud)
* Content Source: [business-central/about-intelligent-cloud.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/about-intelligent-cloud.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bmeier94
* Microsoft Alias: **bmeier**

**Comment by edupont04** [comment]
Hi dNsl9r,

Thank you for your feedback. I have forwarded it to our translation team for further processing.
