### ISSUE TITLE
getting error when renaming My Company

### ISSUE THREAD

**Issue by armazing** [MicrosoftDocs/dynamics365smb-docs#128]
Following the document steps, we got an error "You cannot rename the company that you are currently using. Open a different company, and then you can rename the My Company ..."

Please add in the steps to make sure to open a different company to be able to rename My Company

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81ade2e-c352-6cef-011e-2e933628aa94
* Version Independent ID: 5483fac9-27e6-3249-8a98-798b7376ad54
* Content: [Use Invoicing and Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/about-reuse-company-invoicing)
* Content Source: [business-central/about-reuse-company-invoicing.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/about-reuse-company-invoicing.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
You're absolutely right. Thanks for pointing that out. We'll update the topic and publish it very soon.
