### ISSUE TITLE
Step 1 to setup warehosue employees

### ISSUE THREAD

**Issue by amadse** [MicrosoftDocs/dynamics365smb-docs#129]
First of all the icon doesn't exist in the application.  Next if you search for it you get into something that is not related to setup Warehouse workers
It should be 
Warehouse management/Setup/Worker

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdc2d1fc-df45-9a7a-4154-448eb4572c55
* Version Independent ID: 4bf9c881-58d0-0fe4-b920-1ddb75e22102
* Content: [How to Set Up Warehouse Employees - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/warehouse-how-to-set-up-warehouse-employees)
* Content Source: [business-central/warehouse-how-to-set-up-warehouse-employees.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/warehouse-how-to-set-up-warehouse-employees.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback. No changes will be made to the topic, because:
- The search icon in question is back in the UI.
- "Warehouse Employees" is the correct page for setup of warehouse workers. Also, we don't refer to navigation paths in Help.
