### ISSUE TITLE
Suchbegriff

### ISSUE THREAD

**Issue by teyv** [MicrosoftDocs/dynamics365smb-docs#130]
Suchbegriff sollte nicht "Buchungsperioden", sondern "Buchhaltungsperioden" sein. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a828d1c8-a0fe-dda5-7ebe-235b24b07c66
* Version Independent ID: aa54e1da-15ff-693e-2690-b0823d6f009a
* Content: [Mit Buchhaltungsperioden und Geschäftsjahren arbeiten - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/finance-accounting-periods-and-fiscal-years#feedback)
* Content Source: [business-central/finance-accounting-periods-and-fiscal-years.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-accounting-periods-and-fiscal-years.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by SorenGP** [comment]
Thank you for the feedback. This has been forwarded to the Translation department.
