### ISSUE TITLE
Can't add advance filter fields

### ISSUE THREAD

**Issue by nadeektt** [MicrosoftDocs/dynamics365smb-docs#131]
Hi Experts,

Ex: I need to add more field filters to the 'Suggest Vendor Payments" in Payment Journal.
Exactly like advanced filters in NAV 2018/2017/2016 etc.

Do you guys know a way to to this?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1343f6fc-1309-b19a-fbeb-8a3e5ec7c8b2
* Version Independent ID: 54110362-c3dd-165a-1d27-1b1a2cde6e8e
* Content: [About Searching and Filtering in Business Central - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/ui-search-filter-faq#feedback)
* Content Source: [business-central/ui-search-filter-faq.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-search-filter-faq.md)
* Service: **dynamics365-business-central**
* GitHub Login: @mikebcMSFT
* Microsoft Alias: **mikebc**

**Comment by edupont04** [comment]
Hi nadeektt,

Sorry for the delay in getting back to you on this, but this is currently not possible on reports such as Suggest Vendor Payments. We have significant feedback on this, though, and expect to address it in the future. You might want to vote for this idea: [https://experience.dynamics.com/ideas/idea/?ideaid=2965d0fd-40b3-e811-a8eb-0003ff68c780](https://experience.dynamics.com/ideas/idea/?ideaid=2965d0fd-40b3-e811-a8eb-0003ff68c780)

We'll make it clearer in the FAQ that the current capabilities apply to lists, not reports.

**Comment by SorenGP** [comment]
The topic now states that the filter pane (advanced filters) is not available on report request pages. NOTE: This will be fixed with the Fall '19 release.
