### ISSUE TITLE
Fehler im Beitrag

### ISSUE THREAD

**Issue by teyv** [MicrosoftDocs/dynamics365smb-docs#132]
Der Suchbegriff "Zahlungsvmethode" im Abschnitt "So richten Sie eine Zahlungsmethode ein" muss "Zahlungsform" lauten, andernfalls wird die gewünschte Tabelle nicht angezeigt.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 364d3f4a-42b0-435f-9277-ed055a9109c3
* Version Independent ID: 45ca6e4b-e8d6-b6c7-3705-ae50dc9d191c
* Content: [Zahlungsformen einrichten - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/finance-payment-methods#feedback)
* Content Source: [business-central/finance-payment-methods.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-payment-methods.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by SorenGP** [comment]
Thank you for the feedback. The issue has been forwarded to the Translation department.
