### ISSUE TITLE
Heading Development should be Development and System Administration

### ISSUE THREAD

**Issue by KennieNP** [MicrosoftDocs/dynamics365smb-docs#134]
There is no obvious link from this documentation to the IT pro docs. 

I suggest changing

"And if you are a partner or customer looking at extending the functionality, you will find relevant links under Development and Administration."

to 

"And if you are a partner or customer looking at extending the functionality or learn about system administrative topics, you will find relevant links under Development and System Administration."

Heading "Development" in the table should be "Development and System Administration"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b86d301-cf03-0dd0-abdd-9a73743b4285
* Version Independent ID: 4e4d4219-2c2f-0324-6166-414f31158224
* Content: [Meet Microsoft Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/)
* Content Source: [business-central/index.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/index.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Closing this issue as internal.
