### ISSUE TITLE
Bitte die Übersetzung für Deuztsch komplett überarbeiten.

### ISSUE THREAD

**Issue by ThomasBrodkorb** [MicrosoftDocs/dynamics365smb-docs#136]
Die hier vorliegende Übersetzung verwendet Begriffe und Wörter, die es in der deutschen Sprache überhaupt nicht gibt und auch von einem theoretischen Standpunkt aus keinen Sinn ergeben.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von Problemen docs.microsoft.com ➟ GitHub erforderlich.*

* ID: 4f2bb938-9414-6190-6d38-464b289cba5d
* Version Independent ID: d1586eb3-8b33-edd6-dcab-590797c8624b
* Content: [Antworten auf Anforderungen zu Personendaten - Business Central](https://docs.microsoft.com/de-at/dynamics365/business-central/admin-responding-to-requests-about-personal-data#feedback)
* Content Source: [business-central/admin-responding-to-requests-about-personal-data.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-responding-to-requests-about-personal-data.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by SorenGP** [comment]
Thank you for the feedback. The Translation department is going through the topic and will take appropriate action. The corrected content will be available with the next translation update between one week and one month from now.
