### ISSUE TITLE
EHF Electronic Invoice in Norway for Dynamics BC Web Client

### ISSUE THREAD

**Issue by pejdu** [MicrosoftDocs/dynamics365smb-docs#137]
How to set up output path for EHF Electronic Invoice for running Dynamics BC Web Client? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8576fb5-7e8b-7c36-63f2-b5e5273d96a5
* Version Independent ID: a56d32fa-38dc-50a5-ce16-12d027411267
* Content: [How to Create Electronic Documents for EHF - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/norway/how-to-create-electronic-documents-for-ehf#feedback)
* Content Source: [business-central/LocalFunctionality/Norway/how-to-create-electronic-documents-for-ehf.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Norway/how-to-create-electronic-documents-for-ehf.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Is this what you are looking for? https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/norway/how-to-set-up-ehf

**Comment by SorenGP** [comment]
Closing as the issue seems to be closed with the above answer.
