### ISSUE TITLE
E-Mail in Dynamics 365 Business Central

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#138]
I wrote on 10/02/2018 and 11/28/2018 an E-Mail to clocnav@microsoft.com as suggested from Søren Groes-Petersen on #37, but the issues still exists.

* Testversion vonan -> Testversion von an
* Geschäfts-Zentralblog ->Business Central Blog

![2019-04-02 18_15_07-Window](https://user-images.githubusercontent.com/9556549/55418775-a3402200-5573-11e9-834a-5ceca66ec9e8.png)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3243448c-df56-cb7d-2e08-9084ca24a330
* Version Independent ID: 9e1799ac-14f6-4c70-6032-a9f41cc1d749
* Content: [E-Mail in Business Central einrichten - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/product-news)
* Content Source: [business-central/product-news.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/product-news.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Daniel,

Our translation team are doing what they can, but I will follow up with them about these two bugs.
