### ISSUE TITLE
Wrong German Translation of Inventory

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#139]
Despite my E-Mail from 10/06/2019 to clocnav@microsoft.com no fix. So again: In the ToC there is **Lagerbest**, which is no German word. Translation of **Inventory** is **Lagerbestand**.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 84ddff91-f250-6168-265d-fbe6ffd41a5c
* Version Independent ID: e58801fd-14cc-77b5-4aaf-ccb7bbc9ff78
* Content: [Verwaltung von Bestand - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/inventory-manage-inventory)
* Content Source: [business-central/inventory-manage-inventory.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-manage-inventory.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
This has been forwarded to the Translation department.
