### ISSUE TITLE
Advanced Application Area in DE Version

### ISSUE THREAD

**Issue by aproehl79** [MicrosoftDocs/dynamics365smb-docs#14]
I cannot see the "Manufacturer Code" in the "Nonstock Item Card". Under Company Information the User experience is set to Advanced.
But when i search for "Application Area" everything is selected but "Advanced". How I can activate the "Advanced" Application Area? 

Many other features like "Archiving Sales Order" are also only visible within "Advanced" Application Area. Nothing of them are accessible in my BC tenant.

Under "Systeminformation" it shows me "DE Dynamics NAV 12.0 (21229)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1008a635-ba7d-cc87-a06c-88010ee6b52f
* Version Independent ID: 51943aa7-582b-0fad-fc16-c8ac8bf1b9b5
* Content: [Create and Manage Nonstock Items - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/inventory-how-work-nonstock-items#to-set-up-how-nonstock-item-numbers-are-converted-to-your-own-numbering)
* Content Source: [business-central/inventory-how-work-nonstock-items.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-how-work-nonstock-items.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Hi - You are experiencing a known issue that will be resolved in a future update. For more information, and a development workaround, see the "Why are some UI elements that I used in Dynamics NAV not visible in Business Central?" section at the bottom of this FAQ topic: https://docs.microsoft.com/en-us/dynamics365/business-central/across-faq 
