### ISSUE TITLE
Inconsistent German Translation of "Incoming Documents"

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#140]
Despite my E-Mail from 10/06/2019 to clocnav@microsoft.com no fix. So again: "Incoming Documents" ist translated in the Application with "Eingehende Dokumente". In the Help it is translated with "Eingehende Belege". This is a hard one, because in general Document(/Documents) is translated with "Beleg"/"Belege" in the Application.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7e0acd95-5498-9acf-1d97-698e76d99d7d
* Version Independent ID: 55e87498-2992-45cb-2956-53ddbec08d7e
* Content: [Arbeiten mit eingehenden Belegen - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/across-income-documents)
* Content Source: [business-central/across-income-documents.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-income-documents.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
This has been forwarded to the Translation department.
