### ISSUE TITLE
[de-DE] There is no good German Translation for Compliance

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#141]
Despite my E-Mail from 11/28/2019 to clocnav@microsoft.com no fix. So again: Unfortunately there is no good German Translation for Compliance. That is why German Wikipedia used the English Term: https://de.wikipedia.org/wiki/Compliance_(BWL)

In the Wikipedia article they use also Regeltreue, but is not that common.

I think there are three good alternative:
- Compliance with the law: "Gesetzeskonformität",
- Compliance with policies: "Richtlinienkonformität" or
- Compliance with regulations: "Einhaltung der Vorschriften"

Currently:
- "Konformität" alone means mostly to be conform with the attitude and behaviour of others. 
- "Anwendungs-Kompatibilität" means that the application is compatible with Hardware and/or Software e.g. Windows 10, Google Chrome, …
- "[Dienst-Kompatibilität](https://docs.microsoft.com/de-de/dynamics365/business-central/compliance/compliance-service-compliance)" means that the service is compatible with e.g. Office 365

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c68b80cc-b538-9aa3-47a2-0e692e91a122
* Version Independent ID: 6469c4a8-8277-a3a4-c8ad-aa941de77285
* Content: [Anwendungs-Kompatibilität - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/compliance/compliance-application-compliance)
* Content Source: [business-central/compliance/compliance-application-compliance.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/compliance/compliance-application-compliance.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by edupont04** [comment]
Forwarded to translation team
