### ISSUE TITLE
Wrong translation of Unit Price: Einheitspreis

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#142]
There is a wrong translation of Unit Price: Einheitspreis. In German BC it is called „VK-Preis” oder “Verkaufspreis”. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 9e6c90a8-22c7-8572-195c-b77237a765e8
* Version Independent ID: ebae59fd-cb1e-1da4-80d3-b5afaf712df8
* Content: [Buchungsdatum auf Wertposten - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/design-details-inventory-adjustment-value-entry-posting-date)
* Content Source: [business-central/design-details-inventory-adjustment-value-entry-posting-date.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-inventory-adjustment-value-entry-posting-date.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thanks! Submitting to the translation team.
