### ISSUE TITLE
What's New Notes April 19 Release

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#143]
The Link behind **Check out the latest version of the release notes** should be updated to https://docs.microsoft.com/en-us/business-applications-release-notes/April19/dynamics365-business-central/.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3243448c-df56-cb7d-2e08-9084ca24a330
* Version Independent ID: 9e1799ac-14f6-4c70-6032-a9f41cc1d749
* Content: [What's New in Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/product-news)
* Content Source: [business-central/product-news.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/product-news.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Daniel,
Good catch! This will be updated in the update on Monday.

**Comment by edupont04** [comment]
Done :-)
