### ISSUE TITLE
Minor Issues in FAQ zum Anpassen von Business Central - Business Central / Section Wie gelange ich zum technischen Support von Business Central"?

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#144]
The quotation mark should be deleted in the heading of the section. -> "Wie gelange ich zum technischen Support von Business Central?"

In the sentence "Wenn Ihr Business Central Partner das jeweilige Problem nicht lösen kann, wir**d** er ein Support-Ticket bei Microsoft eröffnen." a **d** is missing.

The next sentence has two comma -> "Wenn Sie sich für eine Testversion angemeldet haben und Business Central noch nicht gekauft haben, haben Sie keinen Wiederverkaufspartner und Sie können das Microsoft-Support-Team nicht direkt kontaktieren."

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 79ad74cc-aba8-7c05-93c2-da28efdbf375
* Version Independent ID: 2f07a9a9-4cf3-c835-29d0-aab1c830277c
* Content: [FAQ zum Anpassen von Business Central - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/across-faq)
* Content Source: [business-central/across-faq.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-faq.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thanks, Daniel - I've forwarded your feedback to the translation team. FYI, the first issue that you mention is by design.

**Comment by edupont04** [comment]
Closing as it will be fixed by translation.

**Comment by DanielGoehler** [comment]
Hi @edupont04, regarding the first issue: _Wie gelange ich zum technischen Support von "Business Central"?_ would be also fine. But the **one** quotation mark at the end looks a little bit lost and in the [English Version](https://docs.microsoft.com/en-us/dynamics365/business-central/across-faq#how-do-i-get-technical-support-for-) it is also not present.

![2019-04-03 13_50_02-FAQ zum Anpassen von Business Central - Business Central _ Microsoft Docs](https://user-images.githubusercontent.com/9556549/55476673-80674980-5617-11e9-82ae-dadf32089ffc.png)
