### ISSUE TITLE
Double link in See Also to Administration

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-docs#145]
There is Administration in the See Also two times with same link (https://docs.microsoft.com/en-us/dynamics365/business-central/admin-setup-and-administration) . It is confusing...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58d0c2b2-6293-9604-440b-987e32fac282
* Version Independent ID: 541e941e-2c6c-3f31-b998-17be0815c1ad
* Content: [Overview of Tasks to Set Up Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/setup)
* Content Source: [business-central/setup.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/setup.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Good catch! It will be fixed in Monday's update.
