### ISSUE TITLE
No way to add Links to Websites, Documents, or Programs on Records

### ISSUE THREAD

**Issue by jeffgit** [MicrosoftDocs/dynamics365smb-docs#146]
[Enter feedback here]
Is this feature already available? We can't find it any where.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f593be4-1a2e-08e8-4e8c-08813c95e159
* Version Independent ID: fb3182ce-7527-9051-e9d8-db9969f566ee
* Content: [How to Link from Records to External Information or Programs - Business Central](https://docs.microsoft.com/en-ca/dynamics365/business-central/ui-how-add-link-to-record#feedback)
* Content Source: [business-central/ui-how-add-link-to-record.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-how-add-link-to-record.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hello jeffgit,

Unfortunately, we have had a delay in making this capability available in Business Central online. We have now made it more clear that the capability is available only on-premises. For more information, see the release notes at https://docs.microsoft.com/en-us/business-applications-release-notes/april19/dynamics365-business-central/comments-notes-links
