### ISSUE TITLE
Sandbox with Production Data

### ISSUE THREAD

**Issue by paul-interdyn** [MicrosoftDocs/dynamics365smb-docs#148]
According to the October '18 release notes, you can create a sandbox using production data (https://docs.microsoft.com/en-us/business-applications-release-notes/October18/dynamics365-business-central/visual-studio-code-improvements), but the steps to do so are not documented here (also not seeing it elsewhere).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 271c01ea-0e69-e107-1e8a-7eede83448bf
* Version Independent ID: 2f05ff73-1137-25af-1546-e378d2f9e466
* Content: [Create a Sandbox Environment - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-create-sandbox-environment#feedback)
* Content Source: [business-central/across-how-create-sandbox-environment.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-how-create-sandbox-environment.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by paul-interdyn** [comment]
Actually, I did find the steps documented here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-environments but it would be nice to at least link to this page from here.

**Comment by SorenGP** [comment]
Thank you for the feedback. The topic has been updated.
