### ISSUE TITLE
No Description in Item Ledger Entries

### ISSUE THREAD

**Issue by aproehl79** [MicrosoftDocs/dynamics365smb-docs#15]
I see no Description in Item Ledger Entries while Descriptions in Purchase Lines, Sales Lines and Item Tracking Lines have been set:

![image](https://user-images.githubusercontent.com/16100797/42132407-85d97ef8-7d17-11e8-9e36-62460fd40ca8.png)

**Comment by edupont04** [comment]
Sorry for the delay in getting back to you on this! You seem to be talking about sample data. If you would like additional sample data added to Business Central, please post a suggestion here: https://experience.dynamics.com/ideas/list/?forum=e288ef32-82ed-e611-8101-5065f38b21f1
