### ISSUE TITLE
Context-sensitive help using help server

### ISSUE THREAD

**Issue by AbsolutelyFreeWeb** [MicrosoftDocs/dynamics365smb-docs#150]
I also just noticed there are no T_ tables files. I'm looking for the classic context sensitive help. 
Worse BC130 does not seem to go to the context-sensitive url (The T_ file) at all when pushing F1 on a field....

In https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/configure-help it says: 

> If you use Help Server, the UI-to-Help mapping functionality that is described in Configure Context-Sensitive Help does not work. Instead, you must rely on the legacy Help lookup mechanism that hinges on .HTM files with filenames that reflect the object IDs, such as N_123.htm for the page object with the ID 123. For more information, see Working with Dynamics NAV Help Server.

I've added the pages in this project, as well as some NAV 2017 files, into the en-US folder, but BC130 always opens the same entry page. What does it take to get context-sensitive help working again?

**Comment by edupont04** [comment]
Hi there,
If you want to us the legacy Help Server, then presumably you are already familiar with it and might even have an existing site up and running for a Dynamics NAV version. If that is the case, you can quite simply reuse those T_ and N_ HTML files to provide context-sensitive Help for your Dynamics 365 Business Central deployment. We wrote about this on the NAV Team blog when we shipped Dynamics NAV 2017 now moved here: [https://cloudblogs.microsoft.com/dynamics365/2016/11/04/dynamics-nav-and-help-a-new-world/](https://cloudblogs.microsoft.com/dynamics365/no-audience/2016/11/04/dynamics-nav-and-help-a-new-world/)
If you don't have an existing Help Server website set up, then you can get the thousands of HTML files for Dynamics NAV 2017 here: [https://www.microsoft.com/en-us/download/details.aspx?id=54315](https://www.microsoft.com/en-us/download/details.aspx?id=54315)
That should certainly do the trick for getting Help Server to work for you. If it doesn't, then something would seem to be wrong in your deployment of Help Server, and you might have to get in touch with our Support folks.

**Comment by AbsolutelyFreeWeb** [comment]
Hi @edupont04 I did contact support and they said it is not working (despite the documentation saying so) and that the developer team refuses to fix the issue regardless of complaints. This is what support told me.
