### ISSUE TITLE
Extend selection to first/last row

### ISSUE THREAD

**Issue by duichwer** [MicrosoftDocs/dynamics365smb-docs#151]
Is this reference still up-to-date for the current BC Release?
Neither this command "Ctrl+Shift+Home/End" for Extend selection to first/last row nor the German "Shift+Strg+Start/Ende" does work in my BC Demo Installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 839e7a63-b074-a7b7-0ee5-b9cea4313de0
* Version Independent ID: 545efe23-da43-c929-3edc-c63f52849cfd
* Content: [Keyboard Shortcuts Quick Reference - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/keyboard-shortcuts-cheatsheet#feedback)
* Content Source: [business-central/keyboard-shortcuts-cheatsheet.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/keyboard-shortcuts-cheatsheet.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SorenGP** [comment]
Thank you for spotting this. Indeed, that keyboard shortcut is not supported. Help has been updated and will be available within one week.
