### ISSUE TITLE
Wrong column heading "Um dies in einer Listenansicht tun"

### ISSUE THREAD

**Issue by duichwer** [MicrosoftDocs/dynamics365smb-docs#152]
The column Heading of the third columns seems to be wrong.
The english Heading "To do this in a tile view" should "Um dies in einer Kachelansicht zu tun" instead of  "Um dies in einer Listenansicht tun".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96fd662-e905-9df6-60f5-c709f92077c1
* Version Independent ID: 172fd943-0f5c-6d4c-b764-ced7fd077a96
* Content: [Keyboard Shortcuts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/keyboard-shortcuts#feedback)
* Content Source: [business-central/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/keyboard-shortcuts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SorenGP** [comment]
This has been forwarded to the Translation department.
