### ISSUE TITLE
Several Links on this page don't work

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#158]
Several Links on this page don't work. E.g. Create and Submit Sales VAT Advance Notifications, ELSTER Transmission Overview, Error Messages of the Elster Transfer Handler and more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b02a3bed-10c6-d6cd-6a60-61a01be70db6
* Version Independent ID: 04afd3c0-bf14-b6d7-ea87-c43d253bb16a
* Content: [Germany Local Functionality - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/germany/germany-local-functionality)
* Content Source: [business-central/LocalFunctionality/Germany/germany-local-functionality.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Germany/germany-local-functionality.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for telling us. All broken links are now fixed. The update will be available within one week.
