### ISSUE TITLE
Missing information on personalizations when upgrading 

### ISSUE THREAD

**Issue by kvamsdal** [MicrosoftDocs/dynamics365smb-docs#164]
Does personalization re-set when upgrading to a new version? (both On premise/In Cloud). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc9174f7-cad5-7550-b93b-036158d40e38
* Version Independent ID: 8e4dabaa-c112-6a2e-dc18-933253579927
* Content: [Personalizing Pages - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-personalization-user#additional-points-of-interest)
* Content Source: [business-central/ui-personalization-user.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-personalization-user.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by lvanvugt** [comment]
What was the result of this issue? It seems nothing was done? If so, why?
