### ISSUE TITLE
Minor wording issue

### ISSUE THREAD

**Issue by y0m0** [MicrosoftDocs/dynamics365smb-docs#167]
Under this section:
https://docs.microsoft.com/en-us/dynamics365/business-central/ui-manage-report-layouts#deciding-whether-to-use-a-word-or-rdlc-report-layout

There is an extra "is" in this sentence:
However each type has certain design features that affect how the generated report is appears in Business Central.

Should be changed to:
However each type has certain design features that affect how the generated report appears in Business Central.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dca07c4-0ff2-adb9-51a3-38bd2d7b4b68
* Version Independent ID: eca5e5c6-7bb8-14bd-25e9-aa41d303e861
* Content: [Custom and Built-In Layouts for Reports and Documents - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-manage-report-layouts#feedback)
* Content Source: [business-central/ui-manage-report-layouts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-manage-report-layouts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SorenGP** [comment]
Thank you for the feedback - This has been fixed and will be available within one week.
