### ISSUE TITLE
To budget depreciation step 1 update

### ISSUE THREAD

**Issue by pdiazms** [MicrosoftDocs/dynamics365smb-docs#171]
FA Projected Value is not a valid search keyword per step 1 in the To budget depreciation section of this page.  Please update to Projected Value or Fixed Asset Projected Value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9d51418-5825-7d30-7773-a97ca9debea9
* Version Independent ID: 0596db97-4348-6291-91b4-e79bce99a8df
* Content: [Manage FA Budgets - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/fa-how-manage-budgets#feedback)
* Content Source: [business-central/fa-how-manage-budgets.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/fa-how-manage-budgets.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello pdiazms,

Thank you for your feedback! We'll get this bug fixed as soon as possible.

**Comment by SorenGP** [comment]
This has been fixed and will be available within one week.
