### ISSUE TITLE
Instructions appear to be outdated and need updating.

### ISSUE THREAD

**Issue by kimberley523** [MicrosoftDocs/dynamics365smb-docs#172]
Some generalities:  
1. Throughout the document there are references to choosing the OK button, there is no OK button anymore - it is just the left arrow in the top left screen.
2. Many menu items have change or are sub menus now.

Some specifics: in the section "Setting up a job":
1. the bill-to customer referenced does not exist in the Cronus database.
2. On the posting fast tab, the options for the Status field are:  Planning, Quote, Open, Completed (there isn't an option for "Order").

"To Customize Pricing"
1. the Resource Action is actually under the Prices menu.
2. The Item action is under Navigate  &gt; Prices &gt; Item
3. The G/L Account Action is under Navigate &gt; Prices &gt; G/L Account
4. There is not a G/L Account 8430 (Travel) in the Cronus Database (maybe this is a different data set?)

"To Create Planning Lines" section:
The line types terminology has changed.  There is no longer an option for "Both Schedule and Contract", it is now Both Budget & Billable.

These are just some examples.  I think these walkthroughs are great and excellent learning tools.  But the changes in the system from the documentation make it difficult to work through them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 850880b4-15c7-9760-17c5-b723b9b2b17f
* Version Independent ID: b52bcf7c-1126-b2ab-c8bc-29c29f851e27
* Content: [Walkthrough - Managing Projects with Jobs - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/walkthrough-managing-projects-with-jobs)
* Content Source: [business-central/walkthrough-managing-projects-with-jobs.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/walkthrough-managing-projects-with-jobs.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello Kimberley523,
Thank you for your feedback! You are quite right that this article is getting to be pretty dusty and could do with a thorough spring cleaning. We hope to get the content updated in the coming weeks as part of an effort on the jobs content all-up.

**Comment by SorenGP** [comment]
The topic has been updated and will be available within one week.
Note:
- In navigation content, we never refer to an action's position on the menus. This is because users can move actions around with the Personalize feature. 
- Most walkthroughs, incl. this one, require the Full Sample Data option. A note has been added to the topic.
