### ISSUE TITLE
More explanation around costing

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#173]
These two toggles do not have a lot of information on what they do and how they might be of benefit.
Automatic Cost Posting
Expected Cost Posting to G/L

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35504438-6146-9f39-d8cb-8cdfbffc477c
* Version Independent ID: 432fa982-b845-19d3-5908-04d3c9f51618
* Content: [Define the General Inventory Setup - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/inventory-how-setup-general#feedback)
* Content Source: [business-central/inventory-how-setup-general.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-how-setup-general.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **SorenGP**

**Comment by SorenGP** [comment]
Thanks for the feedback. The topic has been updated with relevant links . It will be available within one week.

**Comment by makdaddy8888** [comment]
What was the outcome?

Kind Regards
Ben Opit
+61411707070

**Comment by SorenGP** [comment]
Screenshot of the Help staging site:
![image](https://user-images.githubusercontent.com/15833976/68654977-68519400-052f-11ea-94df-5cc934bbf788.png)
It will be on the live site next time we do a weekly refresh.
