### ISSUE TITLE
This page have some duplicat content .

### ISSUE THREAD

**Issue by SaddamCisinlabs** [MicrosoftDocs/dynamics365smb-docs#174]
"Budgets play an important role in business intelligence, such as in financial statement based on account schedules that include budget entries or when analyzing budgeted versus actual amounts in the chart of accounts. For more information, see Business Intelligence."

is twice. Remove it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5edb44-d10a-0f8d-2146-87263c9d2821
* Version Independent ID: ef62b88c-8e9c-9ba4-4801-02d49731d498
* Content: [Creating G/L Budgets - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-how-create-budgets)
* Content Source: [business-central/finance-how-create-budgets.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-how-create-budgets.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thanks you for the feedback. The topic has been updated and will be available within one week.
