### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by LukeAlder** [MicrosoftDocs/dynamics365smb-docs#175]
The following text has a typo:

'In general, search will attempt to match text across all fields; it does not distinguish between uppercase and lowercase characters (in other words, case insensitive), and will match text placed anwhere in the field (at the beginning, end, or in the middle).'

The word 'anwhere' in the above should be replaced with 'anywhere'.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 802c5ab2-6384-9f67-586f-8de66cd361cc
* Version Independent ID: 12fb39ec-1f3c-e49b-de9c-7d9d09b29fc4
* Content: [Sorting, Searching, and Filtering Lists - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/ui-enter-criteria-filters)
* Content Source: [business-central/ui-enter-criteria-filters.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-enter-criteria-filters.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SorenGP** [comment]
Thanks for spotting it. The topic has been updated and will be available within one week.
