### ISSUE TITLE
Payments tolerances

### ISSUE THREAD

**Issue by kgithub25** [MicrosoftDocs/dynamics365smb-docs#179]
In example 2, are diagrams 2 and 3 switched on this page?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ade53c3-d4f4-173e-b20a-4a5cd7fb2c4b
* Version Independent ID: 120039ea-6406-cf55-f1d5-f6b13c3a529b
* Content: [Payment Tolerance and Payment Discount Tolerance - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-payment-tolerance-and-payment-discount-tolerance)
* Content Source: [business-central/finance-payment-tolerance-and-payment-discount-tolerance.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-payment-tolerance-and-payment-discount-tolerance.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Yes, they are. Thank you for spotting this. The topic has been updated and will be available within one week.
