### ISSUE TITLE
Change FlowFilter values in WebClient

### ISSUE THREAD

**Issue by aproehl79** [MicrosoftDocs/dynamics365smb-docs#18]
You write

"In FlowFilter fields, a user can enter a filter value via the user interface in the application that will affect the calculation of a FlowField." 

For example the "Date Filter" in the Item table has effect on how the "Inventory" Field is calculated.

How a user can do this in the business central web client?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b86d301-cf03-0dd0-abdd-9a73743b4285
* Version Independent ID: 4e4d4219-2c2f-0324-6166-414f31158224
* Content: [Meet Microsoft Dynamics Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/index?branch=master)
* Content Source: [business-central/index.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/index.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Closing this issue on behalf of owner, since the misleading wording appears to have been removed. For more information about filtering, see "Sorting, Searching, and Filtering Lists" at https://docs.microsoft.com/en-us/dynamics365/business-central/ui-enter-criteria-filters
