### ISSUE TITLE
More then one Place with Information on Integration Dynamics 365 for Sales

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#180]
There are several separate places for with Information on Integration Dynamics 365 for Sales. I think they should be combining since these separate places have overlapping information.

- [Using Dynamics 365 for Sales from Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/marketing-integrate-dynamicscrm)
  - [Couple and Synchronize Records Manually](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-how-to-couple-and-synchronize-records-manually)
  - [View the Status of a Synchronization](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-how-to-view-synchronization-status)

AND 

- [Integrating with Dynamics 365 for Sales](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-prepare-dynamics-365-for-sales-for-integration)
  - [Setting Up User Accounts for Integrating with Dynamics 365 for Sales](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-setting-up-integration-with-dynamics-sales)
  - [Set Up a Connection to Dynamics 365 for Sales](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-how-to-set-up-a-dynamics-crm-connection)
  - [Synchronizing Data in Business Central and Dynamics 365 for Sales](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-synchronizing-business-central-and-sales)
  - [Modify Table Mappings for Synchronization](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-how-to-modify-table-mappings-for-synchronization)
  - [Manually Synchronize Table Mappings](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-manual-synchronization-of-table-mappings)
  - [Scheduling a Synchronization between Business Central and Dynamics 365 for Sales](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-scheduled-synchronization-using-the-synchronization-job-queue-entries)

AND 

- [Preparing Dynamics 365 for Sales for Integration](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/prepare-dynamics-365-for-sales-for-integration), but this page is not in the Table of Content

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d1e4b3c-28cf-8c08-b0a7-69092862e07d
* Version Independent ID: 68e2ca6e-1fe3-ddf9-5f28-feceef952d24
* Content: [Manage Customers Using Dynamics 365 for Sales - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/marketing-integrate-dynamicscrm)
* Content Source: [business-central/marketing-integrate-dynamicscrm.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/marketing-integrate-dynamicscrm.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by SorenGP** [comment]
Thank you for the feedback. 

The content is deliberately split between setup tasks (under the Administration TOC node) and user tasks (under the Relationship Management TOC node). There are clear references between the two content areas. We have updated the TOC entry name for the user part to make it more clear. 

The topic named "Preparing D365 for Sales for Integration" in developer and IT-Pro help is for on-prem scenarios, so must stay there. We have added a TOC entry for the topic.

The updates will be available within one week.
