### ISSUE TITLE
Email limitiation

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#181]
Can you please share what the email limitation are with Exchange and how many emails can be created in a shared mailbox?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0171dfbc-61f2-e62e-f4a3-bb641b15c3e2
* Version Independent ID: 51deab1e-0243-3178-7640-01bb91591fca
* Content: [Set up email in Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-how-setup-email)
* Content Source: [business-central/admin-how-setup-email.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-how-setup-email.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi makdaddy8888,
You should be able to find this information in the Exchange docs here: https://docs.microsoft.com/en-us/exchange/collaboration-exo/shared-mailboxes

**Comment by SorenGP** [comment]
The link has been added to the topic. The update will be available within one week.
