### ISSUE TITLE
EAN No. not moved to GLN when installed

### ISSUE THREAD

**Issue by ClausJonathansen** [MicrosoftDocs/dynamics365smb-docs#182]
When installing this extension the field EAN No. (13600) in the customer table is NOT moved til GLN (90) as it is done in other tables. This leaves the field GLN empty when opgrading from a previous edition of NAV.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae54faea-be1d-6d67-8b53-014504925f04
* Version Independent ID: 9a9d3538-a636-7c90-d53a-4a128470ed4a
* Content: [OIOUBL Electronic Invoicing Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/denmark/oioubl-electronic-invoicing-overview#feedback)
* Content Source: [business-central/LocalFunctionality/Denmark/oioubl-electronic-invoicing-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Denmark/oioubl-electronic-invoicing-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
This feedback mechanism is only monitored by writers looking to improve documentation.
Please report this code defect to your Microsoft partner.

**Comment by ClausJonathansen** [comment]
I am a partner and I have reported this and nothing happens

**Comment by SorenGP** [comment]
I have forwarded it internally.

**Comment by sorenfriisalexandersen** [comment]
Hi Claus
We closed the reported bug as "by design". I hope you have received that information.
If not, I am sorry.

Thanks
Søren Alexandersen

**Comment by ClausJonathansen** [comment]
Hi Søren

I that case you need to change the documentation.
When upgrading from Dynamics NAV, the OIOUBL-extension will not work, as all EAN/GLN numbers on Customers are missing.

Med venlig hilsen

PC-Software A/S
Claus H. Jonathansen
Systemkonsulent

Mail: clj@pcsoft.dk<mailto:clj@pcsoft.dk>
Skanderborgvej 238, 8260 Viby J.
Tlf.: +45 8738 6999, Fax: +45 8738 6998
Hjemmeside: www.pcsoft.dk<http://www.pcsoft.dk>

Fra: Søren Friis Alexandersen <notifications@github.com>
Sendt: 12. november 2019 20:16
Til: MicrosoftDocs/dynamics365smb-docs <dynamics365smb-docs@noreply.github.com>
Cc: Claus Jonathansen <clj@pcsoft.dk>; Author <author@noreply.github.com>
Emne: Re: [MicrosoftDocs/dynamics365smb-docs] EAN No. not moved to GLN when installed (#182)


Hi Claus
We closed the reported bug as "by design". I hope you have received that information.
If not, I am sorry.

Thanks
Søren Alexandersen

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fdynamics365smb-docs%2Fissues%2F182%3Femail_source%3Dnotifications%26email_token%3DAL7BFREO3BTDRF7I2BDHVWDQTL6INA5CNFSM4HVUSJTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOED3TCVI%23issuecomment-553070933&data=01%7C01%7Cclj%40pcsoft.dk%7C43e07547c5014171b22008d767a4d033%7C09002afd09544dfa8d9895ecfa050624%7C0&sdata=YKRQCV7yw4gen5mzoARsirHIMFHbC9lVAIXavRcVKfo%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAL7BFRAQRHDCI4CF72ARYEDQTL6INANCNFSM4HVUSJTA&data=01%7C01%7Cclj%40pcsoft.dk%7C43e07547c5014171b22008d767a4d033%7C09002afd09544dfa8d9895ecfa050624%7C0&sdata=iefE5CFAroEpLh5H78wqucjEl%2FiDu4H%2FeimbSbJUi3M%3D&reserved=0>.

[Denne e-mail er skannet af Symantec.cloud]
