### ISSUE TITLE
define check layout

### ISSUE THREAD

**Issue by kaeferc** [MicrosoftDocs/dynamics365smb-docs#183]
Not sure how this page is any help as I navigated to the location but there is nothing that indicates how to define the overall check layout

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e89496cf-457c-f2a8-0d33-a2b94cb5adb5
* Version Independent ID: 1f610879-0e2c-5b42-f82f-b75498634ba2
* Content: [Specify the Layout of a Check - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-how-define-check-layouts#feedback)
* Content Source: [business-central/finance-how-define-check-layouts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-how-define-check-layouts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi kaeferc,

Thank you for your feedback! You're right in thinking that the title is slightly misleading. In Business Central, the actual check layout is defined in the four reports that are listed here. So what you do in the **Report Selection - Bank Acc.** page is to specify which of these predefined layouts you want to use to print a particular check.
If you think it would help, we might change the title to be more explicit that this is about specifying which layout to use.

**Comment by SorenGP** [comment]
The title is changed to "Select a Check Layout", and a link is added to this topic: [Create and Modify a Custom Report or Document Layout](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-create-custom-report-layout). The update will be available within one week.
