### ISSUE TITLE
There is no  Service Setup

### ISSUE THREAD

**Issue by kateflower** [MicrosoftDocs/dynamics365smb-docs#184]
Service Setup does not exist, I assume this is service management setup?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85fe715c-5a06-4d19-01a0-b41b978a58e9
* Version Independent ID: 51067fe1-aba0-af2d-c501-ffde32fe115d
* Content: [Set Up Service Management Processes - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/service-setup-service-processes#feedback)
* Content Source: [business-central/service-setup-service-processes.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/service-setup-service-processes.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by SorenGP** [comment]
Thank you for the feedback. The topic has been updated and will be available within one week.
