### ISSUE TITLE
Header and footers on word layouts

### ISSUE THREAD

**Issue by NAVFreak** [MicrosoftDocs/dynamics365smb-docs#185]
I have created a word layout copy of the report 1305 "Standard Sales - Order Conf." from the built in version. However when I export it I can't see the complete footer and header. So you should update on how to update the layout of the footers and and headers in word documents.

The part with document name, document no. and page no. cant be found in the exported layout.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 562ba9ca-f395-bbeb-0775-5a85696e0935
* Version Independent ID: 58c23bed-523d-0432-f76e-2930232816f6
* Content: [Create and Modify Custom Layouts for Reports and Documents - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-create-custom-report-layout#MakeChangesToLayout)
* Content Source: [business-central/ui-how-create-custom-report-layout.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-how-create-custom-report-layout.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SorenGP** [comment]
Hi - I cannot reproduce your feedback. 

Report 1305 only has footer values Home Page, Phone No., and Email, which appear just fine in the Word layout as well. 
![image](https://user-images.githubusercontent.com/15833976/59759056-8fad7900-928f-11e9-82f0-0b179fee02ae.png)

I don't know where doc name, number and page number come from.

**Comment by NAVFreak** [comment]
Now I went to report 1306 "Standard Sales - Invoice", made a new custom layout which becomes a copy of the built-in layout.
Attached is a printout of an invoice with that layout and attached is also a picture of the exported layout.
As you can see in the layout picture the footer of company information does not exist there but it exists on the printout. The question is how I remove/change order of these footer fields.

![image](https://user-images.githubusercontent.com/34970096/59820458-938ed900-932b-11e9-8016-6f657868a75e.png)

![image](https://user-images.githubusercontent.com/34970096/59820710-a43f4f00-932b-11e9-8200-b87cffc37a24.png)

![image](https://user-images.githubusercontent.com/34970096/59820886-b02b1100-932b-11e9-9a67-68f0c655579c.png)

**Comment by SorenGP** [comment]
Thank you! You have helped us discover a bug in the Import Layout function. While testing how to edit footer fields, we discovered that no fields edited in the layout file are actually imported back into Business Central. Development is looking at the issue now and expect to fix it in a monthly update in the near future.

**Comment by NAVFreak** [comment]
Ok, that is good. 
But no news on how to find/change the footer fields?

**Comment by SorenGP** [comment]
The footer fields appear as expected in Word on several machine in my office, so it must be related to your own Word setup or view. Make sure you have selected Print Layout. Choose "Visa" and select another view.
