### ISSUE TITLE
Problem with Append Queries

### ISSUE THREAD

**Issue by toblan** [MicrosoftDocs/dynamics365smb-docs#186]
Hi,

is it possible that there is a problem with Append Queries in order to combine data for several companies in BC version 14.0 ? In my case he is duplicating only data from the first company multiplied by the number of companies I have (27) if I use the PowerBI Business Central connector. I'm logged in with an organization account.
Regs,

Tobias

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f562094f-cff2-2c71-c806-e548041718e2
* Version Independent ID: 4f1e5021-2ea3-ba4b-8da8-a999589b8962
* Content: [Setup Reporting for Business Central in Power BI - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-use-financials-data-source-powerbi#feedback)
* Content Source: [business-central/across-how-use-financials-data-source-powerbi.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-how-use-financials-data-source-powerbi.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi toblan,

This field is for submitting feedback about the docs. You might want to ask your question in the Dynmaics 365 Business Central forum here: [https://community.dynamics.com/business/](https://community.dynamics.com/business/)
I'm closing the issue as it is a question about product functionality.
