### ISSUE TITLE
documentation incomplete

### ISSUE THREAD

**Issue by iruser2** [MicrosoftDocs/dynamics365smb-docs#187]
To add prepayment accounts to the general posting setup
Choose the Lightbulb that opens the Tell Me feature icon, enter General Posting Setup, and then choose the related link.

On the General Posting Setup page, fill in the following fields:

Sales Prepayments Account
Purch. Prepayments Account

I do not have these two fields on this window.

Am i supposed to add them as a code?  The documentation is lacking this vital step.

thanks!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d098146a-7e71-1482-d079-4ac02dc113ac
* Version Independent ID: 6005a455-0cf6-ec5d-a221-05bfd3ff453c
* Content: [Set Up Prepayments - Business Central](https://docs.microsoft.com/en-ca/dynamics365/business-central/finance-set-up-prepayments)
* Content Source: [business-central/finance-set-up-prepayments.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-set-up-prepayments.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by iruser2** [comment]
further to this..... if you open the general posting window via the lookup the smaller popup window does not have a scroll bar on it to see the fields.

if you open the window from the menus the screen has a scrolling bar to see the fields.

the question still stands however what am i filling these accounts in for?  There are gen bus posting groups and gen prod posting group.  in my sandbox 14 combinations there of.  Am i filling in a GL account for the prepayments for each of the combinations?

**Comment by edupont04** [comment]
Hello iruser2,

Thank you for your feedback! If you search for General Posting Setup and open the page that way, both fields are available as columns in the list. If you cannot see the fields even when you scroll to the right, then it sounds like your profile does not have access to the prepayments functionality, and you might want to check with your administrator. In the standard version of Business Central, the Sales Prepayment Account field is shown between the Sales Payment Tolerance Credit Account (Sales Pmt. Tol. Credit Acc.) and Purchasing Account (Purch. Account) fields.

The General Posting Setup page is a powerful tool for setting up the different accounts and other information that ensures that everything is filed correctly when someone in your company posts a document, such as an invoice.

You can specify the same G/L account to be used for all prepayments related to all general business posting groups or general product posting groups, or you can specify specific accounts for specific posting groups. This depends on your company's requirements for tracking prepayments.

I hope this unblocks you. I will get the content updated to make it clearer how to find the fields, and this update will be available here within a week.

**Comment by edupont04** [comment]
Live in English (US) here: https://docs.microsoft.com/en-us/dynamics365/business-central/finance-set-up-prepayments
