### ISSUE TITLE
Power BI dataset for finance doesn't work

### ISSUE THREAD

**Issue by jland555** [MicrosoftDocs/dynamics365smb-docs#188]
Following these instructions, and they work for other datasets, but when trying to connect to finance, it gives the error:  "Data source errorThe 'Number' column does not exist in the rowset. Table: powerbifinance."  Contacted Power BI support, but they don't seem to know how to troubleshoot this.  Others have reported the same issue.  Not sure where to go or how to fix this for clients.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6976a9f3-8aa6-4672-c0d0-cdab7dbac0fc
* Version Independent ID: 1e64d529-a3ed-9ba2-f95e-d283ff21238f
* Content: [Business Central and Power BI Content Packs - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-powerbi#feedback)
* Content Source: [business-central/admin-powerbi.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-powerbi.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi jland555,

We've become aware that the content pack is currently broken due to a field being renamed. The team has been working on providing an update to the content pack, and it should be updated now, I have been told.
I'm closing this issue since it's not related to the content.
