### ISSUE TITLE
To create the purchase order for drop shipment

### ISSUE THREAD

**Issue by AlessandroDev95** [MicrosoftDocs/dynamics365smb-docs#189]
Refer to the following link to solve the missed field Sell-to Customer No. in the UI:
https://community.dynamics.com/nav/f/34/t/313710

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f773c52d-84a2-eac7-00a9-b8c24f5dffb7
* Version Independent ID: 5afdc112-18e8-7984-e382-d9b1a3858fa8
* Content: [Link a Sales Order to a Purchase Order for Direct Shipment - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-drop-shipment#feedback)
* Content Source: [business-central/sales-how-drop-shipment.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/sales-how-drop-shipment.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
This has been fixed to refer to the new field, **Ship-to** and the **Customer Address** option. The update will be available within one week.
