### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by dkip05** [MicrosoftDocs/dynamics365smb-docs#19]
"When yo have set up a salesperson..."

*you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5aee9a8a-3f86-20f3-90f3-661cf756bfea
* Version Independent ID: 77f7b776-7664-20d2-19d5-7f692fb84614
* Content: [Set Up a Salesperson - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-setup-salespeople)
* Content Source: [business-central/sales-how-setup-salespeople.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/sales-how-setup-salespeople.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thanks for finding the typo! This has been fixed in the private repo and will be updated accordingly here when we next publish a doc refresh - no later than October.
