### ISSUE TITLE
what about D and T for date and time

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#190]
mention these?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96fd662-e905-9df6-60f5-c709f92077c1
* Version Independent ID: 172fd943-0f5c-6d4c-b764-ced7fd077a96
* Content: [Keyboard Shortcuts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/keyboard-shortcuts)
* Content Source: [business-central/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/keyboard-shortcuts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SorenGP** [comment]
I have added a section for shortcuts in date fields for "w" and "t". The update will be available within one week.

**Comment by SorenGP** [comment]
See also here: https://docs.microsoft.com/en-us/dynamics365/business-central/ui-enter-date-ranges
