### ISSUE TITLE
how do you save the entries back to BC?

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#191]
I can edit but how does this come back into BC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d8fc6f4-3264-8336-038c-6c5ba7aa22df
* Version Independent ID: 56f76b91-51c4-98d5-ce6a-15cd52dea2d2
* Content: [Viewing and Editing in Excel From Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-work-with-excel)
* Content Source: [business-central/across-work-with-excel.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-work-with-excel.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SorenGP** [comment]
When you use the **Edit in Excel** action, you save it back to BC by publishing. Watch the video.
