### ISSUE TITLE
Privacy Block

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#193]
how does this function work and what is the benefits.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450f9b98-bead-cd35-a10c-ccb67995c9e8
* Version Independent ID: 251d06f2-9ff2-3f53-f5e9-53597ae4d771
* Content: [Create a Customer Card to Register New Customers - Business Central](https://docs.microsoft.com/en-NZ/dynamics365/business-central/sales-how-register-new-customers)
* Content Source: [business-central/sales-how-register-new-customers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/sales-how-register-new-customers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello makdaddy888,

The Privacy Blocked field is used in the context of requests about personal data. For more information, see [https://docs.microsoft.com/en-us/dynamics365/business-central/admin-responding-to-requests-about-personal-data](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-responding-to-requests-about-personal-data).
Closing issue.

**Comment by makdaddy8888** [comment]
Hi Eva

Can you add 2 things to the faq section?

1. Can I mix bc subscriptions
2. As a partner do I need a subscription to help test functionally or log into sandbox environments to test wave releases.

Thanks 

Kind Regards
Ben Opit
+61411707070
