### ISSUE TITLE
Payment Method Code

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#194]
Can you explain more on this feature? What is the purpose. How does it interact with BC

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450f9b98-bead-cd35-a10c-ccb67995c9e8
* Version Independent ID: 251d06f2-9ff2-3f53-f5e9-53597ae4d771
* Content: [Create a Customer Card to Register New Customers - Business Central](https://docs.microsoft.com/en-NZ/dynamics365/business-central/sales-how-register-new-customers)
* Content Source: [business-central/sales-how-register-new-customers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/sales-how-register-new-customers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hi makdaddy888,

You can read about payment methods here:
[https://docs.microsoft.com/en-us/dynamics365/business-central/finance-payment-methods](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-payment-methods)

**Comment by makdaddy8888** [comment]
I don’t think that helped.

Kind Regards
Ben Opit
+61411707070

**Comment by edupont04** [comment]
Hi Ben,
OK, but what kind of content are you looking for concerning payment methods?

**Comment by makdaddy8888** [comment]
What was the original question?

Kind Regards
Ben Opit
+61411707070

**Comment by SorenGP** [comment]
A link has been added from "Register New Customers" to "Defining Payment Methods", which we believe is an effective help topic.
