### ISSUE TITLE
Shiping Advice lable is not correct

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#195]
This should be called Allow Partial Shipping

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450f9b98-bead-cd35-a10c-ccb67995c9e8
* Version Independent ID: 251d06f2-9ff2-3f53-f5e9-53597ae4d771
* Content: [Create a Customer Card to Register New Customers - Business Central](https://docs.microsoft.com/en-NZ/dynamics365/business-central/sales-how-register-new-customers)
* Content Source: [business-central/sales-how-register-new-customers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/sales-how-register-new-customers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
This field is not mentioned Help. It is documented by the tooltip only. In UI, the field is named as follows. 
![image](https://user-images.githubusercontent.com/15833976/68593457-ccc01500-0495-11ea-9748-386a88966777.png)

If you prefer another name, please suggest it as an idea here: https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central
