### ISSUE TITLE
O365 SMTP Setup and 2FA

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-docs#198]
It would be good to note that if you are using an account that requires two factor authentication that the password that has to be used in the SMTP setup is an "App Password" setup for that account from the accounts O365 user profile.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0171dfbc-61f2-e62e-f4a3-bb641b15c3e2
* Version Independent ID: 51deab1e-0243-3178-7640-01bb91591fca
* Content: [Set up email in Business Central - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/admin-how-setup-email#feedback)
* Content Source: [business-central/admin-how-setup-email.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-how-setup-email.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello GreatScott000,

Thank you for your feedback! You're right that the article doesn't describe this scenario, which is becoming more and more common. I'll get that sorted next week.

**Comment by SorenGP** [comment]
This has been added to the topic. The update will be available within one week.
