### ISSUE TITLE
No serial numbers

### ISSUE THREAD

**Issue by martinbirk** [MicrosoftDocs/dynamics365smb-docs#199]
Hi, the picking lists don't contain serial numbers that were entered in the system. There is only an empty line on the printout.
Regards
Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02eef5e2-6cfb-d117-0141-d4244be5bb13
* Version Independent ID: 65355ba2-6fe3-f6c4-1ec3-732d54df6fcf
* Content: [How to Print an Inventory Picking List from a Sales Order - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/switzerland/how-to-print-an-inventory-picking-list-from-a-sales-order#feedback)
* Content Source: [business-central/LocalFunctionality/Switzerland/how-to-print-an-inventory-picking-list-from-a-sales-order.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Switzerland/how-to-print-an-inventory-picking-list-from-a-sales-order.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hi martinbirk,
If you think you have technical problems with your Business Central, then please submit a support request. For more information, see [Report a problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).
Alternatively, check the [Business Central forum](https://community.dynamics.com/business/f/758).
