### ISSUE TITLE
Sales Shipments

### ISSUE THREAD

**Issue by jmbarneck** [MicrosoftDocs/dynamics365smb-docs#20]
There is no option "Sales Shipments" in Business Central. Perhaps this should be "Posted Shipment"?

Also where is the "Track Package" action?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e052224-f893-a230-8e1a-6e8714fd7f55
* Version Independent ID: 273d10db-841d-8a59-209e-51c401a54321
* Content: [How to Track Packages - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-track-packages#feedback)
* Content Source: [business-central/sales-how-track-packages.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/sales-how-track-packages.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Sorry for the delay in getting back to you due to the summer.
If you type Sales Shipment in the search field, then the first hit is "Posted Sales Shipment". So the step is not wrong.
The "Track Package" action is currently hidden. You can suggest to get it shown on the Ideas site (https://experience.dynamics.com/ideas/list/?forum=e288ef32-82ed-e611-8101-5065f38b21f1)

**Comment by edupont04** [comment]
Hello again,
Thank you for your feedback! I have taken it back to the team, and their answer is that the Track Package action is currently hidden but can be added as described in the FAQ: https://docs.microsoft.com/en-us/dynamics365/business-central/across-faq#why-are-some-ui-elements-that-i-used-in-dynamics-nav-not-visible-in-

I realize that this is not what you are looking for, and I have submitted a change to the article to make it clearer. 

Best regards
Eva Dupont
Business Central team
