### ISSUE TITLE
SLA and uptime guarantees 

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#200]
Where do we find a list of SLA's for Business Central?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ab5e24c-39f4-3546-e394-3094e6d9995b
* Version Independent ID: ffe59256-abb6-911b-66b1-c9ee7f553adc
* Content: [Compliance - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/compliance/compliance-overview)
* Content Source: [business-central/compliance/compliance-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/compliance/compliance-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by edupont04** [comment]
Hello makdaddy8888,
The owner of this article is on vacation, so please bear with me. 
We have not published an official SLA, but Business Central online is governed under the [Modern Lifecycle Policy]( https://support.microsoft.com/en-us/help/30881/modern-lifecycle-policy) and relies on the [SLA of the Azure services](https://azure.microsoft.com/en-us/support/legal/sla/sql-database/v1_3/) that Business Central is part of.
You can monitor your tenant's health and specify upgrade windows in the [Tenant Administration Center](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center).

I hope this answers your questions.

**Comment by edupont04** [comment]
Hi again @makdaddy8888,
You can find the service level agreements and other license terms here:
[https://www.microsoft.com/en-us/licensing/product-licensing/products](https://www.microsoft.com/en-us/licensing/product-licensing/products)
I'll get that link added to the docs for easy discoverability.

**Comment by makdaddy8888** [comment]
Can you point me to the exact section?

I think this link sends me elsewhere.

I want to know what the uptime guarantees are please.

**Comment by edupont04** [comment]
You go to https://www.microsoft.com/en-us/licensing/product-licensing/products, scroll down to the section for "https://www.microsoft.com/en-us/licensing/product-licensing/products", choose your language (I assume English would work for you), and allow your browser to download the Word document. Then open that Word document, and in the table of contents, under Service Specific Terms, click the link for Business Central.

**Comment by edupont04** [comment]
Updated accordingly: 
[https://docs.microsoft.com/en-us/dynamics365/business-central/compliance/compliance-service-compliance#service-terms](https://docs.microsoft.com/en-us/dynamics365/business-central/compliance/compliance-service-compliance#service-terms)

**Comment by makdaddy8888** [comment]
Thank you

Perfect!

What happens if bc is not working for let’s say 8 hours how does the maths work?

Kind Regards
Ben Opit
+61411707070
