### ISSUE TITLE
Typing Error under the heading : Making changes to a Word report layout

### ISSUE THREAD

**Issue by quratulaindawood** [MicrosoftDocs/dynamics365smb-docs#203]
Instead of "To can make general formatting.." it should be "To make general formatting..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 562ba9ca-f395-bbeb-0775-5a85696e0935
* Version Independent ID: 58c23bed-523d-0432-f76e-2930232816f6
* Content: [Create and Modify Custom Layouts for Reports and Documents - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-create-custom-report-layout#feedback)
* Content Source: [business-central/ui-how-create-custom-report-layout.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-how-create-custom-report-layout.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SorenGP** [comment]
Fixed. The update will be available within one week.
