### ISSUE TITLE
It was possible to view the xml file with preview in the IE with a stylesheet

### ISSUE THREAD

**Issue by Kielkenny** [MicrosoftDocs/dynamics365smb-docs#204]
Now this is not possible anymore due to the change of the format of the xml file. Within an escalation the old stylesheet was changed and it is possible again to view the xml file in a nice way. 

So we should change above 3. and state:
- in XSL-Filename point to the ustva.xsl file supporting the new interface

And if possible we should add the zip archive with the needed files. If you need more info, please get in touch with me. I have the files available. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78dcab06-54a7-b294-6177-ee94cf0f3961
* Version Independent ID: ef998283-d874-c10c-49e6-7b55c170cd24
* Content: [How to Set Up and Export Sales VAT Advance Notifications - Business Central](https://review.docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/germany/how-to-set-up-and-export-sales-vat-advance-notifications?branch=master#feedback)
* Content Source: [business-central/LocalFunctionality/Germany/how-to-set-up-and-export-sales-vat-advance-notifications.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Germany/how-to-set-up-and-export-sales-vat-advance-notifications.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by edupont04** [comment]
Closing as internal.
