### ISSUE TITLE
Availability guarantee

### ISSUE THREAD

**Issue by PeterWone** [MicrosoftDocs/dynamics365smb-docs#205]
Apropos of #200, cloud has merits for things that can wait for outages, but there is risk in making production dependent on you, two telcos and a carrier, and I know from bitter experience that all involved will point the finger and walk away.

If you sincerely believe there's no risk then you won't mind giving us a binding service level agreement in which you accept liability for all production down-time and consequential costs irrespective of the reason for the outage. 

Meanwhile back in reality, where's the comprehensive, detailed documentation for deployment of on-prem and hybrid including consequences for authentication and authorisation?

**Comment by edupont04** [comment]
Hi @PeterWone ,
You can find the service level agreements and other license terms here:
[https://www.microsoft.com/en-us/licensing/product-licensing/products](https://www.microsoft.com/en-us/licensing/product-licensing/products)
The document that you get in the "Service Level Agreements for Microsoft Online Services (SLA)" section includes a section specifically about Dynamics 365 Business Central, and I hope that answers your concerns. I'll get that link added to the docs for easy discoverability.

As for deployment considerations, here is a link to our current content: 
[https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/deployment](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/deployment)
