### ISSUE TITLE
Suggested improvement to section 'Correcting GST/VAT Amounts'

### ISSUE THREAD

**Issue by tfcrowther** [MicrosoftDocs/dynamics365smb-docs#206]
To adjust GST/VAT for a SALE/PURCHASE document
1.	Open the relevant  order.
2.	Choose the Statistics action.
3.	Choose the Invoicing FastTab.
4.	Drill down the No. of Tax Lines
5.	Manually change the GST/VAT Amount

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 575da794-2931-9b96-521c-744677513f36
* Version Independent ID: 2739bc61-f1db-4814-1980-8d60e50f5fdd
* Content: [How to work With GST on Sales and Purchases - Business Central](https://docs.microsoft.com/en-nz/dynamics365/business-central/finance-work-with-vat#feedback)
* Content Source: [business-central/finance-work-with-vat.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-work-with-vat.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by SorenGP** [comment]
Thank you for the feedback. The topic has been updated and will be available within one week. Note that the translated NZ version will not be available until the next translation pass, within one month.
