### ISSUE TITLE
borken / missing link

### ISSUE THREAD

**Issue by SamMalak** [MicrosoftDocs/dynamics365smb-docs#207]
France (Tax Audit Certification) (link to certification in French) results in page not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fb5c9d0-0b88-dca2-31cb-d9bafe77ea1a
* Version Independent ID: b8851ab3-1fbf-08b7-ce7f-0137310737c4
* Content: [Certifications - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/compliance/compliance-certifications#feedback)
* Content Source: [business-central/compliance/compliance-certifications.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/compliance/compliance-certifications.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by edupont04** [comment]
Thank you for your feedback! Indeed the link is currently broken, presumably due to the French authorities having changed something on their website. The owner of the article is currently on vacation, and he'll investigate once he is back.

**Comment by SamMalak** [comment]
Thanks Eva

Cordialement,
[https://www.absyscyborg.com/images/logo-absys01.png]
Sam MALAK
Directeur de Projet International
Tél. : +33 6 98 66 96 48
smalak@absyscyborg.com
https://www.absyscyborg.com<https://www.absyscyborg.com/>
[http://www.absyscyborg.com/images/SignatureOutlook/facebook.png]<https://www.facebook.com/AbsysCyborg>[http://www.absyscyborg.com/images/SignatureOutlook/linkedin.png]<https://www.linkedin.com/company/absys-cyborg>[http://www.absyscyborg.com/images/SignatureOutlook/twitter.png]<https://twitter.com/AbsysCyborg>[http://www.absyscyborg.com/images/SignatureOutlook/youtube.png]<https://www.youtube.com/channel/UC8_AC9yIZHXlhR8JH91pIrg/playlists>

Ce message et tous les fichiers qui y sont attachés contiennent des informations confidentielles, exclusivement destinées à la personne à laquelle elles sont adressées. Dans l'hypothèse où ce message ne vous serait pas destiné, nous vous remercions de le retourner immédiatement à son émetteur et de le supprimer. La publication, la distribution, l'impression ou tout autre usage non autorisé de ce message est strictement interdit. Les idées et opinions contenues dans ce message sont celles de son auteur et ne représentent pas nécessairement celles d'Absys Cyborg.
P Pensez à l'environnement. N'imprimez que si vous en avez vraiment besoin.

De : Eva Dupont <notifications@github.com>
Envoyé : vendredi 19 juillet 2019 11:59
À : MicrosoftDocs/dynamics365smb-docs <dynamics365smb-docs@noreply.github.com>
Cc : Sam MALAK <SMALAK@absyscyborg.com>; Author <author@noreply.github.com>
Objet : Re: [MicrosoftDocs/dynamics365smb-docs] borken / missing link (#207)


Thank you for your feedback! Indeed the link is currently broken, presumably due to the French authorities having changed something on their website. The owner of the article is currently on vacation, and he'll investigate once he is back.

**Comment by edupont04** [comment]
Just confirming that the current certificate is now published here: [https://certificates.infocert.org/certificates/CERTIF-07-181-R16.pdf](https://certificates.infocert.org/certificates/CERTIF-07-181-R16.pdf)
The article will be updated with the right path in a few days.
