### ISSUE TITLE
You can only select computer check if (rest of sentence missing)

### ISSUE THREAD

**Issue by hougaard** [MicrosoftDocs/dynamics365smb-docs#208]
**Select this option if you want to print a check for the amount on the payment journal line. You must print the checks before you can post the journal lines. You can only select Computer Check if**

The rest of the sentence is missing? If what?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1adf0934-d42d-4e71-18bb-96348ca6be4f
* Version Independent ID: f02164f3-e859-8c1c-65f4-dcf4ec6de09d
* Content: [Issue, Print, Cancel, and Void Checks - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/payables-how-work-checks)
* Content Source: [business-central/payables-how-work-checks.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/payables-how-work-checks.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
This is fixed. The update will be available within one week.
