### ISSUE TITLE
Design Details: Code Examples of Changed Patterns in Modifications

### ISSUE THREAD

**Issue by srenders** [MicrosoftDocs/dynamics365smb-docs#209]
The URL does not work, it points to the current page and not to any examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84cbf19a-2701-d4d5-d232-20127179b557
* Version Independent ID: e2ddbaf2-327a-d3f6-dfdf-1c80d6b5d595
* Content: [Design Details - Dimension Set Entries - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-dimension-set-entries#feedback)
* Content Source: [business-central/design-details-dimension-set-entries.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-dimension-set-entries.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
This has been fixed.
