### ISSUE TITLE
Base Calendars

### ISSUE THREAD

**Issue by DaveBoehmPBSI** [MicrosoftDocs/dynamics365smb-docs#21]
The documentation indicates we should create a base calendar in BC.  This is used to determine shipping dates, etc.

If you use the magnifying glass to "find" "Base Calendar", the page doesn't actually exist.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 763fbd8c-419e-8f6a-fe92-ae5391f88b1d
* Version Independent ID: 085f9959-e6d6-4854-d388-e2fbce91358a
* Content: [How to Set Up Base Calendars - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/across-how-to-assign-base-calendars)
* Content Source: [business-central/across-how-to-assign-base-calendars.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-how-to-assign-base-calendars.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Hi Dave - Thanks for your input. 

The Base Calendar feature has been made accessible in the latest version, so will be publicly available soon. 

Note: Going forward, please use the "Product feedback" button for this type of input.

Regards
Soren, Business Central writer
