### ISSUE TITLE
"Detailed Lines Description" setup not self explanatory

### ISSUE THREAD

**Issue by Kielkenny** [MicrosoftDocs/dynamics365smb-docs#211]
Please add a section explaining the field "Detailed Lines Description" in the finance charge terms. That that one is only used if multiple interest rates are setup in order to put a sum to the additional created finance charge lines. It is not explained in the tooltip. The tooltip is basically copied from the Line Description one. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c53c6c-611f-4167-9c00-7f1c3d8bf62d
* Version Independent ID: a1c00cab-64fb-2443-5c35-cf989e0f02e1
* Content: [Remind or Fine Customers of Overdue Payments - Business Central](https://review.docs.microsoft.com/en-us/dynamics365/business-central/receivables-collect-outstanding-balances?branch=master#feedback)
* Content Source: [business-central/receivables-collect-outstanding-balances.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/receivables-collect-outstanding-balances.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thanks for the feedback. The tooltip will be fixed in a future update soon.
