### ISSUE TITLE
Paths are not available anymore. 

### ISSUE THREAD

**Issue by Kielkenny** [MicrosoftDocs/dynamics365smb-docs#212]
The following fields are not available anymore, please remove from description.
(See TFS 316184)
Export Reference Payments
Import Reference Payments
Currency Exchange Rate File
Export Foreign Payments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 216f0ac2-e4e4-87cd-2ab6-39f312e2c506
* Version Independent ID: 118588a4-e266-6c33-26a5-a0316a4ec293
* Content: [How to Set Up Bank Reference Files - Business Central](https://review.docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/finland/how-to-set-up-bank-reference-files)
* Content Source: [business-central/LocalFunctionality/Finland/how-to-set-up-bank-reference-files.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Finland/how-to-set-up-bank-reference-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Pending Pm returning from vacation.

**Comment by SorenGP** [comment]
Fixed. Will be live within one week.
