### ISSUE TITLE
Translation in Dutch is wrong in above table

### ISSUE THREAD

**Issue by jejesmit** [MicrosoftDocs/dynamics365smb-docs#214]
In the first column it says "Onderhoud" which should not be translated but kept "Service", because it is the name of the type of Item. 
Furthermore in the rest of the table it says "Nr." where the translation must be "Nee". English "No" can refer to Number as well as the opposite of Yes. In this case it is not ment as a Number but as a "Not possible" or "No", so in Dutch it must then be "Nee".

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: ea248ae7-d4ca-5879-0785-d097f3250b5a
* Version Independent ID: adefc344-0777-caa6-7052-416302d9dbb8
* Content: [Artikeltypen - Business Central](https://docs.microsoft.com/nl-NL/dynamics365/business-central/inventory-about-item-types#feedback)
* Content Source: [business-central/inventory-about-item-types.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-about-item-types.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
This will be fixed in the next translation round.
