### ISSUE TITLE
Out of Date Instructions

### ISSUE THREAD

**Issue by Bob-Dzimbowski** [MicrosoftDocs/dynamics365smb-docs#216]
I don't find the options mentioned in this document. I think it is out of date. Also I am using cloud.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee3de901-2ce9-aa4c-2161-a2f2ee9b163b
* Version Independent ID: ac8d678c-f006-2425-fd82-3b7f44c037b0
* Content: [Setting Up and Using a Purchase Approval Workflow - Business Central](https://docs.microsoft.com/en-CA/dynamics365/business-central/walkthrough-setting-up-and-using-a-purchase-approval-workflow#feedback)
* Content Source: [business-central/walkthrough-setting-up-and-using-a-purchase-approval-workflow.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/walkthrough-setting-up-and-using-a-purchase-approval-workflow.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Fixed. Will be available within one week.
