### ISSUE TITLE
Security Role "Solution Customizer"

### ISSUE THREAD

**Issue by james-reinhardt** [MicrosoftDocs/dynamics365smb-docs#217]
This page, and many others reference a "Solution Customizer" security role. Is this the CRM "System Customizer" role? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2957b832-9aee-e050-b034-7f3badb2e27c
* Version Independent ID: a93b51b9-9a52-c8a2-2197-38c02f2e327f
* Content: [Integrating with Dynamics 365 for Sales - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/admin-prepare-dynamics-365-for-sales-for-integration)
* Content Source: [business-central/admin-prepare-dynamics-365-for-sales-for-integration.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-prepare-dynamics-365-for-sales-for-integration.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! Our apologies for the very long wait for an answer!

A member of our team has at long last reviewed your feedback. The article in question no longer refers to that role.
