### ISSUE TITLE
the manual link is no longer valid

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#219]
The URL for outlook on the web appears to have changed.  When I log in now it is:
https://outlook.office365.com/mail/inbox
not the old /owa/ one.  Can you update this page to reflect the new path.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5de7e901-0044-f73a-2564-a3a6e236b49c
* Version Independent ID: a59b13cd-0eba-3e69-d5ed-1a5a0cc7523f
* Content: [Using Business Central with Outlook - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/admin-outlook#feedback)
* Content Source: [business-central/admin-outlook.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-outlook.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi @chris7777au ,

Thank you for your feedback! It sounds like you're using the new Outlook on the web, and I hope you enjoy the new experience. In the new Outlook on the web, getting to the add-ins is a bit complicated, but it's doable. I've updated the steps in our article, and that will be available on the en-us version of our docs in a few days, and the Australian version will be updated in a few more weeks.
In the meanwhile, here is how our colleagues in the Outlook team have describes things: 
https://support.office.com/en-us/article/using-add-ins-in-outlook-on-the-web-8f2ce816-5df4-44a5-958c-f7f9d6dabdce#bkmk_beta

**Comment by chris7777au** [comment]
Hi Eva.

I use Outlook on a mac, but the instructions for checking if it’s installed is via outlook on the web.

Chris Pope
Pacsource Pty ltd
6 Dalmore Drive
Scoresby, Victoria 3179
Australia
T. +61.3.9763.4500
M. +61.447.888.777
E. chris@pacsource.com.au
S. chris_7777

Disclaimer ; The information in this email including any attachments is confidential and may be legally privileged. If an addressing or transmission error has misdirected this email please notify the author by replying to this email and destroy the original message. If you are not the intended recipient, any use, disclosure, copying or distributions prohibited and may be unlawful. Distribution of this email to other parties may result in criminal prosecution.

**Comment by edupont04** [comment]
Hi @chris7777au ,
I haven't tested this on a Mac, but at least in Outlook on Windows you can see the Business Central add-ins in the Get Add-Ins list.
This is now mentioned here: https://docs.microsoft.com/en-us/dynamics365/business-central/admin-outlook#adding-the-add-ins-manually
