### ISSUE TITLE
Wrong URL or content?

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-docs#22]
This page is titled "Design Details: Closing Demand and Supply", but the URL is https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-code-examples-of-changed-patterns-in-modifications and I was hoping to find content on "Code examples of changed patterns in modifications"...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56e5e077-e1df-d91a-b509-366b0c2188d5
* Version Independent ID: 54e9a18e-d92c-b46d-c354-1b4984e93799
* Content: [Design Details - Closing Demand and Supply - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-code-examples-of-changed-patterns-in-modifications)
* Content Source: [business-central/design-details-code-examples-of-changed-patterns-in-modifications.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-code-examples-of-changed-patterns-in-modifications.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the input - The content was wrong and has been fixed. It will be available in about one week. Regards, Soren
