### ISSUE TITLE
The concept of a Customer (entity) being a Contact and vice versa

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#221]
Hello.  I've hit my first 'crossover problem' from other ERP systems.  Dynamics365 BC appears to faciliate a Contact (company) being a customer and vice versa.  This concept (whilst possibly a good one), is not familiar (I have used everything from Xero, Netsuite, Oracle E-business Suite..), where the 'customer' is an entity and 'contacts' are assigned to customers (or vendors, competitors or 'groups'), but typically I don't end up with a contact record AND a customer record.  I've hit this issue when I have created contacts in Outlook (Dynamics Contact Insights plug in), but these 'contacts' can be either companies or people (by design).  It would be helpful if this page provided a deeper background on the relationship between 'customer/company' and 'company/contact'.  When would you create a company as a contact only (not a customer).  

This is compounded by the fact that the 'contact list' is not easily accessible from a menu (i.e. you can go to Vendors or Customers, but there isn't an easily accessible 'contacts' menu option to get to the list, so naturally I have gone and created 'customers' as 'companies' we deal with and then added contacts (people who work for those businesses) in.  When I've started to use Outlook, it's all got a little out of place.  Can you expand on the contact to Customer/Vendor relationship and when a user should move a contact(company) to a 'customer' etc.  

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27f7b38c-3cb5-5ba6-6b9d-dbe4ec300642
* Version Independent ID: 20c9e0cf-8d19-e902-e26c-3a23f9a207b4
* Content: [Create and Manage Company Contacts - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/marketing-contacts)
* Content Source: [business-central/marketing-contacts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/marketing-contacts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
The Company/Person aspect is introduced here: https://docs.microsoft.com/en-au/dynamics365/business-central/marketing-create-contact-companies

The strategic decisions about when to create a customer versus a contact is up to you. A general rule could be that as soon as you need to post transactions, the contact card is not sufficient.

I have added a section named "To view which customer, vendor, or bank account a contact is related to".
