### ISSUE TITLE
My Notifications - Is this available as yet?

### ISSUE THREAD

**Issue by heatherr-nz** [MicrosoftDocs/dynamics365smb-docs#222]
I don't get the option when searching in my current version.  Online only.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 257d688e-f2ac-4c71-b3de-a89b5741f32e
* Version Independent ID: 5c07c0b2-5b00-184c-6b4d-cfe8212dc21c
* Content: [Work With Smart Notifications and Specify When You See Them - Business Central](https://docs.microsoft.com/en-NZ/dynamics365/business-central/ui-smart-notifications)
* Content Source: [business-central/ui-smart-notifications.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-smart-notifications.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by heatherr-nz** [comment]
Found this via My Settings, but not by using the search.

**Comment by edupont04** [comment]
Thank you for your feedback! My Notifications is available in certain Role Centers, but we'll make it clearer that it's always available in My Settings.
