### ISSUE TITLE
ReSync Users from Office Portal to dynamics 365

### ISSUE THREAD

**Issue by himalpatel81** [MicrosoftDocs/dynamics365smb-docs#228]
We made certain changes to the user. for example, change the full name of the user in office portal. When we try to import the user on Dynamics 365 side, it doesn't resync the existing user and thus the changes to the Users name are not synced to the Dynamics 365. Same is the case with delete. When we delete the user in office portal, it doesnt remove the user from Dynamics 365 side. 

We are using "Get New uses from Office 365" under process menu in Users in Dynamics 365.

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).
