### ISSUE TITLE
How to delete user once imported in Dynamics 365 ?

### ISSUE THREAD

**Issue by himalpatel81** [MicrosoftDocs/dynamics365smb-docs#229]
How to delete a user from Dynamics 365 once imported ? Edit and Delete is missing from this document.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af56319-74d0-ce95-7f11-48a0b165ed6e
* Version Independent ID: d496d459-af33-c965-a21b-0e2f44d6a2e9
* Content: [Assign or Edit User Permissions - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/ui-how-users-permissions)
* Content Source: [business-central/ui-how-users-permissions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-how-users-permissions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
The info has been added. The update will be avaialable within one week.
