### ISSUE TITLE
How to reset the default tenancy

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#232]
My default tenancy is set to NZ because that where the original tenant was deployed. I want AU to be the default. What is this process?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f71861b3-1f71-62fa-9cff-c49138d9b1fb
* Version Independent ID: 560d0c1c-41db-e23c-5ad6-66591b493277
* Content: [Multilanguage and Localization - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/about-locale-language#feedback)
* Content Source: [business-central/about-locale-language.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/about-locale-language.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi makdaddy8888,
As described, you can change the user interface language in your Business Central tenant, but you cannot change the country that your tenant is created in. So you would need to create a new tenant in Australia in order to get have a company that is based on Australian local functionality.
However, the NZ and AU versions of Business Central are almost identical.

**Comment by makdaddy8888** [comment]
Thanks Eva

Can you add this to the docs? 

Kind Regards
Ben Opit
+61411707070

**Comment by edupont04** [comment]
Hi Ben (@makdaddy8888),

When your Business Central tenant has been updated to the latest version (check if it says version 15 in the Help and support page, for example), then you can create a new environment based on the Australian version in the Business Central administration center. A link will be added to this article very soon, but here is the direct link: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-environments#create-a-new-production-environment
