### ISSUE TITLE
more features required

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#233]
This is extremely basic for HR requirements. Can some additional features be added here? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaf3e258-8176-f91f-2631-b68017b12866
* Version Independent ID: b70573b8-977b-1cf3-72c9-eaafdbe38615
* Content: [Using Human Resources Functionality - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/hr-manage-human-resources)
* Content Source: [business-central/hr-manage-human-resources.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/hr-manage-human-resources.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Please suggest on Ideas: https://experience.dynamics.com/ideas/
