### ISSUE TITLE
Teams License

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#234]
What are the functions in details on what Teams license can offer? Can this be added to docs rather than the licensing diagram.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58f9ee31-e93e-cd88-67e3-4107c0f7ad81
* Version Independent ID: fdac35d7-1fba-c960-5a27-28e7cdc2ac60
* Content: [Meet Microsoft Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/)
* Content Source: [business-central/index.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/index.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Information about licenses may change and is therefore maintained in the separate "Microsoft Dynamics 365 Business Central
Licensing Guide", which we link to from Business Central help, e.g. from here: https://docs.microsoft.com/en-us/dynamics365/business-central/ui-experiences
