### ISSUE TITLE
how to enter time against a resource in the salesline

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#235]
i can create a quote and add a resource but I cannot enter in times against this resource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b4f6740-496c-0f6a-83e6-722e2e62f671
* Version Independent ID: 512d5f71-0766-e9bc-f224-5b930c610759
* Content: [Set Up Resource Costs, Prices, and Capacity - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/projects-how-setup-resources)
* Content Source: [business-central/projects-how-setup-resources.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/projects-how-setup-resources.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
You quote resource times by filling in the **Quantity** field per the value in the **Unit of Measure Code** field, such as "HOUR". This is described in step 11 here: https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-make-offers
