### ISSUE TITLE
Lack of Details on Directed Pick Logic

### ISSUE THREAD

**Issue by markborges** [MicrosoftDocs/dynamics365smb-docs#236]
Hi, I have been researching these docs for the past hour and I cannot find a clear determination on how the Pick Logic works for Directed scenarios. When I have multiple Bin Contents for the Same Item, Same Bin Ranking, it's not clear what will be the logic to determine the next steps for defining a pick bin. Is this documented somewhere? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdfa7344-a472-11d8-3584-3677883845db
* Version Independent ID: e0af4d18-333c-f1f9-3669-231ba723eef2
* Content: [Pick Items - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/warehouse-pick-items#feedback)
* Content Source: [business-central/warehouse-pick-items.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/warehouse-pick-items.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Have you looked under Setting Up Warehouse Management: https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-warehouse-setup.

Also, these Design Details: Warehouse Setup (former technical white paper content) may help:  https://docs.microsoft.com/en-us/dynamics-nav-app/design-details-warehouse-setup
