### ISSUE TITLE
SN-Specific Warehouse Tracking and Lot-Specific Warehouse Tracking are not fields

### ISSUE THREAD

**Issue by markborges** [MicrosoftDocs/dynamics365smb-docs#237]
Hi, SN-Specific Warehouse Tracking and Lot-Specific Warehouse Tracking are not fields on the Item Tracking Code setup table.

For SN-Specific Warehouse Tracking we have 2 fields: SN Specific Tracking and SN Warehouse Tracking. Does it mean that both have to be activated?

The same applies for Lots.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84775a5d-0d06-4259-c88f-abdacfdcccf7
* Version Independent ID: d98f89e3-c377-a95b-f918-490d4a66aa51
* Content: [How to Enable Picking by FEFO - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/warehouse-picking-by-fefo)
* Content Source: [business-central/warehouse-picking-by-fefo.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/warehouse-picking-by-fefo.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback. The correct check box name has been entered. The change will be available within one week. Note: The **Warehouse Specific Tracking** check box is not related to FEFO. I.e. you can do picking by FEFO without using warehouse documents.
