### ISSUE TITLE
Can I extend the Tell Me page?

### ISSUE THREAD

**Issue by yannstlo** [MicrosoftDocs/dynamics365smb-docs#238]
I would like to add functionality to the tell me page, example: search for a customer, a vendor, an invoice #... 
Can AL Extension be created to add to the TELL ME page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 338187f3-3d4b-0e1e-4b32-809514eccf11
* Version Independent ID: 37556d23-8b14-a8bf-ae3f-5ba85a725969
* Content: [Frequently Asked Questions about Tell Me - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-search-faq)
* Content Source: [business-central/ui-search-faq.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-search-faq.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello @yannstlo 
Thank you for your feedback. This is currently not possible, so you might want to suggest it or vote for an existing feature suggestion at https://aka.ms/bcideas.

Closing the issue as it's a feature request.
