### ISSUE TITLE
Employee Transaction unable to post foreign curreny

### ISSUE THREAD

**Issue by AdamCTC** [MicrosoftDocs/dynamics365smb-docs#239]
Please enable foreign currency transaction in Employee Module in next update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ef7322e-85ec-eaad-738d-843898c5ad76
* Version Independent ID: 84f2f9f2-ebfa-9f63-d633-30f3b8a6036a
* Content: [Record and Reimburse Employees' Business-Related Expenses - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-how-record-reimburse-employee-expenses#feedback)
* Content Source: [business-central/finance-how-record-reimburse-employee-expenses.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-how-record-reimburse-employee-expenses.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Please suggest feature ideas here: https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central
