### ISSUE TITLE
Comments Not Available

### ISSUE THREAD

**Issue by mstallmann** [MicrosoftDocs/dynamics365smb-docs#24]
Comments are not available on this screen.  They don't seem to be available on any master records.  This is a very simple feature that used to be in NAV that should be available.  Very rudimentary.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa21c110-7197-9f9d-be23-b2629400aafe
* Version Independent ID: 4f8067b6-2590-e866-f8fe-bd19136346b4
* Content: [How to Manage Customer Credit Information - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedstates/how-to-manage-customer-credit-information)
* Content Source: [business-central/LocalFunctionality/UnitedStates/how-to-manage-customer-credit-information.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/UnitedStates/how-to-manage-customer-credit-information.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
The Comments functionality is currently hidden with the Application Area system. It will be available in a future update of Business Central. For more  information, see the last section here: https://docs.microsoft.com/en-us/dynamics365/business-central/across-faq
