### ISSUE TITLE
Customer Card - Name 2 

### ISSUE THREAD

**Issue by mserna530** [MicrosoftDocs/dynamics365smb-docs#241]
Docs are unclear as to field descriptions, in addition cannot find Name 2 field on Customer Card - but it is in the Configuration File for Customer (18). What is this field for and where can it be found? Was also not in Personalization on Customer Card or Contacts or Shipping Addresses.

Thank you.

**Comment by edupont04** [comment]
Hello mserna530,

Thank you for your feedback! The Name 2 field is currently not available on the Customer Card, but it is available in the underlying table. The development team will soon announce availability in the release plan: https://docs.microsoft.com/en-us/dynamics365-release-plan/2019wave2/dynamics365-business-central/planned-features
