### ISSUE TITLE
Dimensions and GL Accounts

### ISSUE THREAD

**Issue by murphymcconnell** [MicrosoftDocs/dynamics365smb-docs#243]
The Adjust Currency Batch Job is not useful for GL Accounts in the P&L if it is only using the default dimension for the account rather than calculating the value per dimension combination.  An Additional Reporting Currency becomes useless if it can't accurately reflect the dimensions of the entries.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cbd815c-4e94-b21d-dbfa-411885d4a5dd
* Version Independent ID: f4aced3d-7e1c-6486-f8dc-7749cc9ddd12
* Content: [Update Currency Exchange Rates - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/finance-how-update-currencies#feedback)
* Content Source: [business-central/finance-how-update-currencies.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-how-update-currencies.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
If this is a feature you think is missing in Business Central, please suggest it here here: https://experience.dynamics.com/ideas/
