### ISSUE TITLE
To add a user in Business Central

### ISSUE THREAD

**Issue by dankellett** [MicrosoftDocs/dynamics365smb-docs#244]
In the "To add a user in Business Central" section in point #2 it states "Choose the Get Users from Office 365 action." This action is hidden under the process menu - this isn't obvious and would help if it were mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af56319-74d0-ce95-7f11-48a0b165ed6e
* Version Independent ID: d496d459-af33-c965-a21b-0e2f44d6a2e9
* Content: [Assign or Edit User Permissions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-users-permissions)
* Content Source: [business-central/ui-how-users-permissions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-how-users-permissions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Because users may personalize action locations, Help does not refer to action locations. Note: This topic is restructures and is now named "Create Users According to Licenses."
