### ISSUE TITLE
Update product name from "Business Central" to "Sales"

### ISSUE THREAD

**Issue by sethtbacon** [MicrosoftDocs/dynamics365smb-docs#248]
There appears to be an issue with the product that is being referenced in the first sentence.

"When you integrate Dynamics 365 Sales with Business Central, you can decide whether to synchronize data in selected fields of Business Central records (such as customers, contacts, and sales people) with equivalent records in Business Central (such as accounts, contacts, and users)."

The second mention of "Business Central" should be "Sales" as it reference accounts, contacts, and users which are D365 CE terms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf4cd40b-ac70-ebb4-aca9-dea6ad6bf2f8
* Version Independent ID: ab3ea9a9-83cc-2367-2e48-eb298f03d0c1
* Content: [Synchronization and Data Integration - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-synchronizing-business-central-and-sales#feedback)
* Content Source: [business-central/admin-synchronizing-business-central-and-sales.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-synchronizing-business-central-and-sales.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! Our apologies for the very long wait for an answer!

A member of our team has at long last reviewed your feedback and updated the article in question.
