### ISSUE TITLE
Source Documentation

### ISSUE THREAD

**Issue by burkbry** [MicrosoftDocs/dynamics365smb-docs#249]
Where do I find the source documentation for this page? The following location does not appear to have the latest version:
https://github.com/MicrosoftDocs/dynamics365smb-docs

I'm looking for the "Gaps in Number Series" content.

Let me know.  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4aae8bd7-29e2-3f76-8b79-c1a3b773f85d
* Version Independent ID: 2b8a5553-2d8c-b1ed-f8f3-39c6b974f6ae
* Content: [Create Number Series - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-create-number-series#feedback)
* Content Source: [business-central/ui-create-number-series.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-create-number-series.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by burkbry** [comment]
It appears the content is located in the "repo_sync_working_branch" branch.  I was expecting the content to be in the "Live" branch because the General Availability date for 2019 release wave 2 was October 1, 2019.

**Comment by SorenGP** [comment]
On the live site, the Gaps in Number Series feature is described in the first heading 2 within the Create Number Series topic: https://docs.microsoft.com/en-us/dynamics365/business-central/ui-create-number-series#gaps-in-number-series

**Comment by SorenGP** [comment]
Update: The source files were temporarily out of date. This is now fixed.

**Comment by burkbry** [comment]
Thank you.
