### ISSUE TITLE
Mark Invoicing as Retired On Sales Website

### ISSUE THREAD

**Issue by damienestewart** [MicrosoftDocs/dynamics365smb-docs#252]
Shouldn't it be indicated that Microsoft Invoicing is being retired here as well: https://docs.microsoft.com/en-us/dynamics365/invoicing/about-troubleshooting#feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 802199a0-111d-3423-cad4-0cf8a1c8ec5e
* Version Independent ID: f2b4562c-04d5-4719-1e66-0ff0d3aeaee0
* Content: [Get yourself unblocked - Microsoft Invoicing](https://docs.microsoft.com/en-us/dynamics365/invoicing/about-troubleshooting#feedback)
* Content Source: [invoicing/about-troubleshooting.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/invoicing/about-troubleshooting.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello damienestewart,
Thank your for your feedback. For now, we have put in the notification at the top of this article.
