### ISSUE TITLE
describe "Add. Fee Calculation Types" in Reminder Levels

### ISSUE THREAD

**Issue by dirkree** [MicrosoftDocs/dynamics365smb-docs#253]
Descriptions and an example for "Add. Fee Calculation Types" in Reminder Levels are missing.

I suggest to describe the different "Add. Fee Calculation Types" in Reminder Levels and to add an example, like
- you have one invoice with an amount of 1.100 to appear with level = 1 on a new reminder
- you have Additional Fee Setup for level 1 of
     - Threshold Remaining Amount = 500, Add. Fee per Line = 5, Add. Fee per Line % = 2,00
     - Threshold Remaining Amount = 1000, Add. Fee per Line = 10, Add. Fee per Line % = 5,00

If you use Add. Fee Calculation Type = "Single Dynamic" you get an additional fee calculated with the amount = 65,00.
If you use Add. Fee Calculation Type = "Accumulated Dynamic" you get an additional fee calculated with the amount = 30,00.

… please explain how we these amounts are calculated

**Comment by edupont04** [comment]
Closing as internal.
