### ISSUE TITLE
Withholding Tax in UAE

### ISSUE THREAD

**Issue by Alsiddiq-Pit** [MicrosoftDocs/dynamics365smb-docs#254]
Why Withholding tax function still not exist in UAE United Arab Emirates region in business central ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d3bf397-4c53-90a7-7233-2438ed1a5af7
* Version Independent ID: 2d24a057-38c4-f09c-bf7c-bb1c782b4e01
* Content: [Withholding Tax - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/newzealand/withholding-tax)
* Content Source: [business-central/LocalFunctionality/NewZealand/withholding-tax.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/NewZealand/withholding-tax.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
This feedback mechanism is only monitored by writers looking to improve documentation. Please contact your reselling partner for more information about local functionality in the UAE.
