### ISSUE TITLE
Shortcut for Business Central Help

### ISSUE THREAD

**Issue by pschwambornMC** [MicrosoftDocs/dynamics365smb-docs#255]
In the Graphical Overview Shortcut "Alt+F2 Business Central Help" is wrong. It should be: "Ctrl+F1".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96fd662-e905-9df6-60f5-c709f92077c1
* Version Independent ID: 172fd943-0f5c-6d4c-b764-ced7fd077a96
* Content: [Keyboard Shortcuts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/keyboard-shortcuts)
* Content Source: [business-central/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/keyboard-shortcuts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback. It has been fixed and will be available within one week.

**Comment by SorenGP** [comment]
Now live: https://docs.microsoft.com/en-us/dynamics365/business-central/keyboard-shortcuts
