### ISSUE TITLE
Walkthrough: maximising cash flow and vendor orders

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#256]
Can we please see a walkthrough around the benefits of using cash flow, sales budget, vendor priorities and order promising to determine which products should be purchase. Sometime business need to make decisions when cash flow is low. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff2f22a6-273f-576f-3939-23ebadadb944
* Version Independent ID: 1970df2e-294c-b6b1-c297-664a3749415d
* Content: [Business Process Walkthroughs - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/walkthrough-business-process-walkthroughs#feedback)
* Content Source: [business-central/walkthrough-business-process-walkthroughs.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/walkthrough-business-process-walkthroughs.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by rubenseishima** [comment]
Hello,
Despite taking this long to reply, all I can say is that we do not have plans at this time to publish walkthroughs for those scenarios.
Feel free to reach out for the community, like here: https://community.dynamics.com/business
Additionally, these articles may help you find the answers you are looking for:
* [Walkthrough: Making Cash Flow Forecasts by Using Account Schedules](https://docs.microsoft.com/dynamics365/business-central/walkthrough-making-cash-flow-forecasts-by-using-account-schedules)
* [Calculate Dates for Purchases](https://docs.microsoft.com/dynamics365/business-central/purchasing-date-calculation-for-purchases) / [Calculate Order Promising Dates](https://docs.microsoft.com/dynamics365/business-central/sales-how-to-calculate-order-promising-dates)
* [Prioritize Vendors (payments)](https://docs.microsoft.com/dynamics365/business-central/purchasing-how-prioritize-vendors)

If you have listed the steps and best practices for those scenarios, we [welcome external contributions to the content as described in this article](https://docs.microsoft.com/dynamics365/business-central/dev-itpro/help/contributor-guide#contributing).
