### ISSUE TITLE
OIOUBL betalingsbetingelser ikke mulige at rette i tabel 3 - payment terms

### ISSUE THREAD

**Issue by MikaelTJohansson** [MicrosoftDocs/dynamics365smb-docs#257]
Ud fra jeres guide der skriver følgende:

##Sådan defineres betalingsbetingelser Hvis du angiver betalingsbetingelserne for debitorer, medtages de elektroniske dokumenter rabatter, som du giver for førtidige betalinger.

Vælg ikonet Søg efter side eller rapport, angiv Betalingsbetingelser, og vælg derefter det relaterede link.
I feltet OIOXML-kode skal du vælge en kode for hver betalingsbetingelse, du vil bruge til elektroniske fakturaer.

Så er det ikke muligt at oprette en kode i ovenstående felt, selv ikke ved indlæsning af en konfigurationspakke. 

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 1967419c-b14b-f41a-6516-7ac2bfbd46c2
* Version Independent ID: e5d95a76-47ca-0334-de6f-28a55f85b76d
* Content: [Konfigurere OIOUB-udvidelsen til elektronisk fakturering - Business Central](https://docs.microsoft.com/da-dk/dynamics365/business-central/localfunctionality/denmark/how-to-set-up-oioubl#feedback)
* Content Source: [business-central/LocalFunctionality/Denmark/how-to-set-up-oioubl.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Denmark/how-to-set-up-oioubl.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! Our apologies for the very long wait for an answer!

A member of our team has at long last reviewed your feedback and tested the product. They tell me that they cannot reproduce your experience. So either the product or the docs has been fixed in the meanwhile.
