### ISSUE TITLE
Australian Certifications

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#258]
I heard that Australia is one of the biggest adopters of Business Central. Can we get some accreditation/certifications?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fb5c9d0-0b88-dca2-31cb-d9bafe77ea1a
* Version Independent ID: b8851ab3-1fbf-08b7-ce7f-0137310737c4
* Content: [Certifications - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/compliance/compliance-certifications#feedback)
* Content Source: [business-central/compliance/compliance-certifications.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/compliance/compliance-certifications.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by sorenfriisalexandersen** [comment]
Not sure what you mean. Accreditation for what specifically?

**Comment by makdaddy8888** [comment]
Please close this was meant for suggestions 

Kind Regards
Ben Opit
+61411707070
