### ISSUE TITLE
Staged completions

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#259]
Can we get a check box or some kind of indicator that a job has progress pass stage 1 or stage 2. At the moment the only way to see this is to see the budgeted and acutal job planning lines. 
I'd like to see at an overview what job tasks percentage is completed and a bi report to match.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7d0e112-8f96-e1b0-ce39-4998bc7db75e
* Version Independent ID: 5fe8db51-1f8b-2a0b-a22a-f243448ac043
* Content: [Job Tasks using Resources and Time Sheets - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/projects-manage-projects)
* Content Source: [business-central/projects-manage-projects.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/projects-manage-projects.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Ben,
Thank you for your feedback! Since this is a feature request rather than a correction to the docs, you might want to make the suggestion on the Ideas site at https://aka.ms/bcideas
