### ISSUE TITLE
Assemble to Order - Post Assembly Order

### ISSUE THREAD

**Issue by mstallmann** [MicrosoftDocs/dynamics365smb-docs#26]
It isn't clear to me on the documentation, but it seems to be clear in Business Central that I am unable to post an assembly order generated from a sales order.  The Post button is greyed out for these types of orders.  Customer would like to post separately, but system will not allow.  I am assuming this is to be in line with the items getting consumed and output at the time of order posting.  Please confirm.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ea8a461-764a-c3bb-cb2d-a8b3007bdd66
* Version Independent ID: f3e557dc-8fd3-c6ca-f2c2-b7c0b87ee7ab
* Content: [How to Assemble Items - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/assembly-how-to-assemble-items)
* Content Source: [business-central/assembly-how-to-assemble-items.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/assembly-how-to-assemble-items.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Yes, in assemble-to-order flows, all posting (consumption, output, shipping) happens through the linked sales order. For items set up with Assemble-to-Stock, you can perform posting manually from the assembly order. For more information, see https://docs.microsoft.com/en-us/dynamics365/business-central/assembly-assemble-to-order-or-assemble-to-stock.
