### ISSUE TITLE
Linking to YouTube wrong

### ISSUE THREAD

**Issue by CorpitalMAS** [MicrosoftDocs/dynamics365smb-docs#260]
Under Getting started
1) Setting Up Visual Studio Code for Dynamics 365 Business Central Development links to https://mbspartner.microsoft.com/D365/Videos/101780. It should link to https://www.youtube.com/watch?v=oyLXQiBZx8g
2) Developing in Visual Studio Code for Dynamics 365 Business Central Part 1 links to https://www.youtube.com/watch?v=oyLXQiBZx8g. It should link to https://www.youtube.com/watch?v=04T2pAnXjGQ.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed34ba95-a843-90b0-dd51-c24023ccd9d2
* Version Independent ID: 43259fda-960d-bd7a-97c6-74f569a54e11
* Content: [Developer learning catalog - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/readiness/readiness-learning-developers#feedback)
* Content Source: [business-central/readiness/readiness-learning-developers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/readiness/readiness-learning-developers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by CorpitalMAS** [comment]
Sorry: 2: Should link to https://www.youtube.com/watch?v=ofYS0F5c284

**Comment by edupont04** [comment]
Hi CorpitalMAS,
Thanks for catching those two links! We'll get them updated later this week.

**Comment by edupont04** [comment]
The links are now updated. Closing issue as fixed.
