### ISSUE TITLE
Instructions problem

### ISSUE THREAD

**Issue by Deeptnt** [MicrosoftDocs/dynamics365smb-docs#262]
"Open a report, choose the lookup in the Use default values from field, and then choose the Select from full list action."
How do I open a report?
I have the full list of reports, but no way to open one.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d4fb346-0ffe-7f89-9ca6-56ce1a92b82f
* Version Independent ID: 822a9737-5a78-1d0c-ef1e-2098f54acb7e
* Content: [Apply and Modify Saved Settings on Reports - Business Central](https://docs.microsoft.com/en-ca/dynamics365/business-central/reports-saving-reusing-settings#feedback)
* Content Source: [business-central/reports-saving-reusing-settings.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/reports-saving-reusing-settings.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! You're right that the article is confusing. We'll get that cleaned up in the January round of translations.
To answer your specific question for how to open a report, reports are often run from actions on a page. For example, in the Sales Invoices list page, there's a Reports action in the action bar menu:
![salesinvoices_reports](https://user-images.githubusercontent.com/12425349/146945875-24de8c85-0dc1-4b14-8d1f-078de3b743d4.png)

**Comment by edupont04** [comment]
The article is now updated in English (US). It will be updated in English (CA) in about 4 weeks.
https://docs.microsoft.com/en-ca/dynamics365/business-central/reports-saving-reusing-settings
