### ISSUE TITLE
Cancel FA Entries

### ISSUE THREAD

**Issue by mserna530** [MicrosoftDocs/dynamics365smb-docs#263]
When typing in the Cancel FA Entries into the Tell Me Anything lookup glass nothing appears. Also, the cancel FA does not work when trying to access on the FA ledger. Can we get updated documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0e55595-a2a6-431a-8484-519ee8323668
* Version Independent ID: b936efa5-8763-2c6e-05e9-7d61d23ea5a9
* Content: [Acquire Fixed Assets - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/fa-how-acquire#feedback)
* Content Source: [business-central/fa-how-acquire.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/fa-how-acquire.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello @mserna530,

Thank you for your feedback, and our apologies for the delay in getting back to you! You're right that the guidance is incorrect. the steps should read something like this:

1. Choose the (search) icon, enter FA Ledger Entries, and then choose the related link.
2.  In the FA Ledger Entries page, select the entry or entries that you want to cancel. 
2. Choose the Actions menu, and then choose the Cancel Entries action.
3. Fill in the fields as necessary, and then choose the OK button.

We'll get this corrected in the next doc update.

**Comment by edupont04** [comment]
Now live.
