### ISSUE TITLE
Instructions are incomplete

### ISSUE THREAD

**Issue by mserna530** [MicrosoftDocs/dynamics365smb-docs#265]
To receive more items than specified on the purchase document instructions have a number 2. but then there is nothing after the number '2'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44c4fe80-4e37-08cf-c436-451c658ea9eb
* Version Independent ID: f0c2e419-d6bc-4bae-e0a6-f83f98cacf2e
* Content: [How to Allow Receipts of More Items than Ordered - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/purchasing-how-to-combine-receipts)
* Content Source: [business-central/purchasing-how-to-combine-receipts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/purchasing-how-to-combine-receipts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
This was published by mistake. The original content (combing receipts) has been restored.
