### ISSUE TITLE
Confused about the 'New' shortcut?

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-docs#267]
The 'graphical view' shows 'Shift+N' as shortcut for a new record, while the documentation shows 'Alt+N'.

However, when positioned on the 'Customer List' page, how can I easily create a new entry (cfr. the 'New' action in the ribbon). Alt+N only seems to open the card page of the current record but does not create a new record.

Shift+N on the list page does not work either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96fd662-e905-9df6-60f5-c709f92077c1
* Version Independent ID: 172fd943-0f5c-6d4c-b764-ced7fd077a96
* Content: [Keyboard Shortcuts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/keyboard-shortcuts)
* Content Source: [business-central/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/keyboard-shortcuts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback. The graphical view has been fixed to say **Alt+N** and **Alt+Shift+N**, which are correct for triggering the **New** and **+** actions on cards and documents. The update will be available within one week.

Note: **Alt+N** does create a new record, but it begins by showing templates to base it on, which may give you the impression you are editing an existing record that uses the same template.
