### ISSUE TITLE
Missing a space

### ISSUE THREAD

**Issue by benmarriott-TVT** [MicrosoftDocs/dynamics365smb-docs#268]
You're missing a space on this bit:

Unit Price and Line Amount Including/Excluding VAT on Sales Documents
When you choose an item number in the No. field on a sales document, Business Central fills in the Unit Price field. The unit price comes from either the Item card or the item prices allowed for the item and customer. Business **Centralcalculates** the Line Amount when you enter a quantity for the line.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 575da794-2931-9b96-521c-744677513f36
* Version Independent ID: 2739bc61-f1db-4814-1980-8d60e50f5fdd
* Content: [How to work With VAT on Sales and Purchases - Business Central](https://docs.microsoft.com/en-GB/dynamics365/business-central/finance-work-with-vat#feedback)
* Content Source: [business-central/finance-work-with-vat.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-work-with-vat.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
