### ISSUE TITLE
Correcting Invoice Posted with Incorrect Date

### ISSUE THREAD

**Issue by rtigithub** [MicrosoftDocs/dynamics365smb-docs#27]
An invoice was posted with an incorrect date.  We are unable to cancel or correct because "You cannot cancel / correct this posted purchase invoice because the invoice is based on a purchase order."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c8f216-2ecd-ae0e-a754-05c14bebe5bf
* Version Independent ID: 65149fe7-b68f-68a7-d37e-ac88469a289a
* Content: [Amend or Cancel Unpaid Purchase Invoices - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/purchasing-how-correct-cancel-unpaid-purchase-invoices#see-also)
* Content Source: [business-central/purchasing-how-correct-cancel-unpaid-purchase-invoices.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/purchasing-how-correct-cancel-unpaid-purchase-invoices.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the input - This limitation was missing in Help. Sorry about that.

I have added the following note in the Correct or Cancel Unpaid Purchase Invoices topic:

"This functionality is not possible on posted purchase invoices that are posted from purchase orders. To correct or cancel such a posted purchase invoice with slightly more steps, see Process Purchase Returns or Cancellations."

It will be available in Help within one week.

Regards
Soren

**Comment by mauryfan** [comment]
Good morning,
I have mistakenly accounted for an inventory purchase invoice with incorrect accounting date, 28/08 instead of 28/02.
How can I go about solving this problem? can you change the posting date?
