### ISSUE TITLE
OK shortcut

### ISSUE THREAD

**Issue by NicolaiBohnfeldt** [MicrosoftDocs/dynamics365smb-docs#270]
I miss the CTRL + Enter shortcut to save and close a window. 

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: d96fd662-e905-9df6-60f5-c709f92077c1
* Version Independent ID: 172fd943-0f5c-6d4c-b764-ced7fd077a96
* Content: [Tastaturgenveje - Business Central](https://docs.microsoft.com/da-DK/dynamics365/business-central/keyboard-shortcuts#feedback)
* Content Source: [business-central/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/keyboard-shortcuts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
This has been fixed and will be available within one week.
