### ISSUE TITLE
Add an additional e-mail address or cc e-mail address on the customer account-card

### ISSUE THREAD

**Issue by paulinniger** [MicrosoftDocs/dynamics365smb-docs#271]
Possible to add an additional e-mail address onto the customer account(card), making sure the customer, and a CC receives the electronic invoices to be sent ?  thx,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0171dfbc-61f2-e62e-f4a3-bb641b15c3e2
* Version Independent ID: 51deab1e-0243-3178-7640-01bb91591fca
* Content: [Set up email in Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-how-setup-email#feedback)
* Content Source: [business-central/admin-how-setup-email.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-how-setup-email.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback, but you might want to ask this question in the [Dynamics 365 community](https://community.dynamics.com/business/f/dynamics-365-business-central-forum/) or, potentially, suggest a feature on the [Ideas site](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central).
