### ISSUE TITLE
Extending a trial does not work.

### ISSUE THREAD

**Issue by srenders** [MicrosoftDocs/dynamics365smb-docs#272]
Dear,

It says:
If your first 30-day trial period is expired, you can extend it yourself and things will be business as usual. Just sign in to the demonstration company and start the Extend Trial Period guide from the notification.

But when I, and many others have also reported this to me last week, try this, it does not work. We all get the same error message: "Sorry, you don't have permissions to extend your trial period."
And, we are a SUPER in BC and an admin in O365.

What's wrong here? Is this a bug?
And to confirm, it's the first time we try this in this tenant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dffd5471-dbdb-80b8-56a5-0d6e921eff9f
* Version Independent ID: 9f44b4ef-8069-5747-a78b-a85152996b55
* Content: [Extend Your Trial Version - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-extend-trial#feedback)
* Content Source: [business-central/admin-extend-trial.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-extend-trial.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
As discussed offline, there was a temporary bug in the system, but that has now been fixed so that administrators can again extend the trial as described. Closing issue.
