### ISSUE TITLE
Confirm dialogs with (y)es or (n)o

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#273]
Please add that you can confirm dialogs with (y)es or (n)o now (see [Idea](https://experience.dynamics.com/ideas/idea/?ideaid=14d3f545-4219-ea11-b265-0003ff68f605)). It is language agnostic, e.g. in German it is (J)a or (N)ein.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96fd662-e905-9df6-60f5-c709f92077c1
* Version Independent ID: 172fd943-0f5c-6d4c-b764-ced7fd077a96
* Content: [Keyboard Shortcuts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/keyboard-shortcuts)
* Content Source: [business-central/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/keyboard-shortcuts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
This has been fixed and will be available within one week.
