### ISSUE TITLE
Bank Statement Import - supported formats are ??

### ISSUE THREAD

**Issue by Jeeve65** [MicrosoftDocs/dynamics365smb-docs#274]
On this page some supported file formats are mentioned. However, on the detailed pages ('Telebanking' and 'Import and Reconcile Bank Statements')  different formats are mentioned.
As far as I'm aware, the support for MT940 has been stopped several years ago….. (I think from NAV2013 onwards)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2371b020-c485-474a-913d-f1756d6a76ab
* Version Independent ID: c6023945-8f68-1de5-d12a-f8587b8b72ba
* Content: [Dutch Electronic Banking - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/netherlands/dutch-electronic-banking)
* Content Source: [business-central/LocalFunctionality/Netherlands/dutch-electronic-banking.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Netherlands/dutch-electronic-banking.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! Our apologies for the very long wait for an answer!

A member of our team has at long last reviewed your feedback. The article in question was updated to refer to the data exchange framework since original component was indeed removed.
