### ISSUE TITLE
"post and print" no l0nger exist

### ISSUE THREAD

**Issue by miljance** [MicrosoftDocs/dynamics365smb-docs#275]
The Action "post and print" does not exist since NAV2017. "Post and Send" should be used insted. Please update the Documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2cb8389-84a5-294a-bc81-e2c6dc236e5c
* Version Independent ID: 311de108-2b26-06f1-0c6c-8064692c25bb
* Content: [Posting Sales Documents - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-post-sales#feedback)
* Content Source: [business-central/ui-post-sales.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-post-sales.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
