### ISSUE TITLE
ACH Payments

### ISSUE THREAD

**Issue by mserna530** [MicrosoftDocs/dynamics365smb-docs#279]
This documentation is very unclear for ACH/EFT payments. You first export the file for Vendor remittance, then export the ACH file for the banks - but there is not clear instructions on how to void or delete or correct these lines for errors. You cannot delete the lines once the files have been exported, there is no clear way to void - and once you have exported you cannot make changes to the dimensions because the "check is printed," so the transactions just sit in limbo because they can't be corrected or posted. The documentation really needs to be separated for ACH/EFT payments so it is clear because they don't seem to follow the same rules as the SEPA credit transfers at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ccaa3ee-e77b-9e4e-9a3e-51c055dca6da
* Version Independent ID: cac940f0-d21b-3325-ec26-f740439d9c1f
* Content: [Make Payments with the AMC Banking 365 Fundamentals extension or SEPA Credit Transfer - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/finance-make-payments-with-bank-data-conversion-service-or-sepa-credit-transfer#feedback)
* Content Source: [business-central/finance-make-payments-with-bank-data-conversion-service-or-sepa-credit-transfer.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-make-payments-with-bank-data-conversion-service-or-sepa-credit-transfer.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! Our apologies for the delay in getting back to you on this, but we've made some changes to the article in the meanwhile. You are (still) right that the article is optimized for the European SEPA format, but I have been told that the current description helps users make EFT payments as well.   If you (still) disagree, we'll make another try at making this work.
