### ISSUE TITLE
Unable to create PO

### ISSUE THREAD

**Issue by rtigithub** [MicrosoftDocs/dynamics365smb-docs#28]
I am trying to create a PO from an SO where items will be dropshipped.  When I click on Create Purchase Orders I get a message stating "All items on the sales order are available." and a PO is not created.  A PO for the product does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97a73727-a345-b58e-4ae9-9da47d806007
* Version Independent ID: e67f474c-fdd1-bc0b-c876-e1fa3b3fafe3
* Content: [Purchase Items for a Sale by Creating Purchase Invoices - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/purchasing-how-purchase-products-sale)
* Content Source: [business-central/purchasing-how-purchase-products-sale.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/purchasing-how-purchase-products-sale.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
The Create Purchase Order function is about buying items into your own inventory (replenishment). To purchase for a drop shipment to a customer, see https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-drop-shipment.

NOTE: This feedback mechanism is only monitored by writers looking to improve Help. For questions about using the product, please contact your Microsoft support partner.

**Comment by rtigithub** [comment]
I truly understand that this is about improving the documentation.  I believe that your statement should be included in the documentation, along with the cross reference.

I will take the functionality up with Microsoft directly, since we are a Microsoft partner.

Bob Voigt (bobv@restechimage.com<mailto:bobv@restechimage.com>)
Technical Support (support@restechimage.com<mailto:support@restechimage.com>)
Resolution Technology, Inc.
Woman-Owned Small Business
614.791.0045
[halcon_logo_and_slogan_small]  [MPNlogo]   [cid:image003.png@01D407E2.1E9B13F0]   [_2018_Program_Badge_(English_-_US)_12_27_2017]
