### ISSUE TITLE
Enabling Premium Features for On-Premise

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [MicrosoftDocs/dynamics365smb-docs#281]
How do we enabling premium features for on-premise solution?
We experience that the Manufacturing module works after first login. It looks like after some time it is not accessable anymore. We can see that in the beginning there is no record in the "Application Area Setup" table. But when the module gets disabled there exists record in the table for the company where the module got disabled for.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5acaac44-d784-aa74-0111-1b40a58ef4f2
* Version Independent ID: 7fda754a-773d-4ac2-8db4-7b55e57f2534
* Content: [Choosing the User Experience to Show or Hide Advanced Features - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-experiences?source=docs#feedback)
* Content Source: [business-central/ui-experiences.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-experiences.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by JonFjolnirAlbertsson** [comment]
Consultant at our place had imported data into the table "Application Area Setup". I assume that it created the issue for us.

**Comment by JonFjolnirAlbertsson** [comment]
This is still an issue for us. We are running version 15.0.36510.0

**Comment by SorenGP** [comment]
This feedback mechanism is only monitored by writers looking to improve Help.
For technical issues, please contact Microsoft support. Alternatively, ask your question on [Business Central Community](https://community.dynamics.com/business).
