### ISSUE TITLE
Fejl ved afsendelse på BC Cloud ver. 15.2

### ISSUE THREAD

**Issue by MikaelTJohansson** [MicrosoftDocs/dynamics365smb-docs#282]
Hej,

Efter opgradering til version 15.2, så får vi følgende fejl ved afsendelse af faktura:

"Recordeksportbuffer findes ikke. Id-Felter og -værdier: Id='0'

Samme opsætning virker upåklageligt på tidligere version 15.1

Er I klar over denne fejl?

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: ae54faea-be1d-6d67-8b53-014504925f04
* Version Independent ID: 9a9d3538-a636-7c90-d53a-4a128470ed4a
* Content: [Oversigt over elektronisk OIOUBL-fakturering - Business Central](https://docs.microsoft.com/da-dk/dynamics365/business-central/localfunctionality/denmark/oioubl-electronic-invoicing-overview)
* Content Source: [business-central/LocalFunctionality/Denmark/oioubl-electronic-invoicing-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Denmark/oioubl-electronic-invoicing-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).
