### ISSUE TITLE
Text Redunancy

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-docs#287]
This paragraph is repeated verbatim on the page:

"Responsibility centers provide the ability to handle administrative centers. A responsibility center can be a cost center, a profit center, an investment center, or other company-defined administrative center. Examples of responsibility centers are a sales office, a purchasing department for several locations, and a plant planning office. Using this functionality, for example, companies can set up user-specific views of sales and purchase documents related exclusively to a particular responsibility center."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca132c7d-57bc-930e-c178-a68a650c5190
* Version Independent ID: 76de9554-5667-ef83-6401-54d9b415a8bb
* Content: [How to Work with Responsibility Centers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/inventory-responsibility-centers)
* Content Source: [business-central/inventory-responsibility-centers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-responsibility-centers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by edupont04** [comment]
Now live.
