### ISSUE TITLE
Creating new account schedules

### ISSUE THREAD

**Issue by Sarohavarun** [MicrosoftDocs/dynamics365smb-docs#289]
Choose the Lightbulb that opens the Tell Me feature icon, enter Account Schedules, and then choose the related link.

On the Account Schedules page, choose the New action to create a new account schedule name.

Alternatively, choose the Copy Account Schedule action, fill in the two fields, and then choose the OK button. - Copy account schedule is available only on Account categories page, not on Account schedules page

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 613d9e8a-856d-e913-ca98-c48e8376fb22
* Version Independent ID: a7b2e7f3-d8f4-8504-fa5b-fa9fa0afc4cc
* Content: [Build financial reports using account schedules - Business Central](https://docs.microsoft.com/en-nz/dynamics365/business-central/bi-how-work-account-schedule#feedback)
* Content Source: [business-central/bi-how-work-account-schedule.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/bi-how-work-account-schedule.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! Our apologies for the very long wait for an answer!

A member of our team has at long last reviewed your feedback and tested the product. We cannot reproduce the experience.
