### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by rtigithub** [MicrosoftDocs/dynamics365smb-docs#29]
Graphics do not display properly when Dark theme is applied.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cc0f224-e957-d1a0-1217-200eab95871b
* Version Independent ID: b33066c0-6c04-815b-1487-be70a66491bd
* Content: [Design Details - Assembly Order Posting - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-assembly-order-posting#feedback)
* Content Source: [business-central/design-details-assembly-order-posting.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-assembly-order-posting.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the input. I will forward your finding to the team responsible for rendering on the Docs site.
