### ISSUE TITLE
Over Receipting (overages)

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#293]
Can I please check how BC handles Over Receipting and how this effects the original Purchase Order

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27756a8b-eafb-abaa-c57a-737aa025f670
* Version Independent ID: 936c08fc-81e2-ceee-d714-26e295e434a9
* Content: [How to Receive Items - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/warehouse-how-receive-items)
* Content Source: [business-central/warehouse-how-receive-items.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/warehouse-how-receive-items.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! Our apologies for the very long wait for an answer!

A member of our team has at long last reviewed your feedback, and it turns out that the article was updated in April 2020 and now answers your question.

**Comment by makdaddy8888** [comment]
Thanks sorry I missed this
