### ISSUE TITLE
This setup in other countries

### ISSUE THREAD

**Issue by Martin-Inovex** [MicrosoftDocs/dynamics365smb-docs#294]
I have tried to enable this function, but can't find the field "Same Ext. Doc. No. in Diff. FY". I have looked thru all fields on the Purchases & Payables Setup page, and tried to add fields, but no extra fields to add. The reason is that I am about to import some data where the external document no some times are the same. If they have made a mistake the credit and debit the invoice with the same document no., so I have quit a few lines with the same ext. document number. My work around would be to change the numbers in the import, but with the setting above I could just read them in as they are. 

Anybody knows why the field is not showing in my BC?
(Version: DK Business Central 15.2 (Platform 15.0.39461.40778 + Application 15.2.39060.0))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f4023c8-4918-374e-bf3d-bc8aab5a0c70
* Version Independent ID: f8bfef0a-23d8-8dfd-d89f-f5dc8a97d3dd
* Content: [External Document Numbers and Fiscal Years - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/spain/external-document-numbers-fiscal-years#feedback)
* Content Source: [business-central/LocalFunctionality/Spain/external-document-numbers-fiscal-years.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Spain/external-document-numbers-fiscal-years.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by edupont04** [comment]
Hello Martin-Inovex,

This feature is available only in the Spanish version of Business Central, not in the Danish version. You can choose to make a feature request at [https://aka.ms/bcideas](https://aka.ms/bcideas).
