### ISSUE TITLE
Walkthrough topic for DEF is needed

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-docs#296]
The Data Exchange Framework is IMHO a highly undervalued (or unknown?) feature of BC. Partly this is due to the non-existence of a Walkthrough topic. So it is of great value if such an example topic would be added (like we have in many other places). And preferably one (or more?) that hits most of the options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 350ad27c-dd1c-fde6-27a3-faaf9c0c3da1
* Version Independent ID: 704d9728-05d0-c21a-9d68-d23af8fc6457
* Content: [Define how data is exchanged electronically - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-to-set-up-data-exchange-definitions)
* Content Source: [business-central/across-how-to-set-up-data-exchange-definitions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-how-to-set-up-data-exchange-definitions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hi Luke, 
Our apologies for the severe delay in getting back to you on this! It's a good suggestion, but we're severely shorthanded and lack the bandwidth to do something about it.

**Comment by lvanvugt** [comment]
Maybe make this a community thing?

Would love to help, although I will first have a 5 weeks summer break. ;-)

Hartelijke groet/best regards

Luc van Vugt


-------- Oorspronkelijk bericht --------
Van: Eva Dupont <notifications@github.com>
Datum: 23-07-20 13:29 (GMT+01:00)
Aan: MicrosoftDocs/dynamics365smb-docs <dynamics365smb-docs@noreply.github.com>
Cc: Luc van Vugt <lvanvugt@live.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [MicrosoftDocs/dynamics365smb-docs] Walkthrough topic for DEF is needed (#296)


Hi Luc,
Our apologies for the severe delay in getting back to you on this! It's a good suggestion, but we're severely shorthanded and lack the bandwidth to do something about it.

**Comment by edupont04** [comment]
Dear Luc,
Absolutely we would welcome your contributions! We love the community and all the cool things you and others are up to! But enjoy your vacation as I intend to enjoy mine (fewer weeks, though), and let's reconvene after summer. I'm closing the Issue, but we still appreciate the feedback!
