### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by Andrew-SSFM** [MicrosoftDocs/dynamics365smb-docs#30]
"You can set up a new company in Business Central with RapidStart Services..."  I don't see any options for this.  I can search for some of the documents mentioned above, but some are just blank when opened (Config. Questionnaire).  Is RapidStart no longer available?  Finding it frustrating to find information on D365 BC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ea52f11-68e3-4b42-e0f8-8617e1dce28f
* Version Independent ID: 3d724fd9-9a92-6f32-7761-d2543c003f03
* Content: [Set Up a Company With RapidStart Services - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-set-up-a-company-with-rapidstart)
* Content Source: [business-central/admin-set-up-a-company-with-rapidstart.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-set-up-a-company-with-rapidstart.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Hi Andrew - Thank you for the input. Some RapidStart page controls, and many other controls, have been made invisible in earlier versions of Business Central. In the October update, practically all controls will be available. This know issue is explained as the lasst item here: https://docs.microsoft.com/en-us/dynamics365/business-central/across-faq. - Regards, Soren, BC writer

**Comment by Andrew-SSFM** [comment]
Thank you for the quick reply!  I'll be keeping an eye out for those changes.
