### ISSUE TITLE
CDS Connection preview error during setup

### ISSUE THREAD

**Issue by lhtan-dev** [MicrosoftDocs/dynamics365smb-docs#304]
I'm trying out the CDS connection preview feature with BC and during setup i'm getting this error.

"Table connection for table type CRM must be registered using RegisterTableConnection or cmdlet New-NAVTableConnection before it can be used."

Am i doing something wrong ?

**Comment by amiccin** [comment]
Hi, I'm experiencing the very same problem for a SaaS customer that need to use entities in his own CDS environment.
I cannot find documentation nor I understand how to make this work.

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).
