### ISSUE TITLE
API URI

### ISSUE THREAD

**Issue by embiante** [MicrosoftDocs/dynamics365smb-docs#306]
API URI should use the following syntax: https://eastus2.api.cognitive.microsoft.com/vision/v2.0/analyze
where eastus2 can be different as per exact location

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cb42629-9e7b-ad3c-055a-8c559539ba5b
* Version Independent ID: f4479c0d-8b47-274c-bd8e-52fc91993728
* Content: [Using the Image Analyzer Extension - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-extensions-image-analyzer#feedback)
* Content Source: [business-central/ui-extensions-image-analyzer.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-extensions-image-analyzer.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by rubenseishima** [comment]
Hi,

You are correct. The article was since updated to mention that the displayed URI is an example.
