### ISSUE TITLE
ENUM

### ISSUE THREAD

**Issue by yannstlo** [MicrosoftDocs/dynamics365smb-docs#307]
Working on Business Central V13.
Trying to import a list of records with 1 enum field via the configuration package. Unfortunately, for some reason, the enum field is ignored. Could you please supply information on ENUM with Config package?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c17285d-1100-c2f7-aa54-588c98bd6834
* Version Independent ID: 823c90f0-592f-7d40-6c97-1ac7b7adcf13
* Content: [How to Prepare a Configuration Package - Business Central](https://docs.microsoft.com/en-ca/dynamics365/business-central/admin-how-to-prepare-a-configuration-package)
* Content Source: [business-central/admin-how-to-prepare-a-configuration-package.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-how-to-prepare-a-configuration-package.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).
