### ISSUE TITLE
10 Links in Core Development Section Wrong Link

### ISSUE THREAD

**Issue by tazmon95** [MicrosoftDocs/dynamics365smb-docs#308]
Hello, The top 10 links in the "Core Development" section of this page link back to this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed34ba95-a843-90b0-dd51-c24023ccd9d2
* Version Independent ID: 43259fda-960d-bd7a-97c6-74f569a54e11
* Content: [Developers learning catalog - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/readiness/readiness-learning-developers#feedback)
* Content Source: [business-central/readiness/readiness-learning-developers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/readiness/readiness-learning-developers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @loreleishannonmsft
* Microsoft Alias: **v-lshann**

**Comment by edupont04** [comment]
Fixed in April.
Thank you for your feedback! This was fixed in April.
