### ISSUE TITLE
Cendris does not deliver this service anymore in NL

### ISSUE THREAD

**Issue by jejesmit** [MicrosoftDocs/dynamics365smb-docs#312]
The service for Postcode Updates is no longer offered by Cendris, but through the following website: https://www.postnl.nl/zakelijke-oplossingen/procesoptimalisatie-met-dataoplossingen/postcodetabel/aanvragen 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 220a6f75-2d8e-9341-4383-040e9332c3e1
* Version Independent ID: 8b42cc1e-21c9-a942-7af5-c6d0f70a76b6
* Content: [Nederlandse postcodes - Business Central](https://docs.microsoft.com/nl-nl/dynamics365/business-central/localfunctionality/netherlands/dutch-post-codes#feedback)
* Content Source: [business-central/LocalFunctionality/Netherlands/dutch-post-codes.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Netherlands/dutch-post-codes.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello jejesmit,

Thank you for your feedback! We had not heard of this change, so we're working on an update for the documentation. It will be a few weeks before this update is available in Dutch.
