### ISSUE TITLE
Link to 365 Business Central License Guide is broken

### ISSUE THREAD

**Issue by jejesmit** [MicrosoftDocs/dynamics365smb-docs#314]
The following link is broken:

https://aka.ms/BusinessCentralLicensing

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 3af56319-74d0-ce95-7f11-48a0b165ed6e
* Version Independent ID: d496d459-af33-c965-a21b-0e2f44d6a2e9
* Content: [Gebruikersmachtigingen toewijzen of bewerken - Business Central](https://docs.microsoft.com/nl-nl/dynamics365/business-central/ui-how-users-permissions)
* Content Source: [business-central/ui-how-users-permissions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-how-users-permissions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello, 
Thank you for your feedback! We are aware that the link appears to be broken under certain circumstances, including when clicked from this article. We're working on an update, so please stay tuned. Meanwhile, you can get the licencing guide from this location:
https://dynamics.microsoft.com/en-us/business-central/overview/
