### ISSUE TITLE
Missing function

### ISSUE THREAD

**Issue by NicolaiBohnfeldt** [MicrosoftDocs/dynamics365smb-docs#316]
We need the EDIT LAYOUT button, as it was in NAV PC Windows client - not just "import" and "export".

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 562ba9ca-f395-bbeb-0775-5a85696e0935
* Version Independent ID: 58c23bed-523d-0432-f76e-2930232816f6
* Content: [Oprette og ændre brugerdefinerede layout for rapporter og dokumenter - Business Central](https://docs.microsoft.com/da-DK/dynamics365/business-central/ui-how-create-custom-report-layout)
* Content Source: [business-central/ui-how-create-custom-report-layout.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-how-create-custom-report-layout.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
