### ISSUE TITLE
Step number 5 on Picture in "Advanced warehouse configurations"

### ISSUE THREAD

**Issue by tuandinh-vn** [MicrosoftDocs/dynamics365smb-docs#317]
Step (5) at Put-away Request (on picture) mut be (6)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58785f09-a10c-ea7e-f8f0-72df41128f54
* Version Independent ID: c34cd55e-5333-7cf2-e2f9-d69915787334
* Content: [Design Details - Inbound Warehouse Flow - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-inbound-warehouse-flow#feedback)
* Content Source: [business-central/design-details-inbound-warehouse-flow.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-inbound-warehouse-flow.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! I've been told that the numbers on the picture are correct and that the second (5) should not be a (6) because the diagram is intended to show that the two things (5 and 6) happen at the same time
