### ISSUE TITLE
the 2nd column with wrong caption "Inbound"

### ISSUE THREAD

**Issue by tuandinh-vn** [MicrosoftDocs/dynamics365smb-docs#318]
in the table of four ways using different functionalities depending on the warehouse complexity level.
the column 2 "Inbound Process" must be "outbound Process"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31a09c1-c5e6-48f2-79ff-290e1932e4c8
* Version Independent ID: 9701538a-940c-e10b-3de0-e2e1fa6e5319
* Content: [Design Details - Outbound Warehouse Flow - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-outbound-warehouse-flow)
* Content Source: [business-central/design-details-outbound-warehouse-flow.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-outbound-warehouse-flow.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
