### ISSUE TITLE
Security Bug found when attaching supporting documentation on Purchase Invoice

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#319]
We have identified a security bug when creating new purchase invoice and attaching supporting documents via attachments. 

Where multiple users are entering data the attachments from the other open purchase invoice are visible from any other purchase invoice.

Eg

User A creates an Open Invoice A and Attachment A. Attachment A is visible to user B who is working on Open Invoice B

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fb5508f-038b-e7e3-e18d-f34a24b9304b
* Version Independent ID: 63f68f86-591b-44c5-def4-cfd1eed57a88
* Content: [Process Incoming Documents - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/across-process-income-documents)
* Content Source: [business-central/across-process-income-documents.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-process-income-documents.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! We can't recognize this problem in the base application (and we also see it as a problem with confidentiality rather than security), so you might want to reach out to your support contact to find out why you are seeing this behaviour.

I'm closing the issue because it's not related to the docs.

**Comment by makdaddy8888** [comment]
this is definitely a security issue. What happens if the ceo is place a confidential purchase order relating to a take over bid and someone in the business sees this document that would be a massive breach of sec regulation.

I would suggest strongly that this issue be escalated to the necessary channels.

Thank Eva

Kind Regards
Ben Opit
+61411707070

**Comment by edupont04** [comment]
Hello again, Ben,

Again, I urge you to contact support about this issue. My team and I cannot help you. If you are not sure of how to do that, then please check here: https://docs.microsoft.com/en-au/dynamics365/business-central/product-help-and-support#report-a-problem

BR
Eva Dupont
