### ISSUE TITLE
[de-DE] Register New Customers suggestions

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#32]
The <title>-Tag don't match with the content. In the title it says Kreditor (=Vendor) and the content of this pages it says Debitor (=Customer).

Also the Page is about Registering new Customer. My suggestion for the German Titel is "Ein neuen Debitor anlegen" (Create a new Customer). "Registriert einen neuen Debitor" is my opition uncommon and translates to "Registers a new customer".

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 450f9b98-bead-cd35-a10c-ccb67995c9e8
* Version Independent ID: 251d06f2-9ff2-3f53-f5e9-53597ae4d771
* Content: [Eine Kreditorenkarte erstellen, um einen neuen Kreditor zu erfassen - Business Central](https://docs.microsoft.com/de-DE/dynamics365/business-central/sales-how-register-new-customers)
* Content Source: [business-central/sales-how-register-new-customers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/sales-how-register-new-customers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thanks, Daniel - I have forwarded to the translation department to have this fixed.
Sören

**Comment by dgoldsch** [comment]
Hi Daniel, the English title is "Register New Customers" so we prefer to keep the existing translation for consistency with other translations. The suggested translation is more like "Create a new Customer". 
We will fix the title.
Thanks, Daniel

**Comment by DanielGoehler** [comment]
Hi @dgoldsch,
German noun "Register" an index, a file cabinet or catalog. The related German verb "registieren" is mostly used like sign on for (online) service, register software at the developer company or archive something in an file cabinet. In my opinion the German verbs "anlegen" or "erstellen" would match better, but okay.

"Registriert einen neuen Debitor" sounds strange to me. Why?

In German Grammar sentences contain of [Subject-Verb-Object](https://en.wikipedia.org/wiki/Subject%E2%80%93verb%E2%80%93object). **Customer** is the **S**ubject, **Register** is the **V**erb and there is no **O**bject here. 

My suggestion is as translation is: "Neue Debitoren _(S)_ registrieren _(V)_" (=Register New Customers) instead of "Registriert _(V)_ einen neuen Debitor _(O)_", which sounds strange to me, because I as reader does not know who does registers new customer (missing **S**ubject). 

Also in English "Customers" is plural und "Debitor" in German is singular. Plural would be "Debitoren".
