### ISSUE TITLE
THis is incorrect

### ISSUE THREAD

**Issue by mh1205** [MicrosoftDocs/dynamics365smb-docs#322]
Select the customer that you know or suspect that a duplicate record exists for, and then choose the Edit action.

Should be "Action" the "Function" the Merge Duplicate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6477b22d-ef05-bcc9-4d61-c0d1f7d77f57
* Version Independent ID: be49c64f-fc7b-3b30-7215-a30d4dc93e53
* Content: [Merge Duplicate Customer or Vendor Records - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-merge-duplicate-records#feedback)
* Content Source: [business-central/sales-how-merge-duplicate-records.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/sales-how-merge-duplicate-records.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by jordan992** [comment]
Correct, 
Or need to open the customer card, then click "Action" > "Function" > "Merge With..."
