### ISSUE TITLE
Sales Team

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#323]
Can  you bring the sales team details onto the Salesperson/Purchasers table so we can see what team they are on as well as what their job title is? Maybe campaigns too?
At the moment you can only see Code, Name, Commission and Phone Number and you cannot add using personalise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9dfad9-d584-63b7-833c-e11e27fbd137
* Version Independent ID: 4dceddc3-c9a4-5c40-4def-4b3e468ba36a
* Content: [Relationship Management - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/marketing-relationship-management)
* Content Source: [business-central/marketing-relationship-management.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/marketing-relationship-management.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
