### ISSUE TITLE
Identify who is a Salesperson or Purchaser

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#324]
The table is called Salesperson/Purchaser however you have no way of separating the two. Can you add a field so you can display whos who?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb9dfad9-d584-63b7-833c-e11e27fbd137
* Version Independent ID: 4dceddc3-c9a4-5c40-4def-4b3e468ba36a
* Content: [Relationship Management - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/marketing-relationship-management)
* Content Source: [business-central/marketing-relationship-management.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/marketing-relationship-management.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
