### ISSUE TITLE
Broken hyperlink

### ISSUE THREAD

**Issue by justinbpink** [MicrosoftDocs/dynamics365smb-docs#326]
"I'm looking for a solution provider" hyperlink broken in the How do I get Business Central? section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79ad74cc-aba8-7c05-93c2-da28efdbf375
* Version Independent ID: 2f07a9a9-4cf3-c835-29d0-aab1c830277c
* Content: [FAQ About Using Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-faq#feedback)
* Content Source: [business-central/across-faq.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-faq.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello justinbpink,

Thank you for your feedback! This has now been fixed. This is the correct link: https://www.microsoft.com/en-us/solution-providers/home
