### ISSUE TITLE
Example only describes how to "add an extended item text on a sales order line"

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-docs#328]
How about a purchase line?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6b18849-5bc8-3415-274e-403072387bab
* Version Independent ID: cd9c8b7a-1c90-867e-b9e2-b8e03007fae6
* Content: [Add Extra Lines to Define Extended Item Descriptions - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/ui-how-define-ext-text)
* Content Source: [business-central/ui-how-define-ext-text.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-how-define-ext-text.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
