### ISSUE TITLE
Functionality not available for US

### ISSUE THREAD

**Issue by justinbpink** [MicrosoftDocs/dynamics365smb-docs#329]
I'm not seeing the Action option to Reopen Accounting Periods when I have the last closed period selected for the US. Can this added to the US product? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f487ca2-edf0-2051-f70e-8c51f3316719
* Version Independent ID: a3ecf5c8-c4a0-eaab-9c00-28987c6b6bc8
* Content: [How to Reopen Accounting Periods - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/france/how-to-reopen-accounting-periods)
* Content Source: [business-central/LocalFunctionality/France/how-to-reopen-accounting-periods.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/France/how-to-reopen-accounting-periods.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello justinbpink,

Thank you for your feedback. This feature is specific for the French version of Dynamics 365 Business Central. If you would like to request the feature in the US, you can suggest it here: [https://experience.dynamics.com/ideas/](https://experience.dynamics.com/ideas/categories/list/?category=5adb8819-83ed-e611-8105-5065f38a3bb1&forum=e288ef32-82ed-e611-8101-5065f38b21f1).
