### ISSUE TITLE
Code unit as SOAP Service Important Note [External] is deprecated

### ISSUE THREAD

**Issue by Rehansatti** [MicrosoftDocs/dynamics365smb-docs#330]
[!IMPORTANT] For codeunits that are published as a SOAP web service, the methods exposed in the codeunit must be marked as [External] in the code.

Hi from the above Import note in the document the "[External]" scope is depreciated. we can not add it in the AL. 
Please make it appropriate i found it confusing in terms of AL,
https://github.com/microsoft/AL/issues/4724

**Comment by edupont04** [comment]
Hello Rehansatti,
Thank you for your feedback! You are right that the warning about methods in codeunits is no longer true. We will fix that in an update within a day or two. You can also read about the Scope attribute here: [https://docs.microsoft.com/dynamics365/business-central/dev-itpro/developer/methods/devenv-scope-attribute](https://docs.microsoft.com/dynamics365/business-central/dev-itpro/developer/methods/devenv-scope-attribute).
