### ISSUE TITLE
How to forbid searching the App Source? Any settings for Tell me?

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/dynamics365smb-docs#331]
In Dynamics 365 - Business Central, Online, is it possible to find settings for search/tell me prompt, and for instance, block documentation or block AppSource recommendations?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 338187f3-3d4b-0e1e-4b32-809514eccf11
* Version Independent ID: 37556d23-8b14-a8bf-ae3f-5ba85a725969
* Content: [Frequently Asked Questions about Tell Me - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-search-faq)
* Content Source: [business-central/ui-search-faq.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-search-faq.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)

**Comment by hkusulja** [comment]
Hello,
this is not feature request, this is request to update documentation with mentione information. So please do so.
Thank you
