### ISSUE TITLE
Please document intention and purpose of those accounts?

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/dynamics365smb-docs#333]
BC Customers are struggeling with this setting, sine only legacy authentication (username+password) is used in BC (for SMTP and for this CDS integration), not supporting OAuth2 etc.

Question here is, after initial setup, are those password stored in  BC database?
What is password are expired or changed later?

After initial setup, can admin password be changed? (we want to enable / enfroce MFA, without using AppPasswords)
Or the admin password will be saved and user later also for some modificiations (field mapping change?)

Please update this page with proper intention of user, and about saving passwords and reusing this two accounts with more details on purposes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80825306-8948-b99c-be8a-bb94c6d3a226
* Version Independent ID: c6cb993e-1b67-f6a8-294c-25769fdd153f
* Content: [Setting Up User Accounts for Integrating with Common Data Service - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/admin-setting-up-integration-with-dynamics-sales)
* Content Source: [business-central/admin-setting-up-integration-with-dynamics-sales.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-setting-up-integration-with-dynamics-sales.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Related feedback: https://github.com/MicrosoftDocs/dynamics365smb-docs/issues/332

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! We're looking into it so it will hopefully be answered in the next doc update.

**Comment by rubenseishima** [comment]
Hi,
Sorry for taking this long to reply. In the meantime, a few of your concerns were fixed, which are now [reflected in the current docs](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/system-requirements-business-central-v20#CRM). Mainly, passwords are no longer stored in the database, with the [legacy authentication deprecated in March, 2022](https://docs.microsoft.com/power-platform/important-changes-coming#deprecation-of-office365-authentication-type-and-organizationserviceproxy-class-for-connecting-to-dataverse).
With the currently supported authentication methods, account changes and MFA enforcement steps are done following the used method's procedures.

In case someone else stumbles into this question, I'll leave a link to the [Connect to Microsoft Dataverse](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-how-to-set-up-a-dynamics-crm-connection) article describing a few other connection details.
