### ISSUE TITLE
why not give this to all reports?

### ISSUE THREAD

**Issue by grantbrimhall** [MicrosoftDocs/dynamics365smb-docs#334]
Why would some reports NOT have the SaveValues property? Seems like a nice easy feature to implement. (e.g. Inventory Order Details does not have it, but Customer - Order Details does).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d4fb346-0ffe-7f89-9ca6-56ce1a92b82f
* Version Independent ID: 822a9737-5a78-1d0c-ef1e-2098f54acb7e
* Content: [Apply and Modify Saved Settings on Reports - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/reports-saving-reusing-settings#feedback)
* Content Source: [business-central/reports-saving-reusing-settings.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/reports-saving-reusing-settings.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
