### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by pmatsconsulting** [MicrosoftDocs/dynamics365smb-docs#336]
The link https://docs.microsoft.com/en-us/dynamics365/business-central/a/dev-itpro/administration/monitor-database-locks doesn't work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d659553f-0be4-d081-f460-71ff7d67aa1b
* Version Independent ID: 1dfb3905-25de-564e-62c3-3511bf860c62
* Content: [View Database Locks - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-view-database-locks#feedback)
* Content Source: [business-central/admin-view-database-locks.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-view-database-locks.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The link has been fixed and an update will be published soon.
