### ISSUE TITLE
Not more available?

### ISSUE THREAD

**Issue by dfk-consult** [MicrosoftDocs/dynamics365smb-docs#337]
Microsoft Pay is not more available since Feb. 8th, 2020. Customers should change to Paypal Extension instead. 
What about Stripe? Is there an Extension available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b764f2b-a5ce-1fb1-e1bc-6d7d55887717
* Version Independent ID: 7705cfbe-0625-1103-9c12-98f757ca2bc0
* Content: [Microsoft Pay Standard - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-extensions-microsoft-pay-payments#feedback)
* Content Source: [business-central/ui-extensions-microsoft-pay-payments.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-extensions-microsoft-pay-payments.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
