### ISSUE TITLE
Misspelled Inventory on Bulk Update Item Prices # 3

### ISSUE THREAD

**Issue by mserna530** [MicrosoftDocs/dynamics365smb-docs#339]
3. On the Item FastTab, fill in the No. or Invenotry Posting Group or other fields with the original item prices you want to update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d20592c1-805e-cb34-1f1a-d2f5f6b056a4
* Version Independent ID: a8f2d0d7-a3ba-7994-2b09-e3a0b08afbd3
* Content: [Set Up Special Sales Prices and Discounts for Customers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-record-sales-price-discount-payment-agreements)
* Content Source: [business-central/sales-how-record-sales-price-discount-payment-agreements.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/sales-how-record-sales-price-discount-payment-agreements.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
