### ISSUE TITLE
Can you expand on this page 

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#340]
can you please help elaborate on this section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ef7322e-85ec-eaad-738d-843898c5ad76
* Version Independent ID: 84f2f9f2-ebfa-9f63-d633-30f3b8a6036a
* Content: [Record and Reimburse Employees' Business-Related Expenses - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-how-record-reimburse-employee-expenses)
* Content Source: [business-central/finance-how-record-reimburse-employee-expenses.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-how-record-reimburse-employee-expenses.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hi Ben,

Sorry for our delay in getting back to you on this question. We don't have further to add to the article since policies for reimbursement are typically specific to each organization.
