### ISSUE TITLE
Excel addin for Mac OS

### ISSUE THREAD

**Issue by jnpatrouillault** [MicrosoftDocs/dynamics365smb-docs#341]
Hello
Is Editing to Excel on Mac OS is in the roadmap of Business Central ? We have some customers who wants to use it in their environment.
Thanks

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 5d8fc6f4-3264-8336-038c-6c5ba7aa22df
* Version Independent ID: 56f76b91-51c4-98d5-ce6a-15cd52dea2d2
* Content: [Affichage et édition dans Excel depuis Business Central - Business Central](https://docs.microsoft.com/fr-fr/dynamics365/business-central/across-work-with-excel)
* Content Source: [business-central/across-work-with-excel.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-work-with-excel.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
