### ISSUE TITLE
Rechtschreibfehler Anpanssen 

### ISSUE THREAD

**Issue by JulianTillmann** [MicrosoftDocs/dynamics365smb-docs#342]
Unter https://docs.microsoft.com/de-de/dynamics365/business-central/ui-personalization-manage#to-customize-pages-for-a-profile gibt es einen Rechtschreibfehler: "Anpanssen"

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 37666f25-436e-c4c9-2101-ac7eb2d482a3
* Version Independent ID: cfd398f5-97fd-44f9-2ae7-acf4627ce9d8
* Content: [Anpassen von Seiten für Rollen - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/ui-personalization-manage#feedback)
* Content Source: [business-central/ui-personalization-manage.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-personalization-manage.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! We have forwarded it to our translators, and the fix will be in the next update of the German translations.

**Comment by edupont04** [comment]
Hello @JulianTillmann ,

Our translation team have published an update that includes a fix to this typo. You can verify that here: https://docs.microsoft.com/de-de/dynamics365/business-central/ui-personalization-manage#to-customize-pages-for-a-profile
