### ISSUE TITLE
Applicable versions

### ISSUE THREAD

**Issue by volodymyrfedorets** [MicrosoftDocs/dynamics365smb-docs#343]
I can't see the Save action described in this article. I assume it is available in later versions of BC comparing to the one I'm using. Would be good to see versions where certain feature is available (relevant not only to this specific feature/article).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8bc2119-c9e3-7b5a-465e-7354f9a6edaf
* Version Independent ID: 94aebf3a-19df-64a4-60dc-7fc9c681f506
* Content: [Save and Personalize List Views - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-views#feedback)
* Content Source: [business-central/ui-views.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-views.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! The content on Docs.microsoft.com generally reflects the latest version of Dynamics 365 Business Central unless a different version is explicitly specified.

The ability to save filters was added in 2019 release wave 2: https://docs.microsoft.com/en-us/dynamics365-release-plan/2019wave2/dynamics365-business-central/saving-personalizing-list-views
