### ISSUE TITLE
Setup a bank account dor SEPA Credit Transfer seems to be incorrect

### ISSUE THREAD

**Issue by mh1205** [MicrosoftDocs/dynamics365smb-docs#344]
Point 3 mentions SEPADD instead of SEPACT

Point 4 mentions a field that does not exist on the bank card

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ccaa3ee-e77b-9e4e-9a3e-51c055dca6da
* Version Independent ID: cac940f0-d21b-3325-ec26-f740439d9c1f
* Content: [Make Payments with the AMC Banking 365 Fundamentals extension or SEPA Credit Transfer - Business Central](https://docs.microsoft.com/en-ca/dynamics365/business-central/finance-make-payments-with-bank-data-conversion-service-or-sepa-credit-transfer)
* Content Source: [business-central/finance-make-payments-with-bank-data-conversion-service-or-sepa-credit-transfer.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-make-payments-with-bank-data-conversion-service-or-sepa-credit-transfer.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
