### ISSUE TITLE
To be corrected

### ISSUE THREAD

**Issue by mh1205** [MicrosoftDocs/dynamics365smb-docs#345]
Setup a vendor card for SEPA Credit Transfer

Point 3: replace BANK by the payment method associated with SEPA
Point 4 : the field Export Protocol Code should be filled in with the Protocol associated with SEPA

NOTE : all invoices posted before this modification will NOT have the (new) Export Protocol Code filled in. Hence they will not appear in the Payment Journal when choosing Suggest Vendor Payment

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ccaa3ee-e77b-9e4e-9a3e-51c055dca6da
* Version Independent ID: cac940f0-d21b-3325-ec26-f740439d9c1f
* Content: [Make Payments with the AMC Banking 365 Fundamentals extension or SEPA Credit Transfer - Business Central](https://docs.microsoft.com/en-ca/dynamics365/business-central/finance-make-payments-with-bank-data-conversion-service-or-sepa-credit-transfer)
* Content Source: [business-central/finance-make-payments-with-bank-data-conversion-service-or-sepa-credit-transfer.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-make-payments-with-bank-data-conversion-service-or-sepa-credit-transfer.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
