### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by StuartHodgins** [MicrosoftDocs/dynamics365smb-docs#348]
Second bullet "I the Vendor Ledger Entries page," should be "In the Vendor Ledger Entries page,"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0602a4-fe7d-9dd3-c1d0-344af6ff6099
* Version Independent ID: 91c11081-5aa7-bc88-7ee9-bb865a0110d9
* Content: [Send Remittance Advice Extension - Business Central](https://docs.microsoft.com/en-ca/dynamics365/business-central/ui-extensions-send-remittance-advice#feedback)
* Content Source: [business-central/ui-extensions-send-remittance-advice.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-extensions-send-remittance-advice.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
