### ISSUE TITLE
Limit Posting Periods by Template

### ISSUE THREAD

**Issue by heatherr-nz** [MicrosoftDocs/dynamics365smb-docs#349]
Is this information relevant?  I cannot see the fields as described in my Business Central environment.  There is no Allow Posting From or Allow Posting To fields available against General Journal Templates that I can see.  Is this a localisation issue?  I am using a New Zealand instance of Business Central.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8988fc78-e526-99ce-14ba-444c18f8ca41
* Version Independent ID: deba7290-d0b7-1a52-3a6b-99ed13870e90
* Content: [How to Limit the Posting Period - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/belgium/how-to-limit-the-posting-period)
* Content Source: [business-central/LocalFunctionality/Belgium/how-to-limit-the-posting-period.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Belgium/how-to-limit-the-posting-period.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! As you can see in the URL and in the table of contents (left nav) for this article, it applies to the Belgian version of Business Central. This particular capability is not available in the NZ version. You might want to submit a feature request here: https://aka.ms/businesscentralfeedback
