### ISSUE TITLE
Does BC support Create customized service connection

### ISSUE THREAD

**Issue by Byron-Zhang** [MicrosoftDocs/dynamics365smb-docs#35]
I get the message on "Business Central integrates with Dynamics 365 for Sales only.", but I think it's limited by the system service connection. So I have a question.  Does BC support to create new customized service connection to sync data between CRM and BC for customized entity, not default entity in the system?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d1e4b3c-28cf-8c08-b0a7-69092862e07d
* Version Independent ID: 68e2ca6e-1fe3-ddf9-5f28-feceef952d24
* Content: [Manage Customers Using Dynamics 365 for Sales - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/marketing-integrate-dynamicscrm)
* Content Source: [business-central/marketing-integrate-dynamicscrm.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/marketing-integrate-dynamicscrm.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
This feedback method is only for the documentation. You may want to suggest this capability on the [Ideas site](https://experience.dynamics.com/ideas/list/?forum=e288ef32-82ed-e611-8101-5065f38b21f1), or ask the community in the [forum](https://community.dynamics.com/business/f/758/).
