### ISSUE TITLE
page "Item Availability by Timeline" missing in bc 16

### ISSUE THREAD

**Issue by dfk-consult** [MicrosoftDocs/dynamics365smb-docs#350]
page "Item Availability by Timeline" cannot be found at least in business central 15. 
there is an idea on @ideas to vote for: https://experience.dynamics.com/ideas/idea/?ideaid=71c16061-8499-e911-80e8-0003ff68cb40

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7172099-61d3-f4f8-5a6c-f5e6880c800e
* Version Independent ID: 631ec9b4-9487-2248-a030-5c3ebd9ab7b0
* Content: [How to Modify Planning Suggestions in a Graphical View - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/production-how-to-modify-planning-suggestions-in-a-graphical-view?source=docs)
* Content Source: [business-central/production-how-to-modify-planning-suggestions-in-a-graphical-view.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/production-how-to-modify-planning-suggestions-in-a-graphical-view.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! The Item Availability by Timeline page is in fact available in Business Central online but only from the Planning Worksheet page. We'll get that clarified in the near future.

**Comment by edupont04** [comment]
Hello @dfk-consult  
I was to rash yesterday, so after a double-check I can confirm that the feature is indeed not working in the browser. The confusing content in this article has been removed in the English version today.

Sorry for the confusion!

**Comment by dfk-consult** [comment]
hi,ok. i read that this feature is not available in the web client, because the main component is a. net library.there is a an entry in ideas for that feature. it seems, that its planned for a future release.regardsdipl. ing. franz kalchmair-------- Originalnachricht --------Betreff: Re: [MicrosoftDocs/dynamics365smb-docs] page "Item Availability by Timeline" missing in bc 16 (#350)Von: Eva Dupont An: MicrosoftDocs/dynamics365smb-docs Cc: "Franz Kalchmair, Dipl.Ing." ,Mention 
Hello @dfk-consult
I was to rash yesterday, so after a double-check I can confirm that the feature is indeed not working in the browser. The confusing content in this article has been removed in the English version today.
Sorry for the confusion!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/dynamics365smb-docs/issues/350#issuecomment-624661626",
"url": "https://github.com/MicrosoftDocs/dynamics365smb-docs/issues/350#issuecomment-624661626",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
