### ISSUE TITLE
Flow Diagram

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#351]
Hello Can you please share a flow diagram. This is not the easiest document to follow

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48b711f1-115c-d473-cd69-9a1c82527e3a
* Version Independent ID: 56023061-0a0a-da72-5cb1-f14c4233e2b2
* Content: [Planning With or Without Locations - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/production-planning-with-without-locations#feedback)
* Content Source: [business-central/production-planning-with-without-locations.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/production-planning-with-without-locations.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello Ben,
Thank you for your feedback! That's a great suggestion, and I'm adding it to our backlog for now. I can't promise that we'll get around to it any time soon, though.
FYI, the text-based "flow diagram" has actually been there for many years, dating back to an early version of Dynamics NAV, but you and I can't be the first people who find it hard to understand.

**Comment by edupont04** [comment]
Hi again, Ben @makdaddy8888,
I was to rash yesterday, so after a double-check I can confirm that the feature is indeed not working in the browser. The confusing content in this article will be removed in the next doc refresh later this week.

Sorry for the confusion!

**Comment by makdaddy8888** [comment]
No Problem Eva

I just want to best and most clearest message for everyone.

Can you let me know when published?

Kind Regards
Ben Opit
+61411707070

**Comment by rubenseishima** [comment]
Hello, 
After discussing the scenarios listed on the article with a product manager, he suggested the page needed a few changes to reflect how the feature currently works. We've fixed the article and it will be republished in the near future:

* When the system detects demand at a location, the **Location Mandatory** field setting is not taken into consideration, checking only for the variables listed in steps 2 and 3 on the original article.
* Additionally, for scenario 1.4 under *Demand at "Blank Location"*, the item is planned according to the "minimal alternative" (Reordering Policy = _Lot-for-Lot_ (_Order_ remains _Order_), Include Inventory = _Yes_, all other planning parameters = Empty).

We think these fixes will simplify the article and hopefully not require a flowchart. But feel free to disagree, of course.

**Comment by edupont04** [comment]
Now live in English (US): https://docs.microsoft.com/en-us/dynamics365/business-central/production-planning-with-without-locations
Translations due in aa couple of weeks.
