### ISSUE TITLE
Cancel partial posted purchase invoice updates received quantities

### ISSUE THREAD

**Issue by Celjeta** [MicrosoftDocs/dynamics365smb-docs#353]
When I cancel a partial posted purchase invoice, in purchase order the Qty to Receive and Qty Received are updated also. It should update only field Qty to Invoice and Qty. Invoiced

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c8f216-2ecd-ae0e-a754-05c14bebe5bf
* Version Independent ID: 65149fe7-b68f-68a7-d37e-ac88469a289a
* Content: [Amend or Cancel Unpaid Purchase Invoices - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/purchasing-how-correct-cancel-unpaid-purchase-invoices#feedback)
* Content Source: [business-central/purchasing-how-correct-cancel-unpaid-purchase-invoices.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/purchasing-how-correct-cancel-unpaid-purchase-invoices.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
