### ISSUE TITLE
License / Subscription requirements

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#355]
Hello

Can I check if a Business Central subscription is needed if a 3rd party solution wants to publish data back to Business Central. If so is a Teams license enough or would a device license be preferred? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b41c5d3-03f2-4c75-2fe6-7f34398b185d
* Version Independent ID: 9b9153f2-d2f7-1f87-2e16-25d0b602dcc7
* Content: [Expose objects as web services - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-publish-web-service)
* Content Source: [business-central/across-how-publish-web-service.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-how-publish-web-service.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Ben,

You can read about licensing here: [Licensing in Dynamics 365 Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/licensing)
For all other questions regarding licensing, we refer to the [Business Central Licensing Guide (download)](https://go.microsoft.com/fwlink/?LinkId=871590).

**Comment by makdaddy8888** [comment]
Hi Eva

Can you please point me to the paragraph so I can share this with the partner?

Kind Regards
Ben Opit
+61411707070

**Comment by edupont04** [comment]
Hi Ben,

I'm sorry that I can't be more precise. My team doesn't know when what is updated in the licensing guide, which is why we have to simply refer to it.

**Comment by makdaddy8888** [comment]
So hard to understand ms speak :)

Kind Regards
Ben Opit
+61411707070
