### ISSUE TITLE
How to have multiple approvers in paralel

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/dynamics365smb-docs#356]
How to accomplish following scenario. Please update the docs.

In company there are two bosses., Eather one or eather second must approve. (Not AND, it is OR)
Both bosses/approvers are added to the group. With same sequence number.
But both are asked to approve (in this example scenario, if one approves, the other does not need to do anything)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bfbcf9b-e03f-6f8f-a3c6-3096a88659e5
* Version Independent ID: bd264840-a48d-de2d-728a-23e8e4ad9225
* Content: [How to Set Up Workflow Users - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-to-set-up-workflow-users)
* Content Source: [business-central/across-how-to-set-up-workflow-users.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-how-to-set-up-workflow-users.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello @hkusulja,
Our apologies for the delay in responding to this question. If you want to use the "native" workflow engine, you can set up one of the two approvers as the substitute approver. 

Alternatively, you can build quite elaborate workflows using Microsoft Power Automate that includes a number of templates, such as this one: https://docs.microsoft.com/en-us/power-automate/parallel-modern-approvals. You can then use the built-in connector to integrate with Dynamics 365 Business Central.

**Comment by hkusulja** [comment]
Please update the offical docs about this info / scenario to avoid confusion.
