### ISSUE TITLE
Missing/Wrong Standard Journal

### ISSUE THREAD

**Issue by manichoy** [MicrosoftDocs/dynamics365smb-docs#357]
The Standard Journal Session is about Item Journals. There should be another session about the Standard Journal Function in General Journals. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1814e2a4-7a9a-4ab7-7c22-db275545efff
* Version Independent ID: b05838af-52c6-1f89-d612-3412ada99d7b
* Content: [Using General Journals to Post Directly to G/L - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-work-general-journals#feedback)
* Content Source: [business-central/ui-work-general-journals.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-work-general-journals.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello @manichoy,


Thank you for your feedback! In this article, the section Working with Standard Journals uses the Item Journal as an example, but at the alert just before the steps says "The following procedure refers to the item journal, but the information also applies to the general journal.".

I hope this answers your question.
