### ISSUE TITLE
Version Information?

### ISSUE THREAD

**Issue by update-jeremy** [MicrosoftDocs/dynamics365smb-docs#358]
This is great information, glad to have it.  Is there any way we can please know what versions this applies to?  I have customers on a wide array of On Prem versions -- I need to know which I need to upgrade the application objects for to get this functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88b9d69-c350-a059-520b-4096e424e7f9
* Version Independent ID: 6c0589a0-739c-5481-2111-bcf2e79b4a3c
* Content: [Switzerland Local Functionality - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/switzerland/switzerland-local-functionality)
* Content Source: [business-central/LocalFunctionality/Switzerland/switzerland-local-functionality.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Switzerland/switzerland-local-functionality.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! The content on Docs.microsoft.com generally reflects the latest version of Dynamics 365 Business Central unless a different version is explicitly specified.

**Comment by update-jeremy** [comment]
I'll mark this closed as it's correct for the docs.  Any tips where to find which Swiss versions have received which updates?

**Comment by edupont04** [comment]
Hi Jeremy,

You can check which version a specific environment is on in the Business Central administration center and in the Help and Support page in Business Central. For more information, see this article: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/version-numbers
