### ISSUE TITLE
Insufficient Detail on use of Configuration Template

### ISSUE THREAD

**Issue by theo-stock** [MicrosoftDocs/dynamics365smb-docs#359]
I landed on this page by clicking through on the Configuration Template Line Type field, hoping I would find out how to use the Types "Template" and "Related Template", but found nothing. I also scouted around quite a bit in Docs but still failed.
Luckily I am a Partner and AL Developer, so could read the code from (Say) Item Card "Apply Template" action, and could figure out how to add one or more Default Dimension to a Configuration Template for an Item (in this case).
None of my consultants nor my Customers would have been able to figure this out.
Thanks for your help. Theo Stock (theo.stock@gosolutions.group)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c17285d-1100-c2f7-aa54-588c98bd6834
* Version Independent ID: 823c90f0-592f-7d40-6c97-1ac7b7adcf13
* Content: [How to Prepare a Configuration Package - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/admin-how-to-prepare-a-configuration-package#feedback)
* Content Source: [business-central/admin-how-to-prepare-a-configuration-package.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-how-to-prepare-a-configuration-package.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello @theo-stock,
Thank you for your feedback! You are not the first person to struggle with configuration packages, and you're right that we appear to have lost the information about how to define configuration templates. We'll get that added soon, I hope. Until then, I unfortunately have to refer to Dynamics NAV 2016: https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/hh879459(v=nav.90)
