### ISSUE TITLE
Doc obsolete AND Microsoft Data Exporter doesn't work

### ISSUE THREAD

**Issue by gobrien4418** [MicrosoftDocs/dynamics365smb-docs#36]
The latest installed extension for Quickbooks DESKTOP Data Migration is 2.0.23590.23730

This documentation is out of date as the extension requires you to use the Microsoft Data Exporter (https://go.microsoft.com/fwlink/?linkid=864691) which doesn't work. It is either unable to connect to Quickbooks claiming it is not running OR if I run the Exporter with Admin privileges it tells me my Quickbooks is not the Accountant version so I cannot open 2 companies. Yes, I tried leaving the Quickbooks Desktop application open without logging into a company file and that gets me back to "Quickbooks is not running"

My guess is the developer had Quickbooks Accountant version and didn't realize they were opening a second company via the COM connection which is not allowed with a regular license.

The Extension instructions:

Instructions
To prepare the data for migration, follow these steps:
1) Download and run the Microsoft Data Exporter.
https://go.microsoft.com/fwlink/?linkid=864691
2) Click Next to select the *.zip file containing your exported QuickBooks data.
3) Complete wizard to import data into Business Central.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0e1422a-b890-0c73-d171-4eacc1d4b7fb
* Version Independent ID: b466bd5e-3ea0-3fc7-5a6d-a1fffabd455b
* Content: [Using the QuickBooks Migration Extension - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-extensions-quickbooks-data-migration#tabpanel-issues-closed)
* Content Source: [business-central/ui-extensions-quickbooks-data-migration.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-extensions-quickbooks-data-migration.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by gobrien4418** [comment]
It turns out that the export tools is not compatible with QuickBooks 2016. I installed a trial of QB 2019 and the exporter connected no problem. There is presently ZERO documentation for the export tool. A little effort on that front would have saved me 4 frustrating hours this morning.

**Comment by edupont04** [comment]
Thanks for your feedback! I've asked the team who own this extension to find out what is going on. I'll keep this issue open until we have an answer.

**Comment by jeffli90** [comment]
Has there been a solution to this yet? I'm trying out the trial of business central to see if it's the right system for our us and I can't get our QB 2016 data imported. My error shows "an account cannot be empty".

**Comment by edupont04** [comment]
Just sent off a reminder to the team. Stay tuned.

**Comment by jenolson** [comment]
Thank you for your comments.  We do have documentation on the quickbooks migration extension and it can be found here:
https://docs.microsoft.com/en-us/dynamics365/business-central/ui-extensions-quickbooks-online-data-migration

Also in the documentation is states that account numbers are required: 
Business Central requires that general ledger accounts have account numbers assigned to them. Make sure that account numbers are assigned to your accounts in QuickBooks Online. This is a required field within Business Central therefore you have to have account numbers assigned in QB before you can run the migration,  That is the error you are getting.

thanks
Jennifer

**Comment by akurtz9** [comment]
This is about Quickbooks Desktop, not Quickbooks online. I can verify that 2016 is still not working...

**Comment by edupont04** [comment]
Closing since this is about product, not docs.

**Comment by gobrien4418** [comment]
Hi edupont04, could you point to where in the documentation it lists which versions of Quickbooks are and are not supported? Perhaps a big bold "don't waste 2 hours of your life trying to make this work with Quickbooks 2016" would be about docs, not product?

**Comment by edupont04** [comment]
@jenolson Can you help answer this?

**Comment by jenolson** [comment]
We can update the document to state this is only supported by 2017 and 2018.  I will put a note in the documentation.
