### ISSUE TITLE
ODATA limitation question

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#360]
Is there a limitation on the amount of data or the amount of rows you can submit per transaction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b41c5d3-03f2-4c75-2fe6-7f34398b185d
* Version Independent ID: 9b9153f2-d2f7-1f87-2e16-25d0b602dcc7
* Content: [Expose objects as web services - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-publish-web-service)
* Content Source: [business-central/across-how-publish-web-service.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-how-publish-web-service.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

Thank you for your feedback! You can read about limitations of OData requests here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/operational-limits-online.
I'll add that link to this article.
