### ISSUE TITLE
Creating Accounting Period Column

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#361]
Hello

I want to create an accounting period schedule so that position 1 is Period 1 from July last year then position 2 is August last year and so on. What is this date formula for periods?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 562ba9ca-f395-bbeb-0775-5a85696e0935
* Version Independent ID: 58c23bed-523d-0432-f76e-2930232816f6
* Content: [Create and Modify Custom Layouts for Reports and Documents - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/ui-how-create-custom-report-layout)
* Content Source: [business-central/ui-how-create-custom-report-layout.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-how-create-custom-report-layout.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hi Ben,

Sorry for the delay in getting back to you on this! Did you find an answer? Otherwise, you might find an answer here: https://docs.microsoft.com/dynamics365/business-central/bi-how-work-account-schedule?branch=master#comparing-accounting-periods-using-period-formulas
We're shorthanded here, and this is not my core competency, but I think it would be the Comparison Date Formula field, where I believe you can enter specific dates, for example.

**Comment by makdaddy8888** [comment]
Looks great 

I’ll pass onto the team to look into further.

That is a challenge the accounting periods not being the same date as compared to previous years. I ended up creating a PowerBI report to have this filtered

Kind Regards
Ben Opit
+61411707070

**Comment by edupont04** [comment]
Hi Ben,

Yes, it's somewhat bewildering, this. But I'm told that account schedules can be very powerful for financial overviews and insights, though I'll be the first to admit that I have no idea how (way out of my league). Using Power BI sounds like a great solution for you, though.
I'll see what I can do about stringing the story better together across account schedules, built-in report, Excel, and Power BI.

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
