### ISSUE TITLE
Bug in Account Schedule

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#362]
When personalising the lines and adding the Entity Code Totalling. this does not return any data when clicking the lookup value dots (...)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 613d9e8a-856d-e913-ca98-c48e8376fb22
* Version Independent ID: a7b2e7f3-d8f4-8504-fa5b-fa9fa0afc4cc
* Content: [Build financial reports using account schedules - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/bi-how-work-account-schedule)
* Content Source: [business-central/bi-how-work-account-schedule.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/bi-how-work-account-schedule.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).
