### ISSUE TITLE
Dimension nulstilles

### ISSUE THREAD

**Issue by NicolaiBohnfeldt** [MicrosoftDocs/dynamics365smb-docs#363]
Hvis der ændres modkonto, "nulstilles" dimensionsværdien - i mange tilfælde er dette ikke hensigtmæssigt.

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 1814e2a4-7a9a-4ab7-7c22-db275545efff
* Version Independent ID: b05838af-52c6-1f89-d612-3412ada99d7b
* Content: [Bruge finanskladder, der skal bogføres direkte til Finans - Business Central](https://docs.microsoft.com/da-DK/dynamics365/business-central/ui-work-general-journals)
* Content Source: [business-central/ui-work-general-journals.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-work-general-journals.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hej @NicolaiBohnfeldt ,


Thank you for your feedback! I'm replying in English to help future users also understand this. yes, if you change the balancing account on a journal line where you have specified dimensions, then that information is rolled back when you add the new balancing account number. If you want to suggest a change to this functionality, you can do that here: https://aka.ms/businesscentralideas
