### ISSUE TITLE
Describe units of measure for fields Height, Width, Length, Cubage and Weight on an Item unit of measure page.

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#364]
Item Units of measure contain several fields being Height, width, lenght, cubage and weight.  Selecting "learn more" links you to this documentation page, but there is no information on the page relating to these fields.  Is it possible to add some information on these fields somewhere, that identifies what unit of measure these fields are in?  For example, is weight in kg, mg, or lbs?  Is Height in mm, cm or meters?  Is cubage in CuFT, CuMeters or Cubic Centimeters?  

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37d63058-5104-f4c6-dd07-21caf3a4a4a8
* Version Independent ID: 6c3e166d-bdc9-b823-dfc4-62957f5aa385
* Content: [Create Item Cards for Goods or Services - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/inventory-how-register-new-items#feedback)
* Content Source: [business-central/inventory-how-register-new-items.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-how-register-new-items.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello @chris7777au, 
Our apologies for the delay in getting back to you on this, but the exact units of measures is something that you control - the demonstration company has some definitions, but in your production environment, you can set up the units of measures that you need in your work. We'll make this clearer in the next doc update, but you can read about units of measures here: https://docs.microsoft.com/dynamics365/business-central/inventory-how-setup-units-of-measure

**Comment by edupont04** [comment]
We've added more precise description, I hope. Specifically for the **Height**, **Width**, **Length**, **Cubage**, and **Weight** fields, it doesn't really matter which measurement you use, as long as you are consistent about it. For example, use inches or centimetres for length across all item units of measure, but use the same consistently. The Cubage field is calculated automatically based on length/height/width, and that is then used for calculating if the item will fit into a bin, based on what is already there.

This information had gotten lost some time ago but will become available in  the various translations of this article in the cming weeks: https://docs.microsoft.com/dynamics365/business-central/inventory-how-setup-units-of-measure
