### ISSUE TITLE
Date format when exporting to Excel

### ISSUE THREAD

**Issue by salmosa1** [MicrosoftDocs/dynamics365smb-docs#365]
Hi all,

I'm having a kind of issue when exporting to Excel.
I'm exporting a report through,
"Report.SaveAs(Report::"AST-Export Trf To Excel Header", '', ReportFormat::Excel, OutStrHdrs, RecRef);"
I do it this way because I need to add to a zip file, but I think this is not the problem.

It's a very simple list type report. One of the columns is a date. I change the format of this column like this.
![image](https://user-images.githubusercontent.com/37341780/82556278-b47a3280-9b69-11ea-8191-da707280e47f.png)

It's supposed not to add the regional formatting, because it doesn't have the *.

But when I open the Excel, the format of this column "is not" Date, it appears as Custom,
![image](https://user-images.githubusercontent.com/37341780/82556492-19ce2380-9b6a-11ea-91db-eb4b3b94076b.png)

It's a problem because the Excel must be imported in another app, and it needs to have a true date format. 

Am I doing something wrong? Is anything I could do to fix this? I've try lot of diferent formats, put the format as "="dd/mm/yyyy"", without format, etc, and always is passing the region.

Thanks in advance!

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).
