### ISSUE TITLE
DimensionSets

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#366]
Can you please elaborate what **Dimension Set Entries** does? Web Services Query Object ID 257
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec29b075-9cb9-9f87-c3d8-01d62a645b62
* Version Independent ID: 6be392af-271e-7b31-2e0a-f5c2493dc9b5
* Content: [Design Details - Table Structure - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-table-structure)
* Content Source: [business-central/design-details-table-structure.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-table-structure.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello Ben,

Dimension set entries is an under-the-hood term for how we store dimension sets. You can read about this here: https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-dimension-set-entries-overview.
This query object looks up dimension sets in the Dimension Set Entries table based on the "Shortcut Dimension 1/2/3" codes that are defined in the general ledger setup. Nothing too mysterious, I believe.
