### ISSUE TITLE
Changing company does not work

### ISSUE THREAD

**Issue by sofrustrated** [MicrosoftDocs/dynamics365smb-docs#367]
For Excel add-in for Business Central:

1. Select environment.
2. Select company.
3. Choose OK.
3. Choose Yes.

Nothing happens.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d8fc6f4-3264-8336-038c-6c5ba7aa22df
* Version Independent ID: 56f76b91-51c4-98d5-ce6a-15cd52dea2d2
* Content: [Viewing and Editing in Excel From Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-work-with-excel)
* Content Source: [business-central/across-work-with-excel.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-work-with-excel.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hello @sofrustrated,

Thank you for your feedback! Our apologies for the delay in getting back to you, and I hope you are no longer as frustrated. Using the Excel add-in can be a bit confusing at first. The trick here is to reload the add-in after you change settings such as the environment or the company. For reload the add-in, choose the little fly-out icon in the top-right corner of the add-in (right next to your user name), and then choose Reload.
We'll make this a bit clearer in the next doc refresh.
