### ISSUE TITLE
[de-DE] sales-how-register-new-customers

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#37]
The first sentence "Debitoren sind die Herkunft des Erträge." is wrong. Is has to be "[..] **der** Erträge".

The the following two sentence sound strange to me. (Bing Translate?)

I would suggest the following: "Debitoren sind die Herkunft Ihres Einkommens. Sie müssen jeden Debitor, an den Sie verkaufen, als Debitorenkarte anlegen. Debitorenkarten enthalten die Informationen, die für den Verkauf von Produkten an Debitoren erforderlich sind."

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 450f9b98-bead-cd35-a10c-ccb67995c9e8
* Version Independent ID: 251d06f2-9ff2-3f53-f5e9-53597ae4d771
* Content: [Eine Kreditorenkarte erstellen, um einen neuen Kreditor zu erfassen - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/sales-how-register-new-customers)
* Content Source: [business-central/sales-how-register-new-customers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/sales-how-register-new-customers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Reported to the Business Central translation department, MBSI.

@DanielGoehler If you have access to VSTF, then please report translation errors directly to the MBSI team. See the settings in this bug report that I just created: https://dynamicssmb2.visualstudio.com/web/wi.aspx?pcguid=edca893a-5ed9-48d0-888d-f32486c82901&id=283714

**Comment by DanielGoehler** [comment]
Hi @SorenGP, no, it seams I have no access. It says: NOT AUTHORIZED

**Comment by DanielGoehler** [comment]
Hi @SorenGP,

I reported some issued to clocnav@microsoft.com an Saturday, but to be hornest it is very unsatisfying. You get no feedback. No even receive a message “we received you e-mail and get back to you”. Github is for me more traceable and I see that issued are closed if fixed.

I hope you overthink you process in the future...

**Comment by edupont04** [comment]
I have reported this translation issue on behalf of you. Closing the issue accordingly.
