### ISSUE TITLE
Shortcut to goto the next line but goto the beginning of the new line

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#370]
When you enter a line in you can press enter 20 times but what command allow you to carriage return
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96fd662-e905-9df6-60f5-c709f92077c1
* Version Independent ID: 172fd943-0f5c-6d4c-b764-ced7fd077a96
* Content: [Keyboard Shortcuts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/keyboard-shortcuts#QuickEntry)
* Content Source: [business-central/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/keyboard-shortcuts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hi Ben,

Eh, I think you'll need a combination along the lines of Down Arrow (move to same field in the next row) and then Home to move to the first field in that row.
Closing issue.

**Comment by makdaddy8888** [comment]
When doing thousands of lines per month you need a faster way. It’s only a suggestion to help make the product better

Kind Regards
Ben Opit
+61411707070

**Comment by edupont04** [comment]
Hi Ben,
I do hear what you're saying, and you can submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
