### ISSUE TITLE
Different Send On Behalf of

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#371]
Can we have a different send as on what is being sent for example sales documents should goto sales@domain.com or purchasing documents should goto purchasing@domain.com
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9afe7e0d-9a4e-ad47-e04d-717e6315e768
* Version Independent ID: 1f1e0f8d-9c90-0204-0480-45bc89fcbba4
* Content: [Set Up Document-Specific Email Content - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-send-documents-email)
* Content Source: [business-central/ui-how-send-documents-email.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-how-send-documents-email.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

Thank you for your feedback! Since this question is not about the docs, I recommend that you vote for this suggestion: https://experience.dynamics.com/ideas/idea/?ideaid=5f574a76-47c1-e811-b96f-0003ff68dcaf
