### ISSUE TITLE
Add information how to cancel posted sales invoice with a prepayment line

### ISSUE THREAD

**Issue by erolkunman** [MicrosoftDocs/dynamics365smb-docs#372]
Please add information how to correct following situation:
Prepayment invoice is made.
Sales order is partially posted (let's say half the quantity).
Now this posted sales invoice is Cancelled but it does not cancel Prepayment deduction.

Please add instructions how to cancel a posted sales invoice with a prepayment line (the one with quantity -1).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eaabeeb-dc70-6164-3a2d-62547fbb5d08
* Version Independent ID: d469c2c9-49ea-6842-6a31-977dacca5a01
* Content: [How to Correct Prepayments - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-how-to-correct-prepayments)
* Content Source: [business-central/finance-how-to-correct-prepayments.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-how-to-correct-prepayments.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! You are right that the prepayment invoice is not automatically reversed when the original sales order/invoice is cancelled. This is currently a manual process that users will have to remember to do. If you want to suggest this as a new capability, you can suggest it here: https://aka.ms/businesscentralideas
We'll make this a bit clearer in the next doc refresh.
