### ISSUE TITLE
VAT Statement Setup Impossible for US BC 16.1 With Current Documentation

### ISSUE THREAD

**Issue by KTL-KSweeney** [MicrosoftDocs/dynamics365smb-docs#373]
Running US Business Central 16.1 (Platform 16.0.12630.13560 + Application 16.1.12629.12805), I cannot access VAT Statements. The VAT Statement (Reports & Analysis) has a field for the Statement Template Name; however, drilling into the full list does not allow users to create new templates.

I am looking for documentation on setting up VAT Statement Templates and Registration Numbers for multiple EU countries for a US-based company selling and shipping to Europe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00d179cc-41fd-5960-14f4-a653dda0394b
* Version Independent ID: e583b8d6-7b6a-dd10-037e-1bd604f3cdad
* Content: [Set Up a VAT Statement - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-how-setup-vat-statement)
* Content Source: [business-central/finance-how-setup-vat-statement.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-how-setup-vat-statement.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Unfortunately, this is currently not supported in the US version of Dynamics 365 Business Central. You may want to work with a consultant to add the capability to your environment based on the specific countries that you ship to, or you might want to submit a feature request here: https://aka.ms/businesscentralfeedback

**Comment by KTL-KSweeney** [comment]
Eva,

I know that this functionality is not supported. I need this documentation to be updated accordingly, because it took a Microsoft support ticket to identify this functionality as missing for the US release.

Sincerely,
Kieran Sweeney


Kieran Sweeney
Business Software Consultant
Office:301-360-0001
Direct:301-517-6694
KTL Solutions, Inc. - Disclaimer
 This message contains confidential information and is intended only for the individual(s) addressed in the message. If you are not the named addressee, you should not disseminate, distribute, or copy this e-mail. If you are not the intended recipient, you are notified that disclosing, distributing, or copying this e-mail is strictly prohibited.

**Comment by KTL-KSweeney** [comment]
> Hello,
> Thank you for your feedback. Unfortunately, this is currently not supported in the US version of Dynamics 365 Business Central. You may want to work with a consultant to add the capability to your environment based on the specific countries that you ship to, or you might want to submit a feature request here: https://aka.ms/businesscentralfeedback

If VAT Statements and uploads are not supported in the US Release, then please update documentation. It took a formal MS Support ticket to identify that this functionality was not present in the US Release, and proper documentation would save many other VARs from wasting time.
