### ISSUE TITLE
Available versions

### ISSUE THREAD

**Issue by MarkCWEV** [MicrosoftDocs/dynamics365smb-docs#374]
I believe this a recently added feature. Is it possible to add what version features are available in. A lot of MS docs have and APPLIES TO section at top. See: https://docs.microsoft.com/en-us/sql/t-sql/queries/from-transact-sql?view=sql-server-ver15

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41fdade0-78f9-07b9-2c6b-1c0533d0b0d5
* Version Independent ID: ef21188d-24b7-0486-f078-eb0867a11225
* Content: [How to Copy Existing Items to New Items - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/inventory-how-copy-items)
* Content Source: [business-central/inventory-how-copy-items.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-how-copy-items.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! The content on Docs.microsoft.com generally reflects the latest version of Dynamics 365 Business Central unless a different version is explicitly specified.
This particular capability has been available in Business Central for a year.

**Comment by MarkCWEV** [comment]
> Hello,
> Thank you for your feedback! The content on Docs.microsoft.com generally reflects the latest version of Dynamics 365 Business Central unless a different version is explicitly specified.
> This particular capability has been available in Business Central for a year.

thanks for reply, but that was kind of my point. There are 2 facotrs

It's not consistent with most of Microsoft documentation
IMHO there should be _at _least__an indication of what version a feature was intorduced in. Most people are not on latest version 9esp on-prem)

Thanks

Mark
