### ISSUE TITLE
falscher Link

### ISSUE THREAD

**Issue by derjuffi** [MicrosoftDocs/dynamics365smb-docs#375]
Designdetails: Eingehender Lagerfluss.
Dieser Link öffnet die Seite mit dem Ausgehenden Lagerfluss

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a09ecb55-c99f-952b-c582-2745de3b0bbb
* Version Independent ID: 531d8ca0-daeb-c0cc-300b-29004e5a4850
* Content: [Designdetails - Lagerhaus Einrichten - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/design-details-warehouse-setup)
* Content Source: [business-central/design-details-warehouse-setup.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-warehouse-setup.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
