### ISSUE TITLE
Prsonalisierungen

### ISSUE THREAD

**Issue by cloudservivesolutions** [MicrosoftDocs/dynamics365smb-docs#376]
Schreibfehler:
Prsonalisierungen

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bc9174f7-cad5-7550-b93b-036158d40e38
* Version Independent ID: 8e4dabaa-c112-6a2e-dc18-933253579927
* Content: [Personalisieren von Seiten - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/ui-personalization-user)
* Content Source: [business-central/ui-personalization-user.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-personalization-user.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This has already been fixed in the latest update.
