### ISSUE TITLE
Optione,

### ISSUE THREAD

**Issue by cloudservivesolutions** [MicrosoftDocs/dynamics365smb-docs#377]
Schreibfehler:
Optione,

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 31f66244-a00f-4ee4-83d6-90b26eb25913
* Version Independent ID: 8293d84c-f76f-06d9-3483-c5a7b1209fe0
* Content: [Anpassen von Business Central - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/ui-customizing-overview)
* Content Source: [business-central/ui-customizing-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-customizing-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! This has been reported to our translation team, and it will be fixed in the next translation update.
