### ISSUE TITLE
Business Central available for Government

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#379]
Is SaaS BC available in Australian Government Azure ?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1fd6e96-76f1-6d75-570d-1d1cd571be0d
* Version Independent ID: 4647bb84-b1ce-abac-5aa3-41df2134d40e
* Content: [Australia Local Functionality - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/australia/australia-local-functionality)
* Content Source: [business-central/LocalFunctionality/Australia/australia-local-functionality.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Australia/australia-local-functionality.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by edupont04** [comment]
Hello Ben,
As I am sure that you know, we list availability here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-countries-and-translations
If you would like to Business Central on the Australian Government Cloud, then I suggest you post that suggestion on the Ideas site: https://aka.ms/businesscentralideas

**Comment by makdaddy8888** [comment]
Hi Eva

 An you add a link on this page point people to that list of availability 

Kind Regards
Ben Opit
+61411707070
