### ISSUE TITLE
On-premises integration - Broken link

### ISSUE THREAD

**Issue by fomlhaut** [MicrosoftDocs/dynamics365smb-docs#382]
This link at the beginning of the document is broken:
[Preparing Dynamics 365 Sales for Integration on-premises](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/prepare-dynamics-365-for-sales-for-integration.md)

I think the correct link is this, without the Markdown extension (.md) at the end:
[https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/prepare-dynamics-365-for-sales-for-integration](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/prepare-dynamics-365-for-sales-for-integration)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2957b832-9aee-e050-b034-7f3badb2e27c
* Version Independent ID: a93b51b9-9a52-c8a2-2197-38c02f2e327f
* Content: [Integrating with Dynamics 365 Sales - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-prepare-dynamics-365-for-sales-for-integration)
* Content Source: [business-central/admin-prepare-dynamics-365-for-sales-for-integration.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-prepare-dynamics-365-for-sales-for-integration.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
