### ISSUE TITLE
Dynamics GP migration

### ISSUE THREAD

**Issue by heatherr-nz** [MicrosoftDocs/dynamics365smb-docs#384]
This page is very confusing - it suggest migration from Dynamics GP is possible, but the extension that used to be there is no longer.  It says to use Cloud Migration, but when going to the Cloud Migration page, there is no option for Dynamics GP.  There is nothing in AppSource.  Can you migrate from Dynamics GP or not?  Is it country specific?  If so, it would be good if that was made clear.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1844e77-f298-ade6-b18b-d52049c65e1a
* Version Independent ID: 01396e92-b599-0a24-c813-e2fd9282723b
* Content: [Migrate Data from Dynamics GP with the Data Migration Extension - Business Central](https://docs.microsoft.com/en-nz/dynamics365/business-central/ui-extensions-dynamicsgp-data-migration)
* Content Source: [business-central/ui-extensions-dynamicsgp-data-migration.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-extensions-dynamicsgp-data-migration.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Heather,
Thank you for your feedback! This will be fixed in the next doc update - you absolutely can migrate from Dynamics GP: https://docs.microsoft.com/en-nz/dynamics365-release-plan/2020wave1/dynamics365-business-central/enhanced-dynamics-gp-chart-accounts-migration

**Comment by heatherr-nz** [comment]
Everything I have read or tried to download to use since posting this says it is not supported in New Zealand.  If there is a supported way to do it in New Zealand, I would appreciate some details on how to do so.  I am starting a migration this week and would like to use the migration tool.

**Comment by edupont04** [comment]
Hm, I've reached out to get an official statement. Stay tuned!

**Comment by edupont04** [comment]
Hello again,

The team has confirmed that the migration tool is currently only available in US, CA, and GB. They are working on making it available in AU/NZ as well, but they don't have a published timeline yet. You might want to use RapidStart Services to help with the migration, or to migrate to Business Central on-premises and then migrate to the cloud from there. I'll get the article updated to reflect this.

The program manager is willing to answer additional questions if you allow me to share your email address with them?

**Comment by heatherr-nz** [comment]
Thanks for the update on this.  Good to know the official statement.
