### ISSUE TITLE
Diagrams would be helpful here.

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#385]
Is is possible to get some screen shots. What Arrow do i press for example?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdee6dc5-5e01-4ef8-8c67-c06224b27eea
* Version Independent ID: caa86f49-040e-4f62-2332-91162a56d968
* Content: [Use Your Data to Create an App - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-use-financials-data-source-powerapps)
* Content Source: [business-central/across-how-use-financials-data-source-powerapps.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-how-use-financials-data-source-powerapps.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,
Thank you for your feedback! The article hasn't been updated after the redesign of the Power Apps Home page. This will be fixed in the next doc update.
