### ISSUE TITLE
Posted Purchase Invoice - Correct Cancel needs change

### ISSUE THREAD

**Issue by TWBlais** [MicrosoftDocs/dynamics365smb-docs#386]
As indiciated in Issue ID 349046, there needs to be additional scenario clarified with Correct/Cancel.  If a Posted Purchase Invoice was processed from a  separate Purchse Invoice using the line Action > Get Receipt Lines rather than directly from the Purchase Order, the Posted Purchase Invoice - Correct / Cancel is blocked with a warning: " You cannot correct this posted purchase invoice because Item ***** is used on a Purchase Order.   The key is that the user can Correct/Cancel if the Purchase Order is directly posted as Invoiced. However, the Correct/Cancel does not work for a Posted Purchase Invoice in the specific Get Receipt Line invoicing scenario.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c8f216-2ecd-ae0e-a754-05c14bebe5bf
* Version Independent ID: 65149fe7-b68f-68a7-d37e-ac88469a289a
* Content: [Amend or Cancel Unpaid Purchase Invoices - Business Central](https://docs.microsoft.com/en-ca/dynamics365/business-central/purchasing-how-correct-cancel-unpaid-purchase-invoices)
* Content Source: [business-central/purchasing-how-correct-cancel-unpaid-purchase-invoices.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/purchasing-how-correct-cancel-unpaid-purchase-invoices.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
