### ISSUE TITLE
Typo - These may be different in you solution

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-docs#389]
These may be different in you**r** solution

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96fd662-e905-9df6-60f5-c709f92077c1
* Version Independent ID: 172fd943-0f5c-6d4c-b764-ced7fd077a96
* Content: [Keyboard Shortcuts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/keyboard-shortcuts)
* Content Source: [business-central/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/keyboard-shortcuts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
