### ISSUE TITLE
[de-DE] Deferral Translation

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#39]
Hi,

"Deferral Schedule" has a fixed German translation in the Business Central Application. It is "Abgrenzungsplan" not "Aufschubzeitplan" and "Deferral Template" is "Abgrenzungsvorlage" not "Aufschubvorlage". Unfortunately both are used in this article, but you cannot find "Aufschubzeitplan" and "Aufschubvorlage" in Business Central.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bb43416e-0c20-8b0f-cbb1-7b5aa85cfd08
* Version Independent ID: d98810e3-3dce-79d5-39f5-de9440406063
* Content: [Einnahmen und Ausgaben abgrenzen - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/finance-how-defer-revenue-expenses)
* Content Source: [business-central/finance-how-defer-revenue-expenses.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-how-defer-revenue-expenses.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Hi Daniel - We appreciate your feedback about wrong German translations. Going forward, please send email directly to the NAV/BC translation coordinators: clocnav@microsoft.com. This public site is not a suited channel for this. 

I have forwarded this one already.

Thanks
Sören
