### ISSUE TITLE
Bank Feed with Business Central On Prem

### ISSUE THREAD

**Issue by KTL-KSweeney** [MicrosoftDocs/dynamics365smb-docs#390]
Only after opening a ticket with Microsoft has it become apparent that the Bank Feed functionality is severely limited for the On Prem Version of Business Central (Ticket 120062324003206).

In addition to paying per seat, development is necessary to hook into Yodlee's API for On-Prem.

Please update your documentation to disclose those severe limitations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd798ca6-4c2b-4470-3c46-894c4c68c8a8
* Version Independent ID: c7ac4f0e-ccf3-70e1-5a6a-90063ab963cb
* Content: [Set Up Yodlee Bank Feeds - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/bank-how-setup-bank-statement-service)
* Content Source: [business-central/bank-how-setup-bank-statement-service.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/bank-how-setup-bank-statement-service.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by KTL-KSweeney** [comment]
Thank you!

Sincerely,
Kieran Sweeney


Kieran Sweeney
Business Software Consultant
Office:301-360-0001
Direct:301-517-6694
KTL Solutions, Inc. - Disclaimer
 This message contains confidential information and is intended only for the individual(s) addressed in the message. If you are not the named addressee, you should not disseminate, distribute, or copy this e-mail. If you are not the intended recipient, you are notified that disclosing, distributing, or copying this e-mail is strictly prohibited.
