### ISSUE TITLE
Added Detail for Recording Usage against Job Planning Lines

### ISSUE THREAD

**Issue by theo-stock** [MicrosoftDocs/dynamics365smb-docs#391]
This relates to paragraph headed "To record usage for a job planning line of type Budget".
In Step 5. you can add that the user can optionally select multiple Planning lines for transferring to the Job Journal at the same time. 

This could be an alternative for Step 10. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeab2416-7c83-f086-e9e2-bb2b094ed6d4
* Version Independent ID: 98a3c38a-990c-4cf0-9a7e-8eda2248cc7d
* Content: [Record Billable and Budgeted Usage of Job Resources - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/projects-how-record-job-usage)
* Content Source: [business-central/projects-how-record-job-usage.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/projects-how-record-job-usage.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by edupont04** [comment]
Thank you for your feedback! This was fixed in today's doc update as well as your other reported issue.
