### ISSUE TITLE
Heading does not match Body of Paragraph

### ISSUE THREAD

**Issue by theo-stock** [MicrosoftDocs/dynamics365smb-docs#392]
This relates for paragraph "To record usage for a job planning line of type Billable".
1. the Body of this paragraph describes how to Transfer a Planning Line of Type Billable to a Sales Invoice (nothing to do with the Job Journal. Either the Heading or the Body should be altered to match each other.
2. Assuming this relate to sending a Planning Line to a Sales Invoice (or Credit Memo), Point 7. "On the Job Planning Lines page, select the relevant line, and then choose the Post action." is in error, as there is no Post Action on the Planning Line. It should be the Post Action on the related Sales Invoice (or Credit Memo)
3. In Step 5. The User has the option of selecting multiple Planning Lines of Type Billable and send them to an Invoice (or Credit Memo) at the same time. This is an alternative to using Step 9.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeab2416-7c83-f086-e9e2-bb2b094ed6d4
* Version Independent ID: 98a3c38a-990c-4cf0-9a7e-8eda2248cc7d
* Content: [Record Billable and Budgeted Usage of Job Resources - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/projects-how-record-job-usage)
* Content Source: [business-central/projects-how-record-job-usage.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/projects-how-record-job-usage.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by edupont04** [comment]
We've cleaned up the worst confusion, I hope. Part of the problem appears to be that we chose to see what you think of as two separate tasks (track usage, invoice customer) as one workflow. We've clarified that in today's update, I hope.
