### ISSUE TITLE
How to end a users session

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#393]
Can you please share an article or a process on how to end a users sessions remotely. This is needed incase a table gets locked and you want to kick users out.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbc54780-19ba-4d44-cd54-3435966b1293
* Version Independent ID: 1417b68c-68fd-9f06-fafa-854edc3c1e75
* Content: [Manage users and roles - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-users-profiles-roles)
* Content Source: [business-central/admin-users-profiles-roles.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-users-profiles-roles.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello Ben,
You hit a good one, here! The team is looking into improving the experience around this, but for now, the administrator can go to the Business Central admin center and cancel the session: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-environments#managing-sessions

We'll get this added to this article in our next doc refresh, so thank you for bringing this up!
