### ISSUE TITLE
Blanket Purchase Orders

### ISSUE THREAD

**Issue by AlejandroLorenzoVG** [MicrosoftDocs/dynamics365smb-docs#395]
When searching for Blanket Purchase Orders, the search keeps on showing Blanket Sales Orders. It seems the Blanket Purchase Orders is not available.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7033a8ca-8596-5125-ac2b-72fca7838353
* Version Independent ID: c8cb3c61-ed8c-8ae0-28ba-c584f1ad20e2
* Content: [How to Create Blanket Sales Orders - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-to-create-blanket-sales-orders)
* Content Source: [business-central/sales-how-to-create-blanket-sales-orders.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/sales-how-to-create-blanket-sales-orders.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
