### ISSUE TITLE
Over-Receipt/Approval Functionality

### ISSUE THREAD

**Issue by mgoodson-silverw** [MicrosoftDocs/dynamics365smb-docs#396]
A few issues occur when trying to turn on Approvals for Over-Receipt:

1. In the online documentation it states their is a standard workflow when there is not, but the applicable information is there to build your own. Highlighted below is the online documentation:
"You can set up an approval workflow to require that over-receipts must be approved before they can be handled. In that case, you must select the Approval Required check box on the Over-Receipt Codes page. A dedicated workflow response, Approve Over-Receipt exists in the standard workflow data for this purpose. For more information, see Create Workflows."

2. After a workflow is created and an approval does get sent properly using the correct workflow code. Issue is when you try to Approve you get an error saying "The requested operation is not supported". I debugged the issue and will provide where the error is occurring.
![OverReceiptApproval](https://user-images.githubusercontent.com/67922235/86623866-47dbbb80-bf90-11ea-8570-1fbd46b9b7e8.jpg)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27756a8b-eafb-abaa-c57a-737aa025f670
* Version Independent ID: 936c08fc-81e2-ceee-d714-26e295e434a9
* Content: [How to Receive Items - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/warehouse-how-receive-items)
* Content Source: [business-central/warehouse-how-receive-items.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/warehouse-how-receive-items.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! You're right that there is no sample workflow for approving over-receipts in the demonstration company for Dynamics 365 Business Central trials. We'll get that clarified in the next doc refresh. 

If you think you have identified a bug in code, please contact technical support.
