### ISSUE TITLE
User Tasks

### ISSUE THREAD

**Issue by henrikohm** [MicrosoftDocs/dynamics365smb-docs#400]
This would actually make sense if a link to a record - like the "old" days - was possible, but no.
not even the normal links are possible.
"Please look at this Prod. BOM for me. If you dont know how to access then this is the link to a page with >100 records."
What it should have said: "Please look at this specific BOM as it may require som development."

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 5308402f-4290-a713-523a-784a49770f40
* Version Independent ID: 1abda990-fbab-b4d3-105d-b794cf9f2ccb
* Content: [Tildele og administrere opgaver - Business Central](https://docs.microsoft.com/da-dk/dynamics365/business-central/across-user-tasks)
* Content Source: [business-central/across-user-tasks.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-user-tasks.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. I'm not sure if I understand you correctly, but it sounds like you are comparing user tasks to standard tasks in the Manufacturing module or something like that. When you create a user task and assign it to a user, you create the link to where to carry out the task by specifying the report or page on the Task Item FastTab on the User Task page. When the user then starts the task, they can choose the "Got to Task Item" action that then opens the page or report.

If you think something is not working in your Business Central, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/dynamics365/business-central/product-help-and-support#report-a-problem).

**Comment by henrikohm** [comment]
Hello Eva

Not correct.
When you want/need review of data (master data, documents etc) in a company you want to be able to inform others that they need to do something.
In the old versions Notes could be assigned to single people (only one sadly), but in BC this is not possible and thus email must be used.
That’s why the User Tasks could be used to create a task to a specific user/group to ex. Change bom, review sales order etc.
This is not possible in BC16 to point to a single record including a page (and why a page… users do not know about page numbers) and therefore not really useful.
Why is it not possible to create a task from ALL pages to the current record to a specific user/group.

A standard task in Manufacturing has absolutely nothing to do with this – standard tasks are used on routes to fill in master data like tools etc.

You have closed the case now. I do not agree.

Med venlig hilsen / Best regards / Mit freundlichen Grüßen

Henrik Ohm


[cid:image003.png@01D4D4FC.517E5D30]
Solution Architect Dynamics 365
+ 45 2969 0509
Columbus Danmark
Lautrupvang 6
2750 Ballerup
hoh@columbusglobal.com<mailto:hoh@columbusglobal.com%0d>

www.columbusglobal.com<http://www.columbusglobal.com/>

**Comment by edupont04** [comment]
Hej Henrik,

Thank you for clarifying your point! You are right that User Tasks cannot be linked with a specific record but only with page objects and reports. Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)

I am preparing an update, though, that will make it a bit clearer what this feature is about.

**Comment by henrikohm** [comment]
Hej Eva

Ok I will create a feature request.
As a general task mgt system the User Tasks are not really usable.
Also it’s only 3 roles that get the tasks shown in the Role Center – everybody else does not get this info.

Have a nice summer 😊


Med venlig hilsen / Best regards / Mit freundlichen Grüßen

Henrik Ohm


[cid:image003.png@01D4D4FC.517E5D30]
Solution Architect Dynamics 365
+ 45 2969 0509
Columbus Danmark
Lautrupvang 6
2750 Ballerup
hoh@columbusglobal.com<mailto:hoh@columbusglobal.com%0d>

www.columbusglobal.com<http://www.columbusglobal.com/>

**Comment by edupont04** [comment]
Tak - og i lige måde :-)
