### ISSUE TITLE
CP is not a valid option in the Comparison Period Formula field

### ISSUE THREAD

**Issue by heatherr-nz** [MicrosoftDocs/dynamics365smb-docs#401]
CP as stated in this documentation throws an error if used in the Comparison Period Formula field.  P is the correct value to use.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 613d9e8a-856d-e913-ca98-c48e8376fb22
* Version Independent ID: a7b2e7f3-d8f4-8504-fa5b-fa9fa0afc4cc
* Content: [Build financial reports using account schedules - Business Central](https://docs.microsoft.com/en-nz/dynamics365/business-central/bi-how-work-account-schedule)
* Content Source: [business-central/bi-how-work-account-schedule.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/bi-how-work-account-schedule.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for your feedback! I agree that the information is a bit bewildering, and we'll get that clarified soon. However, as far as I know, CP can be used as described in examples such as _-1FY[1..CP]_. But it always has to be another fiscal period, along the lines of "now but back then", so to speak. So you would use it to compare Q3 in fiscal year 2019 to Q1 and/or Q2 that same fiscal year, or compare this week last month to the rest of that month. At least, that's how I understand the formula.

**Comment by heatherr-nz** [comment]
Thanks for the clarification.  That does seem to work.  Maybe just provided some more extensive examples would be good.  There are loads of common things that are done all the time that could be included.

**Comment by edupont04** [comment]
Thank you for your feedback! A somewhat better explanation will be added in the next doc update.
