### ISSUE TITLE
What version of Business Central is this referring to?

### ISSUE THREAD

**Issue by cparker4486** [MicrosoftDocs/dynamics365smb-docs#402]
This page doesn't specify which version of Business Central supports the instructions. We have BC but there's nothing remotely like what's described here in our system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6477b22d-ef05-bcc9-4d61-c0d1f7d77f57
* Version Independent ID: be49c64f-fc7b-3b30-7215-a30d4dc93e53
* Content: [Merge Duplicate Customer or Vendor Records - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-merge-duplicate-records)
* Content Source: [business-central/sales-how-merge-duplicate-records.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/sales-how-merge-duplicate-records.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! The content on Docs.microsoft.com generally reflects the latest version of Dynamics 365 Business Central unless a different version is explicitly specified. This particular capability has been available since April 2019: https://docs.microsoft.com/business-applications-release-notes/April19/dynamics365-business-central/application-enhancements#merge-duplicate-customers-vendors-or-contacts

**Comment by cparker4486** [comment]
Thanks for getting this information to me. I just wish the website was as informative. The problem is that just about every one of MS's products is changing daily and it's impossible to keep up with. Not knowing version numbers that correspond to documentation exacerbates the issue. Ideally, the top of the page would list the versions the content was compatible with.

Thanks for your consideration.

**Comment by edupont04** [comment]
Hi cparker4486,

I'm closing this issue, but your feedback is not lost. I'm tracking the feedback about versioning the docs through another Issue that is now pinned to the top of the list.
