### ISSUE TITLE
Misc typo

### ISSUE THREAD

**Issue by gary-PSSI** [MicrosoftDocs/dynamics365smb-docs#403]
For reports and XMLports, you can set filters as on lists to delimit which data to include in the report or XMLport, but you cannot sort and search.

should be

you can set filters on lists to delimit
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 802c5ab2-6384-9f67-586f-8de66cd361cc
* Version Independent ID: 12fb39ec-1f3c-e49b-de9c-7d9d09b29fc4
* Content: [Sorting, Searching, and Filtering Lists - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-enter-criteria-filters)
* Content Source: [business-central/ui-enter-criteria-filters.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-enter-criteria-filters.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback, but the statement is actually accurate as-is, though it can be easily misunderstood. Our meaning is that you can filter on lists, and you can filter on reports and XMLports just like on lists. We'll get it clarified that this is the meaning.
