### ISSUE TITLE
The Note at the bottom is missing the link 

### ISSUE THREAD

**Issue by LenCardinal** [MicrosoftDocs/dynamics365smb-docs#405]
The note:

>  Note
> 
> All feature descriptions in user documentation for Business Central assume the Premium experience, meaning the descriptions cover the full scope of UI elements. Therefore, users with the Essential experience may in some topics read about functionality and UI elements that are not visible in their user interface. For more linformation, see

ends with 'see' but does not have the link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f66244-a00f-4ee4-83d6-90b26eb25913
* Version Independent ID: 8293d84c-f76f-06d9-3483-c5a7b1209fe0
* Content: [Customizing Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-customizing-overview)
* Content Source: [business-central/ui-customizing-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-customizing-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by brentholtorf** [comment]
Hello,

Thanks for reporting the missing link. I have updated the article and it will be published soon.
