### ISSUE TITLE
Typo in 1st note

### ISSUE THREAD

**Issue by bcraigie** [MicrosoftDocs/dynamics365smb-docs#406]
[Enter feedback here]
you use the Over-Receive field **top** handle should read you use the Over-Receive field **to** handle

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27756a8b-eafb-abaa-c57a-737aa025f670
* Version Independent ID: 936c08fc-81e2-ceee-d714-26e295e434a9
* Content: [How to Receive Items - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/warehouse-how-receive-items)
* Content Source: [business-central/warehouse-how-receive-items.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/warehouse-how-receive-items.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
