### ISSUE TITLE
Min. Count For Async Import

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-docs#407]
Our consultants are facing issues when exporting / importing rapidstart packages containing 20+ tables. According to https://www.yammer.com/dynamicsnavdev/#/Threads/show?threadId=719707062263808, there's a limitation on the number of tables to be used (but I can't find any reference to this in the documentation) or to increase the 'Min. Count For Async Import' parameter (but I can't find the field on the standard pages).

Would it be possible to update documentation with some more info on this limitation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0fbb8d7-a830-8b43-664f-e64a9e2109a5
* Version Independent ID: a7206a73-39e4-86e9-774f-fc1121b327b0
* Content: [Tips and Tricks - RapidStart Services - Business Central](https://docs.microsoft.com/en-Us/dynamics365/business-central/admin-tips-and-tricks-rapidstart-services)
* Content Source: [business-central/admin-tips-and-tricks-rapidstart-services.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-tips-and-tricks-rapidstart-services.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello fvet,
Thank you for your feedback! As can be seen from the non-public thread on this subject, it's not so easy to provide strict rules when it comes to RapidStart. In this example, both the number of tables and the amount of data in each table have significant impact on performance. We'll try to make this a bit more clear in this list of tips and tricks in the next doc update.
