### ISSUE TITLE
To Print the VAT Audit Report

### ISSUE THREAD

**Issue by CarmenNunes** [MicrosoftDocs/dynamics365smb-docs#408]
1. Choose the Search icon, enter **VAT**, and then choose **VAT  Statements**.
![image](https://user-images.githubusercontent.com/68849177/88531428-bd203680-cffa-11ea-894d-74842d90e7f2.png)

2. Select one of your **VAT Statement Template** 
![image](https://user-images.githubusercontent.com/68849177/88531457-cc9f7f80-cffa-11ea-93ae-f237adf5352e.png)

3.  At **VAT Statements** select **Report** to access to **"VAT Audit Report"**
![image](https://user-images.githubusercontent.com/68849177/88531496-d9bc6e80-cffa-11ea-8b19-727ae8cc87a5.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d4d4c97-e76c-239f-5365-0f2155b38c40
* Version Independent ID: c883067b-ffee-3c29-cadb-1ab06396fb9d
* Content: [How to Print VAT Audit Reports - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/localfunctionality/unitedkingdom/how-to-print-vat-audit-reports)
* Content Source: [business-central/LocalFunctionality/UnitedKingdom/how-to-print-vat-audit-reports.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/UnitedKingdom/how-to-print-vat-audit-reports.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
