### ISSUE TITLE
Misspelling of word - "Concumption"

### ISSUE THREAD

**Issue by AlinaHromadska** [MicrosoftDocs/dynamics365smb-docs#409]
You need to change the spelling of the word "Concumption" to "Consumption" in the sentence - "Concumption is posted manually in the output journal or production journal."

 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 690eac98-0b6d-2a82-6cd4-7e0ab849ba34
* Version Independent ID: d6f47217-042a-ca86-87f0-dede1c9a3606
* Content: [How to Set Up Work Centers and Machine Centers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/production-how-to-set-up-work-and-machine-centers)
* Content Source: [business-central/production-how-to-set-up-work-and-machine-centers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/production-how-to-set-up-work-and-machine-centers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
