### ISSUE TITLE
[de-DE] FAQ: Phone No.?

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#41]
Is the phone no. 1-800-865-9408 also for German Customers to extend the trial? If yes the international calling prefix is missing.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 79ad74cc-aba8-7c05-93c2-da28efdbf375
* Version Independent ID: 2f07a9a9-4cf3-c835-29d0-aab1c830277c
* Content: [FAQ zum Anpassen von Business Central - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/across-faq)
* Content Source: [business-central/across-faq.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-faq.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Daniel,
Sorry for the delay in getting back to you on this very relevant question! The phone number 1-800-865-9408 only applies to the US. To find the German phone number, change the language to de-de. 
I'm closing the issue because it's not about the docs as such.
