### ISSUE TITLE
Variants vs Identifiers vs Stock Keeping Units vs UOMs

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#410]
Can you help clarify a basic fundamental of how to manage eaches vs boxes of product as Business Central has a number of different mechanisms and i'm struggling (by reading the help guides) to understand how i'm supposed to manage what should be a relatively straight forward task.

I have a product (an item card), for the EACH (i.e. one of).  I package this item in a box of 24.  I sell both the EACH and by the Box.

I would assume this is a fairly common scenario, it's consistent with products like Shopify, Magento, BigCommerce etc. and it is fairly common for wholesalers to sell in this manner.

Can you provide a walk-through to show how best to set this up?  

Here's where i'm coming unstuck (so it may just require a little more explanation in the help files).

Am I...

1.  setting up the ITEM, and then creating a UOM for EACH (1) and BOX (24); or

2. setting up a variant (as per GS1 rules, there is a GTIN for an EACH and for the BOX)

3.  setting up a SKU

4.  setting up a SKU of a Variant

5.  setting up an identifier of a UOM?

6.  setting up an identifier of a UOM and a Variant?

7.  setting up a variant, with an identifier and then running the action "create stock keeping unit".

As you can see... it's a little murky and the help files don't provide easy clear direction on how to approach this.  UOM's to me are for converting A to B (inches to centimeters etc), Variants are often used in other applications to describe different versions of the same style (i.e different colours of the same style shirt, or different sizes of the same shirt).  SKU's could be the most logical - but they rely on UOM's and Variants (I think...) 

So functionally - what is the correct workflow to set up an item (starting at the each) and setting up the packaging (which is typically a box of eaches)?  Wholesale prices can often be different for an EACH vs a BOX to reflect the additional 'costs' of picking and packing an EACH vs a box of product.  

Thanks.
Chris.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dffa3b10-2ce8-2096-8ff3-ad23c4966e04
* Version Independent ID: 35fa1d6f-4340-f1a5-e098-5bd6c5839a8a
* Content: [How to Set Up Stockkeeping Units - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/inventory-how-to-set-up-stockkeeping-units)
* Content Source: [business-central/inventory-how-to-set-up-stockkeeping-units.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-how-to-set-up-stockkeeping-units.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by brentholtorf** [comment]
Hi Chris,

Thanks for asking. Business Central is designed to be flexible and often provides multiple ways to do something. In your case, it sounds like using UoMs (#1 on your list) will likely do the trick, especially because you mention prices. Here are links to a couple of articles that I hope will help: 

- https://docs.microsoft.com/en-us/dynamics365/business-central/inventory-how-setup-units-of-measure
- https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-record-sales-price-discount-payment-agreements
