### ISSUE TITLE
Is this a free service are there charges per document?

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#412]
Can you please confirm what the costs are for this serivce?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e0acd95-5498-9acf-1d97-698e76d99d7d
* Version Independent ID: 55e87498-2992-45cb-2956-53ddbec08d7e
* Content: [Work with Incoming Documents - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/across-income-documents)
* Content Source: [business-central/across-income-documents.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-income-documents.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello Ben,
Thank you for your feedback! The cost depends on the external OCR service that you use for the processing of physical documents or images, such as ReadSoft Online: https://store.readsoftonline.com/nav.
This will be made clearer in the next doc update.
