### ISSUE TITLE
Link does not work on this page

### ISSUE THREAD

**Issue by kkgram** [MicrosoftDocs/dynamics365smb-docs#413]
In the section other countries the link does not work https://appsource.microsoft.com/product/dynamics-365-business-central/ 

![image](https://user-images.githubusercontent.com/32876762/89931141-177ce200-dc0c-11ea-8a81-19bf08fc4aa3.png)

If you press the link you get the error below

![image](https://user-images.githubusercontent.com/32876762/89930993-ddabdb80-dc0b-11ea-9471-6499ad7db0dc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 203baec6-0fa8-b294-a7ee-5b5a4c153fde
* Version Independent ID: 8f2c2fc3-f5e5-7c15-56c6-9a5fbc1a577a
* Content: [Local functionality in Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/about-localization)
* Content Source: [business-central/about-localization.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/about-localization.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update. This is the right link: https://appsource.microsoft.com/en-us/marketplace/apps?product=dynamics-365%3Bdynamics-365-business-central&page=1
