### ISSUE TITLE
Generating XMLPorts still creates C/AL code.

### ISSUE THREAD

**Issue by meilel** [MicrosoftDocs/dynamics365smb-docs#415]
Generating XMLPorts from XML Schema as described in the documentation generates C/AL code (even in BC 160).
I think it should generate AL code in all BC versions, else its not really helpful.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32700315-68a5-7730-ea62-98f7e7ce453f
* Version Independent ID: f9d7f0ec-4728-ad7a-a331-6bcddce2f792
* Content: [Create XMLports based on XML schemas - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-to-use-xml-schemas-to-prepare-data-exchange-definitions)
* Content Source: [business-central/across-how-to-use-xml-schemas-to-prepare-data-exchange-definitions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-how-to-use-xml-schemas-to-prepare-data-exchange-definitions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! You're right that the article refers to the legacy Dynamics NAV development environment. This will be fixed in the next doc update.

**Comment by beemubotokka** [comment]
Thank you for status update. This is not only documentation issue, it's also applies to BC functionalities. Currently BC SaaS (v 16.4.14693.15090) still creates .txt file, this hasn't changed to anywhere.

**Comment by nikolakukrika** [comment]
Thanks a lot for the feedback. We will be removing this functionality soon, since it has not received a wide adoption. It has never been converted to AL, at this point we should have removed it from the product.

We will update the UI not to expose the functionality and documentation that is not supported any more.

**Comment by edupont04** [comment]
The article has been updated accordingly. Thank you for calling attention to this!
