### ISSUE TITLE
Getting error when connecting Dynamic 365 business central to Power BI

### ISSUE THREAD

**Issue by lisa-chew** [MicrosoftDocs/dynamics365smb-docs#416]
Hi, 

I am trying to connect Dynamic 365 business central online to power BI as instructed here by going through: 
Start Power BI Desktop --> Select Get Data --> Online Services --> Dynamics 365 Business Central --> connect,  but it prompt me error below after I signing in:
"
Details: "Microsoft.Mashup.Engine1.Library.Resources.HttpResource: Request failed: 
OData Version: 4, Error: The remote server returned an error: (400) Bad Request. (Request data is invalid.)
OData Version: 3, Error: The remote server returned an error: (400) Bad Request. (Request data is invalid.)"

Please advise what is the steps that I am missing. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f562094f-cff2-2c71-c806-e548041718e2
* Version Independent ID: 4f1e5021-2ea3-ba4b-8da8-a999589b8962
* Content: [Building Reports in Power BI Desktop to Display Business Central Data - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-use-financials-data-source-powerbi)
* Content Source: [business-central/across-how-use-financials-data-source-powerbi.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-how-use-financials-data-source-powerbi.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, Thanks for the feedback. Unfortunately, it is hard to determine the cause of this error without knowing more about your environment. One thing you can try, if not already done, is to make sure you have the latest version of Power BI Desktop. 

We recommend that you contact Microsoft support through the normal channel. We will then update the docs as a result as needed. Regards.
