### ISSUE TITLE
Keyboard shortcuts - Keyboard Shortcuts in the Calendar (Date Picker)- hyperlinked

### ISSUE THREAD

**Issue by SirBETE** [MicrosoftDocs/dynamics365smb-docs#419]
The sections Keyboard Shortcuts in the Calendar (Date Picker), Keyboard Shortcuts in Date Fields and Keyboard Shortcuts in the Report Preview are hyperlinked.
Unlike the other H2 sections ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96fd662-e905-9df6-60f5-c709f92077c1
* Version Independent ID: 172fd943-0f5c-6d4c-b764-ced7fd077a96
* Content: [Keyboard Shortcuts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/keyboard-shortcuts)
* Content Source: [business-central/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/keyboard-shortcuts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello,
Thank you for catching this! It will be fixed in our next doc refresh.
