### ISSUE TITLE
[de-DE] Why are some UI elements that I used in Dynamics NAV not visible in Business Central?

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#42]
"Warum sind einige Benutzeroberflächenelemente, die ich nutzte in Dynamics NAV nicht sichtbar in Business Central" > "Warum sind einige Oberflächenelemente, die ich in Dynamics NAV verwendet habe, in Business Central nicht sichtbar?"

Also instead of "Diese Funktionen wurden verwendet, um die Benutzeroberfläche in der Standardeinstellung von Business Central zu vereinfachen. Beispielsweise werden Felder, die in der Regel nicht genutzt werden wie Faxnr. häufig entfernt und auf Menübändern von Listen und Karten werden doppelte Aktionen entfernt und die meistverwendeten Aktionen gefördert." DeepL and little bit of tweaking would translate it like this:
"Diese Möglichkeiten wurden genutzt, um die Benutzeroberfläche in der Standardversion von Business Central zu vereinfachen. So wurden beispielsweise Felder, die nicht häufig verwendet werden, wie z. B. die Faxnr., entfernt, und auf Menübändern auf Listen und Karten wurden doppelte Aktionen entfernt und die am häufigsten verwendeten Aktionen werden hervorgehoben."

Also "Wenn Sie möchten, das Ihre Lösung Business Central dieselben Benutzeroberflächenelemente wie Ihre Lösung Dynamics NAV enthalten, brauchen Sie mehrere Schritte in der Entwicklungsumgebung um die #Advanced Steuerelemente durch Erweiterung zu nehmen." is not understandable. Suggestion:
"Wenn Sie möchten, dass Ihre Business Central-Lösung die gleichen Oberflächenelemente wie Ihre Dynamics NAV-Lösung enthält, müssen Sie in der Entwicklungsumgebung einige Schritte durchführen, um die #Advanced-Steuerelemente mittels Extension an die Oberfläche zu bringen."

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 79ad74cc-aba8-7c05-93c2-da28efdbf375
* Version Independent ID: 2f07a9a9-4cf3-c835-29d0-aab1c830277c
* Content: [FAQ zum Anpassen von Business Central - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/across-faq)
* Content Source: [business-central/across-faq.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-faq.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for reporting these issues about translations into German! I have sent your feedback to the translation team for further processing. Closing the issue accordingly.
