### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by mhenricus** [MicrosoftDocs/dynamics365smb-docs#420]
Where is defined how the data that is exported is filtered?
Where is defined how data is grouped, like for the Balance Sheet I can see groups, but which accounts are taken into that group?
Would be nice to have more information about this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bca601ad-a164-7d2f-1339-e7a45a19576c
* Version Independent ID: c69dee3c-8868-cefd-9e82-0d1ab534b8a2
* Content: [Work with financial overviews in Excel - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-analyze-excel)
* Content Source: [business-central/finance-analyze-excel.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-analyze-excel.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello mhenricus,

Thank you for your feedback! The pre-configured Excel reports that you can launch from the Business Manager and Accountant home pages are based on whatever data is in the company that you are working in. For example, the demonstration company, CRONUS,  has set up the chart of accounts to list 3 cash accounts under Current Assets: 10100 Checking account, 10200 Saving account, and 1030 Petty Cash. They have the Account Subcategory field set to Cash, and it's their combined amount that shows up as "Cash" in the Balance Sheet Excel report.
I hope you find this information useful. We'll try to make it clearer in our next major update (October 1).

**Comment by edupont04** [comment]
Now live.
