### ISSUE TITLE
 "Warehouse Class Code" on the items page

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#421]
The _Learn More_ link on the Warehouse Class Code field links to this page, but there is no information on this page relating to the field at all.  Can you include information about this field on this page OR correct the link so that it directs to the correct help page?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37d63058-5104-f4c6-dd07-21caf3a4a4a8
* Version Independent ID: 6c3e166d-bdc9-b823-dfc4-62957f5aa385
* Content: [Create Item Cards for Goods or Services - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/inventory-how-register-new-items)
* Content Source: [business-central/inventory-how-register-new-items.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-how-register-new-items.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hello Chris,

Thank you for your feedback! The Learn More link is actually pointing at the right place,  but the tooltip for the Warehouse Class Code field is a bit ... economic, so to say. Through the warehouse class codes, the program ensures that each item is stored only in bins that meet its storage needs. You can set up warehouse class codes and assign them to zones, bins, and items, depending on your business needs. We'll get that clarified in a future update of the tooltip and here in the product Help.

**Comment by chris7777au** [comment]
Hi Eva.

Figured that may be the case.  As an admin, I guess I’m looking to Microsoft to have clear documentation on each field (regardless of how economic those fields may be) so that as a customer we can use the field correctly (without guessing what the developers intention was).  If you can look adding some commentary somewhere in future on this page (or the page the link goes to), that would be great.

Cheers
Chris Pope
Pacsource Pty ltd
6 Dalmore Drive
Scoresby, Victoria 3179
Australia
T. +61.3.9763.4500
M. +61.447.888.777
E. chris@pacsource.com.au<mailto:chris@pacsource.com.au>
S. chris_7777

Disclaimer ; The information in this email including any attachments is confidential and may be legally privileged. If an addressing or transmission error has misdirected this email please notify the author by replying to this email and destroy the original message. If you are not the intended recipient, any use, disclosure, copying or distributions prohibited and may be unlawful. Distribution of this email to other parties may result in criminal prosecution.

**Comment by edupont04** [comment]
Hello Chris,
We're adding a new section to the article in our next major update. The fields are explained here: https://docs.microsoft.com/en-AU/dynamics365/business-central/design-details-warehouse-setup#class

**Comment by edupont04** [comment]
Now live.
