### ISSUE TITLE
IS there missing data here?

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#422]
Hello
What are the listed fonts? I ask a a customer wanted to install Khmer which is a Cambodian font . Is this permitted?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 082b762b-f7b9-3d50-af8a-c892b34f6347
* Version Independent ID: 3170ce53-ed8e-da6c-7a9f-bf5d6d31e20a
* Content: [Available Fonts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-fonts)
* Content Source: [business-central/ui-fonts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-fonts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by brentholtorf** [comment]
Hello,

Here are links to topics that list the [fonts](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-fonts) and [languages](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-countries-and-translations) that Business Central supports. I checked, and didn't see Khmer or Cambodia listed. We're expanding to new countries all the time though, so who knows, maybe it will become available soon.

**Comment by makdaddy8888** [comment]
There are no fonts listed on that page.

Kind Regards
Ben Opit
+61411707070

**Comment by makdaddy8888** [comment]
Let me be specific. The link provided does not share what fonts are available.

**Comment by brentholtorf** [comment]
The [Available Fonts](https://docs.microsoft.com/dynamics365/business-central/ui-fonts) page has a list of fonts.
