### ISSUE TITLE
Average vs Specific setup option - incorrect comment

### ISSUE THREAD

**Issue by slavakos** [MicrosoftDocs/dynamics365smb-docs#425]
It looks like the Comment for Average vs Specific setup option had been swapped.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5a40235-e14f-f7c0-1517-d1559a986f81
* Version Independent ID: 2a3c68fb-a4e8-5c07-fd84-14c571cdbfff
* Content: [Setup Best Practices - Costing Method - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/setup-best-practices-costing-method)
* Content Source: [business-central/setup-best-practices-costing-method.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/setup-best-practices-costing-method.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by edupont04** [comment]
Now live.
