### ISSUE TITLE
Valutakode for en eller flere Finanskladdelinje er forkert. Du kan kun bruge DKK eller EUR.

### ISSUE THREAD

**Issue by CurabisMartin** [MicrosoftDocs/dynamics365smb-docs#426]
I try to make at payment in Business Central cloud version, with standard BC settings. INTBANK for international transfer and DOMBANK for Danish transfer. All payments to DOMBANK works fine - also FIK-payments. 

When I try to generate a file, it tells me that it can only be done in DKK and EUR. So international payments in e.g. SEK and GBP returns an error.

If I try to make a payment in SEK I get this message:

Valutakode for en eller flere Finanskladdelinje er forkert. Du kan kun bruge DKK eller EUR.
(In English: Currency code for one or more Financial Journal line is incorrect. You can only use DKK or EUR.)
I guess that there must be a setting that tells the system, that I can only make payments in those currencies, but I cannot find that setting. 

They currency and rates are set in the system. The bank account is set with blank in currency to allow all currencies. I have tried to change currency on the bank account. It was set to blank (LCY) to allow all currencies, but I have also tried with SEK with the same error. Can it be an error in the definition bank export setup of BTI?

Hope you can help me.

[Angiv feedback her]

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 76c9bb7a-4cd4-6f81-86b1-9f2f01c20c54
* Version Independent ID: 7ed784bd-4154-23ce-130d-0490cdcedd5e
* Content: [Brug af udvidelsen Betalinger og afstemninger (DK) - Business Central](https://docs.microsoft.com/da-dk/dynamics365/business-central/ui-extensions-payments-reconciliation-formats-dk#to-use-the-extension-to-export-payment-data)
* Content Source: [business-central/ui-extensions-payments-reconciliation-formats-dk.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-extensions-payments-reconciliation-formats-dk.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. It sounds like you might have come across a bug. Since your question is not about the Help, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).
