### ISSUE TITLE
Item Tracking

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#429]
If you create a Job Planning Line and you add an Item that has tracking you cannot post the invoice as "You cannot use items tracking on Sales Lines created from a job"
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2276afa0-eb92-c372-299a-40521b40c88e
* Version Independent ID: f21f7b2c-3c3d-cc2e-ae39-92fb19582dfc
* Content: [Purchase Items or Services for a Job and Manage Supplies - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/projects-how-manage-project-supplies)
* Content Source: [business-central/projects-how-manage-project-supplies.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/projects-how-manage-project-supplies.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

I cannot reproduce this in my setup, probably because I don't quite understand the Jobs module. I suggest you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).
