### ISSUE TITLE
Error in the description of deletion of customizations

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-docs#430]
The first step in deleting customizations is says to choose the _Customized Pages action_, but is is called _Manage customized pages_

And it is to be found under _Navigate_.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37666f25-436e-c4c9-2101-ac7eb2d482a3
* Version Independent ID: cfd398f5-97fd-44f9-2ae7-acf4627ce9d8
* Content: [Customizing Pages for Roles - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-personalization-manage)
* Content Source: [business-central/ui-personalization-manage.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-personalization-manage.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by lvanvugt** [comment]
Ouch, wrongly read: it does state it, but not so clear in the layout. You might consider improving this.

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by edupont04** [comment]
Now live.
