### ISSUE TITLE
misc typo

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-docs#431]
This article provides tips to how to make progress.
should be
This article provides tips on how to make progress.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2fce298-457b-2328-fabf-ad1e2eadc57f
* Version Independent ID: 9f7133dd-c5b6-aa40-9989-8180bb4edc2b
* Content: [Warnings and Error Messages - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/product-error-messages)
* Content Source: [business-central/product-error-messages.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/product-error-messages.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by edupont04** [comment]
Now live.
