### ISSUE TITLE
Reword Deleting Customer Cards section

### ISSUE THREAD

**Issue by dianalogan** [MicrosoftDocs/dynamics365smb-docs#433]
[Reword "To delete customer cards with ledger entries, contact to Microsoft partner to do so through code." to "To delete customer cards with ledger entries, contact a Microsoft partner."]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450f9b98-bead-cd35-a10c-ccb67995c9e8
* Version Independent ID: 251d06f2-9ff2-3f53-f5e9-53597ae4d771
* Content: [Create a Customer Card to Register New Customers - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/sales-how-register-new-customers)
* Content Source: [business-central/sales-how-register-new-customers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/sales-how-register-new-customers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
