### ISSUE TITLE
Diagram or example workthough

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#434]
Can you please assist with a demo scenario as an example or maybe how the sales cycle flow through to delivery might work? Including expected steps? This would help share the value of assembly in BC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d00a91a9-68d4-7bdd-fe87-0cf5e6d112f3
* Version Independent ID: daee230a-57c5-1386-905e-d3811f4b0a8c
* Content: [Assembly Management - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/assembly-assemble-items)
* Content Source: [business-central/assembly-assemble-items.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/assembly-assemble-items.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,
We have described the process here: [https://docs.microsoft.com/dynamics365/business-central/walkthrough-selling-assembling-and-shipping-kits](https://docs.microsoft.com/dynamics365/business-central/walkthrough-selling-assembling-and-shipping-kits), and you can see more technical descriptions in the [Design Details: Supply Planning](https://docs.microsoft.com/dynamics365/business-central/design-details-supply-planning) section.
We'll get those links added to this article in the next doc update.
