### ISSUE TITLE
Settings in video are not correct

### ISSUE THREAD

**Issue by mhenricus** [MicrosoftDocs/dynamics365smb-docs#435]
The data in the second video is not correct. This will only import the first currency found.
To fix this, the first node should be /gesmes:Envelope/Cube/Cube/Cube
See also: https://community.dynamics.com/business/f/dynamics-365-business-central-forum/402899/ecb-exchange-rate-service-only-imports-first-rate/1096202#1096202

![image](https://user-images.githubusercontent.com/69308907/94656803-d302ee00-0300-11eb-8a6a-ce7b0d534334.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cbd815c-4e94-b21d-dbfa-411885d4a5dd
* Version Independent ID: f4aced3d-7e1c-6486-f8dc-7749cc9ddd12
* Content: [Update Currency Exchange Rates - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-how-update-currencies)
* Content Source: [business-central/finance-how-update-currencies.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-how-update-currencies.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

Thanks for letting us know. I've created a work item to update the settings we show in the video. Until that's done, I've added a note before the video to call out the correct setting.
