### ISSUE TITLE
Missed field in Tax fasttab section of Company information 

### ISSUE THREAD

**Issue by nperezo** [MicrosoftDocs/dynamics365smb-docs#436]
Re. Mexico Electronic Invoicing setup for Business Central Essential mode (Saas):
I'm sorry but there aren't the following fields that you have mentioned:
- SAT Certificate Thumbprint
- Send PDF Report
- PAC Code
- PAC Environment

I found the "PAC Code" field in PAC WEB SERVICES (page 10455), but i couldn't find the other ones.
I'll appreciate your prompt solution/help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6de8b2d2-0e6b-00f1-9728-b896a718237c
* Version Independent ID: 5e893f29-ebd1-7639-82e8-45cc67f8f949
* Content: [How to Set Up Electronic Invoicing - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/mexico/how-to-set-up-electronic-invoicing)
* Content Source: [business-central/LocalFunctionality/Mexico/how-to-set-up-electronic-invoicing.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Mexico/how-to-set-up-electronic-invoicing.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! It turns out that the article was mixing up two different steps. The missing fields are available in the **General Ledger Setup** page, not the **Company Information** page.
This will be fixed in the next doc update.
