### ISSUE TITLE
UK Group VAT supported or not?

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-docs#437]
With the release of Business Central 2020 Wave 2020 there is this reference in the release plan
[VAT group reporting](https://docs.microsoft.com/en-us/dynamics365-release-plan/2020wave2/smb/dynamics365-business-central/group-vat-reporting) but this says it is not supported [Not in scope of this feature](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedkingdom/making-tax-digital-submit-vat-return#not-in-scope-of-this-feature).  Which is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35bb67a1-ea3e-ae63-2b5d-c7f6e099459e
* Version Independent ID: a6a3650f-2c0a-4d1e-b1a6-8472e0151df9
* Content: [Making Tax Digital - Submitting VAT Returns - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedkingdom/making-tax-digital-submit-vat-return)
* Content Source: [business-central/LocalFunctionality/UnitedKingdom/making-tax-digital-submit-vat-return.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/UnitedKingdom/making-tax-digital-submit-vat-return.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by brentholtorf** [comment]
Hi,

Yes, the VAT group reporting feature has shipped as an extension. Here's a link to the article that describes it.

https://docs.microsoft.com/en-us/dynamics365/business-central/ui-extensions-vat-group
