### ISSUE TITLE
Recommended documentation update. 

### ISSUE THREAD

**Issue by JeffreyChavarria** [MicrosoftDocs/dynamics365smb-docs#438]
https://docs.microsoft.com/en-us/dynamics365/business-central/bank-how-setup-bank-statement-service#to-enable-automatic-import-of-bank-statements

"Issues can best be resolved by unlinking the online bank account and then re-creating the link."

In an already linked account, this action will result in the account losing access to previous transactions.

Reference: https://developer.yodlee.com/Knowledge_Base/Transactions

"At the time of account addition, 90 days of transactions is pulled and as the consumer continues to access the Yodlee platform his or her transaction history is built in the Yodlee’s database. For example, a consumer may have an account at a bank for five years but has added his or her account to the Yodlee platform a year ago. In this case, only a year and 90 days of transactions will be present in Yodlee’s database and the executeTransactionSearch API can retrieve these transactions."

Thanks,
Best Regards.

**Comment by edupont04** [comment]
Hello @JeffreyChavarria,

Thank you for your feedback! The way I read the information in the Envestnet Yodlee knowledge base, our statement about unlinking the bank account does not contradict their information. Your account has been added to the Yodlee platform, and the API counts from that first addition.
