### ISSUE TITLE
Applies to Doc Due Date offset function

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#439]
We noticed that when using the Suggest Vendor Payments and we want to use the Applies-to-Doc. Due Date offset this field is not working as expected. We do not have the Find Payment Discounts enabled so then the Applies-to-doc due date offset should work. 
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff228543-8999-8073-3d13-2de0800c677d
* Version Independent ID: 5d180045-1481-2a02-83af-c33c6d1d54f8
* Content: [Use the Suggest Vendor Payments Batch Job - Business Central](https://docs.microsoft.com/en-ca/dynamics365/business-central/payables-how-suggest-vendor-payments)
* Content Source: [business-central/payables-how-suggest-vendor-payments.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/payables-how-suggest-vendor-payments.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/dynamics365/business-central/product-help-and-support#report-a-problem).
