### ISSUE TITLE
[de-DE] Finance -> Finanzbuchhaltung

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#44]
The English Word "Finance” has a fixed German translation in the BC Application: "Finanzbuchhaltung". But is not always used.
---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d8f9a60b-28c6-1406-637d-05b72728c7ac
* Version Independent ID: d0ee01cd-65a3-70ba-5205-a1d97568403b
* Content: [Einrichten von Prozessen in Financials - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/finance-setup-finance)
* Content Source: [business-central/finance-setup-finance.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-setup-finance.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for reporting these issues with the translation to German! This has been reported to the translation team. Closing the issue accordingly.
