### ISSUE TITLE
cannot find field when personalising

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#441]
Hi Team

we are trying to show these 2 fields 
**Bal. Account Type** and **Bal. Account No**. even though we are trying to use the personalization option.

Is this a bug? 
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd57c018-ea96-6b1a-21b6-40b2c9f21e9e
* Version Independent ID: 5f23a357-47d6-8151-460d-e0374badf294
* Content: [How to Settle Purchase Invoices Promptly - Business Central](https://docs.microsoft.com/en-ca/dynamics365/business-central/finance-how-to-settle-purchase-invoices-promptly)
* Content Source: [business-central/finance-how-to-settle-purchase-invoices-promptly.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-how-to-settle-purchase-invoices-promptly.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello Ben,

Thank you for your feedback! You're right that these fields cannot be added with the personalisation tool. Instead, you must contact a Microsoft partner who can add them through code. We'll get this clarified in the next doc refresh.
