### ISSUE TITLE
List all available Fonts in BC SaaS

### ISSUE THREAD

**Issue by ChrisBlankDe** [MicrosoftDocs/dynamics365smb-docs#443]
Please List all available Fonts in BC SaaS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 082b762b-f7b9-3d50-af8a-c892b34f6347
* Version Independent ID: 3170ce53-ed8e-da6c-7a9f-bf5d6d31e20a
* Content: [Available Fonts - Business Central](https://docs.microsoft.com//en-us/dynamics365/business-central/ui-fonts)
* Content Source: [business-central/ui-fonts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-fonts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by edupont04** [comment]
Now live.
