### ISSUE TITLE
Repair Status Flags

### ISSUE THREAD

**Issue by KTL-KSweeney** [MicrosoftDocs/dynamics365smb-docs#445]
Please update documentation to indicate that the flags (e.g. In Process) dictate which statuses can be selected from the current record. In other words, users must have the In Process flag enabled on the Pending record to switch from Pending to In Process.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ef143c5-dae8-7d81-419e-4f2d5b857a14
* Version Independent ID: 8c6b4067-dfef-1ec9-2237-b5bab4ab9c4e
* Content: [Service Order Status and Repair Status - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/service-service-order-status-and-repair-status)
* Content Source: [business-central/service-service-order-status-and-repair-status.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/service-service-order-status-and-repair-status.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by edupont04** [comment]
Updated.

**Comment by KTL-KSweeney** [comment]
Thanks!

Sincerely,
Kieran Sweeney


Kieran Sweeney
Business Software Consultant
Office:301-360-0001
Direct:301-517-6694
KTL Solutions, Inc. - Disclaimer
 This message contains confidential information and is intended only for the individual(s) addressed in the message. If you are not the named addressee, you should not disseminate, distribute, or copy this e-mail. If you are not the intended recipient, you are notified that disclosing, distributing, or copying this e-mail is strictly prohibited.
