### ISSUE TITLE
Repair Status Change Prerequisites + Priority Mapping

### ISSUE THREAD

**Issue by KTL-KSweeney** [MicrosoftDocs/dynamics365smb-docs#446]
Please update documentation to indicate that the flags (e.g. In Process) dictate which statuses can be selected from the current record. In other words, users must have the In Process flag enabled on the Pending record to switch from Pending to In Process.

Furthermore, it appears that there are no pages exposed in D365BC with which to relate priority with Repair Status. As a result, selecting a repair status will immediately result in an exception because Priorities are a required field. Please document that configuration packages are necessary and identify the missing page for addition in the next major release.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ef143c5-dae8-7d81-419e-4f2d5b857a14
* Version Independent ID: 8c6b4067-dfef-1ec9-2237-b5bab4ab9c4e
* Content: [Service Order Status and Repair Status - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/service-service-order-status-and-repair-status)
* Content Source: [business-central/service-service-order-status-and-repair-status.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/service-service-order-status-and-repair-status.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! This is complicated, but we'll try to have this fixed in the next doc update.

FYI, the priority is set in the Service Order Status Setup page. Then, when you set up a repair status in the Repair Status Setup page, the priority is updated when you set the Service Order Status field.

If you want to suggest a feature request, you can do so here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)

**Comment by edupont04** [comment]
Follow up: If you meant the priority field on the service order header rather than the lines, then the program fills in this field based on the highest priority on the service item lines.

**Comment by KTL-KSweeney** [comment]
Thanks! I had a hard time getting to that page—probably because I didn’t have the search name. I ended up using a configuration package to import these Service Order Statuses.

Sincerely,
Kieran Sweeney


Kieran Sweeney
Business Software Consultant
Office:301-360-0001
Direct:301-517-6694
KTL Solutions, Inc. - Disclaimer
 This message contains confidential information and is intended only for the individual(s) addressed in the message. If you are not the named addressee, you should not disseminate, distribute, or copy this e-mail. If you are not the intended recipient, you are notified that disclosing, distributing, or copying this e-mail is strictly prohibited.

**Comment by edupont04** [comment]
Updated.
