### ISSUE TITLE
Topics : Example – Fixed Application with Average Cost  

### ISSUE THREAD

**Issue by sigitsup1771** [MicrosoftDocs/dynamics365smb-docs#447]
Link : https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-item-application

On below statement :
If the user had not made the fixed application between the purchase credit memo and the purchase with the incorrect direct unit cost (step 2 in the previous scenario), then the cost would have been adjusted differently.

The following table shows the result on the item's value entries if step 2 in the previous scenario is performed without a fixed application.

Item Ledger Entry Type	Valued Quantity	Cost Amount (Actual)	Appl.-to Item Entry	Valued by Average Cost	Item Ledger Entry No.	Entry No.
01-01-20	Purchase	  1	200.00		No	1	1
01-01-20	Purchase	  1   1000.00		No	2	2
01-01-20	Purchase	 -1	433,33		Yes	3	3
01-01-20	Purchase 	  1	100.00		No	4	4
01-01-20	Sale	         -2    866,67		Yes	5	5

Why value on purchase return 433.33 not 600  ( purchase return transaction happen before entry no 4 ) and Sale value 866.67 not 350 ?
on purchase return value = (200+1000)/(1+1) = 600
on Sale value = (600+100)/(1+1)=350

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d637fa6f-a440-1f1b-ed97-1a2d7f9e8bb5
* Version Independent ID: c32b25eb-3691-dec7-2eae-3dbbac6f05cf
* Content: [Design Details - Item Application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-item-application)
* Content Source: [business-central/design-details-item-application.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-item-application.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hi,

The example is correct. I think what was unclear was that the result is after posting the correction. The table introduction has been updated to reflect that.

The costing method is Average, and all transactions are from the same day (01-01-20), and therefore the average cost period is the same. So, to calculate the average Business Central adds up all inbound transactions (purchases) in the same average cost period, as follows: 

amount: 200+1000+100 = 1300; 
qty: 1+1+1 = 3. 

That gives an average cost: 1300/3 = 433,3(3)

This cost is then assigned to outbound (sales) transactions:

Qty -1; Amount -433,33
Qty -2; Amount -866,66

If you're interested, here's a link to an article about average cost, https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-average-cost.
