### ISSUE TITLE
Skilled Resources and Resourse Skills

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#449]
Can you please provide detailed documentation on this area. You can find this on the item card under resources

The help text is very limited. Are there any functions that this area of Resources has that might be beneficial to mention?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84ddff91-f250-6168-265d-fbe6ffd41a5c
* Version Independent ID: e58801fd-14cc-77b5-4aaf-ccb7bbc9ff78
* Content: [Managing Inventory - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/inventory-manage-inventory)
* Content Source: [business-central/inventory-manage-inventory.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-manage-inventory.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Ben,

These two actions are for tasks that are related to items of type service. If an item requires service using resources with particular skills, you must assign resource skills to the item. We'll add some content about this in our next doc update.

**Comment by edupont04** [comment]
Now live.
