### ISSUE TITLE
Wrong reservations when "Create Return-Related Documents" in "Sales Return Order"

### ISSUE THREAD

**Issue by aproehl79** [MicrosoftDocs/dynamics365smb-docs#45]
When selecting action "Create Return-Related Documents" from "Sales Return Order" the system creates "Purchase Return Order", "Purchase Order" and "Sales Order" as expected:

![image](https://user-images.githubusercontent.com/16100797/46337588-2e287a00-c62e-11e8-99c2-9461ab406ed5.png)

Problem is that the reservations made by the system are incorrect. The Sales Order is reserved against the Sales Return Order instead of the Purchase Order.

![image](https://user-images.githubusercontent.com/16100797/46337815-caeb1780-c62e-11e8-945c-4f1feee01512.png)

The Purchase Return Order has no reservation. Should have a reservation against the Sales Return Order:

![image](https://user-images.githubusercontent.com/16100797/46338007-4d73d700-c62f-11e8-9f4f-425f2a95adce.png)

**Comment by SorenGP** [comment]
Hi - If you believe that this reservation logic is wrong, then please report it through your Microsoft support provider. Alternatively, suggest a change on the Ideas site. Choose the **Product feedback** button.

Going forward, please do not use this documentation feedback mechanism to discuss product issues.

Sören, Business Central writer
