### ISSUE TITLE
Page needs to provide details for features that reference it

### ISSUE THREAD

**Issue by ilyalehrman** [MicrosoftDocs/dynamics365smb-docs#450]
When setting up a resource, clicking on Learn More takes you to this page even when the page has no mention of the item that referenced it.

For example, the field Contract Class on the New Resource page has the 'Learn more' link that is supposed to lead to the explanation what Contract Class is / used for. After navigating to this page, however, there's absolutely no mention of Contract Class. That's more than useless, that misleading and confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b4f6740-496c-0f6a-83e6-722e2e62f671
* Version Independent ID: 512d5f71-0766-e9bc-f224-5b930c610759
* Content: [Set Up Resource Costs, Prices, and Capacity - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/projects-how-setup-resources)
* Content Source: [business-central/projects-how-setup-resources.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/projects-how-setup-resources.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! In the current version of Dynamics 365 Business Central, each field is explained in a tooltip, and the Learn More links apply to the page where the field is shown. You can read about the Help system here: [Dynamics 365 Business Central User Assistance Model](https://docs.microsoft.com/dynamics365/business-central/dev-itpro/user-assistance?toc=/dynamics365/business-central/toc.json)

In some cases, this does not always work for people. We know that, and we're taking your feedback into consideration for what might change in the future.

For you information, the Contract Class field the collective agreement for the employee's contract. You can enter a maximum of 20 characters, both numbers and letters.
