### ISSUE TITLE
Minor edit to scope suggested. 

### ISSUE THREAD

**Issue by eyestone57** [MicrosoftDocs/dynamics365smb-docs#451]
I believe this section should point to WMS using Zones _and _Bins not _or _. I have been successful testing the this process in a Bin Only (Silver location in Cronus) using bins. I have not tested yet in a location using Advanced Warehousing _not _using Directed Pick and Put-away but I believe this order would work there as well.  A minor edit to be sure, but with significant impact.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e736a056-8fcd-bc0d-0258-dc64f0c8749f
* Version Independent ID: d8077588-7773-9a48-6c21-e2982e04e02d
* Content: [Count Inventory With Document-Based Functionality - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/inventory-how-count-inventory-with-documents)
* Content Source: [business-central/inventory-how-count-inventory-with-documents.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-how-count-inventory-with-documents.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! We don't currently have someone who is an expert on this, so please forgive me if I am leading you the wrong way after all!

The way the product works is that the **Whse. Phys. Inventory Journal** page calculates inventory on _bin_ level and shows which items in which bins must be counted. So the current wording in this article is right that if you use bins, then you must use the **Whse. Phys. Inventory Journal** page. If you don't use bins, then use the **Phys. Inventory Journal** page.

If you arrange your warehouse in zones, then I believe that is simply a way to organize bins. So you're right that the current wording should be changed to reflect that it's really about whether or not you use bins. We'll get that cleared up in the next doc refresh.

**Comment by eyestone57** [comment]
Hello back. I understand and agree with your thoughts re. the journals, however I am addressing the recently introduced Physical Inventory Order not either of the other methods that you mention. I believe BINS is supported by this new Document but Zones and by extension, ZONES AND BINS is not. If the intent is not to support a simple warehouse using only BIN Mandatory, then I will be surprised as the Order presents BIN as a field in Table 5876 which is the subline table to the Order header. I was able to successfully process using Bins. The Order posted properly and the subsequent ILE's were correct. 
So it is Zones, not Bins I believe should be the limiting factor.

**Comment by edupont04** [comment]
Sorry, yes, you're right. You can use physical inventory orders if you use bins, but not if you use zones. 
My apologies for the confusion!

FYI, you can see when and why this feature was added here: https://docs.microsoft.com/business-applications-release-notes/april19/dynamics365-business-central/application-enhancements#use-physical-inventory-orders-to-better-structure-your-physical-inventory-counting
And you can read about its origins here: https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/hh933819(v=nav.90)
