### ISSUE TITLE
Which version does this apply to?

### ISSUE THREAD

**Issue by cparker4486** [MicrosoftDocs/dynamics365smb-docs#452]
I have v14.6 on-premises and this information doesn't apply to me. I am the SUPER user but a search for "retention" doesn't find anything at all.

I have no idea which version of BC any of these documentation pages are referring to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce850dab-5ea7-a7c5-1532-4452688dd7c9
* Version Independent ID: 56e66049-43d8-cae5-b705-34c4c259d3b2
* Content: [Clean Up Data with Retention Policies - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-data-retention-policies)
* Content Source: [business-central/admin-data-retention-policies.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-data-retention-policies.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! The content on Docs.microsoft.com generally reflects the latest version of Dynamics 365 Business Central unless a different version is explicitly specified.
In general, we recommend that organizations that deploy Business Central on-premises deploy their customized Help content to their own website, be that an online library or the legacy Help Server website. That way, users such as yourself will not be confused that the content on Docs.microsoft.com does not match their experience of the product.

**Comment by cparker4486** [comment]
Thanks for the recommendation but I have to be frank and let you know that it's an impossibility for many businesses. It's _literally_ impossible to do that because it's so far down on the priority list.

I feel like Microsoft removed all hint of version(s) of software from the docs. Is that true? If so, my take is it was too hard even for the experts to understand what was happening so you just got rid of it and put the responsibility on the customer.

Back to your first statement. What is the latest version?

Thank you!

**Comment by edupont04** [comment]
Closing as answered. Also, we now have downloads available per major version and last-update-before-latest-version: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/help/contributor-guide#get-content-from-the-github-repos
