### ISSUE TITLE
Bulk Editing - Making Contacts into Customers

### ISSUE THREAD

**Issue by SaveMH** [MicrosoftDocs/dynamics365smb-docs#454]
Hello,

I am having trouble figuring out if it is possible to bulk create customers from contacts.  I have company and person contacts created but I do not have a Customer Card created for that contact.  Is there an easy way to bulk create new customers from the company contact cards? 

Currently, I am viewing each Company Contact card and going to "Actions > Functions > Create As > Customer" to create a new customer.  Is there a faster way to do this?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e385858d-8ce1-3633-a11f-14fefb1bafdf
* Version Independent ID: 2cc8dd7b-3cf2-89b0-8b54-c647f94eaa6b
* Content: [Set Up Information for Contacts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/marketing-setup-contacts)
* Content Source: [business-central/marketing-setup-contacts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/marketing-setup-contacts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. The default version of Dynamics 365 Business Central does not have functionality to bulk-create customers based on existing contacts. As you have found out, you can create each individual contact as a customer but not as a batch. You can search AppSource for an app to help you, or you can submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
