### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by skeck** [MicrosoftDocs/dynamics365smb-docs#456]
"Items" should be translated to "Artikel", not "Elemente".

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e8cb2416-68da-4085-1996-81284267ae01
* Version Independent ID: f242d19a-bbc5-685a-4a26-01b3713fa2ec
* Content: [Artikelreferenzen verwenden - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/inventory-how-use-item-cross-refs#feedback)
* Content Source: [business-central/inventory-how-use-item-cross-refs.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-how-use-item-cross-refs.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! This has been reported to our translation team, and it will be fixed in the next translation update.
