### ISSUE TITLE
German documentation is badly translated - how can i help

### ISSUE THREAD

**Issue by EikeKortz** [MicrosoftDocs/dynamics365smb-docs#459]
I am trying to use the German pages for Business Central documentation over and over again, you just can't read it because the translations are often so bad. I'd like to help but while there is an "edit" button on the English pages, there is no option for me to edit the German translation? is there any way to support the product here?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 613d9e8a-856d-e913-ca98-c48e8376fb22
* Version Independent ID: a7b2e7f3-d8f4-8504-fa5b-fa9fa0afc4cc
* Content: [Finanzberichte mithilfe von Kontenschemata bauen - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/bi-how-work-account-schedule)
* Content Source: [business-central/bi-how-work-account-schedule.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/bi-how-work-account-schedule.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! Our internal processes mean that our translation repos cannot receive contributions. We encourage you to submit feedback about what you consider incorrect or poor translations using the Feedback link at the bottom of the relevant article here on the Docs.microsoft.com site. Each submitted issue is then reported to our translation team,  who will triage and fix in the next translation update, which could be 1-2 months later.

Thanks!
