### ISSUE TITLE
Planning Date vs. Planned Delivery Date

### ISSUE THREAD

**Issue by DaveBoehmPBSI** [MicrosoftDocs/dynamics365smb-docs#46]
When I change the "Planning Date", the "Planned Delivery Date" changes to match the "Planning Date", and vice versa.  I think this is counter-intuitive.  Why two dates, if they always match?  I would like to have a "Start Date" and "End Date" for each budgeted line item.  The description in the documentation indicates the "Planning Date" is the date a budgeted, billable, or "budget and billable" line is to be delivered.  It says nothing about the "Planned Delivery Date".  Why these two dates are always the same, and why there isn't any "start date" is not explained here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d120b85-a4c6-8a89-ff10-fe19b78ef924
* Version Independent ID: dd35a369-e248-d790-9ea8-2b4b896cc059
* Content: [Set Up and Manage a Budget for a Job - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/projects-how-manage-budgets)
* Content Source: [business-central/projects-how-manage-budgets.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/projects-how-manage-budgets.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback

I have investigated if the two fields can ever be different, for example per a lead-time setting. This is not the case, so I agree with you that the design is confusing. It seems that only the Planned Delivery Date field is relevant for the user as this is where you define the "end date". The Planning Date field, according to the tooltip, is used for filtering in various job reports. 

Please choose the Product feedback button to suggest a product improvements, such as to hide the Planning Date field or resolve the confusion somehow else.

Meanwhile, I have updated the topic to explain this better, and I have explained the relation of the Planned Delivery Date field with the End Date and Start Date fields on the related job task. The updated help will be available in approximately one week.

**Comment by Sine815** [comment]
The Planning Date is changed via the Change Job Dates report. The Planned Delivery Date remains on the same date.

I don't know if this really makes sense.
