### ISSUE TITLE
Как настроить мне

### ISSUE THREAD

**Issue by matuhinal** [MicrosoftDocs/dynamics365smb-docs#460]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0da49338-8ade-ae30-8c49-e6c6c9b17633
* Version Independent ID: bde83d6f-8a32-7907-b0a1-12a7f84a78a1
* Content: [Set Up Banking - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/bank-setup-banking)
* Content Source: [business-central/bank-setup-banking.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/bank-setup-banking.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).
