### ISSUE TITLE
SLA

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#461]
Where is the link for MS SLA on BC?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b86d301-cf03-0dd0-abdd-9a73743b4285
* Version Independent ID: 4e4d4219-2c2f-0324-6166-414f31158224
* Content: [Meet Microsoft Dynamics 365 Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/)
* Content Source: [business-central/index.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/index.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

The Dynamics 365 Business Central service follows the Modern Lifecycle Policy. For more information, see [https://docs.microsoft.com/en-us/lifecycle/policies/modern](https://docs.microsoft.com/en-us/lifecycle/policies/modern)

Your Business Central reselling partner will help you with technical support. They can submit support requests through the admin center and view information about service availability.

**Comment by makdaddy8888** [comment]
Can you please add this element in the docs somewhere prominent so that this is easy to find. I get this SLA question a lot as well as the backup and retention policy clearly defined 

Kind Regards
Ben Opit
+61411707070

**Comment by edupont04** [comment]
The information was already available here: https://docs.microsoft.com/en-us/dynamics365/business-central/compliance/compliance-service-compliance#service-terms

Now also added here: https://docs.microsoft.com/en-us/dynamics365/business-central/across-faq#what-are-the-service-level-agreements-for-the-cloud
And linked to from the landing page (the See Also section).
