### ISSUE TITLE
Is there a similar feature in the Business Central US version? where we can setup up partial payments to set the installments in 30 D, 60 D and 90 Days ?

### ISSUE THREAD

**Issue by Srinathns29** [MicrosoftDocs/dynamics365smb-docs#462]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f0109b5-e9f8-5537-d13d-5f3c6f9cb8cf
* Version Independent ID: 669e2224-0f43-e744-d313-ff1d72d4fff2
* Content: [Setting Up Payment Terms - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/italy/how-to-set-up-payment-terms)
* Content Source: [business-central/LocalFunctionality/Italy/how-to-set-up-payment-terms.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Italy/how-to-set-up-payment-terms.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello, 
Thank you for your question! You can set up payment terms that you then associate with the relevant payment methods. It's a bit complicated to explain, but you can get a kind of introduction in the video that is embedded in this article: https://docs.microsoft.com/en-us/dynamics365/business-central/finance-payment-methods

We'll make it easier to find the Payment Terms page in the next doc update.

**Comment by edupont04** [comment]
Now live.
