### ISSUE TITLE
Abono

### ISSUE THREAD

**Issue by Tonogbanua** [MicrosoftDocs/dynamics365smb-docs#463]
[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: a8844b53-7bd8-67ab-a099-f608f2ed92f2
* Version Independent ID: 992df4d1-648d-7899-1aa5-2c5429f14241
* Content: [Crear facturas o abonos de servicios - Business Central](https://docs.microsoft.com/es-es/dynamics365/business-central/service-how-create-invoices)
* Content Source: [business-central/service-how-create-invoices.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/service-how-create-invoices.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
