### ISSUE TITLE
Korrektur: So bereiten Sie ein Konfigurationspaket vor

### ISSUE THREAD

**Issue by 0nlyDavid** [MicrosoftDocs/dynamics365smb-docs#465]
Sehr geehrtes Microsoft Support/ Docs Team,

ich bin auf den deutschen Dokumentation zum Thema "So bereiten Sie ein Konfigurationspaket vor" gestoßen. Generell fand ich die Seite sehr hilfreich und wollte lediglich anmerken, dass die Seite vermutlich einmal Korrektur gelesen werden sollte.

Beispiele hierfür wären:
"So bereiten Sie ein Konfigurationspaket vofr"
"...neues Unternehmen basierend auf einerm Konfigurationspaket..."
"...einen Fragebogen oder einen Satz von Fragebogen hinzufügen."
"...wenn ein Debitor weitere Anleitung dazu anfordert, wie eine entsprechende Einstellung wählen soll."
"..Dinge berücksichtigen, da diese darauf auswirken, ob Sie oder Ihr Kunde es importieren können."

Ich hoffe Sie können mit meinem Feedback etwas anfangen.

Mit freundlichen Grüßen,

David

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6c17285d-1100-c2f7-aa54-588c98bd6834
* Version Independent ID: 823c90f0-592f-7d40-6c97-1ac7b7adcf13
* Content: [So bereiten Sie ein Konfigurations-Paket vor - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/admin-how-to-prepare-a-configuration-package)
* Content Source: [business-central/admin-how-to-prepare-a-configuration-package.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-how-to-prepare-a-configuration-package.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! This has been reported to our translation team, and it will be fixed in the next translation update.
