### ISSUE TITLE
Odd characters in test

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-docs#466]
[Enter feedback here]
There seems to be a number of instances (I counted 9) of extraneous characters (XE) in the body of this article.  Just one example:

> Inventory valuation **XE** "Inventory Valuation" is the determination of the cost that is assigned to an inventory item, as expressed by the following equation.

Are these supposed to mean something?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4feeab6-025c-e633-16fa-cde01e4f75c4
* Version Independent ID: 2ceac390-b05b-e31e-cdc5-3baeb9b1033c
* Content: [Design Details - Inventory Valuation - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/design-details-inventory-valuation)
* Content Source: [business-central/design-details-inventory-valuation.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-inventory-valuation.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

Thanks for bringing this to our attention. The short answer is no, those characters had no meaning. They were mistakenly added by a script we ran a while ago, but we've removed them now. On a side note, we did a sweep in the repo and found the extra characters in another article as well, so thanks again for mentioning them.

**Comment by edupont04** [comment]
Now live.
