### ISSUE TITLE
What is the benefit of Queue Times

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#467]
Can you please elaborate on this function. Maybe some examples would also be helpful.

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 690eac98-0b6d-2a82-6cd4-7e0ab849ba34
* Version Independent ID: d6f47217-042a-ca86-87f0-dede1c9a3606
* Content: [How to Set Up Work Centres and Machine Centres - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/production-how-to-set-up-work-and-machine-centers)
* Content Source: [business-central/production-how-to-set-up-work-and-machine-centers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/production-how-to-set-up-work-and-machine-centers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

Good question, and thanks for asking. 

Queue times are similar to other non-production times, such as wait times and move times, in that they help provide a more accurate overall picture of production times. Use queue times to provide a buffer between the time that a component arrives at a machine or work center and when the operation actually starts. For example, a part is delivered to a machine center at 10:00 but it takes an hour to mount it on the machine so the operation does not start until 11.00. To account for that hour, the queue time would be one hour. 

The topic has been updated to be more clear, and it will be published in our weekly doc refresh.

**Comment by makdaddy8888** [comment]
Thanks Brett

Can you also update the other elements that need similar definitions. This process seems to be lacking in substance. An example is always beneficial too

Kind Regards
Ben

**Comment by brentholtorf** [comment]
Thanks Ben,

I've created a deliverable for 17.3 for the work to beef up this topic. Thanks again for the input.

Happy Holidays!
Brent
