### ISSUE TITLE
Account schedules calculates wrong

### ISSUE THREAD

**Issue by NicolaiBohnfeldt** [MicrosoftDocs/dynamics365smb-docs#470]
Looks like account schedules calculates wrong.

In Acc. Schedule Overview (490, List) i choose year and date filter 01-01-20..31-12-20
![image](https://user-images.githubusercontent.com/58515232/101494329-773f8b80-3967-11eb-81d8-0da01c5de4e7.png)

Current period is correct 01-01-20..31-12-20.
Period -1 is calculated 01-12-19..31-12-19 ?
Period -2 is calculated 01-11-19..30-11-19 ?

![image](https://user-images.githubusercontent.com/58515232/101494564-ce456080-3967-11eb-86bb-d1bb70c6056a.png)

![image](https://user-images.githubusercontent.com/58515232/101494817-182e4680-3968-11eb-9020-10e3332db0c4.png)

I think it should be:

Current period: 01-01-20..31-12-20
Period -1: 01-01-19..31-12-19
Period -2: 01-01-18..31-12-18

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 613d9e8a-856d-e913-ca98-c48e8376fb22
* Version Independent ID: a7b2e7f3-d8f4-8504-fa5b-fa9fa0afc4cc
* Content: [Oprette finansrapporter ved hjælp af kontoskemaer - Business Central](https://docs.microsoft.com/da-DK/dynamics365/business-central/bi-how-work-account-schedule)
* Content Source: [business-central/bi-how-work-account-schedule.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/bi-how-work-account-schedule.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Nicolai,
Thank you for your feedback. I'm not sure what is going on here, but since your question is not about the Help, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).

**Comment by NicolaiBohnfeldt** [comment]
It looks like a Business Central bug...
