### ISSUE TITLE
Outdated information related to adding a user or updating user information in Business Central 

### ISSUE THREAD

**Issue by justinandl** [MicrosoftDocs/dynamics365smb-docs#471]
Hello, 

It appears the instructions outlined in the "To add a user or update user information in Business Central" section of the following help page are outdated and need updating: https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-users-permissions 

![Example](https://user-images.githubusercontent.com/57770371/102122739-cc155300-3dfa-11eb-9a29-92f40683b0ee.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af56319-74d0-ce95-7f11-48a0b165ed6e
* Version Independent ID: d496d459-af33-c965-a21b-0e2f44d6a2e9
* Content: [Create Users According to Licenses - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-users-permissions)
* Content Source: [business-central/ui-how-users-permissions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-how-users-permissions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello @justinandl, 
Thank you for your feedback. Can you share with me what you find incorrect about the steps in that section?

If you are confused about the use of both "Microsoft 365" and "Office 365", then I quite understand - across Microsoft. we are rolling out this change gradually. For more information, see https://docs.microsoft.com/en-us/microsoft-365/?view=o365-worldwide

**Comment by justinandl** [comment]
Hello Eva,

Here is the feedback we received from our BC Cloud customer on the process:

This issues is that the instructions are not clear and don’t match the interface.

https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-users-permissions<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdynamics365%2Fbusiness-central%2Fui-how-users-permissions&data=04%7C01%7CJustin.Andl%40WesternComputer.com%7C199e466ea3254542ff6508d8a061d591%7Cd5c7cb1fb4df4224b710522adc1f049c%7C0%7C0%7C637435689388933409%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OCr3oCx4wlNTC857i%2BBHmXgHOMSfyQJJMUKGl%2B7ZAuc%3D&reserved=0>

[cid:image008.png@01D6D2BA.E3649C60]

What is the “related link”?  There are many links that come up when you search for “users”:

[cid:image009.png@01D6D2BA.E3649C60]

Next it says:  “Choose the ______ or”…?  What is missing?


[WC_Lighter Blue _transparent]<http://www.westerncomputer.com/>
Justin Andl / CSM
Justin.Andl@WesternComputer.com<mailto:Justin.Andl@WesternComputer.com>
Western Computer
Office: 805-581-5020 | Direct: 805-830-5805 | Mobile: 818-207-0220 | Skype: justinandl
www.WesternComputer.com<http://www.westerncomputer.com/>

[Twitter] <https://twitter.com/WesternComputer>  [Facebook]  <https://www.facebook.com/Western-Computer-236693736372775/>  [Google +]  <https://plus.google.com/100654748440944415515/posts>  [LinkedIn]  <https://www.linkedin.com/company/western-computer>  [Youtube]  <https://www.youtube.com/channel/UCc0f4SGZJDyrGg-A8wU4YIQ>

**Comment by edupont04** [comment]
Thanks for the clarification, Justin!
There is indeed a typo that will be removed, but step 1 can be used quite literally, since we recommend that the admin goes to the Users page rather than running the wizard straight from the search. The wizard works equally well in both cases, but it's safer to go to the Users page (step 1) and then choose the action to run the wizard.
![image](https://user-images.githubusercontent.com/12425349/102244821-17b02580-3efd-11eb-9a57-499a4c2e92ad.png)

**Comment by justinandl** [comment]
Eva, thanks for the quick response.  This makes sense.  Have a great day.

[WC_Lighter Blue _transparent]<http://www.westerncomputer.com/>
Justin Andl / CSM
Justin.Andl@WesternComputer.com<mailto:Justin.Andl@WesternComputer.com>
Western Computer
Office: 805-581-5020 | Direct: 805-830-5805 | Mobile: 818-207-0220 | Skype: justinandl
www.WesternComputer.com<http://www.westerncomputer.com/>

[Twitter] <https://twitter.com/WesternComputer>  [Facebook]  <https://www.facebook.com/Western-Computer-236693736372775/>  [Google +]  <https://plus.google.com/100654748440944415515/posts>  [LinkedIn]  <https://www.linkedin.com/company/western-computer>  [Youtube]  <https://www.youtube.com/channel/UCc0f4SGZJDyrGg-A8wU4YIQ>
