### ISSUE TITLE
Misc Typo

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-docs#472]
The following line contains a typo

Distributing reports in this manner means that refreshing data for reports will done individually by each user. This situation might impact Business Central performance.

should be

Distributing reports in this manner means that refreshing data for reports will **be** done individually by each user. This situation might impact Business Central performance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f562094f-cff2-2c71-c806-e548041718e2
* Version Independent ID: 4f1e5021-2ea3-ba4b-8da8-a999589b8962
* Content: [Building Reports in Power BI Desktop to Display Business Central Data - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-use-financials-data-source-powerbi)
* Content Source: [business-central/across-how-use-financials-data-source-powerbi.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-how-use-financials-data-source-powerbi.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! This has been fixed and the update will be published soon.
