### ISSUE TITLE
BC17.1 ON PREM to 365 Sales Version 1710 (9.1.0.26145) integration many questions

### ISSUE THREAD

**Issue by danaBC92** [MicrosoftDocs/dynamics365smb-docs#474]
After many combinations of settings and reading what we think is all the relevant documentation, we are almost giving up.
At least to me is not clear, but maybe someone has the answer. The CRM and BC are in different Azures, as implemented by different companies.

-Is it even possible to make this integration using NavUserPassword authentication? Do we have to make any extensions?
-Do you have to install the apps manually in the CRM from the BC kit?
-Do we have to configure anything special in the Administration console of BC for this to work?
-Could it work with a self signed certificate for the web client?
-Can you still use Office 365 authentication type in CDS page in Business Central or is it deprecated?
-How exactly to register the app in Azure of the CRM? Do you still choose WEB? And this may sound stupid but here it goes: do you choose CRM or Business Central as a platform?
-How should the redirect URL look like? Must it be this type "https://MyServer:443/BC160/OAuthLanding.htm" in both systems?
-Did anyone succeed the integration between these versions?

Thank you,

**Comment by danaBC92** [comment]
Updates: we did not give up and have answers:

-Is it even possible to make this integration using NavUserPassword authentication? Do we have to make any extensions?
**Yes, it worked without extensions.**
-Do you have to install the apps manually in the CRM from the BC kit?
**No, there was something installed because of previous tests, we uninstalled it and then ran Redeploy Integration solution. This installed the solutions in Sales again.**
-Do we have to configure anything special in the Administration console of BC for this to work?
**We checked Enable SSL but to this point, I am not sure it had an effect.**
-Could it work with a self signed certificate for the web client?
**Has to be a proper one**
-Can you still use Office 365 authentication type in CDS page in Business Central or is it deprecated?
**Yes, it worked with 365 authentication**
-How exactly to register the app in Azure of the CRM? Do you still choose WEB? And this may sound stupid but here it goes: do you choose CRM or Business Central as a platform?
**Has to be Web, only when assigning permissions you have to choose Business Central**
-How should the redirect URL look like? Must it be this type "https://MyServer:443/BC160/OAuthLanding.htm" in both systems?
**we used the url in our browser, that was starting with HTTPS, and at the end of it added OAuthLanding.htm**
-Did anyone succeed the integration between these versions?

**Comment by brentholtorf** [comment]
Thanks for your tenacity in these areas. There has been considerable churn in these areas during the last year. For example, authentication requirements have changed, CDS is now Dataverse, and the process for registering an app in Azure portal is different. 

We've been doing our best to keep up, and have recently published some updated content that I think aligns with your questions. Please have a look at [Connecting to On-Premises Versions of Business Central 2019 release wave 1 and Microsoft Dynamics NAV 2018](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-prepare-dynamics-365-for-sales-for-integration#connecting-to-on-premises-versions-of-business-central-2019-release-wave-1-and-microsoft-dynamics-nav-2018).
