### ISSUE TITLE
Invalid link to PartnerSource with Client ID/Secret

### ISSUE THREAD

**Issue by ichladil** [MicrosoftDocs/dynamics365smb-docs#476]
Hello, the link to the PartnerSource with Client ID/Secret (https://mbs.microsoft.com/partnersource/global/deployment/downloads/tax-regulatory-updates/365dynamicsbctaxdigitsupinfo) on this page https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedkingdom/making-tax-digital-submit-vat-return seems to be invalid. Could you please point it to some existing document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35bb67a1-ea3e-ae63-2b5d-c7f6e099459e
* Version Independent ID: a6a3650f-2c0a-4d1e-b1a6-8472e0151df9
* Content: [Making Tax Digital - Submitting VAT Returns - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedkingdom/making-tax-digital-submit-vat-return)
* Content Source: [business-central/LocalFunctionality/UnitedKingdom/making-tax-digital-submit-vat-return.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/UnitedKingdom/making-tax-digital-submit-vat-return.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! We're working on making the download available again, but I can't tell you when that will happen, unfortunately. I'll update this Issue when the download is available again.

**Comment by edupont04** [comment]
Hello @ichladil,
The download has now been added here:
[https://docs.microsoft.com/dynamics/s-e/365business/365dynamicsbctaxdigitsupinfo_173](https://docs.microsoft.com/dynamics/s-e/365business/365dynamicsbctaxdigitsupinfo_173)

I'll get the link updated in our docs.

**Comment by edupont04** [comment]
Closing as fixed, albeit temporarily. The article will be updated again once the information has been moved to a permanent location.
