### ISSUE TITLE
Job Queue entry statusses explained?

### ISSUE THREAD

**Issue by wolterOnEntocare** [MicrosoftDocs/dynamics365smb-docs#478]
There is a list of statusses where a bit more explanation would be worthwile:

    On Hold
    Ready
    In Process
    Error
    Finished
E,g: what's the difference between a job that's 'Ready' and one that's 'Finished'?
What does 'On-Hold' mean, is the job waiting for the pre-programmed time to arrive and then the job will start...?
(I know it's not like that, but I had to find it out the hard way).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fcb95cd-fd17-03c1-d52b-368c37671df9
* Version Independent ID: 2d7b250b-a699-f4bd-14f6-4496ec33cd42
* Content: [Schedule jobs to run automatically - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-job-queues-schedule-tasks)
* Content Source: [business-central/admin-job-queues-schedule-tasks.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-job-queues-schedule-tasks.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! This will be fixed in the next doc update.

**Comment by edupont04** [comment]
Now live.
