### ISSUE TITLE
Broken Link in "Note"

### ISSUE THREAD

**Issue by sauerkreut** [MicrosoftDocs/dynamics365smb-docs#479]
Good day,
there is a broken link in the Note-section of the document. "Feature Management" is pointing to "https://businesscentral.dynamics.com/?page=xzy" where it should be "https://businesscentral.dynamics.com/?page=2610"

Kind regards
Walter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8cb2416-68da-4085-1996-81284267ae01
* Version Independent ID: f242d19a-bbc5-685a-4a26-01b3713fa2ec
* Content: [Use Item Cross-References - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/inventory-how-use-item-cross-refs)
* Content Source: [business-central/inventory-how-use-item-cross-refs.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-how-use-item-cross-refs.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! Good catch - this will be fixed in the next doc update.

**Comment by edupont04** [comment]
Now live.
