### ISSUE TITLE
How to automatically set-applies-to-ID?

### ISSUE THREAD

**Issue by dennister16** [MicrosoftDocs/dynamics365smb-docs#48]
Using the button 'Applicate', it puts a Applies-to ID to some ledger entries. How exactly does this function determine, and in which order, which lines to give an ID or not. 
And why do the lines need to have the same Dimension/Business Unit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7234e6b-ccc5-f83c-3fee-b2bc91ff77ba
* Version Independent ID: c4efaa94-73c2-0b41-0fe9-47aa8c896b95
* Content: [How to Apply General Ledger Entries - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/france/how-to-apply-general-ledger-entries)
* Content Source: [business-central/LocalFunctionality/France/how-to-apply-general-ledger-entries.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/France/how-to-apply-general-ledger-entries.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Hi dennister16, 

The **Applies-to ID** field is only filled in when you choose the **Set Applies to ID** action. If the field is filled in "by itself", then there may be an error in your solution, which you must contact your Microsoft partner about. 

The "Reconcile Vendor Payments Manually" topic in the global help explains the **Set Applies-to ID** field better, so I have added a link to it from the French topic. The change will be available in approximately one week.

Regards
Soren, Business Central writer
