### ISSUE TITLE
Falsche Übersetzung

### ISSUE THREAD

**Issue by AJasp** [MicrosoftDocs/dynamics365smb-docs#480]
Hallo,
die Übersetzung ist meiner Ansicht nach nicht ganz passend. Ges geht dabei um Lieferbedingungen (nicht Liefermethoden), weiter unten heißt es plötzlich Versandcode. Bitte prüfen und überarbeiten

[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e7e4fe92-e8b5-6363-229c-4a4804caa919
* Version Independent ID: 21d9cfce-d3f5-18a8-5a8d-6f1cfe56ac31
* Content: [Vorgehensweise: Versandagentenmethoden einrichten in - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/sales-how-set-up-shipment-methods)
* Content Source: [business-central/sales-how-set-up-shipment-methods.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/sales-how-set-up-shipment-methods.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hallo,
Danke für Ihre Feedback! Wir haben unsere Übersetzung Team notifiziert.

**Comment by jowilco** [comment]
@AJasp Vielen Dank für Ihr Feedback. Wir ermitteln die Ursache für dieses Problem.

**Comment by jowilco** [comment]
@AJasp Vielen Dank für Ihr Feedback. Wir haben die Übersetzungen aktualisiert, und die aktualisierten Übersetzungen sind live. Dieses Problem wird geschlossen.
