### ISSUE TITLE
Colored Locations no longer in Cronus

### ISSUE THREAD

**Issue by Bob-Dzimbowski** [MicrosoftDocs/dynamics365smb-docs#481]
[This page and others are no longer valid because the locations that come with Cronus US or Canada do not include the ones specified. The new ones that come with Cronus are: East, Main, Out Log, Own Log, West. Please bring back the old locations and setups.]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a09ecb55-c99f-952b-c582-2745de3b0bbb
* Version Independent ID: 531d8ca0-daeb-c0cc-300b-29004e5a4850
* Content: [Design Details - Warehouse Setup - Business Central](https://docs.microsoft.com/en-ca/dynamics365/business-central/design-details-warehouse-setup)
* Content Source: [business-central/design-details-warehouse-setup.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-warehouse-setup.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! Yes, we didn't get the docs updated when we refreshed the demo data in Cronus. This will be fixed in one of the next doc updates.

**Comment by edupont04** [comment]
Hi Bob,

Unfortunately, we cannot use the classic names in our demo data anymore. You can use any names you like, of course, but the names in the Cronus demonstration company will not be changed back to the classic names.

**Comment by Bob-Dzimbowski** [comment]
It's not about the names. The location setups with related data is no longer there.

Thanks,

Bob Dzimbowski
Manufacturing Consultant, VOX ISM<http://www.voxism.com/>
Phone: 416-457-6884<mailto:416-457-> | Email: bdzimbowski@voxism.com<mailto:bzimbowski@voxism.com> | Fax: 416.488-6309<file:///C:/Users/VoxUser/Downloads/416.488-6309>
www.voxism.com<http://www.voxism.com/> | Sign up for our newsletter<http://visitor.r20.constantcontact.com/d.jsp?llr=849qb9dab&p=oi&m=1103606868987&sit=ey6xwojfb&f=d065e3e0-9e2c-4753-aa29-1b508a9a0bbb>
[cid:0e8dee6a-77de-46ae-ace7-dfd94548f156]<http://www.linkedin.com/company/vox-ism/> [cid:adc3b8ab-9dff-4b37-a610-c50ef4008b69] <http://www.youtube.com/channel/UC5ra-iSkqSSmx9MYYYAtt7g>  [cid:552efe00-b99c-4bfd-9dd2-7532d37860f5] <http://twitter.com/vox_ism>  [cid:b9286d01-7db8-42c9-97dc-2ec024fcc009] <http://www.facebook.com/VoxISMCanada/>  [cid:db88fa6f-8c3b-45a7-be0c-4c748a2278c4] <http://www.instagram.com/voxismcanada/?hl=en>

[cid:a5a16e0a-892b-41dd-a060-ae2dccc4dfa7]<https://voxism.com/events/>

________________________________

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. I suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
