### ISSUE TITLE
Misc typo

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-docs#482]
Job queues in Business Central enables users to schedule and run specific reports and codeunits. 

should be 

Job queues in Business Central **enable** users to schedule and run specific reports and codeunits. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fcb95cd-fd17-03c1-d52b-368c37671df9
* Version Independent ID: 2d7b250b-a699-f4bd-14f6-4496ec33cd42
* Content: [Schedule jobs to run automatically - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-job-queues-schedule-tasks)
* Content Source: [business-central/admin-job-queues-schedule-tasks.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-job-queues-schedule-tasks.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Yep, you're right, so thank you for your feedback! This will be fixed in the next doc update.

**Comment by edupont04** [comment]
Now live.
