### ISSUE TITLE
Import multiple SEPA CAMT statements grouped in one file

### ISSUE THREAD

**Issue by nicolassaleron** [MicrosoftDocs/dynamics365smb-docs#486]
Hello,

It is quite usual for a company to have several bank accounts in the same establishment.

SEPA CAMT allows banks to group in one file, the statements of several bank accounts.
However Business Central rejects a file if there is several statements.
In the meantime, some banks do not provide the ability to download a separate file per bank account.

Is there a build-in solution or a workaround you could add in the documentation for this issue?
(the current solution is either splittig the SEPA CAMT file manually or developing a customization).

Thank you in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67402087-b9d4-e473-9dc3-319514ea7abf
* Version Independent ID: db9a1a9e-e419-2baf-cc2d-cf337487e876
* Content: [How to Import and Reconcile Bank Statements - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/netherlands/how-to-import-and-reconcile-bank-statements)
* Content Source: [business-central/LocalFunctionality/Netherlands/how-to-import-and-reconcile-bank-statements.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Netherlands/how-to-import-and-reconcile-bank-statements.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by nicolassaleron** [comment]
sorry, I am closing the issue because it is not related to netherlands localization.

**Comment by edupont04** [comment]
Hello @nicolassaleron 
Thank you for your feedback. We can't recommend third party solutions here unfortunately. I suggest that you submit a feature request to add support for multiple statements in the same file here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
