### ISSUE TITLE
further information of quality measures

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#487]
How can the quality measure be used. Are there some working examples to help share this element?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e14cbc-9c22-61d8-fd69-067b46947510
* Version Independent ID: af380751-d3b2-9b9e-73d2-a16256d4a336
* Content: [How to Create Routings - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/production-how-to-create-routings)
* Content Source: [business-central/production-how-to-create-routings.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/production-how-to-create-routings.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Ben,

We don't really have good guidance for how to apply quality control to your processes, be that routing in production or other processes. It depends in part on culture and local or industry-specific best practices, so you might want to check in with the community here for what people are doing: [https://community.dynamics.com/business](https://community.dynamics.com/business)

Sorry that I can't be more helpful than that!
