### ISSUE TITLE
Descriptions incorrect on Advanced Connection Settings

### ISSUE THREAD

**Issue by JennReinhardt** [MicrosoftDocs/dynamics365smb-docs#488]
The setup page doesn't match the options described in the documentation...the docs are incorrect.  In the descriptions there are 3 OData Web Service fields, but on the actual page it only show 2 and in the documentation we say Enable CDS Connection to Enable the Connection to Dataverse, but the window actually says “Enable Dynamics 365 Sales Connection”
 
In the Connection Settings in the Setup Guide section the following needs to be changed:
1. Business Central OData Web Service URL  description should not be there as it's not a field on the page.
2. Enable CDS Connection and description are incorrect, it should say Enable Dynamics 365 Sales Connection with a description of Enable the connection to Dynamics 365 Sales.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2957b832-9aee-e050-b034-7f3badb2e27c
* Version Independent ID: a93b51b9-9a52-c8a2-2197-38c02f2e327f
* Content: [Integrating with Dynamics 365 Sales - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-prepare-dynamics-365-for-sales-for-integration)
* Content Source: [business-central/admin-prepare-dynamics-365-for-sales-for-integration.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-prepare-dynamics-365-for-sales-for-integration.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by brentholtorf** [comment]
Thanks for pointing out these changes. The topic is updated and will be republished shortly.
