### ISSUE TITLE
Service Credit Memos does not relate to anything

### ISSUE THREAD

**Issue by Deeptnt** [MicrosoftDocs/dynamics365smb-docs#489]
[Enter feedback here]
When following instruction "To create a service credit memo" there is no link to the task.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8844b53-7bd8-67ab-a099-f608f2ed92f2
* Version Independent ID: 992df4d1-648d-7899-1aa5-2c5429f14241
* Content: [Create Invoices or Credit Memos for Services - Business Central](https://docs.microsoft.com/en-ca/dynamics365/business-central/service-how-create-invoices)
* Content Source: [business-central/service-how-create-invoices.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/service-how-create-invoices.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello @Deeptnt,
Thank you for your feedback. Please forgive me if I haven't understood your feedback, but our procedures very rarely include links to pages within the product. Instead, we write a step such as "Choose the <Lightbulb> icon, enter **Service Credit Memos**, and then choose the related link."

**Comment by Deeptnt** [comment]
Hello Eva,
What I ment was that if you search for Service Credit Memos there is no task linked to this search.
Regards,

Thomas Tessier
Conseiller senior
thomas@tntservicesinformatiques.com<mailto:thomas@tntservicesinformatiques.com>
418 682.3190
[TNT_LOGO_80X200_SIGNATURE_80-100]
1010, avenue Marguerite-Bourgeoys
Québec (Québec) G1S 3X9
https://www.tntservicesinformatiques.com<https://www.tntservicesinformatiques.com/>

De : Eva Dupont <notifications@github.com>
Envoyé : 26 janvier 2021 08:29
À : MicrosoftDocs/dynamics365smb-docs <dynamics365smb-docs@noreply.github.com>
Cc : Thomas Tessier <thomas@tntsi.ca>; Mention <mention@noreply.github.com>
Objet : Re: [MicrosoftDocs/dynamics365smb-docs] Service Credit Memos does not relate to anything (#489)


Hello @Deeptnt<https://github.com/Deeptnt>,
Thank you for your feedback. Please forgive me if I haven't understood your feedback, but our procedures very rarely include links to pages within the product. Instead, we write a step such as "Choose the icon, enter Service Credit Memos, and then choose the related link."

**Comment by edupont04** [comment]
Bonjour, M. Tessier,

Thank you for the clarification! Service credit memos are part of the Service Management functionality that requires the experience to be set to *Premium* in the **Company Information** page for your Business Central company. For more information, see [Change Which Features are Displayed](https://docs.microsoft.com/dynamics365/business-central/ui-experiences).

I hope this answers your questions. Otherwise, do let us know!

**Comment by Deeptnt** [comment]
Bonjour Eva,
Thank you for your quick reply. :)
I will try and get the premium.
Best regards,

Thomas Tessier
Conseiller senior
thomas@tntservicesinformatiques.com<mailto:thomas@tntservicesinformatiques.com>
418 682.3190
[cid:image004.jpg@01D6F3FD.1B78DEF0]
1010, avenue Marguerite-Bourgeoys
Québec (Québec) G1S 3X9
https://www.tntservicesinformatiques.com<https://www.tntservicesinformatiques.com/>
[cid:image002.png@01D6F3FD.1B742400]<https://www.linkedin.com/company/tnt-services-informatiques/>[cid:image003.png@01D6F3FD.1B742400]<https://www.facebook.com/TNTServicesinformatiquesinc/>
