### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by gonzaloriosley** [MicrosoftDocs/dynamics365smb-docs#49]
The "Design Details: Inbound Warehouse Flow." link at the beginning of the article, actually refers to the "Design Details: Outbound Warehouse Flow." page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a344b759-511a-d9f9-9b63-69a2031b9ccd
* Version Independent ID: fb04a7a3-6759-fa31-3d46-33af0f32d2e0
* Content: [Design Details - Warehouse Overview - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-warehouse-overview#feedback)
* Content Source: [business-central/design-details-warehouse-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-warehouse-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback - This has been fixed and will be available in approximately one week.
