### ISSUE TITLE
Field Monitoring Setup

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#491]
can you please add some context on how to use Field Monitoring. I could not see anything related to this in the help documentation.
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f842e9d-aa0b-1b1c-c6be-dfac6730e393
* Version Independent ID: 5ba6fbd0-487c-c742-9acc-8b120c9337ff
* Content: [Using General Functionality Across Business Areas - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/ui-across-business-areas)
* Content Source: [business-central/ui-across-business-areas.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-across-business-areas.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

You can read about monitoring sensitive fields here: https://docs.microsoft.com/dynamics365/business-central/across-log-changes#monitoring-sensitive-fields

BR 
Eva
