### ISSUE TITLE
Australian Specific law for Low Value Fixed Assets

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#492]
Hello Team

Can you please share how we can setup the attached Australian law requirement for LowValue FA? [https://www.ato.gov.au/Business/Depreciation-and-capital-expenses-and-allowances/General-depreciation-rules---capital-allowances/Low-value-assets-(pool)/](url)
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4407032-3ab2-06cc-d994-064a0d982d87
* Version Independent ID: 76cf6594-a1c6-c456-5c1a-26b5791663a5
* Content: [Depreciation Methods - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/fa-depreciation-methods)
* Content Source: [business-central/fa-depreciation-methods.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/fa-depreciation-methods.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
