### ISSUE TITLE
Contract = Billable, Schedule = Budget

### ISSUE THREAD

**Issue by OneThreeOne** [MicrosoftDocs/dynamics365smb-docs#493]
This was really useful, thanks. But worth pointing out that, in the UK at least Contract = Billable, and Schedule = Budget.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 850880b4-15c7-9760-17c5-b723b9b2b17f
* Version Independent ID: b52bcf7c-1126-b2ab-c8bc-29c29f851e27
* Content: [Walkthrough - Managing Projects with Jobs - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/walkthrough-managing-projects-with-jobs)
* Content Source: [business-central/walkthrough-managing-projects-with-jobs.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/walkthrough-managing-projects-with-jobs.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! You're right that the walkthrough does not reflect the current version of the demonstration company in Business Central. This will be fixed in a coming doc update.

**Comment by edupont04** [comment]
Closing as fixed.
