### ISSUE TITLE
Create an App Registration for Business Central in Azure Portal

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [MicrosoftDocs/dynamics365smb-docs#494]
Hi 

Does this section instruction apply to the Business Central App Registration or does it mean that we need to create a new app registration for the Email Application?
We are trying to activate this feature for an existing OnPrem customer which has been upgraded from version 16 to 17.3. The customer already has Azure AD and BC OnPrem working with Excel and Outlook integration.
We are trying to activate the sending of emails by running the command "Email Application AAD Registration" from BC web client.
We use the BC Application registration values for following fields (client) ID, Redirect URI (optional) and Client secret. We get the following error.
The email was not sent because of the following error: "Could not get access token. Please, try to log out and log in again."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0171dfbc-61f2-e62e-f4a3-bb641b15c3e2
* Version Independent ID: 51deab1e-0243-3178-7640-01bb91591fca
* Content: [Set up email in Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-how-setup-email)
* Content Source: [business-central/admin-how-setup-email.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-how-setup-email.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by brentholtorf** [comment]
Hi,

It looks like you're doing everything correctly. The fact that you can't get the access token though, suggests that you might be using an incorrect client ID or client secret. Have you tried using the Verify Registration button on the Email Application AAD Registration page to verify your app registration? 

It could also be that your app registration is not configured correctly. For example, you might have chosen an incorrect option in the Supported account types field. We've seen that before. If that's the case, you might consider creating a new app registration. If you do, follow the steps in this topic, [Register an Application in Azure AD](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/register-app-azure#register-an-application-in-azure-active-directory).
