### ISSUE TITLE
Clarification question

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-docs#496]
Some list pages, like Items, also include a Power BI part.

I believe only Items, Customers and Vendors include Power BI parts out of the box. If so, why not mention all 3?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e852cab8-70e8-c316-1b60-1fa37eb87bd0
* Version Independent ID: 50aa54e6-d2bc-2939-bd6a-1877c8d1ab9b
* Content: [Working with Power BI Reports in Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-working-with-powerbi)
* Content Source: [business-central/across-working-with-powerbi.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-working-with-powerbi.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! We've chosen to just name one list page here because the precise number can vary, depending on the version of the base product, customizations, and any apps that you might have added. So we're going to leave the sentence as-is.

**Comment by j2associates** [comment]
Fair enough. I would still argue for Vendor, Customer and Item, but I
appreciate that you took the time to respond and explain.

Have a great day!
