### ISSUE TITLE
Dampener Period

### ISSUE THREAD

**Issue by Rain5** [MicrosoftDocs/dynamics365smb-docs#5]
I disagree with your advice re: Dampener Period.  My understanding of Dampener Period is to reduce the noise that the Planning System can create when scheduled receipts are expected prior to their need dates.  I would recommend using it the opposite of your suggestion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec04e8cb-fd08-218e-a1d1-17e386e65b49
* Version Independent ID: 6beba65c-bab6-eb7e-91af-83e88f3d0b66
* Content: [Setup Best Practices - Planning Parameters - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/setup-best-practices-planning-parameters)
* Content Source: [business-central/setup-best-practices-planning-parameters.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/setup-best-practices-planning-parameters.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thanks - Your definition is correct in terms of minimizing noise, but this setup best-practice advice is also correct in terms of providing higher customer service when a supplier supports it. I have explained this better. (Available after next update.)
