### ISSUE TITLE
post after closure

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#500]
Hello

There is an option to post after a period is closed. 

Can this page reflect that this is an option.

Can you also share how to the letter Z is added.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20f591a9-39c4-fb94-6d87-2a1d0e555f26
* Version Independent ID: ea4aa166-e4bc-441f-7376-8833a098e51d
* Content: [Review and Post the Year-End Closing Entry - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/year-how-post-year-end-close-entry)
* Content Source: [business-central/year-how-post-year-end-close-entry.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/year-how-post-year-end-close-entry.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hello Ben,

Thank you for your feedback! This will be made clearer in the next doc update. Except, I don't understand what you mean with the letter Z. Can you please clarify?

**Comment by edupont04** [comment]
Now live.
