### ISSUE TITLE
show me

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#501]
It would be great if you could share how to do this via a video.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 562ba9ca-f395-bbeb-0775-5a85696e0935
* Version Independent ID: 58c23bed-523d-0432-f76e-2930232816f6
* Content: [Create and Modify Custom Layouts for Reports and Documents - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-create-custom-report-layout)
* Content Source: [business-central/ui-how-create-custom-report-layout.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-how-create-custom-report-layout.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Great suggestion, thanks! I've added this title to our video backlog.
