### ISSUE TITLE
Incorrect Column Values

### ISSUE THREAD

**Issue by javisoft** [MicrosoftDocs/dynamics365smb-docs#502]
Under the section [To set up account schedule lines], on step 2, the table shows the values "Net Change" and "Balance at Date" under the column "Totaling Type", but those values correspond to the column "Row Type" instead? The same issue with the column "Row Type" and "Amount Type"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9e642b3-7dc3-3bad-3d62-0ff19d87356c
* Version Independent ID: 3a597fe7-6b47-828e-8c86-4a1ad5846f92
* Content: [Walkthrough - Making Cash Flow Forecasts by Using Account Schedules - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/walkthrough-making-cash-flow-forecasts-by-using-account-schedules)
* Content Source: [business-central/walkthrough-making-cash-flow-forecasts-by-using-account-schedules.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/walkthrough-making-cash-flow-forecasts-by-using-account-schedules.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! You're right that the rows are misaligned with the column headers so that there are no values for the Description column header, which then makes everything move one column to the left. This will be fixed in the next doc update.

**Comment by edupont04** [comment]
Now fixed.
