### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-docs#503]
The link in the following line is broken.

see Analyzing Job Queue Lifecycle Trace Telemetry in the Business Central Developer and IT Pro help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fcb95cd-fd17-03c1-d52b-368c37671df9
* Version Independent ID: 2d7b250b-a699-f4bd-14f6-4496ec33cd42
* Content: [Schedule jobs to run automatically - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/admin-job-queues-schedule-tasks)
* Content Source: [business-central/admin-job-queues-schedule-tasks.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-job-queues-schedule-tasks.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update. Here's the real link: https://docs.microsoft.com/en-US/dynamics365/business-central/dev-itpro/administration/telemetry-job-queue-lifecycle-trace

**Comment by j2associates** [comment]
Thanks for taking the time to send me the true link!

I'm not sure where to suggest this, but I have read a lot of the Job Queue
and Job Queue Entry topics. It would really be great if there were some
Telemetry links included there just to make people aware.. I knew they had
to be somewhere, but I didn't know that Telemetry was what I should be
looking for until just recently.

Have a great day!

**Comment by edupont04** [comment]
Thanks for the feedback! Yes, the job queue can be a very bewildering place. I can't promise that we'll add links to telemetry, but I've put it on our backlog.
