### ISSUE TITLE
update links with 2021

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#504]
missing updates to the produce please add the 2021 wave 1 and 2
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3243448c-df56-cb7d-2e08-9084ca24a330
* Version Independent ID: 9e1799ac-14f6-4c70-6032-a9f41cc1d749
* Content: [What's New in Business Central - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/product-news)
* Content Source: [business-central/product-news.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/product-news.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

The link to the 2021 release wave 1 release plans will be added when the major update is generally available in April '21.
