### ISSUE TITLE
Terminology changes in BC17.4

### ISSUE THREAD

**Issue by GreatScott000** [MicrosoftDocs/dynamics365smb-docs#506]
Under To Print the VAT audit report, point 1 refers to "VAT Statements", in at least 17.4 this is "Tax Statements" and the "Note" just before point 5 refers to "check box", the controls for Boolean value are not check boxes anymore (haven't been for a quite a while). 

Please review possible changes to this page.  The change from VAT to Tax has been done in a number of places.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d4d4c97-e76c-239f-5365-0f2155b38c40
* Version Independent ID: c883067b-ffee-3c29-cadb-1ab06396fb9d
* Content: [Print VAT Audit Reports - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedkingdom/how-to-print-vat-audit-reports)
* Content Source: [business-central/LocalFunctionality/UnitedKingdom/how-to-print-vat-audit-reports.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/UnitedKingdom/how-to-print-vat-audit-reports.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! I suspect this is actually a translation issue in the product, so I'm circling back with the translation team but wanted to give you early (OK, earl_ier_)  feedback. The article is about VAT statements and VAT audits, not tax statements.

**Comment by GreatScott000** [comment]
Sorry for the delay.  I am unable to reproduce the issue now too.  I will open an issue if I figure out what was happening.

**Comment by edupont04** [comment]
Thanks for the update! Closing the Issue.
