### ISSUE TITLE
Marketplace Extensions with Docker Environments

### ISSUE THREAD

**Issue by morcadium** [MicrosoftDocs/dynamics365smb-docs#507]
When attempting to install extensions from the marketplace in a Docker container running the US release of 17.4, the following error occurs:
`Installation of extensions from the marketplace is not supported for your system configuration. For more information, see https://docs.microsoft.com/en-us/dynamics365/business-central/ui-extensions`

There doesn't appear to be any information in the related MS Document explaining why this operation is forbidden.

Please update this article with Marketplace extension limitations or instructions as they relate to Docker Containers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f6ce33-2528-c87d-d097-257e598ec407
* Version Independent ID: d606ddd8-17c5-0864-cc19-1489b3dbf901
* Content: [Installing Extensions to Customize Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-extensions)
* Content Source: [business-central/ui-extensions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-extensions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! Apps in the marketplace apply to Business Central online only and cannot be installed in Business Central on-premises deployments, including Docker containers. This will be clarified in the next doc update.

**Comment by morcadium** [comment]
Thanks for the information. Is there a reason for this limitation?

I encountered this problem while attempting to enhance an App Source offering.

To make the marketplace more robust, I would imagine that MS would want developers to code unimpeded in Docker with the appropriate dependencies.  This is specially important when SaaS has Unit Testing does not grant developers the same test tool libraries as are available in Docker via the BcContainerHelper.

Sincerely,
Kieran Sweeney
________________________________

**Comment by edupont04** [comment]
Hi Kieran,

Thanks for the follow-up! I can't answer questions about product strategy here, but I've been told that there are practical reasons for not allowing AppSource apps on-premises. I suggest that you join our community in Yammer if you haven't already, and you might want to submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)

**Comment by edupont04** [comment]
Someone else has already posted a feature request that you can vote up here: https://experience.dynamics.com/ideas/idea/?ideaid=42616aad-587b-eb11-8fed-0003ff4582f9

**Comment by edupont04** [comment]
Now live.
