### ISSUE TITLE
Strict Expiration posting

### ISSUE THREAD

**Issue by consultancyCP** [MicrosoftDocs/dynamics365smb-docs#508]
This is the only page I could find which any mentions "strict expiration posting".

The way this is described suggests that strict expiration posting and picking according to FEFO are not the same thing, and complement each other.
Furthermore, is sounds as though strict expiration posting only ensures that items which not expired are included in the pick.

In my experience and recent testing, **this is not the case**. Strict Expiration posting works in a similar way as picking according to FEFO, in that warehouse activity lines are pre-populated with tracking information and items expiring first are prioritised.

The tooltip in application also suggests a different behaviour to what actually happens.

![image](https://user-images.githubusercontent.com/43605541/109489994-870acf80-7a7f-11eb-8f30-bcd57f6ab035.png)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84775a5d-0d06-4259-c88f-abdacfdcccf7
* Version Independent ID: d98f89e3-c377-a95b-f918-490d4a66aa51
* Content: [How to Enable Picking by FEFO - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/warehouse-picking-by-fefo)
* Content Source: [business-central/warehouse-picking-by-fefo.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/warehouse-picking-by-fefo.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

Thanks for the input. You're right about how it works. If you use strict expiration posting, the lines are sorted according to the FEFO principle, regardless of whether you've enabled FEFO for the location. We've updated the topic to reflect that.
