### ISSUE TITLE
how to run the model

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#509]
Run the model, and publish it as a web service.

How does one do this?

Can a video be shared?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26e1b798-b9ed-005c-cdb3-5510548de0d9
* Version Independent ID: 939ca6a9-c120-b4e9-8aef-76e17bf3ed95
* Content: [Using the Sales and Inventory Forecast Extension to Manage Inventory - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-extensions-sales-forecast?ranMID=24542&ranEAID=je6NUbpObpQ&ranSiteID=je6NUbpObpQ-c6wdT_lTH0Jw0St1fXxnyg&epi=je6NUbpObpQ-c6wdT_lTH0Jw0St1fXxnyg&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=%28ir__f0gmn1kds9kfqgf0kk0sohzwxn2xpsdvqh9dysx200%29%287593%29%281243925%29%28je6NUbpObpQ-c6wdT_lTH0Jw0St1fXxnyg%29%28%29&irclickid=_f0gmn1kds9kfqgf0kk0sohzwxn2xpsdvqh9dysx200)
* Content Source: [business-central/ui-extensions-sales-forecast.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-extensions-sales-forecast.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

When you have the Forecasting Model for Microsoft Dynamics 365 Business Central experiment open in Microsoft Azure Machine Learning Studio, you'll find a Run button and a Deploy Web Service button at the bottom of the workspace.

**Comment by makdaddy8888** [comment]
Hello Brent

This is a very valuable element that business central can offer. Do you think someone at MS could elaborate more on this element?
We all understand the basis of how an experiment works but a season ML specialist might be willing and able to add more on this? What do you think?
