### ISSUE TITLE
What about shortcutkeys for actions like F9 for posting?

### ISSUE THREAD

**Issue by PaulVanGampelaere** [MicrosoftDocs/dynamics365smb-docs#51]
I still find the ShortCutKey property but can't access it from the web client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 839e7a63-b074-a7b7-0ee5-b9cea4313de0
* Version Independent ID: 545efe23-da43-c929-3edc-c63f52849cfd
* Content: [Keyboard Shortcuts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/keyboard-shortcuts-cheatsheet)
* Content Source: [business-central/keyboard-shortcuts-cheatsheet.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/keyboard-shortcuts-cheatsheet.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hi Paul, currently the ShortcutKey property only applies to the Windows client, not the Web client. Support for this in the Web client is targeted for a future release, however. Thanks for the feedback.

**Comment by PaulVanGampelaere** [comment]
Hi,
Good news!
The shortcut keys are available in the fall release of Business Central. (BC15)
This version was released in the beginning of october.

Met vriendelijke groeten / Meilleures salutations / Best regards
Paul Van Gampelaere
Business Solution Architect

Van: SylvainLKK <notifications@github.com>
Verzonden: donderdag 17 oktober 2019 10:50
Aan: MicrosoftDocs/dynamics365smb-docs <dynamics365smb-docs@noreply.github.com>
CC: Paul Van Gampelaere <Paul.VanGampelaere@cegeka.com>; Author <author@noreply.github.com>
Onderwerp: Re: [MicrosoftDocs/dynamics365smb-docs] What about shortcutkeys for actions like F9 for posting? (#51)


Good Morning jswymer,
It almost one year from the last update about adding shortcut as F9 for posting; do you have any news?
