### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mbutlin** [MicrosoftDocs/dynamics365smb-docs#511]
I think the link to the French tax authority is broken again unfortunately.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2fb5c9d0-0b88-dca2-31cb-d9bafe77ea1a
* Version Independent ID: b8851ab3-1fbf-08b7-ce7f-0137310737c4
* Content: [Certifications - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/compliance/compliance-certifications)
* Content Source: [business-central/compliance/compliance-certifications.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/compliance/compliance-certifications.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by mbutlin** [comment]
I forgot to say I found the documentation if its of any use after a bit of messing about:
https://jaime.jlogiciels.fr/ouvrir_certificat.php?id_elmt=323&fichier=CERTIF-07-181-A2-MICROSOFT%20France.pdf&HR=08:15:03

I used this site:
https://certificates.infocert.org/#

then did a product search for Microsoft Dynamics 365 Business Central and then looked for NF203 certificate.  I am not French or an Accountant but our French company and the head of finance their has confirmed the PDF in the link above was what the French auditors were after.

**Comment by edupont04** [comment]
Now live.
