### ISSUE TITLE
F4 Shortcut documentation is missing

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-docs#512]
According to the keyboard shortcut list, F4 is NOT supported.

However, when hitting F4 (in Microsoft New Edge) e.g. on the customer card, the system open a apparently random page.
What we think is that the F4 takes the user to the assistedit / drilldown of the last flowfield that is shown on the page.

However, this is unwanted behavior. Users coming from the RTC client, tend to use F4 a lot on drilldown fields / field with a dropdown, but it does show a totally irrelevant page, which is confusing.

Can you please **document** the logic behind the F4 key?

For us, it seemed like a bug instead, but it won't be solved according to https://partner.microsoft.com/en-us/dashboard/collaborate/engagements/1173/feedback/wits/Bugs/389423

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96fd662-e905-9df6-60f5-c709f92077c1
* Version Independent ID: 172fd943-0f5c-6d4c-b764-ced7fd077a96
* Content: [Keyboard Shortcuts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/keyboard-shortcuts)
* Content Source: [business-central/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/keyboard-shortcuts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by brentholtorf** [comment]
Hello Frédérik,

Thanks for reporting this. I think you've found a issue that's related to some legacy code from the Windows client, so I've created a bug for the development team to investigate. The documentation is correct in that the F4 key is not used by Business Central online, so it should not open pages or dialog boxes. In browsers, the F4 key should highlight the URL in the Address bar. 

To display the options in a drop-down field in Business Central, use the Alt+Down arrow keyboard shortcut combination.
