### ISSUE TITLE
Business Central 2.60 and 3.00

### ISSUE THREAD

**Issue by RasmusTidselbak** [MicrosoftDocs/dynamics365smb-docs#514]
It seems that someone has been a having fun with Search and Replace.

I assume that you are talking about Navision 2.60 and so forth instead of BC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 279b7a2d-e936-86a9-3d9a-5bc83133d9fd
* Version Independent ID: 2c59b045-6884-b9f6-809b-a7f6f5e300aa
* Content: [Design Details - Item Tracking Design - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-item-tracking-design)
* Content Source: [business-central/design-details-item-tracking-design.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-item-tracking-design.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hej Rasmus,

Yes, you're right that we've messed up the product names in the old design details articles. We're trying to (find time to) get this cleaned up, but in the meanwhile, you can choose to think of it as proof that Business Central has deep roots and a long pedigree.

**Comment by edupont04** [comment]
This particular article will be updated as part of 2021 release wave 1. The remaining design details will be processed for the same issue in the coming months.

**Comment by edupont04** [comment]
Closing this since the specific article is now updated (in English only until end of April).
