### ISSUE TITLE
Credit Limit Information

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#515]
Can you please provide more details on Credit Limit how to manage for example.
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450f9b98-bead-cd35-a10c-ccb67995c9e8
* Version Independent ID: 251d06f2-9ff2-3f53-f5e9-53597ae4d771
* Content: [Create a Customer Card to Register New Customers - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/sales-how-register-new-customers)
* Content Source: [business-central/sales-how-register-new-customers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/sales-how-register-new-customers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Ben,

This is as close as I can get at this time:
https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-register-new-customers#managing-credit-limits

Closing the Issue.
