### ISSUE TITLE
"Use Item Cross-References" is listed twice

### ISSUE THREAD

**Issue by HannesHolst1** [MicrosoftDocs/dynamics365smb-docs#516]
Hello,

The section for "Use Item Cross-References" is listed twice in the overview. The descriptions and the links of both entries are identical. One entry can be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84ddff91-f250-6168-265d-fbe6ffd41a5c
* Version Independent ID: e58801fd-14cc-77b5-4aaf-ccb7bbc9ff78
* Content: [Managing Inventory - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/inventory-manage-inventory)
* Content Source: [business-central/inventory-manage-inventory.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-manage-inventory.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

Thanks for pointing this out. We've deleted the duplicate row, and the topic will be republished soon.
