### ISSUE TITLE
creating vendor from contact card

### ISSUE THREAD

**Issue by wic365** [MicrosoftDocs/dynamics365smb-docs#517]
The documentation shows only the "create vendor" from then Vendor side. You can create Vendor from a Contact. Unfortunaltely here, contrarily when you create a customer, the TEMPLATE selection isn't rising.
Did I miss something?
B.R.
Chris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb27fbf6-f6e0-a77e-5b6b-e5051baa58a2
* Version Independent ID: 4ff82855-db32-1774-235f-6c0e3d55bdbf
* Content: [Create a Vendor Card to Register a New Vendor - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/purchasing-how-register-new-vendors)
* Content Source: [business-central/purchasing-how-register-new-vendors.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/purchasing-how-register-new-vendors.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Chris,

Thank you for your feedback. I'll get the article updated to also link to this article: [To create a customer, vendor, employee, or bank account from a contact](https://docs.microsoft.com/dynamics365/business-central/marketing-create-contact-companies#to-create-a-customer-vendor-employee-or-bank-account-from-a-contact)

You're right that when you create a customer from a contact, you're asked if you want to base the new customer on a template, while this is not true when you create a vendor from a contact. 

If you would like to make the two processes more similar, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)

**Comment by edupont04** [comment]
Now live. Closing Issue.
