### ISSUE TITLE
This statement very very hard to understand / explain

### ISSUE THREAD

**Issue by AndreaDiCeglie** [MicrosoftDocs/dynamics365smb-docs#518]
[Immetti qui i commenti]
"La parola "data di lavoro", nella lingua impostata in Lingua imposterà la data sulla data di lavoro attualmente impostata e specificata nella pagina Impostazioni personali."

The word for 'workdate', in the language set by Language setting, will set the date to the currently set work date that is specified on the My Settings page. Instead of entering the entire word, you can enter part of the word, starting from the beginning, such as 'w' or 'work'.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: e75fc0c2-d5f5-4652-56de-44fbdc9d8343
* Version Independent ID: ad0e08e1-cc52-f2e6-1ce9-cbb1c3efdc7b
* Content: [Immissione di date e ore in Business Central - Business Central](https://docs.microsoft.com/it-it/dynamics365/business-central/ui-enter-date-ranges)
* Content Source: [business-central/ui-enter-date-ranges.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-enter-date-ranges.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hi,

Thanks for reporting this issue. We have reworked the description to make it more clear, and added a little more information about what a work date is and an example of when they're useful. 

Though the content will be published soon in English, there will be some delay before the translated version becomes available.
