### ISSUE TITLE
Processing rules

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-docs#521]
I'm missing some information / samples on how to use the 'Processing Rules' on rapidstart packages.
See https://www.navug.com/communities/community-home/digestviewer/viewthread?GroupId=49&MessageKey=75c95752-08dc-480a-94eb-f49ad33559fd&CommunityKey=95503735-5a0b-4af1-8326-9bd7bb3b4d3d&tab=digestviewer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dad3507-9206-82e9-e958-667a5c3bb5de
* Version Independent ID: eb99bfd3-56d8-d4b0-5880-f20a1c9def6f
* Content: [How to Create Custom Company Configuration Packages - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-how-to-create-custom-company-configuration-packages)
* Content Source: [business-central/admin-how-to-create-custom-company-configuration-packages.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-how-to-create-custom-company-configuration-packages.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! I've added this to our backlog and hope to get someone to take a close look before summer. I'll keep this feedback entry open until then.

**Comment by edupont04** [comment]
Hello @fvet,

We've added a few words on how to apply processing rules, but I can't provide examples yet. Once we have some key team members back from vacation, I hope to be able to enhance the article further.

**Comment by edupont04** [comment]
Updated to provide a very simple example. Closing Issue.
