### ISSUE TITLE
File SEPA Payments does not exist

### ISSUE THREAD

**Issue by mh1205** [MicrosoftDocs/dynamics365smb-docs#527]
[Enter feedback here]

see title : File SEPA Payments (see point 1) does not exist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65b88651-a3cb-3c2e-1870-1d69dae49afc
* Version Independent ID: 9eba4c5a-1136-ef4c-2002-f0434b8f1a46
* Content: [How to File SEPA Payments - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/belgium/how-to-file-sepa-payments)
* Content Source: [business-central/LocalFunctionality/Belgium/how-to-file-sepa-payments.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/Belgium/how-to-file-sepa-payments.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Now live. We apologize for not having updated the docs sooner, but the Belgian version of Dynamics 365 Business Central now uses the functionality in the base version for managing SEPA payments. See the updated guidance here: https://docs.microsoft.com/en-us/dynamics365/business-central/finance-make-payments-with-bank-data-conversion-service-or-sepa-credit-transfer#setting-up-sepa-credit-transfer
