### ISSUE TITLE
more details required

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#529]
Hi Team

Can you please elaborate more on this page.

There are a heap of other pages that relate to this document and they are not shared.

Thank you
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2b99e4f-0564-0bf6-be18-7886860f3211
* Version Independent ID: c667a45d-24a2-c359-1d8f-ee477c0cce5b
* Content: [Create and Manage Interactions with Contacts - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/marketing-interactions-overview)
* Content Source: [business-central/marketing-interactions-overview.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/marketing-interactions-overview.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

The page is intended to simply give an overview of the feature area, and provide a sort of mini table of contents that offer a short description of the information that the topics in the are provide. It's a standard construction in the docs. Closing this issue.
