### ISSUE TITLE
Choose the Email Body Layout Code field, and then select a layout from the drop-down list.

### ISSUE THREAD

**Issue by TrippyZ** [MicrosoftDocs/dynamics365smb-docs#530]
"Choose the Email Body Layout Code field, and then select a layout from the drop-down list."

That statement is wrong.  The Email Body Layout Code field is not visible on the page.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0171dfbc-61f2-e62e-f4a3-bb641b15c3e2
* Version Independent ID: 51deab1e-0243-3178-7640-01bb91591fca
* Content: [Set up email in Business Central - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/admin-how-setup-email#set-up-reusable-email-texts-and-layouts-for-sales-and-purchase-documents)
* Content Source: [business-central/admin-how-setup-email.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/admin-how-setup-email.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by edupont04** [comment]
Now live.
