### ISSUE TITLE
Can this BOM explosion also work on the PO receiving Side

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#531]
We can see that BC has the ability to explode BOM's on inventory items. Is this functional also available when a PO Receipt is coming in.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20683b54-f305-0aa7-13a7-892450cdde00
* Version Independent ID: f2843ad1-f8a5-25aa-37e8-cbfa2cbdab6c
* Content: [Work with Bills of Material to Manage Components - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/inventory-how-work-boms)
* Content Source: [business-central/inventory-how-work-BOMs.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/inventory-how-work-BOMs.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello David,
My apologies for the late response. You can replace an assembly BOM with its constitute items (= "exploding it") on a purchase return order but not on a posted purchase receipt. 

I hope this answers your question. Otherwise, please let me know.
