### ISSUE TITLE
Regulation no. is outdated

### ISSUE THREAD

**Issue by GylfiThorThorisson** [MicrosoftDocs/dynamics365smb-docs#532]
[Enter feedback here]

In TAB311  you can find the following text constant LocalLegalStatementCaptionLbl
   This invoice originates in a ERP system that conforms with regulation no. 505/2013

Being an Icelandic resident I have never heard you need to notify the government if printing multiple copies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da83efef-1368-480c-62fa-7ec332c6c156
* Version Independent ID: 63fc0163-506b-1152-b115-9baec14557ee
* Content: [Electronic Invoicing Requirement for Issuing Single-Copy Invoice - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/iceland/electronic-invoicing-requirement-issuing-single-copy-invoice)
* Content Source: [business-central/LocalFunctionality/Iceland/electronic-invoicing-requirement-issuing-single-copy-invoice.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/Iceland/electronic-invoicing-requirement-issuing-single-copy-invoice.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,Thank you for your feedback! I see that you closed the Issue already yourself, so I'm just adding that the statement has been around for a very long time, and it was also part of the docs for Dynamics NAV 2013 R2: https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2013r2/dn306165(v=nav.71)
