### ISSUE TITLE
Wrong Page Displayed

### ISSUE THREAD

**Issue by tanya-tessteam** [MicrosoftDocs/dynamics365smb-docs#534]
While in the data exchange definition I clicked on the data format and asked to learn more and it took me to the OCR documentation.  They have nothing to do with each other and I was trying to get to the date formulas.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f95976d-bf59-417a-1fee-54a9c8d1d085
* Version Independent ID: 8867d3a3-cfef-11cc-0938-acb8e48560f9
* Content: [Use OCR to Turn PDF into E-Invoices - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/across-how-use-ocr-pdf-images-files)
* Content Source: [business-central/across-how-use-ocr-pdf-images-files.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/across-how-use-ocr-pdf-images-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hi,

Thanks for catching this. It looks like the pages for data exchange definitions point to an article that's only relevant to the definitions related to OCR. I've created a bug to get the mapping updated in the next product update. 

In the meantime, you can find information about date formulas in [this article](https://docs.microsoft.com/dynamics365/business-central/ui-enter-date-ranges#entering-dates). Hope that helps.
