### ISSUE TITLE
Reversing Entries

### ISSUE THREAD

**Issue by jms09** [MicrosoftDocs/dynamics365smb-docs#536]
Reversing Entries are for much more than corrections.  

Reversing Entries are routinely used for accrual entries, which have to be subsequently 'removed', in the sense of entirely offset, so that the ultimate entry can be entered without double entering amounts or calculating and entering only the differences between the original entry and the final entry.

Jerald Savin, CPA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c0c4f82-94bf-ee44-9f15-15cab3277de1
* Version Independent ID: b7e8a4e6-826f-c1d7-54ba-c2ef370f3c0d
* Content: [Undo a Posting by Posting a Reversing Entry - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-how-reverse-journal-posting)
* Content Source: [business-central/finance-how-reverse-journal-posting.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/finance-how-reverse-journal-posting.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Jerald,

Thank you for your feedback and insights! We've added your feedback to our backlog and will use it to update this article later this year.

**Comment by edupont04** [comment]
Now live.
