### ISSUE TITLE
KPI Web Services Based on Account Schedules - Closing date included?

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/dynamics365smb-docs#538]
Account Schedules can include amounts including closing date or without closing dates in BC, based on chosen column types for each Account Schedule.

Please update this documentation page, and clarify, should "KPI Web Services Based on Account Schedules" - include or not - the closing dates for the amounts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81ca7496-2a40-ede1-56ad-37ff6696295c
* Version Independent ID: 51d6faa8-f678-23d3-2839-3704917d6a56
* Content: [Set Up and Publish KPI Web Services for Account Schedules - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/bi-how-to-set-up-and-publish-kpi-web-services-based-on-account-schedules)
* Content Source: [business-central/bi-how-to-set-up-and-publish-kpi-web-services-based-on-account-schedules.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/bi-how-to-set-up-and-publish-kpi-web-services-based-on-account-schedules.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by brentholtorf** [comment]
Hello,

Thanks for bringing this up. We do not include the closing dates so that people can use the date filters in Power BI to analyze different periods of time. We will update the content right away to make that clear.

**Comment by hkusulja** [comment]
Hello,
please close this github reported issue, once this is resolved, and not before.

Also, since Account schedules, can include closing entries, used for various reporting purposes, as an option, i do not see, why in KPI Web Service, does not respect this option also. For usage in OData/Power BI , sometimes it is good to have also closing entries.

Anyhow, please document the specification of the product.
And if, this is a feature request, to have closing entries option enabled and included in KPI Web service, i have started thread https://community.dynamics.com/business/f/dynamics-365-business-central-forum/420642/closing-entries-missing-in-account-schedule-kpi-web-service
