### ISSUE TITLE
IC Types

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#539]
There are 4 options for IC Types can you please update this page with what each of them do.

I saw the note on IC Type File Transfer. Would be good if Azure Blob could be used.

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c748d8ad-0f5e-126e-0555-b047af1e8c96
* Version Independent ID: beb88306-1c4e-3e69-cb6d-06d62ddd71a6
* Content: [Set Up Intercompany Transaction Posting - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/intercompany-how-setup)
* Content Source: [business-central/intercompany-how-setup.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/intercompany-how-setup.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Ben,
Thank you for your feedback! To help me understand your request better, are you referring to the Transfer Type field in the Intercompany Partner setup page? That field specifies how you share information with this intercompany partner, as explained in the field description (tooltip):
- File Location: You send the partner a file containing intercompany transactions. 
- Database: The partner is set up as another company in the same database. 
- Email: You send the partner transactions by email.

**Comment by makdaddy8888** [comment]
Yes that’s correct.

Some additional details on each of there items would be helpful to explain the process further.

Kind Regards
Ben Opit
+61411707070

**Comment by edupont04** [comment]
Hello Ben,

Well, there isn't a lot more to say about these values. It all hinges on internal logic that, depending on your choice in this field, then manage the intercompany postings. 

Intercompany postings is designed for users who control more than one legal business entity and have set up multiple companies to separate the accounting functions of each of these entities. This broad description applies to many users, especially those operating in international markets or regions with widely disparate business cultures and regulatory environments. Once you adopt intercompany postings, doing business with your subsidiary and internal partner organizations becomes as simple as engaging with your external vendors and customers. You enter intercompany transaction information only once in the appropriate documents. You can use the functionality you are already familiar with, such as receivables and payables management. Mapping facilities for the chart of accounts and dimensions help ensure that information appears in the right places.

Intercompany transactions are explained here: [https://docs.microsoft.com/dynamics365/business-central/intercompany-how-manage-intercompany-inbox](https://docs.microsoft.com/dynamics365/business-central/intercompany-how-manage-intercompany-inbox).

If you want to add Azure blobs as storage for intercompany postings, then I suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)

**Comment by makdaddy8888** [comment]
Thank you for the details.

That is very helpful

Kind Regards
Ben Opit

**Comment by edupont04** [comment]
Great! I've taken your feedback and identified some content that was never ported from Dynamics NAV to Business Central. I hope to get that content added at some point in the coming months. I'm closing the feedback for now, but I thank you for your feedback, Ben!
