### ISSUE TITLE
Outbound Sales Items explanations

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#540]
Can you please add a section on what each of the outbound sales items are for clarity too?

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c748d8ad-0f5e-126e-0555-b047af1e8c96
* Version Independent ID: beb88306-1c4e-3e69-cb6d-06d62ddd71a6
* Content: [Set Up Intercompany Transaction Posting - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/intercompany-how-setup)
* Content Source: [business-central/intercompany-how-setup.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/intercompany-how-setup.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

Thank you for your feedback! As explained by the field description (tooltip), the **Outbound Sales Item No. Type** field specifies what type of item number is entered in the **IC Partner Reference** field for items on purchase lines that you send to this IC partner.

**Comment by edupont04** [comment]
Answered. Also related to this feedback: https://github.com/MicrosoftDocs/dynamics365smb-docs/issues/539
