### ISSUE TITLE
Auto Accept in IC Partner

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#541]
Can you please add a section on what the Auto Accept option does in IC Partner page?
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c748d8ad-0f5e-126e-0555-b047af1e8c96
* Version Independent ID: beb88306-1c4e-3e69-cb6d-06d62ddd71a6
* Content: [Set Up Intercompany Transaction Posting - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/intercompany-how-setup)
* Content Source: [business-central/intercompany-how-setup.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/intercompany-how-setup.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Ben,

Thank you for your feedback! As explained in the field description (tooltip):
"Specifies that transactions from this intercompany partner are automatically accepted."

**Comment by edupont04** [comment]
Answered + also related to this feedback: https://github.com/MicrosoftDocs/dynamics365smb-docs/issues/539
