### ISSUE TITLE
Wrong sentence on Payment Terms

### ISSUE THREAD

**Issue by mynavblog** [MicrosoftDocs/dynamics365smb-docs#542]
The first sentence on the page is not correct:

_Payment terms determine how you **whelp** you manage due dates..._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f0109b5-e9f8-5537-d13d-5f3c6f9cb8cf
* Version Independent ID: 669e2224-0f43-e744-d313-ff1d72d4fff2
* Content: [Set Up Payment Terms (IT) - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/italy/how-to-set-up-payment-terms)
* Content Source: [business-central/LocalFunctionality/Italy/how-to-set-up-payment-terms.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/Italy/how-to-set-up-payment-terms.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hi,

Thanks for pointing this out. The typo is corrected and the content will be republished soon.
