### ISSUE TITLE
Rollecenter afhængig og danner ikke .csv fil

### ISSUE THREAD

**Issue by Michael-Hanzen** [MicrosoftDocs/dynamics365smb-docs#544]
Hej Soren,
Jeg oplever at rapporten "Moms -Listeangivelsedisk" kun dukker op hvis man bruger Rollen Revisor (det er ikke nævnt), og at rapporten ikke nævnt i artiklen danner en kommasepareret fil (.csv) der direkte kan uploades på Skat.dk, men et andet format som Skat.dk ikke accepterer.

![image](https://user-images.githubusercontent.com/83945625/117624466-3dbcb780-b175-11eb-8b4e-d0b26f9071fa.png)

Jeg har i NAV/BC on-premise versionerne normalt bedt en udvikler ændre format i rapporten til csv, men vil mene det er noget jeg fremadrettet selv burde kunne indstille et eller andet sted i BC Cloud versionerne.

Jeg ser frem til at høre fra dig, gerne pr. e-mail til mh@systemconnect.dk

Med venlig hilsen
Michael Hansen

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 87cd3884-d697-3be1-164e-8e436f3b9f16
* Version Independent ID: a9c3c6fc-cf77-40d6-cb2b-91c939a841b9
* Content: [Momsindberetning - Business Central](https://docs.microsoft.com/da-dk/dynamics365/business-central/localfunctionality/denmark/vat-vies-reporting)
* Content Source: [business-central/LocalFunctionality/Denmark/vat-vies-reporting.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/Denmark/vat-vies-reporting.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hej Michael,
Søren arbejder ikke hos os længere, så du må nøjes med mig. Som jeg forstår dig, så mener du, at rapporten generer det forkerte filformat. I så fald må jeg bede dig rapoortere det til Microsoft Support gennem din Business Central forhandler, da jeg ikke kan gøre det for dig. Du kan også bede om en ændring her: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)

Hvad angår tilgængeligheden af rapporten, så bør du kunne finde den gennem søgefeltet fra alle rollecentre: [https://docs.microsoft.com/da-dk/dynamics365/business-central/ui-search](https://docs.microsoft.com/da-dk/dynamics365/business-central/ui-search)
