### ISSUE TITLE
Search for special characters doesn't work

### ISSUE THREAD

**Issue by LenCardinal** [MicrosoftDocs/dynamics365smb-docs#546]
In the Search for Special Characters section, (1) it should be specific and say 'single quotes' to distinguish from 'quotes' which by default are 'double quotes'.

Also, either way, neither single quotes nor double quote works. Build 18.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 802c5ab2-6384-9f67-586f-8de66cd361cc
* Version Independent ID: 12fb39ec-1f3c-e49b-de9c-7d9d09b29fc4
* Content: [Sorting, Searching, and Filtering Lists - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-enter-criteria-filters)
* Content Source: [business-central/ui-enter-criteria-filters.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-enter-criteria-filters.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! The article has been updated to your recommendation. The update will be published soon.
