### ISSUE TITLE
Power BI Reports Insights Not Showing on Dashboard

### ISSUE THREAD

**Issue by SaveMH** [MicrosoftDocs/dynamics365smb-docs#548]
On the main company dashboard the Power BI Reports tile/page recently stopped showing our reports.  I think this has to do with the latest update as it was working before.  We are on version 18.  Refreshing the page and uploading new reports still does not show reports.  Tile has link for "Upload demo reports for this page" and when clicked states 

"We are uploading a demo report to Power BI in the background for you. Once the upload finishes, choose Refresh to see it in this page.
If you have already reports in your Power BI workspace, you can choose Select Reports instead."

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/dynamics365/business-central/product-help-and-support#report-a-problem).
