### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Rukkulakki** [MicrosoftDocs/dynamics365smb-docs#549]
The link to printer registration https://docs.microsoft.com/en-us/universal-print-connector-printer-registration results in a 404 page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59ad1ee4-b385-14b2-f029-16770954bb61
* Version Independent ID: 513943bd-47b2-4f58-f780-70277ef7e532
* Content: [Setting Up Printers - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-specify-printer-selection-reports)
* Content Source: [business-central/ui-specify-printer-selection-reports.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-specify-printer-selection-reports.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Hello, 
The link has been fixed to target https://docs.microsoft.com/universal-print/fundamentals/universal-print-connector-printer-registration. The updated article will be published soon Thanks for the feedback!.
