### ISSUE TITLE
Mac shortcut for Enter seems wrong

### ISSUE THREAD

**Issue by DavidRoys** [MicrosoftDocs/dynamics365smb-docs#55]
Enter
(Fn+down Arrow)

I'm not sure Mac keyboard shortcut is right here as it is the same as the previous shortcut in the table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d96fd662-e905-9df6-60f5-c709f92077c1
* Version Independent ID: 172fd943-0f5c-6d4c-b764-ced7fd077a96
* Content: [Keyboard Shortcuts - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/keyboard-shortcuts)
* Content Source: [business-central/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/keyboard-shortcuts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! Yes, the keyboard shortcut was wrong. The article has been fixed and an update will be published soon.
