### ISSUE TITLE
Specific example would be nice

### ISSUE THREAD

**Issue by ilyalehrman** [MicrosoftDocs/dynamics365smb-docs#550]
Could you provide a specific example rather than just generic "enter the right information in the right way". Maybe provide some use cases? For example: how would you record an expense that is then tied to a company credit card?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ef7322e-85ec-eaad-738d-843898c5ad76
* Version Independent ID: 84f2f9f2-ebfa-9f63-d633-30f3b8a6036a
* Content: [Record and Reimburse Employees' Business-Related Expenses - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-how-record-reimburse-employee-expenses)
* Content Source: [business-central/finance-how-record-reimburse-employee-expenses.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/finance-how-record-reimburse-employee-expenses.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback, and my apology for the delay in getting back to you! 

We don't usually provide the type of content that you are asking for because it would depend too heavily on your organization's setup and practices. For example, the company credit card is usually tied to a bank account, so you could register expenses against that bank account. But your organization might have a different setup, in which case my guidance would be incorrect.

I hope this answers your questions. Otherwise, do let us know!

**Comment by ilyalehrman** [comment]
Thanks!

That, however, is exactly why you’d want to provide a couple of different examples. Business apps drive processes as much as processes drive business apps, so for a company that’s just coming into BC, it may be very useful to have an idea of how to implement a particular process using Business Central, rather than trying to create a process and then find out that BC implementation isn’t possible w/o modification. We’re currently migrating a company from QuickBooks to Business Central because they’ve outgrown QB and want to stay in the Microsoft ecosystem. They want to know a “Business Central best practice” for expense management, and there’s 0 guidance on that. The purely technical solution does not address the business need, and at least a hint regarding possible directions would help tremendously – BC isn’t exactly like installing Windows Server 😊.

Ilya Lehrman
o 215-995-5562 | m 610-505-8505
inWorks LLC: Infrastructure ***@***.***D752FB.03A2AA60]  / Intranets ***@***.***D752FB.03A2AA60]  / Solutions ***@***.***D752FB.03A2AA60]  / ***@***.***D752FB.03A2AA60]
Want to meet? Put 30 minutes on my calendar at http://bit.ly/30minuteswithilya
