### ISSUE TITLE
Sales documents fields clarification - Your Reference vs. External Document No.

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/dynamics365smb-docs#551]
Please clarify and update documentation regarding Sales documents (Sales Quote, Sales Order and Sales Invoice) about usage, intention, and difference between fields "Your Reference" and "External Document No"

Thank you
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ad18716-656b-e1fe-3072-dda34dcd1552
* Version Independent ID: 2759fb7c-d617-94fc-080e-63469b67fabf
* Content: [Create a Sales Offer to a Customer - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-make-offers)
* Content Source: [business-central/sales-how-make-offers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/sales-how-make-offers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by hkusulja** [comment]
Hello,
I think that before (some NAV versions etc.) only External document field existed.
Later, and in BC (v16 i think and later) new field was added "Your reference".
I might be wrong here also.

However, there is no any documentation, guidance, or clarification what purpose and difference of those fields.

My own view is that in Sales documents (Sales Quote, Sales Order, Sales Invoice):
 - External document (our internal organization, other/external system, like internal SharePoint document number, or other/CRM system id if needed etc.)
 - your reference (reference of the customer that is visible, like their purchase order number, or their agreement number etc.)

But I might be wrong. So, I hope that Microsoft will write clarification on those two fields and their purpose, use and clarification.

Reference to community discussion is also here - https://community.dynamics.com/nav/f/microsoft-dynamics-nav-forum/280887/your-reference-vs-external-document-no/802397#802397

**Comment by hkusulja** [comment]
@edupont04 yes, that is it, it would be nice to clarify this on public offical docs.microsoft.com page. For now it is confusing and different partners are saying different things...

**Comment by hkusulja** [comment]
Ok, please check with product group and update current documentation and clarification on this, thank you!

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by hkusulja** [comment]
@edupont04 - Can you explain when will be next doc update and what will be text in it? Tx

**Comment by edupont04** [comment]
Hello again,
We published the update today, but in English only, and here is the description for purchasing: https://docs.microsoft.com/en-us/dynamics365/business-central/purchasing-ext-doc-no
Closing the Issue as fixed.

**Comment by hkusulja** [comment]
@edupont04 Thank you for the update, also on - https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-invoice-sales#external-document-numbers

However, i was hoping for more clarification when you say "external", does this means, our organization customers or vendors system, or our internal organization but other system (like CRM) ?

**Comment by hkusulja** [comment]
I know, but it should be clarification what is intention of this field, not just specs what it does.

also, since external document information is part of journal, and your reference is not. But can both of those get it printed in reports, right?
