### ISSUE TITLE
Note would be helpful

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-docs#554]
In the section **To modify a custom layout**, there are several steps to modifying a custom layout. The last step is to reimport the changes you made. If you get distracted or otherwise forget this last step, your changes will be lost. I think it would be helpful to have one of your notes somewhere near the list of steps in the topic that would say something along the lines of Remember, your changes will not be saved until you upload them back into Business Central.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 562ba9ca-f395-bbeb-0775-5a85696e0935
* Version Independent ID: 58c23bed-523d-0432-f76e-2930232816f6
* Content: [Create and Modify Custom Layouts for Reports and Documents - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-create-custom-report-layout)
* Content Source: [business-central/ui-how-create-custom-report-layout.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-how-create-custom-report-layout.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

Thanks for pointing this out. I've added an "Important" alert immediately after the final step to reinforce the need to import the modified report layout. The updated topic will be published soon.
