### ISSUE TITLE
Sync Timing for Contacts

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#556]
Would it be possible to add a section to this page that clearly articulates how the Contact Sync operation functions on an ongoing basis.  Once established, is the process automated, or does the user need to manually trigger the contact sync?  If it's manual, is there any way to automate the process?

The current documentation is unclear as to how the sync process should occur on an ongoing basis AFTER it's set up.  

Thank you.
Chris

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be2a9cdb-ccff-0083-16af-6eaa309416f4
* Version Independent ID: 2897af77-749b-da01-ec4d-54976ed10bcc
* Content: [Share contacts between Business Central and Outlook - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/admin-synchronize-outlook-contacts)
* Content Source: [business-central/admin-synchronize-outlook-contacts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/admin-synchronize-outlook-contacts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! Our apologies for the very long wait for an answer!

A member of our team has at long last reviewed your feedback. The article has been updated to answer your question.
