### ISSUE TITLE
Print Picking List

### ISSUE THREAD

**Issue by TWBlais** [MicrosoftDocs/dynamics365smb-docs#558]
[Enter feedback here]
The first line of Print a picking list from a sales order states:
" You can print an inventory picking document from a sales order, sales invoice or any other document that initiates shipment of items. "

HOWEVER, there is no Print Picking List from a Sales Invoice. It is a billing document, so the Help is incorrect and misleading.

Thank you.
Tom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f6f97c-3fad-dbfd-e0d3-54318b7ae8d1
* Version Independent ID: 955ac75d-d4e0-6e6c-c7ad-adef1074aba4
* Content: [How to Print an Inventory Picking List from a Sales Order - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-print-picking-list)
* Content Source: [business-central/sales-how-print-picking-list.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/sales-how-print-picking-list.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! You're right that you cannot create a picking list from a sales invoice. This will be fixed in the next doc update.

**Comment by edupont04** [comment]
Hello again,
The article has now been updated accordingly.
