### ISSUE TITLE
Wrong documentation?

### ISSUE THREAD

**Issue by pm-biteam** [MicrosoftDocs/dynamics365smb-docs#56]
Hello Mircosoft Team,

The above mentioned documentation states at step 3 "Notification Templates" window. Isn't this functionality already changed since NAV 2016 and nowadays solved over customization of report layouts? At least I still can't find the "notification tempaltes" window in Business Central. A clarification would be great on how to customize these messages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c8abdcb-336b-e718-0cc3-3e69ab793cfb
* Version Independent ID: 17849231-f864-3ad8-5ff2-6664c1295ff1
* Content: [Setting Up Workflow Notifications - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-setting-up-workflow-notifications)
* Content Source: [business-central/across-setting-up-workflow-notifications.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-setting-up-workflow-notifications.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback

I have replaced all mention of the (obsolete) Notification Template functionality with information about how to customize report 1320, Notification Email, using the report layout customization feature, described here: https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-create-custom-report-layout

The updated help will be available in approximate one week.
