### ISSUE TITLE
bin setup

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#563]
the tool tip on Receipt Bin Code comes to this page.

how do we setup Receipt Bin Codes?
Can you expand on the Bin setup too please siting an example?

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b90de8f3-c15f-8c3a-975a-152251db24bf
* Version Independent ID: 32f5d631-6591-a74f-25eb-dffbfd1d73ce
* Content: [Set Up a Location Card and Define Transfer Routes - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/inventory-how-setup-locations)
* Content Source: [business-central/inventory-how-setup-locations.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/inventory-how-setup-locations.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

Thank you for your feedback! You're right that the article is a bit too simplistic, but there are hints in the embedded video. There are also good learnings in the [walkthrough for basic warehousing](https://docs.microsoft.com/en-us/dynamics365/business-central/walkthrough-picking-and-shipping-in-basic-warehousing) that we updated last week. The walkthrough for advanced warehousing will be updated later this week.  

Essentially, bins are a way to group inventory in a location. You can choose to create separate bins for receipts, shipments, and other warehouse operations. Once bins are defined for a location, you can then assign them on the location card. For example, create a bin for receiving inventory, and then specify that bin in the Receipt Bin Code field. 

You can read about the background in the design details here (not yet updated to reflect current demo data): https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-warehouse-setup  

We're in process of updating the docs for warehousing and will roll out updates over the coming months.

**Comment by edupont04** [comment]
Now live.
