### ISSUE TITLE
Page doesn't identify what to do if the "New" function is greyed out.

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#568]
I'm trying to add an account category, but my "NEW" option is greyed out.  There's nothing on this page that indicates what would cause this (permissions etc, or other functionality that would lock the users ability to add new account  categories).  I've tried using both business manager and accountant rolls.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96d2116f-83ee-acf5-48f8-73abc4a00287
* Version Independent ID: 3f257051-6e66-67ef-40c9-add293f6b2e4
* Content: [Learn About General Ledger and COA - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/finance-general-ledger)
* Content Source: [business-central/finance-general-ledger.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/finance-general-ledger.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Chris,
Thank you for your feedback! This sounds strange, so if you choose the **Edit List** action, does the **New** action then become activated? That's the experience I have in the Account Categories list, at least. I hope that helps?

**Comment by chris7777au** [comment]
Hi Eva.

No it doesn’t.  We use the Wiise implementation (Australianised BC) so we are wondering if they have somehow managed to flag a setting so that it prevents the ‘business manager’ user from adding new G/L Account Categories.  The problem for us is when you go to the help page relating to this topic, there’s nothing on the page to guide you IF the ‘new’ is greyed out.  If you want to improve this page, put a small box in that says something like “your user must be a member of XYZ group to have privileges to add or edit G/L Account groups.  Get your administrator to do ABC to if required” (clearly you wouldn’t get me writing your help doco… but you get my drift, at least something to guide the user or admin as to EXACTLY what permission group is required to edit IF its something related to permissions.  It may be something different, but ‘good’ help files will have something to point me in the right direction.  Currently I’m paying a consultant to contact Wiise, who will probably have to contact Microsoft, to relay the problem back to the consultant so that I can pay them to tell me the answer to something that….. Microsoft should have had on their help page 😉

Eva I hope this is taken in the right manner --… can you consider updating this page (in fact there’s probably a benefit to having a block at the bottom of any Microsoft functionality help page) that gives you a short run down on the required permissions ‘required’ to access or edit the functionality.  Netsuite used to do this fairly well (I’m an old NS customer), but Microsoft hasn’t baked this into it’s help system yet, so functionality vs permissions is a bit of a black box!

Cheers
Chris Pope
Pacsource Pty ltd
Unit 84, 1470 Ferntree Gully Road
Knoxfield, Victoria 3180, Australia
T. +61.3.9763.4500
M. +61.447.888.777
E. ***@***.******@***.***>

Disclaimer ; The information in this email including any attachments is confidential and may be legally privileged. If an addressing or transmission error has misdirected this email please notify the author by replying to this email and destroy the original message. If you are not the intended recipient, any use, disclosure, copying or distributions prohibited and may be unlawful. Distribution of this email to other parties may result in criminal prosecution.


From: Eva Dupont ***@***.***>
Reply to: MicrosoftDocs/dynamics365smb-docs ***@***.***>
Date: Tuesday, 8 June 2021 at 10:41 pm
To: MicrosoftDocs/dynamics365smb-docs ***@***.***>
Cc: Chris Pope ***@***.***>, Author ***@***.***>
Subject: Re: [MicrosoftDocs/dynamics365smb-docs] Page doesn't identify what to do if the "New" function is greyed out. (#568)


Hello Chris,
Thank you for your feedback! This sounds strange, so if you choose the Edit List action, does the New action then become activated? That's the experience I have in the Account Categories list, at least. I hope that helps?

**Comment by edupont04** [comment]
Hi Chris,

Once again, thank you for your feedback! Out of the box, you should be able to work with account categories if you have the Business Manager or Accoutant role. However, Wiise may have made changes that are out of my reach to even know about. They are supposed to make it easy for you to know if they tweak built-in functionality, and it sounds like they might have done that here (tweak, but not document, that is).

As for you very valid suggestion that add a definition of just which permissions are required to carry out a task, I have to turn thumbs-down on that. The reason is that if list the required permissions, then your admin (or Wiise, in this case) can overrule that. Or one my colleagues can roll out an update that changes those permissions. 

We consider it one of our product's advantages that it is so adaptable, whereas some of our competitors are more rigid and therefore can be perceived as more predictable as to how what works.

To meet you in the middle ground the way that we Danes prefer, I'll add a blurb about permissions to this article. But I encourage you to get your admin to check if you have effective permissions to the G/L Account Category table (they can do that from the Users page). To me, it sounds like you don't, for some reason. But if you do, and the New action remains disabled, then you guys have to go through Product Support.

**Comment by chris7777au** [comment]
Hey Eva.

Your in Denmark?  Lovely country!  Our major EU distributor is in Hedensted.

I understand your point you have made (and I appreciate your detailed, transparent response).

You are correct – Wiise has made changes by adding a tool called Wiisdom (financial reporting), and for this reason they have removed the ability to add G/L Account Categories (we received this knowledge overnight… very very annoying!!)

Regarding defining which permissions are required – I’m talking permissions, not Role.  I am the administrator of our tenant.  I had a problem recently where I could not edit data in Excel (as is explained in all the help files).  It simply would not do it…. Found out later after going through Wiise support that I had to add a permission to the Business Manager role.

Reading the standard Business Central User Guide – Microsoft do not appear to publish any detail about various ‘permissions’ and there are heaps of them! (9291 of them to be precise…. ).  Where (as an Admin) do I determine what permissions affect a user?  Where’s the bible on permissions (i.e. where can I go to identify exactly what the Media Set permission does?). It’s a bit of a black box without any structured documentation – a bit like the wild west!  This is probably outside your scope (I understand), but as an admin it makes it near on impossible to work out what ‘permissions’ need to be included or removed to enable/prevent a certain function.  Microsoft has given us ‘massive flexibility and functionality’ and then appears not to have defined anything (i.e. have at it… just see if it breaks!).

Perhaps I’m missing something!  At the end of the day the Administration question is this:  “I cannot add G/L Account Categories, what permission controls this?”  If I needed to look it up, where would I locate the information that would help me identify the related permissions?

Make sense?

Chris Pope
Pacsource Pty ltd
Unit 84, 1470 Ferntree Gully Road
Knoxfield, Victoria 3180, Australia
T. +61.3.9763.4500
M. +61.447.888.777
E. ***@***.******@***.***>

Disclaimer ; The information in this email including any attachments is confidential and may be legally privileged. If an addressing or transmission error has misdirected this email please notify the author by replying to this email and destroy the original message. If you are not the intended recipient, any use, disclosure, copying or distributions prohibited and may be unlawful. Distribution of this email to other parties may result in criminal prosecution.


From: Eva Dupont ***@***.***>
Reply to: MicrosoftDocs/dynamics365smb-docs ***@***.***>
Date: Thursday, 10 June 2021 at 12:49 am
To: MicrosoftDocs/dynamics365smb-docs ***@***.***>
Cc: Chris Pope ***@***.***>, Author ***@***.***>
Subject: Re: [MicrosoftDocs/dynamics365smb-docs] Page doesn't identify what to do if the "New" function is greyed out. (#568)


Hi Chris,

Once again, thank you for your feedback! Out of the box, you should be able to work with account categories if you have the Business Manager or Accoutant role. However, Wiise may have made changes that are out of my reach to even know about. They are supposed to make it easy for you to know if they tweak built-in functionality, and it sounds like they might have done that here (tweak, but not document, that is).

As for you very valid suggestion that add a definition of just which permissions are required to carry out a task, I have to turn thumbs-down on that. The reason is that if list the required permissions, then your admin (or Wiise, in this case) can overrule that. Or one my colleagues can roll out an update that changes those permissions.

We consider it one of our product's advantages that it is so adaptable, whereas some of our competitors are more rigid and therefore can be perceived as more predictable as to how what works.

To meet you in the middle ground the way that we Danes prefer, I'll add a blurb about permissions to this article. But I encourage you to get your admin to check if you have effective permissions to the G/L Account Category table (they can do that from the Users page). To me, it sounds like you don't, for some reason. But if you do, and the New action remains disabled, then you guys have to go through Product Support.

**Comment by edupont04** [comment]
Hi Chris,

Yes, Hedensted is a very popular hub for distribution :-)

Anyway, I'll be adding this blurb to the article:

> **Access to create and edit accounts and account categories**
> In a small organization, such as the CRONUS demonstration company, most users can edit the chart of accounts, except users with a TEAM MEMBER license. However, in larger organizations, access to edit the chart of accounts is limited by roles and permissions. If you are an administrator, or you have the Business manager or Accountant role, you can check the permissions for all users to make sure the right people have access to the relevant tables. For more information, see [To get an overview of a user's permissions](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-define-granular-permissions#to-get-an-overview-of-a-users-permissions).

I understand and respect that you are looking for a very different way of determining who can do what and who cannot. But this is as close as I can get right now.
