### ISSUE TITLE
Customer priority 

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#570]
Is it possible to use the customer priority to determine which customers get which limited subsection of items, for example, I may have 1000 pieces of cutlery in the warehouse and too many sales orders to fill the requirement how can we make sure that our priority customers get the first pic without using reservations?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 847659e7-41b7-3d5f-4361-33d044b039fd
* Version Independent ID: 1a0c6212-dbd0-cf87-981d-6ec6e9da3a05
* Content: [Create a Sales Order and Sell Products - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/sales-how-sell-products)
* Content Source: [business-central/sales-how-sell-products.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/sales-how-sell-products.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,
Thank you for your feedback! This scenario is not supported out-of-the-box. There might be an app for it on AppSource, but you might want to submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
