### ISSUE TITLE
Item Substitution Entry

### ISSUE THREAD

**Issue by rtigithub** [MicrosoftDocs/dynamics365smb-docs#571]
There is no documentation for how to utilize the Item Substitution. We have created substitute items but they are not picked up in the BOM. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37d63058-5104-f4c6-dd07-21caf3a4a4a8
* Version Independent ID: 6c3e166d-bdc9-b823-dfc4-62957f5aa385
* Content: [Create Item Cards for Goods or Services - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/inventory-how-register-new-items)
* Content Source: [business-central/inventory-how-register-new-items.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/inventory-how-register-new-items.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello, thank you for your feedback! You're right that we don't talk about item substitution in this article. I've added it to our backlog to get that added in a future update.

However, for your specific problem, I simply don't know if item substitution is picked up on by assembly BOMs. If you need an urgent answer to that question, you might want to ask the [community](https://community.dynamics.com/business).
