### ISSUE TITLE
The Dynamics 365 Sales URL Content is repeated

### ISSUE THREAD

**Issue by TrippyZ** [MicrosoftDocs/dynamics365smb-docs#572]
Field | Description
-- | --
Dynamics 365 Sales URL | The URL of your Dynamics 365 Sales instance. This enables users to open corresponding records in Business Central from records in Dynamics 365 Sales, such as an account or product. The Business Central records open in Business Central.
Dynamics 365 Sales URL | The URL of your Dynamics 365 Sales instance. This enables users to open corresponding records in Business Central from records in Dynamics 365 Sales, such as an account or product. The Business Central records open in Business Central.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2957b832-9aee-e050-b034-7f3badb2e27c
* Version Independent ID: a93b51b9-9a52-c8a2-2197-38c02f2e327f
* Content: [Integrating with Dynamics 365 Sales - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/admin-prepare-dynamics-365-for-sales-for-integration)
* Content Source: [business-central/admin-prepare-dynamics-365-for-sales-for-integration.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/admin-prepare-dynamics-365-for-sales-for-integration.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by brentholtorf** [comment]
Hi,

Thanks for spotting and reporting this issue. The duplicate description has been removed and the content will be republished soon.
