### ISSUE TITLE
Dynamic Low-Level Code

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#573]
Most 'learn more' functions on the Manufacturing Setup page lead to this help page.  Can you please define the fields DYNAMIC LOW-LEVEL CODE and OPTIMISE LOW-LEVEL code calculations as these do not appear to be defined anywhere (i.e. what do these switches do?)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 640a66c0-fa25-ff03-2590-b52c6bec5655
* Version Independent ID: 388e1852-54bc-32c4-b8e1-a69f513ab82a
* Content: [Design Details - Planning Parameters - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/design-details-planning-parameters)
* Content Source: [business-central/design-details-planning-parameters.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/design-details-planning-parameters.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Chris,

Thanks for pointing this out to us! I've added a work item to our backlog to get more complex fields explained. Specifically for the  Dynamics Low-level Code field, I found an article in the Dynamics NAV docs that you might find useful: https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/hh178594(v=nav.90)

**Comment by edupont04** [comment]
Now live: https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-planning-parameters#use-low-level-codes-to-manage-derived-demand
