### ISSUE TITLE
SOPA Act

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#576]
Can I check how BC can help the construction industry around the Security of Payment Act SOPA

https://www.fairtrading.nsw.gov.au/trades-and-businesses/construction-and-trade-essentials/security-of-payment

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1fd6e96-76f1-6d75-570d-1d1cd571be0d
* Version Independent ID: 4647bb84-b1ce-abac-5aa3-41df2134d40e
* Content: [Australia Local Functionality - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/localfunctionality/australia/australia-local-functionality)
* Content Source: [business-central/LocalFunctionality/Australia/australia-local-functionality.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/Australia/australia-local-functionality.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
