### ISSUE TITLE
Order Tracking Policy information

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#578]
In BC when I click on the help text for Order Tracking Policy I am directed to this page.

However there is no details on this field.

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37d63058-5104-f4c6-dd07-21caf3a4a4a8
* Version Independent ID: 6c3e166d-bdc9-b823-dfc4-62957f5aa385
* Content: [Create Item Cards for Goods or Services - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/inventory-how-register-new-items)
* Content Source: [business-central/inventory-how-register-new-items.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/inventory-how-register-new-items.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

Thank you for your feedback! I can see that you're curious about fields that are related to the planning system. You can read about that here:  https://docs.microsoft.com/dynamics365/business-central/design-details-central-concepts-of-the-planning-system

We'll add a couple of links to the See also section in our next doc update.

**Comment by edupont04** [comment]
Now live.
