### ISSUE TITLE
Critical Items

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#580]
Can you please provide information on Critical items.
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37d63058-5104-f4c6-dd07-21caf3a4a4a8
* Version Independent ID: 6c3e166d-bdc9-b823-dfc4-62957f5aa385
* Content: [Create Item Cards for Goods or Services - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/inventory-how-register-new-items)
* Content Source: [business-central/inventory-how-register-new-items.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/inventory-how-register-new-items.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

As the tooltip for the Critical field says, the field "Specifies if the item is included in availability calculations to promise a shipment date for its parent item." 
The planning engine is very complex, so we'll add a couple of links to the See also section, including this overview: https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-central-concepts-of-the-planning-system
