### ISSUE TITLE
not found the link mentionned in docs. Delete Archive

### ISSUE THREAD

**Issue by ludovicpwd** [MicrosoftDocs/dynamics365smb-docs#581]
the menu is not present in BC Saas V18.
[Tapez vos commentaires ici]

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 3f4ae087-a1fd-7343-f2dd-57d7b4536272
* Version Independent ID: 46bdbddd-5b62-3970-aa86-0fb08f44147c
* Content: [Procédure d’archivage des documents vente et achat - Business Central](https://docs.microsoft.com/fr-fr/dynamics365/business-central/across-how-to-archive-documents)
* Content Source: [business-central/across-how-to-archive-documents.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/across-how-to-archive-documents.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Now live.
