### ISSUE TITLE
Misc typo

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/dynamics365smb-docs#582]
The following sentence

The By Permission Set part shows the assigned permission sets through which the permissions are granted to the user, the source and type of the permission set, and to which extend the different access types are permitted.

should be (I think)

The By Permission Set part shows the assigned permission sets through which the permissions are granted to the user, the source and type of the permission set, and to which **extension** the different access types are permitted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b3149c9-3ef3-9b86-722b-b006a501263c
* Version Independent ID: 2331d586-dda8-ad98-0c75-d96245d56a45
* Content: [Define Granular Permissions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-define-granular-permissions)
* Content Source: [business-central/ui-define-granular-permissions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-define-granular-permissions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! This will be fixed in the next doc update. The correct wording is "to which extent the different access types are permitted."

**Comment by edupont04** [comment]
Now live.
