### ISSUE TITLE
Why is India not listed on this page?

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-docs#584]
Even though there is Indian local functionality provided (see [https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/india/india-local-functionality](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/india/india-local-functionality) it is not listed on this page. Strange. Shouldn't it be added?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 203baec6-0fa8-b294-a7ee-5b5a4c153fde
* Version Independent ID: 8f2c2fc3-f5e5-7c15-56c6-9a5fbc1a577a
* Content: [Local functionality in Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/about-localization)
* Content Source: [business-central/about-localization.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/about-localization.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Luc,

Thank you for your feedback! You're right that we forgot to update the table. This will be fixed in the next doc update.

**Comment by edupont04** [comment]
Now live.
