### ISSUE TITLE
There is no discussion in this web page of the Bottom Filter Bar in List View of Entities. What field is the filter based on, and when the Filter bar will appear or not appear.

### ISSUE THREAD

**Issue by devman2k** [MicrosoftDocs/dynamics365smb-docs#585]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 802c5ab2-6384-9f67-586f-8de66cd361cc
* Version Independent ID: 12fb39ec-1f3c-e49b-de9c-7d9d09b29fc4
* Content: [Sorting, Searching, and Filtering Lists - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-enter-criteria-filters)
* Content Source: [business-central/ui-enter-criteria-filters.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-enter-criteria-filters.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hello @devman2k,
Thank you for your feedback! To help us understand the feedback, which list view were you looking at? In the base version of Business Central, lists generally do not have something I would recognize as a "bottom filter bar", at least not in the browser.

**Comment by devman2k** [comment]
Crm not BC


Thanks,
Bryan



Bryan Tuttle
President
MCT,MCSD,MCDBA,MCAD

CodeRight Inc.
20 Marion Drive
Tewksbury, MA 01876
Phone: 781-389-9695
________________________________

**Comment by edupont04** [comment]
Hi Bryan,

Thanks for the clarification! I'm closing the Issue as not applicable to Business Central.

**Comment by devman2k** [comment]
Ok but strange. As the page I was commenting on was on CRM. Not BC.
Thanks
Bryan
