### ISSUE TITLE
Does not show up in search

### ISSUE THREAD

**Issue by JustinDouglas** [MicrosoftDocs/dynamics365smb-docs#59]
as of the Oct 18 release searching for "Responsibility Centres" does not pull up any results except links to documentation.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca132c7d-57bc-930e-c178-a68a650c5190
* Version Independent ID: 76de9554-5667-ef83-6401-54d9b415a8bb
* Content: [How to Work with Responsibility Centres - Business Central](https://docs.microsoft.com/en-ca/dynamics365/business-central/inventory-responsibility-centers)
* Content Source: [business-central/inventory-responsibility-centers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-responsibility-centers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
This is a known issue that will be fixed in the December update. 

Going forward, please do not use documentation feedback to report product issues.
