### ISSUE TITLE
Komische Übersetzung

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#592]
In Business Central heißen die Arten auf der Artikelkarte **Bestand**, **Service** und **kein Bestand**. In Doku steht stattdessen **Lagerbestand**, **Nicht-Lager** und **Dienst**. Die letzten Beiden sind verwirrend. Dies sollte korrigiert werden. 
Weiterhin steht in der Tabelle bei **Nicht-Lager** bei einige Optionen "Nr." statt "Nein".

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: ea248ae7-d4ca-5879-0785-d097f3250b5a
* Version Independent ID: adefc344-0777-caa6-7052-416302d9dbb8
* Content: [Artikel-Arten verstehen - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/inventory-about-item-types)
* Content Source: [business-central/inventory-about-item-types.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/inventory-about-item-types.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by jowilco** [comment]
@DanielGoehler
Vielen Dank für Ihr Feedback. Wir ermitteln die Ursache für dieses Problem.

**Comment by jowilco** [comment]
@DanielGoehler 
Vielen Dank für Ihr Feedback. Wir haben die Übersetzungen aktualisiert, und die aktualisierten Übersetzungen sind live. Dieses Problem wird geschlossen.
