### ISSUE TITLE
Bilder veraltet

### ISSUE THREAD

**Issue by DanielGoehler** [MicrosoftDocs/dynamics365smb-docs#595]
Die Bilder in diesem Artikel sind alle auf Englisch und stammen aus NAV 2013. Diese sollte aktualisiert und übersetzt werden.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 9e6c90a8-22c7-8572-195c-b77237a765e8
* Version Independent ID: ebae59fd-cb1e-1da4-80d3-b5afaf712df8
* Content: [Buchungsdatum auf Wertposten - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/design-details-inventory-adjustment-value-entry-posting-date)
* Content Source: [business-central/design-details-inventory-adjustment-value-entry-posting-date.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/design-details-inventory-adjustment-value-entry-posting-date.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! We do not supply translations for illustrations. I agree with you that the dates shown are pretty old, but the information is still valid.

**Comment by DanielGoehler** [comment]
Hi @edupont04, how about transferring the table images to markdown tables?

**Comment by edupont04** [comment]
Hello Daniel,

That's a good suggestion! I've added it to our backlog, but I cannot promise when we'll get the work done.

**Comment by edupont04** [comment]
Hello Daniel,

The English source for this particular article is now updated so that the data is translatable: https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-inventory-adjustment-value-entry-posting-date

It will be available in German end of August. I'm closing the Issue as fixed since the translated version will be published (almost) automatically.
