### ISSUE TITLE
Requisition worksheet

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#599]
The requisition worksheet can carry out action messages. What do each of these messages do?
For example what does cancel do? I cannot see any help info on docs.

Thank you

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe3e2d1-8867-002b-c5c0-5492417adea4
* Version Independent ID: 635ff905-4ff7-49b2-df5a-cdb1143dcae8
* Content: [About Planning Functionality - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/production-about-planning-functionality#requisition-worksheet)
* Content Source: [business-central/production-about-planning-functionality.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/production-about-planning-functionality.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

Thank you for your feedback! We'll add a link to the description of action messages to the table of contents in the next doc update. Action messages part of MPS/MRP and are explained here: https://docs.microsoft.com/en-us/dynamics365/business-central/production-how-to-run-mps-and-mrp

**Comment by edupont04** [comment]
Now live.
