### ISSUE TITLE
Managing Projects with Jobs

### ISSUE THREAD

**Issue by rbaadhio** [MicrosoftDocs/dynamics365smb-docs#6]
The app seemed easy to work with and to initiate the workflow and computation of hours and company resources.
It is hard to bring oneself to break down the pricing, and so forth due to the strongly held beliefs in assisting noble work. Nevertheless, we have come to a pricing in the $99,980 to cover immediate costs for office supplies, car, transportation, and hourly wages, health benefits, trips, meetings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 850880b4-15c7-9760-17c5-b723b9b2b17f
* Version Independent ID: b52bcf7c-1126-b2ab-c8bc-29c29f851e27
* Content: [Walkthrough - Managing Projects with Jobs - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/walkthrough-managing-projects-with-jobs#feedback)
* Content Source: [business-central/walkthrough-managing-projects-with-jobs.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/walkthrough-managing-projects-with-jobs.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Closing this issue since it is not related to the docs.
