### ISSUE TITLE
Cannot see the 'Bal account type' and Bal account no' fields

### ISSUE THREAD

**Issue by SabinaFazal** [MicrosoftDocs/dynamics365smb-docs#60]
I am trying to follow the process to do a bank to bank transfer, but cannot see the fields 'Bal account type' and Bal account no' fields on the journal.
I am using a daily journal from general ledger.

Can you please provide more information as to how where these fields are?

Thanks,

Sabina

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43d90372-bad0-e14f-e4f4-365631740cdf
* Version Independent ID: 0a791a84-fe8c-f65c-a9fd-b58b00af9f78
* Content: [Transfer Bank Funds - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/bank-how-transfer-bank-funds)
* Content Source: [business-central/bank-how-transfer-bank-funds.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/bank-how-transfer-bank-funds.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Hi SabinaFazal,

Thanks for reaching out about this! Some of the fields in your journal are hidden from the default view. In order to see those two fields, you can choose the "Show more columns" action. If you can't see that action, then it's hiding under the "Page" menu item in the navigation bar.

**Comment by SorenGP** [comment]
The topic has been updated. See step 6 in the first procedure.
