### ISSUE TITLE
Incorrect steps to review a posted bank rec

### ISSUE THREAD

**Issue by JennReinhardt** [MicrosoftDocs/dynamics365smb-docs#601]
These steps are incorrect for the NA Bank Reconciliation documentation:
To view the posted bank account reconciliations
Choose the Lightbulb that opens the Tell Me feature. icon, enter Bank Accounts, and then choose the related link.
Choose the bank account that you want to view the posted reconciliations for, and then choose the Statements action.
Choose the Close button.

The correct steps are:
1.	Choose the Lightbulb that opens the Tell Me feature. icon, enter Bank Accounts, and then choose the related link.
2.	Choose the bank account that you want to view the posted reconciliations for, and then choose **Related**, then **Bank Acc.**, and finally select **Posted Reconciliations**.
 
3.	Select the Statement No. to view and you should be taken to an exact copy of the Bank Rec Worksheet.
4.	Choose Print/Send and make your details selections in the report options page. The bank rec test report that was printed prior to posting will be printed again.  This can then be used for auditing purposes.
 
5.	X out of the report to close the report.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d479e5cc-ce54-8e11-3949-65ed6043671b
* Version Independent ID: 4f8582f6-e7fe-c08f-6422-ed0b67cff78b
* Content: [Reconciling Bank Accounts \[US\] - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedstates/how-to-reconcile-bank-accounts)
* Content Source: [business-central/LocalFunctionality/UnitedStates/how-to-reconcile-bank-accounts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/UnitedStates/how-to-reconcile-bank-accounts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello Jenn,
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by edupont04** [comment]
Now live.
