### ISSUE TITLE
Status Definitions

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#602]
I cannot find any documentation on the status of sales order and purchase orders.

For Example in the Sales Order the status can be either Open, Cancelled or Released. What other status are available also where else can Status be used? Purchase Orders?

I want to suggest that more status are created but I cannot see a list of statuses. I will create a BCideas for more statuses.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f842e9d-aa0b-1b1c-c6be-dfac6730e393
* Version Independent ID: 5ba6fbd0-487c-c742-9acc-8b120c9337ff
* Content: [Using General Functionality Across Business Areas - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-across-business-areas)
* Content Source: [business-central/ui-across-business-areas.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-across-business-areas.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

Thank you for your feedback! The product has many fields with the name Status, and they fall into a couple of different "types" of status, depending on the type of page that the field is on.

Specifically for documents such as sales orders/purchase invoices/other sales and purchasing documents, the Status field has 4 values in the base application: Open, Released, Pending Approval, and Pending Prepayment. These are somewhat explained in the tooltip for the field. Those 4 values support two fairly common workflows in many businesses, namely document approval (you can only post the invoice after XYZ has signed off on it) and prepayments (don't ship the products until the agreed-upon prepayments have been registered). There is a lot of business logic hinging on this field for documents to test that the document is in the right "state" before being processed. 

Different ISVs may have extended the Status field to support other workflows, and you can extend it yourself with a customer-specific or app-specific extension, for example.

The many other Status fields in the base product have different logic around them but typically don't fall into a collective bucket like the Status fields on documents.
As for suggesting we add more states, I'll leave that to the engineering team to process.
