### ISSUE TITLE
Typo - "...you must first create G(L budgets"

### ISSUE THREAD

**Issue by pholding** [MicrosoftDocs/dynamics365smb-docs#605]
There is a typo in the second paragraph - "To analyse budgeted amounts, you must first create G(L budgets" should be "To analyse budgeted amounts, you must first create G/L budgets"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f772a75e-f627-c535-d805-abfab9780b44
* Version Independent ID: 2026edcb-202e-3c72-5ceb-dd19afe5ce87
* Content: [Analyse Actual Versus Budget - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/bi-how-analyze-actual-versus-budget#feedback)
* Content Source: [business-central/bi-how-analyze-actual-versus-budget.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/bi-how-analyze-actual-versus-budget.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by jowilco** [comment]
@pholding 
Thanks for your feedback. We have updated the en-gb page, and the updated page is live. Closing this issue.
