### ISSUE TITLE
How does this resolve dimensions in subledger

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#606]
This option to update dimensions is fantastic but what is the process to update the subledger posting? 
Otherwise what's the benefit of changing the dimension? Seems like it makes the dimensions even more messed up.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9abcd6f5-c62a-9266-0f21-3812b2057549
* Version Independent ID: b0ad0720-b45f-9038-230a-2be0f6452d5b
* Content: [Troubleshooting and Correcting Dimensions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-troubleshooting-correcting-dimensions)
* Content Source: [business-central/finance-troubleshooting-correcting-dimensions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/finance-troubleshooting-correcting-dimensions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello Ben,
Thank you for your feedback. This new capability is supposed to handle that for you. The troubleshooting content is there just in case something goes wrong, perhaps due to how that particular chart of accounts is set up, for example. If you find that your dimensions get messed up, I suggest you contact support.

**Comment by makdaddy8888** [comment]
Hi Eva

Maybe I didn’t explain well enough.

MS created a way to change the dimensions incase you want to make some changes to the dimensions that you initially setup. This feature  allows for the dimensions to be updated. However the subledger entries do not get changed and they stay the way they were originally set to.
In other words this feature doesn’t go deep enough into the chart of account to make effective dimensional changes.

Kind Regards
Ben

**Comment by edupont04** [comment]
Hi Ben,
Thank you for your explanation. Since the team is on summer vacation, I can't provided additional insights. You might want to make a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
