### ISSUE TITLE
how often does BC get updated

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#607]
can you add this FAQ to the refence page on the latest Wave release?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2c52232-916f-f918-1ee2-86cd6fdbacf0
* Version Independent ID: 2f07a9a9-4cf3-c835-29d0-aab1c830277c
* Content: [FAQ About Using Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-faq)
* Content Source: [business-central/across-faq.yml](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/across-faq.yml)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Ben,
Thank you for your feedback! We'll get that added in the next update.
