### ISSUE TITLE
how to find blank fields

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#608]
can you share how to find where a field contains no data?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff6c864c-65d2-2e71-7892-f4ce2b333f01
* Version Independent ID: 54110362-c3dd-165a-1d27-1b1a2cde6e8e
* Content: [About Searching and Filtering in Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-search-filter-faq)
* Content Source: [business-central/ui-search-filter-faq.yml](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-search-filter-faq.yml)
* Service: **dynamics365-business-central**
* GitHub Login: @mikebcMSFT
* Microsoft Alias: **mikebc**

**Comment by jill-kotel-andersson** [comment]
Hello,

to filter on empty fields, just enter two single quotes as the filter value for that field. I hope this answers your question.

![image](https://user-images.githubusercontent.com/56507949/129175144-f2f2c12f-f631-468c-93d4-f4abc88b8462.png)

**Comment by jill-kotel-andersson** [comment]
This will be fixed in the next doc update.

**Comment by edupont04** [comment]
This is now explained here: https://docs.microsoft.com/en-us/dynamics365/business-central/ui-enter-criteria-filters#-an-exact-character-match
