### ISSUE TITLE
Missing Report on this page 

### ISSUE THREAD

**Issue by PWWaugh** [MicrosoftDocs/dynamics365smb-docs#609]
No Report to Print ! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 654fee36-121f-57b0-3cf6-8e98a5877874
* Version Independent ID: 1e10af6b-512f-ed35-6356-503155a19f79
* Content: [Print Bank Account Reconciliation Reports - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/australia/how-to-print-bank-account-reconciliation-reports)
* Content Source: [business-central/LocalFunctionality/Australia/how-to-print-bank-account-reconciliation-reports.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/Australia/how-to-print-bank-account-reconciliation-reports.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by jill-kotel-andersson** [comment]
Hello,

Thank you for your feedback. Since your question is not about the Help, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).
