### ISSUE TITLE
This is not at all helpful. 

### ISSUE THREAD

**Issue by NZJulie** [MicrosoftDocs/dynamics365smb-docs#61]
This is not at all helpful.  Details of what goes into each field is needed.
I have entered in rates, but when I enter invoices they are not being converted!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cbd815c-4e94-b21d-dbfa-411885d4a5dd
* Version Independent ID: f4aced3d-7e1c-6486-f8dc-7749cc9ddd12
* Content: [Updating Currency Exchange Rates - Business Central](https://docs.microsoft.com/en-NZ/dynamics365/business-central/finance-how-update-currencies)
* Content Source: [business-central/finance-how-update-currencies.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-how-update-currencies.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi NZJulie,
I'm sorry to hear that you don't find the content helpful. We don't provide detailed information about the individual fields in the docs, but you should be able to find information about each field in the tooltips that are part of the product.
For the currency exchange rates to kick in when you create invoices, you can either set up an exchange rate service and enable it in the **Currency Exchange Rate Services** page, or you can set up exchange rates manually in the **Currencies** page. Then, you can assign currency codes to your customers and vendors. Business Central will pick up the rates depending on your settings. 

If you find that the product does not respond to your set up, please contact your Dynamics 365 reselling partners. If you don't have a reselling partner yet, you can find one on the [Solution Providers website](https://www.microsoft.com/en-gb/solution-providers/home).
