### ISSUE TITLE
What doe SmartList Permissions do?

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#610]
On the Permissions page 9850 there is a SmartList function. What does this do?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b3149c9-3ef3-9b86-722b-b006a501263c
* Version Independent ID: 2331d586-dda8-ad98-0c75-d96245d56a45
* Content: [Define Granular Permissions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-define-granular-permissions)
* Content Source: [business-central/ui-define-granular-permissions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-define-granular-permissions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Ben,

In some versions of Business Central, the SmartList Designer Permissions action opens a view where you can see which query objects created by SmartList Designer users need to access, so you can set up the related permissions in permission sets that you can assign to the users of the database.
The SmartList Designer is deprecated now, though.
