### ISSUE TITLE
Ereignismeldung: Abbrechen

### ISSUE THREAD

**Issue by AJasp** [MicrosoftDocs/dynamics365smb-docs#611]
Die Ereignismeldung "Abbrechen" (DE-Version) ist in diesem Hilfeartikel nicht beschrieben.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: cab5a2e2-4760-d1d5-218b-be5bce80a715
* Version Independent ID: b1a80fd4-85ad-a6c0-37f8-59f20dfe6acf
* Content: [So führen Sie Gesamtplanung, MPS und MRP aus - Business Central](https://docs.microsoft.com/de-DE/dynamics365/business-central/production-how-to-run-mps-and-mrp)
* Content Source: [business-central/production-how-to-run-mps-and-mrp.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/production-how-to-run-mps-and-mrp.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by jill-kotel-andersson** [comment]
Hello,

Thank you for your feedback! We are looking into this.

**Comment by AJasp** [comment]
Hello,
thank you for your reply. 
I think that this is a translation error in the application (DE). Until now the options were named as they are documented in the docs.
Best Regards
Andreas

**Comment by jowilco** [comment]
@AJasp 
Thank you for the feedback. The UI and documentation has been made consistent:
Stornieren instead of Abbrechen
Neu planen instead of Neu berechnen

Note that the documentation changes are live and the UI changes will be visible with the next release.
