### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by pholding** [MicrosoftDocs/dynamics365smb-docs#612]
The section titled "To block shipments for unpaid prepayment" says to select "Cheque Prepayment when Posting" however this should be "Check Prepayment when Posting" as per the application. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67b3b756-7c2f-1312-1411-d0cb4de16f92
* Version Independent ID: 94035023-12a4-b335-1f90-9f3e7eee2f1a
* Content: [Setting Up and Invoicing Sales Prepayments - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/walkthrough-setting-up-and-invoicing-sales-prepayments)
* Content Source: [business-central/walkthrough-setting-up-and-invoicing-sales-prepayments.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/walkthrough-setting-up-and-invoicing-sales-prepayments.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by jill-kotel-andersson** [comment]
Hello,

Thank you for your feedback! This will be fixed in the next doc update.

**Comment by jowilco** [comment]
@pholding 
Thank you again for the feedback. The fix is now live.
