### ISSUE TITLE
Permissions for UNinstalling extensions

### ISSUE THREAD

**Issue by Jeeve65** [MicrosoftDocs/dynamics365smb-docs#614]
Although I think it is implied, this page specifies that a user needs specific permissions for installing apps, but nothing is mentioned about which permissions a users needs for UNinstalling apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18ef22cd-6149-41b4-1743-df71dcb66d21
* Version Independent ID: a7c6922c-ccce-fb75-9ada-a4ff7def845c
* Content: [Installing and Uninstalling Extensions in Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-extensions-install-uninstall)
* Content Source: [business-central/ui-extensions-install-uninstall.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-extensions-install-uninstall.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by brentholtorf** [comment]
Hello, 

Installing and uninstalling extensions requires the same permissions. We'll update the article shortly to clarify that. Thanks for pointing this out.
