### ISSUE TITLE
reclassification of item variance

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#617]
Hello 

I notice that the reclassification report does not allow you to reclassify item using item variance.

eg. 1000 items in blue to be reclassified as 1000 items as variance black.

Can you please update this section or confirm if the reclassification report is not to be used for variance.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb507d22-6552-6b8f-212c-8aca352eb526
* Version Independent ID: 733f44f8-c3c4-78cb-f578-306963b6d9a2
* Content: [Count, Adjust, and Reclassify Inventory - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/inventory-how-count-adjust-reclassify)
* Content Source: [business-central/inventory-how-count-adjust-reclassify.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/inventory-how-count-adjust-reclassify.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Ben,

Thank you for your feedback! You can use the item reclassification journal to change item tracking. You can:

- Change lot or serial numbers.
- Create or modify lot or serial number information.
- Reclassify expiration dates for lot or serial numbers.

But the item reclassification journal does not support variants. If you want to get that added to the product, I suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
