### ISSUE TITLE
Type

### ISSUE THREAD

**Issue by joemarselo** [MicrosoftDocs/dynamics365smb-docs#62]
written: Assemply Output. it should be Assembly Output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea248ae7-d4ca-5879-0785-d097f3250b5a
* Version Independent ID: adefc344-0777-caa6-7052-416302d9dbb8
* Content: [Understanding Item Types - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/inventory-about-item-types)
* Content Source: [business-central/inventory-about-item-types.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/inventory-about-item-types.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thanks - I have fixed the typo. Will be out in approx one week.
