### ISSUE TITLE
Forward Exchange Contracts FEC

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#622]
Can  you pleawe create a new section on how BC can help business manage FEC [see here](https://www.investopedia.com/terms/f/forward-exchange-contract.asp)
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41d13b69-88a5-8a95-d90b-0d4051683eb5
* Version Independent ID: 2b7e8965-3e0f-7c7f-988c-992a0f85b57d
* Content: [Reconcile Bank Accounts and Apply Payments - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/receivables-apply-payments-auto-reconcile-bank-accounts)
* Content Source: [business-central/receivables-apply-payments-auto-reconcile-bank-accounts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/receivables-apply-payments-auto-reconcile-bank-accounts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is about a scenario not currently supported in our docs, and potentially also not by the product itself, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)

**Comment by makdaddy8888** [comment]
Hi Eva

This is a supported feature Nav has been able to do this in the past. It’s just not documented 

Kind Regards
Ben Opit
+61411707070
