### ISSUE TITLE
Correction on customer type

### ISSUE THREAD

**Issue by mlathouwers** [MicrosoftDocs/dynamics365smb-docs#625]
Business Central contact filter: Type is Person and the contact is assigned to a company. Dataverse contact filter: The contact is assigned to a company and the parent customer type is **Account**

Last word should be **Customer** in stead of **Account**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf4cd40b-ac70-ebb4-aca9-dea6ad6bf2f8
* Version Independent ID: ab3ea9a9-83cc-2367-2e48-eb298f03d0c1
* Content: [Synchronization and Data Integration - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-synchronizing-business-central-and-sales#standard-table-mapping-for-synchronization)
* Content Source: [business-central/admin-synchronizing-business-central-and-sales.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/admin-synchronizing-business-central-and-sales.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by brentholtorf** [comment]
Hello

Thanks for pointing this out. The topic has been corrected and the update will be published soon.
