### ISSUE TITLE
Opportunity job missing?

### ISSUE THREAD

**Issue by mlathouwers** [MicrosoftDocs/dynamics365smb-docs#626]
Shouldn't there be a row in the table that mentions the sync of opportunities?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2957b832-9aee-e050-b034-7f3badb2e27c
* Version Independent ID: a93b51b9-9a52-c8a2-2197-38c02f2e327f
* Content: [Integrating with Dynamics 365 Sales - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-prepare-dynamics-365-for-sales-for-integration)
* Content Source: [business-central/admin-prepare-dynamics-365-for-sales-for-integration.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/admin-prepare-dynamics-365-for-sales-for-integration.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by brentholtorf** [comment]
Hello,

Thanks for pointing this out. The section titled Standard Sales Entity Mapping for Synchronization mentions the mapping for opportunities and the sync directions.
