### ISSUE TITLE
link to mkt material

### ISSUE THREAD

**Issue by jaybeegee66** [MicrosoftDocs/dynamics365smb-docs#627]
helllo

I think it would be useful to add a link to the marketing docuementation/product leaflet of the HR module in BC?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaf3e258-8176-f91f-2631-b68017b12866
* Version Independent ID: b70573b8-977b-1cf3-72c9-eaafdbe38615
* Content: [Using Human Resources Functionality - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/hr-manage-human-resources)
* Content Source: [business-central/hr-manage-human-resources.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/hr-manage-human-resources.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! We do not usually refer to marketing material in the docs. If you disagree with our decision, you can submit a documentation request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
