### ISSUE TITLE
request approval limit

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#628]
I understand what the sales and purchase order limit does. Can I check what this "Request Approval Limit"feature does?

Request Amount Approval Limit this is in Approval User Setup page. 

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9e8ecd4-7b52-27d1-5959-9ba0b039849e
* Version Independent ID: 51b0b66a-7468-fb4b-7732-3793d6159a9d
* Content: [Approve or Reject Documents in Workflows - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/across-how-use-approval-workflows)
* Content Source: [business-central/across-how-use-approval-workflows.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/across-how-use-approval-workflows.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,

As the tooltip for the field says, this field "Specifies the maximum amount in $ that this user is allowed to approve for this record." I can add that the Dynamics NAV docs also say that "To use this field, you must select the Approver Chain option in the Approver Limit Type field in the Workflow Responses window.". I'll get something along those lines added to the article.

**Comment by edupont04** [comment]
Oops, I now see that we already have this information: https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-to-set-up-approval-users
Closing as question answered.

**Comment by makdaddy8888** [comment]
Hi Eva

Is there some way I can see what changes have been made to the help docs. This way I can also learn what changes ms are making to the docs? Good way for me to continue to improve my knowledge. Learn as it changes.

Kind Regards

**Comment by edupont04** [comment]
Hi Ben,

We have a pretty basic RSS feed set up that you can read about here: https://docs.microsoft.com/en-us/dynamics365/business-central/index#get-notified-about-changes-through-an-rss-feed
It has some limitations, though, but it's the best we can do at this point in time.

**Comment by makdaddy8888** [comment]
Hi Eva

How come the RSS doesn’t have the most recent topics?





Regards

Ben Opit
0411707070
