### ISSUE TITLE
Objetos en Business Central

### ISSUE THREAD

**Issue by SistemasHernan** [MicrosoftDocs/dynamics365smb-docs#63]
[Escribir comentarios aquí]
Buenas tardes, me gustaría hacer una consulta referente a los objetos en Business Central, ¿Existe alguna pagina donde pueda encontrar una lista de todos los objetos con la descripción de cada uno de ellos?, deseo desarrollar una extensión y me gustaría saber que objetos son los que tendría que extender les su funcionalidad. 

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ vinculación de problemas de GitHub.*

* ID: 6b86d301-cf03-0dd0-abdd-9a73743b4285
* Version Independent ID: 4e4d4219-2c2f-0324-6166-414f31158224
* Content: [Microsoft Dynamics Business Central - Business Central](https://docs.microsoft.com/es-MX/dynamics365/business-central/index)
* Content Source: [business-central/index.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/index.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Help on Docs for Business Central is conceptual and procedural only, so does not have systematic descriptions of objects. However, the (retired) Help for NAV 2016 has topics for windows, tables, reports, and batch jobs: https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/hh174014(v%3dnav.90)

Reading descriptions of all object types in Business Central is only possible by "reading the code". If you would like a better way to read descriptions of all objects, you can suggest it as a feature improvement on the Ideas site. Choose the **Product feedback** button in the help topic.
