### ISSUE TITLE
Prepayment roundings.

### ISSUE THREAD

**Issue by averied** [MicrosoftDocs/dynamics365smb-docs#638]
I follow the steps for Invoice prepayment, but there is an issue and it's not documented how to solve it. 

If you create invoice lines from multiple shipments, the prepayment amount is distributed among the lines. 

For example, say you created a sales order, and made a prepayment for 700 euros, and posted 3 partial shipments of one item. 

Now you create an Sales invoice, and create 3 Invoice Lines from the shipments.  Each line is assigned 233,33 for prepayment amount. So when you try to post the Invoice, it throws an error saying that Prepayment Amount should be 700 (If you sum the lines, the amount is 699,99)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: debdb0f8-6908-8250-8388-1e52d0f0516a
* Version Independent ID: 1c28a769-8d50-02e8-fcb6-edf25c0a64f7
* Content: [Invoice Prepayments - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-invoice-prepayments)
* Content Source: [business-central/finance-invoice-prepayments.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/finance-invoice-prepayments.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi @averied 

My apologies for the delay in getting this verified, but you can personalise the Sales Order page to add the Prepayment % or Prepayment Amount field to the lines. That way you get control over the distribution. For more information, see this article: https://docs.microsoft.com/dynamics365/business-central/ui-personalization-user

I'll add a tip to the Prepayments content to point this out.

![image](https://user-images.githubusercontent.com/12425349/144439404-c5960c57-fca4-4343-be4f-6a5da1690b86.png)

**Comment by edupont04** [comment]
Closing as fixed.
