### ISSUE TITLE
Replenishment System

### ISSUE THREAD

**Issue by rtigithub** [MicrosoftDocs/dynamics365smb-docs#64]
There does not appear to be any documentation or explanation for the Replenishment System field of the item card.  The word "replenishment" does not produce any results in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cc0f224-e957-d1a0-1217-200eab95871b
* Version Independent ID: b33066c0-6c04-815b-1487-be70a66491bd
* Content: [Design Details - Assembly Order Posting - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/design-details-assembly-order-posting)
* Content Source: [business-central/design-details-assembly-order-posting.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-assembly-order-posting.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Hi - I get 11 hits when I search for "replenishment system". Go here: https://docs.microsoft.com/en-us/search/index?search=%22replenishment+system%22&scope=BusinessCentral

The best topic for the Replenishment System field is probably this one: https://docs.microsoft.com/en-us/dynamics365/business-central/production-how-to-plan-for-new-demand.

Soren, Business Central writer

**Comment by rtigithub** [comment]
So if I click on Help and then search on replenishment no results are found in the BusinessCentral documentation.
[cid:image007.png@01D4810B.1CFB4680][cid:image008.png@01D4810B.1CFB4680]

Bob Voigt (bobv@restechimage.com<mailto:bobv@restechimage.com>)
Technical Support (support@restechimage.com<mailto:support@restechimage.com>)
Resolution Technology, Inc.
Woman-Owned Small Business
614.791.0045
[halcon_logo_and_slogan_small]  [MPNlogo]   [cid:image003.png@01D407E2.1E9B13F0]   [_2018_Program_Badge_(English_-_US)_12_27_2017]
