### ISSUE TITLE
Hybrid Exchange support

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-docs#640]
Hi, on the page there is note that 
```
We do not support hybrid scenarios, such as connecting Business Central online to an on-premises version of Exchange
```
But what about support for BC Online/OnPrem and Exchange onprem in Hybrid configuration? (Exchange Online with mailboxes hosted on Exchange onprem). Is this scenario supported? What I know, the Graph API should be able to forward the requests to onprem exchange when needed and configured correctly. Is it true?

Customers are asking...

Thanks!
Kamil Sacek
MVP for Business Apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0171dfbc-61f2-e62e-f4a3-bb641b15c3e2
* Version Independent ID: 51deab1e-0243-3178-7640-01bb91591fca
* Content: [Set up email in Business Central - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/admin-how-setup-email)
* Content Source: [business-central/admin-how-setup-email.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/admin-how-setup-email.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello Kamil,

Thank you for your feedback! I agree that it's a bit confusing, but the wording that you highlight is specifically for connecting Business Central online to Exchange Server on-premises, which is not supported. Later in the same article, you can see how Business Central on-premises can connect to Exchange Online: https://docs.microsoft.com/en-US/dynamics365/business-central/admin-how-setup-email#setting-up-email-for-business-central-on-premises

**Comment by kine** [comment]
Hi Eva,
yes, but it is not clear, if Exchange onprem in Exchange Hybrid configuration is supported or not. I am not sure if I can say that Exchange online="Exchange onprem in Hybrid config" (where Exchange onprem servers exists and are connected with Exchange online, but the mailboxes are hosted onprem)... that's what I want to clear up.

**Comment by edupont04** [comment]
Hi Kamil,
Theoretically it would work, but it's an edge scenario as far as I know. There are some notes in this Exchange article that could be interpreted as problematic for your customers: https://docs.microsoft.com/en-us/exchange/transport-routing

In our own article, it's not a supported scenario. If you want confirmation that it either is or not, I suggest you use the Technology group in Yammer. I'm going to close this Issue as not (really) about the docs.

**Comment by kine** [comment]
Thanks Eva, knowing that it is "edge" scenario and that it is "not supported" is info for me, which I can use. I understand.
Thanks!
