### ISSUE TITLE
Depreciate books

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#641]
Hello

Can you add some more details and a link on deprecation books options and benefits as well as in the details on the Depreciation Book field "Allow changes in Depr. Fields" and how that can help people achieve desired outcomes.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1a279f-a7ce-8cc9-c479-9c32d858bb8e
* Version Independent ID: 45db169a-85d9-081c-d3de-25f6c04022ae
* Content: [Manage Fixed Assets - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/fa-manage)
* Content Source: [business-central/fa-manage.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/fa-manage.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,
Thank you for your question! The trick is to set up depreciation books to match your company's requirements. Once the depreciation books are defined, you don't have to think about it again, so to speak. For more information, see https://docs.microsoft.com/en-us/dynamics365/business-central/fa-how-setup-depreciation

**Comment by makdaddy8888** [comment]
Hi Eva

I was seeking more help documentation on each of the 13 Boolean options like substract discont, allow changes in depreciation book, allow indexation etc. seems there a whole section that’s not documented 

Kind Regards
Ben Opit
+61411707070
