### ISSUE TITLE
Item type for warranty, licenses etc.

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/dynamics365smb-docs#643]
Regarding the recent Business Central updates, please update this page, with cooperation from product group.
It should be clear, which Item Type should be used for line items, such as "warranty service, software license, software subscription etc.". Since these are not physical items, and instead are services, but you can also resell them and inventory tracking could be on etc.

Recent BC updates did implement new features regarding mentioned situation/scenarios, so please update the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea248ae7-d4ca-5879-0785-d097f3250b5a
* Version Independent ID: adefc344-0777-caa6-7052-416302d9dbb8
* Content: [Understanding Item Types - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/inventory-about-item-types)
* Content Source: [business-central/inventory-about-item-types.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/inventory-about-item-types.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

Thanks for your feedback. It sounds like you want to use lot or serial numbers to track non-inventory items. Unfortunately, that isn't supported right now, but it's an excellent idea for a new feature. Please go to aka.ms/bcideas and create a feature request so that it gets on the product team's radar.

**Comment by hkusulja** [comment]
Hello, please reopen this here, since this is not the case and it is not a new feature request, instead this is asking for documentation clarification. Since there were existing BC updates, i believe information is wrong, so please check and fix.

So, in a documentation table on page, regarding the column - Location Transfer. I believe, after BC update (v19) it is supported now to have non-inventory items put to a location and use location transfer. I am also not sure, but think it is possible already to use Inventory Revaluation, Inventory costing, for non-inventory and service item types.

Also, if you can put in example / typical purpose, where should be the real use case scenario for the "warranty service, software license, software subscription etc.), since this is a common question from various BC customers and partners - what is Microsoft recommendation and suggestion to use which Item type?

**Comment by brentholtorf** [comment]
Hello,

The type depends on whether you want to use the full range of inventory features for the item, or whether a smaller subset will do. The table in the article shows a matrix of which to use, and when. But you make a good point, and we can provide a text example to help people understand the table. Stay tuned.

**Comment by hkusulja** [comment]
Ok, any info for the updating, with requested example.
Items that needs to be tracked (purchase, sales, stock (by location?)) that are services used for resalling, such as IT services - Microsoft 365 subscriptions, Adobe subscriptions, Some IT warranty / service support service SKU's / Items etc.
Where to put them, since they are not physical items, but needs to have tracking (and possible Item tracking / serial number etc.)

**Comment by brentholtorf** [comment]
Hello,

I've been in contact with the subject matter expert, and he says that the table is correct. If you want to track non-physical items such as software licenses, you should use the Inventory type. We've updated the descriptions of the three item types.

**Comment by hkusulja** [comment]
But those are not physical items, like warranty, or software subscriptions etc..
I understand workaround is to put it to inventory, but this is not proper solution.
For example, regulatory in EU specifies the inventory as physical goods (including software on physical CD), but software as a subscription is a service and is not inventory.

**Comment by brentholtorf** [comment]
Very true, but that's the way it works right now. I suggest that you go to our [Ideas List](https://experience.dynamics.com/ideas/categories/list/?category=50db8819-83ed-e611-8105-5065f38a3bb1&forum=e288ef32-82ed-e611-8101-5065f38b21f1) and request the improvement. I'm sure that a lot of other people would also want the ability to use lot or serial number tracking for non-inventory items.

**Comment by edupont04** [comment]
Closing the Issue as non-actionable.
