### ISSUE TITLE
Versandmethoden einrichten

### ISSUE THREAD

**Issue by MacGnol** [MicrosoftDocs/dynamics365smb-docs#644]
Auf der Seite wird als Tipp die Einrichtung von Versandmethoden für Incoterms empfohlen. Bitte eine Verlinkung dazu einfügen für mehr Details.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: e7e4fe92-e8b5-6363-229c-4a4804caa919
* Version Independent ID: 21d9cfce-d3f5-18a8-5a8d-6f1cfe56ac31
* Content: [Lieferbedingungen einrichten - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/sales-how-set-up-shipment-methods)
* Content Source: [business-central/sales-how-set-up-shipment-methods.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/sales-how-set-up-shipment-methods.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! the article in question includes a link to the definition of Incoterms at https://iccwbo.org/resources-for-business/incoterms-rules. This is as close as we can get to explaining Icoterms.
