### ISSUE TITLE
Datos fiscales eliminados de la ultima actualización (URGENTE)

### ISSUE THREAD

**Issue by QingqiongHu** [MicrosoftDocs/dynamics365smb-docs#649]
Hola, con la ultima actualización ahora las notas de abono no incluyen el numero de factura rectificada ni el CIF/NIF del cliente. Estos campos son datos fiscales obligatorios en España. ¿Hay forma de recuperar estos campos? Gracias!

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 9da35d1e-cf63-9e8f-11fd-99e23f9c061c
* Version Independent ID: ecb08d58-d4cc-0784-1df4-9a85829a9329
* Content: [Procesamiento de devoluciones de ventas o cancelaciones - Business Central](https://docs.microsoft.com/es-ES/dynamics365/business-central/sales-how-process-sales-returns-cancellations#feedback)
* Content Source: [business-central/sales-how-process-sales-returns-cancellations.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/sales-how-process-sales-returns-cancellations.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
