### ISSUE TITLE
ADD INCLUDE macro not replaced

### ISSUE THREAD

**Issue by TrippyZ** [MicrosoftDocs/dynamics365smb-docs#652]
This page has several occurrences of the text "ADD INCLUDE".  From the positioning it looks that this was a macro that has not been replaced prior to publishing the content
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4eb792f3-7edc-76bd-235b-39f412d1c990
* Version Independent ID: a3a8442a-f3d9-7c4e-a70a-86b3133d562c
* Content: [How to Add Fields to a Word Report Layout - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/ui-how-add-fields-word-report-layout)
* Content Source: [business-central/ui-how-add-fields-word-report-layout.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-how-add-fields-word-report-layout.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We've fixed the article, and the update will be published soon.

**Comment by edupont04** [comment]
Now live.
