### ISSUE TITLE
Mentions of non-existing page "Stock Put-Aways" in Walkthrough: Receiving and Putting Away in Basic Warehouse Configurations

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-docs#653]
This article refers to a page called "Stock Put-Aways", which cannot be found in current GB BC, and for which there are no results in the root folder of the current BC GB 19.1 codebase.

Presumably it should be something else? Please update so that readers finding this guide can actually use it. Thanks ;-)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcd58190-a7af-5bad-48a2-f79fdc89e666
* Version Independent ID: 5c32818d-e08b-8b2d-411f-92bebbd429e1
* Content: [Walkthrough - Receive and put away in basic warehouse configurations - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/walkthrough-receiving-and-putting-away-in-basic-warehousing)
* Content Source: [business-central/walkthrough-receiving-and-putting-away-in-basic-warehousing.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/walkthrough-receiving-and-putting-away-in-basic-warehousing.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! This appears to be a flaw in our translation from English (US) to English (UK). As you can see in our US version, the name of the page was changed to **Inventory Put-Away** a long time ago: https://docs.microsoft.com/en-us/dynamics365/business-central/walkthrough-receiving-and-putting-away-in-basic-warehousing#about-this-walkthrough

I'll ask our translators to change the term in the next round of translations that starts next week.

**Comment by dnpb** [comment]
Thanks :)

**Comment by edupont04** [comment]
This has been fixed in the latest update for English (UK): https://docs.microsoft.com/en-gb/dynamics365/business-central/walkthrough-receiving-and-putting-away-in-basic-warehousing
