### ISSUE TITLE
Directions not clear

### ISSUE THREAD

**Issue by BobZ750** [MicrosoftDocs/dynamics365smb-docs#654]
I need to setup a device but the instructions seem outdated. There is no button to add a group:
![image](https://user-images.githubusercontent.com/95635090/144869479-948b9572-b527-41e8-977a-b842248570ec.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3af56319-74d0-ce95-7f11-48a0b165ed6e
* Version Independent ID: d496d459-af33-c965-a21b-0e2f44d6a2e9
* Content: [Create Users According to Licenses - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-users-permissions#to-create-a-dynamics-365-business-central-device-users-group)
* Content Source: [business-central/ui-how-users-permissions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-how-users-permissions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! I'm not sure what's going on, but if you're the administrator of that Microsoft 365 account, or the delegated admin of the reselling partner, then you should be able to see that button as in the following screenshot from my test account that is based on production code:
<img width="353" alt="image" src="https://user-images.githubusercontent.com/12425349/145050673-bbdbc8e4-35cf-4e80-9a8b-93e7d6723f96.png">
 
If you are the admin and still can't see the button, I encourage you to contact Microsoft 365 support by asking a question in the Help pane (choose the ? in the top right corner of the Microsoft 365 admin center).
