### ISSUE TITLE
WHT for Foreign Suppliers invoicing in foreign currencies

### ISSUE THREAD

**Issue by peteloo** [MicrosoftDocs/dynamics365smb-docs#655]
The WHT calculation is working well for suppliers without ABN and foreign suppliers invoicing in local currencies, as long as the invoice line has WHT Business Posting Group code and WHT Product Posting Group code combination defined in WHT Posting Setup.
However, if the foreign supplier invoices in foreign currencies (e.g. USD) and the invoice lines are in USD cost, the WHT calculation seems to ignore these invoices.
Is it expected to request foreign suppliers to invoice in local currency in order for WHT to be calculated?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a166e1-ae39-9181-9a02-4161a0b68f08
* Version Independent ID: b9a326ea-4540-c407-8a37-c140d132fda8
* Content: [Withholding Tax in the Australian version - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/localfunctionality/australia/withholding-tax)
* Content Source: [business-central/LocalFunctionality/Australia/withholding-tax.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/Australia/withholding-tax.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by peteloo** [comment]
Hi 
Thanks for looking into this.  
I tested WHT calculation in BC using a local vendor (without ABN) and a foreign vendor (USD currency), and purchase invoice lines with items and GL account.
In all instances, the WHT calculation works for the local vendor without ABN, and it is likely that the WHT functionality was developed around this.
If the purchase from the foreign vendor (USD) is denominated in local currency, the WHT will also be calculated on the payment lines which match in local currency - this logic is equivalent to the local vendor without ABN because the base (local) payment currency is used.
If the purchase from the foreign vendor is denominated in foreign currency (USD) and the payment lines match in USD, the WHT calculation will be skipped.
At the moment, my workaround is to either:
1. have all foreign vendors configured with 'blank' (local) currency and set all their foreign invoices with foreign currency code - these are then converted to base (local) currency for WHT calculation (because the 'foreign vendor' card would be similar to a local vendor without ABN)
2. have all foreign purchase invoices updated to local currency for processing WHT.  This also means converting the actual invoice currency to local currency to ensure the correct payment amount.

Do you have the contact channel for technical support to get this WHT calculation reviewed?

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback and more elaborate scenario. I've talked to a couple of people here, and I recommend that you contact technical support and ask them to start what we call a _collaboration request_ with the product team. We need that in order to get the right people to look into your problem. You found a workaround, which is great, but I suspect we need to get engineers to get your scenario to work. 
For more information on how to get in touch with Microsoft Support, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).

**Comment by peteloo** [comment]
Hi
Thanks for the link to report this to the engineers.
A further review of the ATO rules regarding WHT is that it is calculated on local income by non-ABN registered entities or by foreign entities.  This may be assuming that local income is denominated in AUD.
However, a scenario could be royalty payments to a foreign entity that is subjected to WHT.  The foreign entity may invoice in foreign currency, and this scenario may not have been considered.
I'll report this scenario to Microsoft Support.
Thanks
