### ISSUE TITLE
No JSON example

### ISSUE THREAD

**Issue by kine** [MicrosoftDocs/dynamics365smb-docs#66]
I can select JSON format in the definition, but in this document there is no info how to setup JSON import/export functionality. Only XML.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 350ad27c-dd1c-fde6-27a3-faaf9c0c3da1
* Version Independent ID: 704d9728-05d0-c21a-9d68-d23af8fc6457
* Content: [Define how data is exchanged electronically - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-to-set-up-data-exchange-definitions)
* Content Source: [business-central/across-how-to-set-up-data-exchange-definitions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-how-to-set-up-data-exchange-definitions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback
Importing/exporting files of type Json works in the same was as for the three other file types.
I have therefore just updated the "To create a data exchange definition" section to describe Json as the fourth option in the File Type field.
The update will be available in approx. one week.
