### ISSUE TITLE
External Document Number value missing in Register Customer Payment

### ISSUE THREAD

**Issue by peteloo** [MicrosoftDocs/dynamics365smb-docs#660]
The steps to record customer payment against several sales invoices are very clear.
However, one important invoice identification value needed is the External Document Number field (which is usually a manually entered PO number).

This External Document Number field is populated in the Sales Invoice header and can be seen in the Posted Sales Invoice list (table Sales Invoice Header 112), but when the Register Customer Payment is run, the value is not passed over to the corresponding field in this Register Customer Payment list (table Payment Registration Buffer 981).

Can this important piece of payment reconciling data be added to the Register Customer Payment list?

Thanks 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 641c8356-328b-dd30-611b-b491396e9073
* Version Independent ID: 95418530-4ed2-60aa-016f-06b9d4115cbd
* Content: [Apply Payments to Unpaid Sales Documents - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/receivables-how-reconcile-customer-payments-list-unpaid-sales-documents)
* Content Source: [business-central/receivables-how-reconcile-customer-payments-list-unpaid-sales-documents.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/receivables-how-reconcile-customer-payments-list-unpaid-sales-documents.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
