### ISSUE TITLE
Your table of application rules has something weird going on

### ISSUE THREAD

**Issue by Sceptre7** [MicrosoftDocs/dynamics365smb-docs#664]
The table of application rules somehow has picked up BAS labels - for example, for (4) it is showing "Total Amounts Withheld From All Payments (4)" - which has nothing to do with payment application rules at all.

============
Match Confidence | Priority | Related Party Matched | Doc. No./Ext. Doc. No. Matched | Amount Incl. Tolerance Matched
-- | -- | -- | -- | --
High | 1 | Fully | Yes - Multiple | One Match
High | 2 | Fully | Yes - Multiple | Multiple Matches
High | 2A-2B GST Net Amt. (3) | Fully | Yes | One Match
High | Total Amounts Withheld From All Payments (4) | Fully | Yes | Multiple Matches

==============

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c3b01cb-410e-d92a-a439-67c68e9b19b1
* Version Independent ID: 1349d9eb-f806-17eb-6764-0f8c32700eeb
* Content: [Rules for Automatic Application of Payments - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/receivables-how-set-up-payment-application-rules#feedback)
* Content Source: [business-central/receivables-how-set-up-payment-application-rules.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/receivables-how-set-up-payment-application-rules.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! This has been reported to our translation team, and it will be fixed in the next translation update for English (Australia).

**Comment by edupont04** [comment]
Now live.
