### ISSUE TITLE
Is the first section wrong in this article?

### ISSUE THREAD

**Issue by OysteinAker** [MicrosoftDocs/dynamics365smb-docs#667]
[The first section of this article refers to print the report "Omsetningsoppgaven". This report is the old version as far as I can find and is not sorted the same way as the actual file and reporting which is created further down in the article where you describe how to send a VAT report as a file  through the new API ]

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: 095f24ce-ac1a-e58b-d6a3-feabcbe19218
* Version Independent ID: 1f75ef73-2b26-296b-11aa-bf68108ec389
* Content: [Norsk mva-rapportering \[NO\] - Business Central](https://docs.microsoft.com/nb-no/dynamics365/business-central/localfunctionality/norway/norwegian-vat-reporting)
* Content Source: [business-central/LocalFunctionality/Norway/norwegian-vat-reporting.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/Norway/norwegian-vat-reporting.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! You're right that the first section refers to the older report that is no longer relevant for businesses in Norway and replaced by the new electronic format. But the older report is still available in the Norwegian version for some reason. 

We'll get it clarified in the next doc update that you're supposed to use the new format, not the old, starting January 2022.

**Comment by edupont04** [comment]
Now live in English. The translation into Norwegian will happen in 3 weeks.
