### ISSUE TITLE
When do we get more videos?

### ISSUE THREAD

**Issue by jarrodcase** [MicrosoftDocs/dynamics365smb-docs#668]
[Enter feedback here]
Guys this page is fantastic. WHY are you not doing videos with ALL of the articles and if you are, when can we expect them? I can then send clients the URL/link for their reference and it's simple, easy to follow.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f773c52d-84a2-eac7-00a9-b8c24f5dffb7
* Version Independent ID: 5afdc112-18e8-7984-e382-d9b1a3858fa8
* Content: [Link a Sales Order to a Purchase Order for Direct Shipment (contains video) - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/sales-how-drop-shipment)
* Content Source: [business-central/sales-how-drop-shipment.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/sales-how-drop-shipment.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

We're very happy to hear that the videos are helpful. As for when to expect new videos, we typically produce them for selected new features when we deliver a new release. For existing features, we have a backlog that we whittle down as time allows.
