### ISSUE TITLE
pptx availability for videos (https://www.youtube.com/watch?v=r0hukvOlZ18)

### ISSUE THREAD

**Issue by xgaronnat** [MicrosoftDocs/dynamics365smb-docs#669]
Hello,

Where can we find pptx used for readiness videos ?
We need them for training purpose.

Thanks,
Xavier.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: ed34ba95-a843-90b0-dd51-c24023ccd9d2
* Version Independent ID: 43259fda-960d-bd7a-97c6-74f569a54e11
* Content: [Catalogue d’apprentissage Développeurs - Business Central](https://docs.microsoft.com/fr-fr/dynamics365/business-central/readiness/readiness-learning-developers)
* Content Source: [business-central/readiness/readiness-learning-developers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/readiness/readiness-learning-developers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @loreleishannonmsft
* Microsoft Alias: **margoc**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback.

The team behind the videos that are listed in this article have not shared the underlying PowerPoint slides with the community. Instead, they expect you to direct your prospects to this article and to the landing page on the Microsoft Learn site: https://docs.microsoft.com/learn/dynamics365/business-central

I realize that this is not the answer that you expected, so you might want to submit a feature request of type Documentation here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
