### ISSUE TITLE
Availability Cloud versus OnPrem

### ISSUE THREAD

**Issue by Quivelus** [MicrosoftDocs/dynamics365smb-docs#671]
We are extending functionality on Import Code Statements and notice that in the BE version quite a lot of functions still have Scope=OnPrem (see attachments for example functions)
![BusinessCentral_BE_Codeunit_CODAWriteStatements_ScopeOnPrem](https://user-images.githubusercontent.com/36342809/152322261-544a9def-1581-4c18-9dae-34575164d699.png)
![BusinessCentral_BE_Report_ImportCODAStatement_ScopeOnPrem](https://user-images.githubusercontent.com/36342809/152322264-d03c18fa-4d3f-4763-844b-470e9c949667.png)
, while nothing on this page refers to functionality (not) being available in the Cloud or OnPrem. Could you please elaborate? Is this code planned to be cloud-ready soon? Many thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 313c8448-d253-a509-8fc1-9642f2c1de79
* Version Independent ID: 0ba9eae2-239f-ef1e-317f-7a71db443dbd
* Content: [How to Import CODA Statements \[BE\] - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/belgium/how-to-import-coda-statements)
* Content Source: [business-central/LocalFunctionality/Belgium/how-to-import-coda-statements.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/Belgium/how-to-import-coda-statements.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by Quivelus** [comment]
Hi @edupont04 ,

Thank you for those clarifications. I submitted a feature request as proposed (https://experience.dynamics.com/ideas/idea/?ideaid=d16072f4-ee88-ec11-b820-0003ff45e043). Let's hope for some votes 👍 🥇 :-).

**Comment by edupont04** [comment]
Hello again, @Quivelus,

I've just received an update from the engineering team, and they encourage you to submit requests for a change of scope for the relevant methods in the ALAppExtensions repo like this one: https://github.com/microsoft/ALAppExtensions/issues/16131

This way, they suggest, you'll get your extension running faster. Our very best wishes from the Business Central engineering team!
