### ISSUE TITLE
Tax Clauses ?

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/dynamics365smb-docs#672]
Please document functionality for table "Tax Clauses" when and how to use it.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af8e82f4-8ef0-fdc8-384e-6a40e52b0095
* Version Independent ID: 826c7b3b-6807-05b6-413d-7d393aa1cfd6
* Content: [Reporting Sales Tax in the US Version - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedstates/us-sales-tax)
* Content Source: [business-central/LocalFunctionality/UnitedStates/us-sales-tax.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/UnitedStates/us-sales-tax.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by rubenseishima** [comment]
Hello, 

Sorry for taking this long to reply. Similar to VAT, tax clauses are used to describe a non-standard tax applied, or an exemption. The [setup shares similar steps to the VAT clauses setup](https://learn.microsoft.com/dynamics365/business-central/finance-setup-vat#to-set-up-vat-clauses). You can see a short description on the available fields by hovering the cursor over them.

Regarding when to use it, we recommend talking to a tax expert, since that varies depending on state, city, and other factors.

**Comment by hkusulja** [comment]
Hello,
VAT is used for EU.
Tax is used for US.
There are similarities, but there are differences. Please document properly Tax functionality and its options (nevertheless of VAT)

I have some old documentation in old - depracticed NAV , so it should be updated and put here as information on how to use this functionality and its options.

**Comment by rubenseishima** [comment]
Hi,

From what I understood then, what you are looking for is an article similar to the "Design Details" ones. Unfortunately, at this time we can't promise to have one available on tax clauses.
You can ask questions in the [community](https://community.dynamics.com/business) or submit a [documentation request](https://aka.ms/bcideas).

**Comment by edupont04** [comment]
Hello @hkusulja,
If you can see a table called Tax Clause, then it is not provided by Microsoft. Microsoft's base app has a table called VAT Clause as described by my colleague rubenseishima above.

The product's support for US sales tax mechanism is described in this article: https://learn.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedstates/us-sales-tax

It's essentially the same as it was in Dynamics NAV, except we've simplified the setup a bit. It (still) doesn't use the VAT Clause table, but you can use the VAT clause functionality to capture taxes that are not sales tax, for example.

Closing the loop as a question answered.

**Comment by hkusulja** [comment]
VAT and Tax is different thing. It is possible that US company, as operations in US, (then uses Tax), but also doing export to EU, and also using VAT functionality in parallel.

There is no documentation on Tax Clasues, and how do they work, so please update documentation, on given link it is also not described.
