### ISSUE TITLE
Tax Statements

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/dynamics365smb-docs#674]
Please document how to setup and use "Tax Statements" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af8e82f4-8ef0-fdc8-384e-6a40e52b0095
* Version Independent ID: 826c7b3b-6807-05b6-413d-7d393aa1cfd6
* Content: [Reporting Sales Tax in the US Version - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedstates/us-sales-tax)
* Content Source: [business-central/LocalFunctionality/UnitedStates/us-sales-tax.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/UnitedStates/us-sales-tax.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by rubenseishima** [comment]
Hi,

The current 'Tax Statements' page (317) in the US version is a caption mistake applied on top of the 'VAT Statements' page.
While it is not fixed, you might consider [opening a feature request](https://aka.ms/businesscentralfeedback) to revert the page rename in the US version.

**Comment by hkusulja** [comment]
Hello VAT and Tax is not the same in BC.
VAT is used in business inside EU for example.
Tax is used inside US .
Different options, settings, and functionality, but very similar.

This is not product feature request, instead this is only asking to document the functionality. I do have some old example of NAV book which explains it, but it should be updated on visible here on public documentation page for Tax statements.

**Comment by edupont04** [comment]
Closing as answered. Do not use the incorrectly named Tax Statements functionality in the US. Only use that functionality in countries that use VAT: https://learn.microsoft.com/dynamics365/business-central/finance-how-report-vat

**Comment by hkusulja** [comment]
@edupont04 sorry, what you mean by "incorrectly named".
I am here talking about US environments with US companies, that uses Sales Tax functionality and "Tax Statement" is called inside Business Central.
Please reopen until fixed / documentation updated.

**Comment by hkusulja** [comment]
Can you please reference information about known bug? Since Support team via ticket says otherwise.

We are talking about "Tax Statements" which are BC page 317, and does are US related, and are not documented on existing documentation pages - https://learn.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedstates/us-sales-tax 
therefore asking to document functionality.
If the functionality will be renamed, please do so, but it is also not visible on roadmap that rename.

VAT Statement is not supported in US companies, as per your link, and that is fine and out of scope of this Github issue.


Current screenshoot of production with BC 20.5 version (and is the same past several years)

![image](https://user-images.githubusercontent.com/7479326/193300813-ed942c77-9591-4359-acdd-c7a23ec8b10d.png)
