### ISSUE TITLE
Calculate and Post Tax Settlement

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/dynamics365smb-docs#675]
Please document how to use "Calculate and Post Tax Settlement" with Sales Tax in US

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af8e82f4-8ef0-fdc8-384e-6a40e52b0095
* Version Independent ID: 826c7b3b-6807-05b6-413d-7d393aa1cfd6
* Content: [Reporting Sales Tax in the US Version - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedstates/us-sales-tax)
* Content Source: [business-central/LocalFunctionality/UnitedStates/us-sales-tax.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/UnitedStates/us-sales-tax.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by rubenseishima** [comment]
Hello,

Apologies for the wait. The **Calculate and Post Tax Settlement** feature work similarly to report requests in the application. You can learn more about the available options at the [Run and print reports](https://learn.microsoft.com/dynamics365/business-central/ui-work-report) article. You can also hover over the available fields to read a short description.

Specifics about how to use the page with sales tax should be discussed with a tax expert on a case-by-case basis.

**Comment by hkusulja** [comment]
@rubenseishima thank you for answer

It is not question about how tax in general works, instead what exactly it does in BC , technically as a product documentation.
For example, which tables does it use, which statuses does it change (fields) etc.

I have some old documentation in old - de practiced NAV , so it should be updated and put here as information on how to use this functionality and its options

**Comment by rubenseishima** [comment]
Hi,

Similar to the question about tax clauses, at the moment we can't promise an in-depth article on tax settlements. 
Having said that, feel free to submit a [documentation request on the Ideas site](https://aka.ms/bcideas). Depending on the community support the idea may be fast-tracked.

I am sorry I couldn't be of more help.

**Comment by hkusulja** [comment]
Hello, I do not agree. This is not related to product or improvement or feature request or Idea.
This is related to documentation of the Product.
