### ISSUE TITLE
Wrong Heading

### ISSUE THREAD

**Issue by azadhussainster** [MicrosoftDocs/dynamics365smb-docs#679]
The Header "Adding new customers" should be changed to "Adding new employees".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92c618aa-df56-0f95-cbe2-3d70fca63c5f
* Version Independent ID: c446d4df-4407-4140-0719-ecd63f267073
* Content: [Set Up Employees and Modify Information - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/hr-how-register-employees)
* Content Source: [business-central/hr-how-register-employees.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/hr-how-register-employees.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by edupont04** [comment]
Now live.
