### ISSUE TITLE
Prepayment does not include VAT/GST amount

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#68]
On applying a 100% prepayment at both CUSTOMER and ORDER level, the prepayment amount did not include GST/VAT (tax).  Why would GST/VAT not be included in the Prepayment calculation on the ORDER?  The CUSTOMER is in a foreign (non-base) currency, would this affect the GST calculation (i.e. can this only be calculated at time of INVOICE when the exchange rate is known?  

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d098146a-7e71-1482-d079-4ac02dc113ac
* Version Independent ID: 6005a455-0cf6-ec5d-a221-05bfd3ff453c
* Content: [Set Up Prepayments - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/finance-set-up-prepayments)
* Content Source: [business-central/finance-set-up-prepayments.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-set-up-prepayments.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Chris7777au,

Thanks for your feedback! 

This feedback mechanism is intended to be enhancements to the docs only. For questions about functionality, please use the [Dynamics 365 Business Central community](https://community.dynamics.com/business/), your Business Central reselling partner, or [the Ideas site](https://experience.dynamics.com/ideas/list/?forum=e288ef32-82ed-e611-8101-5065f38b21f1). 

That said, you appear to have missed enabling automatic calculation of GST on prepayments in the General Ledger Setup. For more information, see 
[Calculate Goods and Services Tax on Prepayments](https://docs.microsoft.com/en-AU/dynamics365/business-central/localfunctionality/australia/how-to-calculate-goods-and-services-tax-on-prepayments)

**Comment by chris7777au** [comment]
Thanks Eva.  

What are the chances of Microsoft updating the documentation to put a pointer into the prepayments page?  One of the problems I’m having with the documentation (I’m coming from Netsuite) is the fact that it’s quite limited and the “see also” section isn’t well developed.  It would be handy to have this link in the ‘see also’ section of the prepayments page, as it would immediately point you in the right direction if you were experiencing this issue.

A real easy solution that makes a big improvement to documentation.

Cheers
Chris.
