### ISSUE TITLE
What about tracking purchasing shipments?!

### ISSUE THREAD

**Issue by ilyalehrman** [MicrosoftDocs/dynamics365smb-docs#681]
When a vendor ships a purchased item, whether for inventory or drop-shipment (the latter, arguably, being more important), where in BC do I record that shipment information, like agent/tracking number?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f773c52d-84a2-eac7-00a9-b8c24f5dffb7
* Version Independent ID: 5afdc112-18e8-7984-e382-d9b1a3858fa8
* Content: [Link a Sales Order to a Purchase Order for Direct Shipment (contains video) - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-drop-shipment)
* Content Source: [business-central/sales-how-drop-shipment.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/sales-how-drop-shipment.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! You can choose to add a line to your purchase invoice where the Type field is set to Comment, and then use that line to specify the relevant information. There are no specific fields available for the information, as far as I know. If you want to have dedicated fields, you might want to submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)

**Comment by edupont04** [comment]
Now live.
