### ISSUE TITLE
Moms - listeangivelse disk

### ISSUE THREAD

**Issue by joergenlund** [MicrosoftDocs/dynamics365smb-docs#682]
Hvis man søger efter den beskrevne funktion "Moms - listeangivelse disk." finder man ingenting.
Kunne i anvise hvordan denne fil genereres Pft

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 87cd3884-d697-3be1-164e-8e436f3b9f16
* Version Independent ID: a9c3c6fc-cf77-40d6-cb2b-91c939a841b9
* Content: [Momsindberetning \[DK\] - Business Central](https://docs.microsoft.com/da-dk/dynamics365/business-central/localfunctionality/denmark/vat-vies-reporting)
* Content Source: [business-central/LocalFunctionality/Denmark/vat-vies-reporting.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/Denmark/vat-vies-reporting.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hej @joergenlund 

Tak for dit feedback! Det viser sig, at vi har glemt at opdatere denne og andre artikler. Nutildags anbefaler vi, at man bruger raporten _Oversigt over EU-salg_. Det kan du læse om hér: https://docs.microsoft.com/dynamics365/business-central/finance-how-report-vat

Vi får det fikset hurtigst muligt.

**Comment by edupont04** [comment]
Now live in English. Danish translations will be available around March 18, 2022.
