### ISSUE TITLE
Add the "Prod. Order - Calculation (99000767) 

### ISSUE THREAD

**Issue by btschosi** [MicrosoftDocs/dynamics365smb-docs#687]
Can we also include this report to this Page... It is not there, and I can't find it anywhere in Docs.  It is a manufacturing Report.  I'm not sure if there are others that we don't have listed here.  But here is one of them I noticed we do not have when a partner was asking about it.

"Prod. Order - Calculation (99000767) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1fc2a88-e561-786c-d82c-6e0587303646
* Version Independent ID: c4be2261-5bfa-4ae2-e1be-e0800ff1cd7c
* Content: [Production Reports and Analytics - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/production-reports)
* Content Source: [business-central/production-reports.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/production-reports.md)
* Service: **dynamics365-business-central**
* GitHub Login: @AndreiPanko
* Microsoft Alias: **andreipa**

**Comment by edupont04** [comment]
Hi Bryan,
Thank you for your feedback! This will be fixed in the next doc update.

Going forward, please use the internal processes for changes to the docs. Ping me if you're not sure how. For now, I'll accept the Issues you've created here.

**Comment by edupont04** [comment]
Now live.

**Comment by edupont04** [comment]
Now live.
