### ISSUE TITLE
A useful tool would be to be able to have an action message that creates a purchase Quote document. Or if a purchase Quote document can copy lines from Purchase requisition list. This is to support the scenario where item purchase are infrequent for example for a bill of materials of items used in manufacture but NOT frequently. This is the case with a Machine Tool manufacturer who may not make a particular machine for several years but then needs to order a long list of bespoke parts that need to be manufactured. In this case a purchase enquiry is the Action rather than a Purchase order. part

### ISSUE THREAD

**Issue by Paul-Fenny** [MicrosoftDocs/dynamics365smb-docs#688]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc0748b5-65ff-eb8f-eabc-84677828a4f3
* Version Independent ID: f6a15b19-eea1-7fd1-6610-17773e9727fe
* Content: [Create a Purchase Quote to Request an Offer - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/purchasing-how-request-quotes)
* Content Source: [business-central/purchasing-how-request-quotes.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/purchasing-how-request-quotes.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)

**Comment by Paul-Fenny** [comment]
Eva,

I suggest you speak to Microsoft about this page as the Link I used was clearly labelled “feedback About this Page” it the Microsoft page I was reading regarding purchase quotes in MS Business Central

**Comment by edupont04** [comment]
Hi Paul,
I am from Microsoft, and yes, you did submit feedback about the article about purchase quotes. But the way I read your feedback, you're looking for functionality that is currently not available. That I why I suggest you go to that website to request feature change.
