### ISSUE TITLE
RapidStart services-role cener

### ISSUE THREAD

**Issue by Mr-Pingu** [MicrosoftDocs/dynamics365smb-docs#69]
"When you use RapidStart Services, we recommend that you use the RapidStart Services Implementer Role Center as it provides the correct context for your configuration work"

I assigned all the right and am a Super User but the RapidStart Services Implementer Role is nowhere to be seen in the "Role Center-list" 
How do I start the RapidStart Services Implementer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd5f8ff5-018b-67f8-5bc7-1784b054167c
* Version Independent ID: 1bfdf570-9515-9e0c-7718-189ac71a3bfb
* Content: [How to Use the RapidStart Services Role Implementer Center - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-how-to-use-the-rapidstart-services-role-center-to-track-progress)
* Content Source: [business-central/admin-how-to-use-the-rapidstart-services-role-center-to-track-progress.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/admin-how-to-use-the-rapidstart-services-role-center-to-track-progress.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback
This Role Center, along with many others, will be added within the next couple of updates. I will therefore leave the topic unchanged. 
You can still access the functionality. Simply search for Configuration Worksheet, as stated in step 1.
Soren
Business Central writer

**Comment by heatherr-nz** [comment]
As at today, this functionality is still not available. I understand that these might be published in advance, but this seems a long time in advance with still not released into the product.  It is very confusing for users when the help materials do not line up with functionality available.

**Comment by edupont04** [comment]
Hello heatherr-nz,

Thank you for your feedback! I have forwarded your feedback to the team who own this Role Center, and they say that it is indeed not currently available. We (the people who do the docs) were told 6 months ago that it would be made available shortly, as my colleague states above, but the team changed that decision. 
I will get the Help updated accordingly, and I've asked the product team to revise the decision on which Role Centers are available.

**Comment by heatherr-nz** [comment]
Thanks very much for the feedback.
