### ISSUE TITLE
Missing definitions, clarifications, and examples.

### ISSUE THREAD

**Issue by ilyalehrman** [MicrosoftDocs/dynamics365smb-docs#699]
The page does not provide definitions critical to understanding reminder terms / levels functionality. 

What is a grace period? Is the grace period the time when finance charge is not accrued? Or is it simply the time when the customer doesn't *have* to pay?

What does reminder due date calculation calculate? Is the reminder due date the date when the new balance (if there are fees) takes effect? Is it when the next level reminder takes effect?

How about a real-world example of reminder terms and their levels and how they may be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c53c6c-611f-4167-9c00-7f1c3d8bf62d
* Version Independent ID: a1c00cab-64fb-2443-5c35-cf989e0f02e1
* Content: [Collect Outstanding Balances - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/receivables-collect-outstanding-balances#feedback)
* Content Source: [business-central/receivables-collect-outstanding-balances.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/receivables-collect-outstanding-balances.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,

Thank you for your feedback! As we describe in the existing content, you can use reminders and/or finance charges in whichever way makes sense to you. You don't have to use reminders, but if you do, you can configure the reminders to do what you want them to do. 

You decide what "grace periods" mean for each reminder type, and you decide when to send reminders for what.

You can (well, you _should_) also set up payment terms, and there you can specify how the due date is calculated, such as _7D_ for 7 days from current date.

We do not have plans to add concrete examples beyond the ones already present.
