### ISSUE TITLE
Fejl i tekst

### ISSUE THREAD

**Issue by ClausHamann** [MicrosoftDocs/dynamics365smb-docs#7]
Skulle der ikke stå: "Kreditorposter, der er indstillet til Afvent, medtages ikke." (første "ikke" er fjernet)

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: ff228543-8999-8073-3d13-2de0800c677d
* Version Independent ID: 5d180045-1481-2a02-83af-c33c6d1d54f8
* Content: [Bruge kørslen Lav kreditorbetalingsforslag - Business Central](https://docs.microsoft.com/da-dk/dynamics365/business-central/payables-how-suggest-vendor-payments)
* Content Source: [business-central/payables-how-suggest-vendor-payments.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/payables-how-suggest-vendor-payments.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Yes, this was incorrect and has been changed to (English): Vendor ledger entries that are On Hold are not included in the batch job.
