### ISSUE TITLE
assigning document layouts to multiple email addresses

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#700]
Hello.

The docs state you can include a 'send to email' in a customer (or Vendor) Document Layout.  What happens, or is there a way to include multiple recipients?  For example, some customers ask that invoices are sent to purchasing@xyz.com and warehouse@xyz.com so that both get a copy prior to arrival of the goods.  At the moment it appears as though I can only include one, or can we just seperate email addresses with commas (or other separator) to include more?  

The docs do not inform you if you can only assign ONE email, or if there's a method to include multiple.

Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 562ba9ca-f395-bbeb-0775-5a85696e0935
* Version Independent ID: 58c23bed-523d-0432-f76e-2930232816f6
* Content: [Create and Modify Custom Layouts for Reports and Documents - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/ui-how-create-custom-report-layout)
* Content Source: [business-central/ui-how-create-custom-report-layout.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-how-create-custom-report-layout.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

I did some digging around and the functionality you're looking for is described in the following article, and you're absolutely correct in that it doesn't explicitly say whether you can specify more than one recipient for a type of document. 

https://docs.microsoft.com/dynamics365/business-central/ui-define-customer-vendor-document-layouts

Thanks for pointing that out, I think others might have the same question so I've updated the article and it will be published in the near future.

In the meantime, to answer your question, yes, you can add multiple email addresses for the contacts you've created for your customers or vendors. When you create or edit a document layout, you can choose the **Select Email from Contacts** action, and then choose as many contacts as you'd like. You can also enter email addresses manually, separated by a semicolon and without spaces between them. For example purchasing@xyz.com;warehouse@xyz.com.

**Comment by chris7777au** [comment]
You Brent… are a legend!

Thanks for clarifying and best of all thanks for confirming you will update the Docs.

Cheers
Chris Pope
Pacsource Pty ltd
Unit 84, 1470 Ferntree Gully Road
Knoxfield, Victoria 3180, Australia
T. +61.3.9763.4500
M. +61.447.888.777
E. ***@***.******@***.***>

Disclaimer ; The information in this email including any attachments is confidential and may be legally privileged. If an addressing or transmission error has misdirected this email please notify the author by replying to this email and destroy the original message. If you are not the intended recipient, any use, disclosure, copying or distributions prohibited and may be unlawful. Distribution of this email to other parties may result in criminal prosecution.


From: Brent Holtorf ***@***.***>
Reply to: MicrosoftDocs/dynamics365smb-docs ***@***.***>
Date: Thursday, 7 April 2022 at 10:21 pm
To: MicrosoftDocs/dynamics365smb-docs ***@***.***>
Cc: Chris Pope ***@***.***>, Author ***@***.***>
Subject: Re: [MicrosoftDocs/dynamics365smb-docs] assigning document layouts to multiple email addresses (Issue #700)


Hello,

I did some digging around and the functionality you're looking for is described in the following article, and you're absolutely correct in that it doesn't explicitly say whether you can specify more than one recipient for a type of document.

https://docs.microsoft.com/dynamics365/business-central/ui-define-customer-vendor-document-layouts

Thanks for pointing that out, I think others might have the same question so I've updated the article and it will be published in the near future.

In the meantime, to answer your question, yes, you can add multiple email addresses for the contacts you've created for your customers or vendors. When you create or edit a document layout, you can choose the Select Email from Contacts action, and then choose as many contacts as you'd like. You can also enter email addresses manually, separated by a semicolon and without spaces between them. For example ***@***.******@***.******@***.******@***.***>.
