### ISSUE TITLE
"Customizing Business Central Online Using Extensions" says to use Role/Group called `EXTEND. MGT. - ADMIN`, but actual name is `EXTEN. MGT. - ADMIN`

### ISSUE THREAD

**Issue by dnpb** [MicrosoftDocs/dynamics365smb-docs#701]
The page says these:

>To install or uninstall extensions from AppSource or add per-tenant extensions, you must have the right permissions. You must either be a member of the EXTEND. MGT. - ADMIN user group or you must have the EXTEND. MGT. - ADMIN permission set. If you are an administrator, you can assign user groups and permissions to other users in your company.
> [...]
> The EXTEND. MGT. - ADMIN permission set was introduced in Business Central 2021 release wave 1 as a replacement for the D365 EXTENSION MGT permission set in earlier versions.

So that says to use a Role or Group named `EXTEND. MGT. - ADMIN`.

The problem is that a BC19 Docker I have here has no such Group, and has a differently named Permission Set! - `EXTEN. MGT. - ADMIN`

![image](https://user-images.githubusercontent.com/63455896/159009344-b22090a5-05ea-4cbd-bd5b-e347e52bf270.png)

Please fix the documentation to match what is actually present in BC, i.e.
* Fix the Role name
* Advise whether the Group is meant to exist automatically, as it doesn't seem to for me:

![image](https://user-images.githubusercontent.com/63455896/159009492-405a9897-cc29-40f8-baba-38c417afe8b4.png)

Should the Group be auto-created? If we create one manually and add the corresponding Role, does it get the same magic voodoo?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f6ce33-2528-c87d-d097-257e598ec407
* Version Independent ID: d606ddd8-17c5-0864-cc19-1489b3dbf901
* Content: [Customizing Business Central Online Using Extensions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-extensions)
* Content Source: [business-central/ui-extensions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-extensions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Now live.
