### ISSUE TITLE
Is MPS Master Planning Schedule or Master Production Schedule?

### ISSUE THREAD

**Issue by markborges** [MicrosoftDocs/dynamics365smb-docs#712]
Hi,

Does MPS stand for Master Production Schedule or Master Planning Schedule?

On this page, the very first paragraph states:

"...The planning system can calculate either Master **Planning** Schedule (MPS) or Material Requirements Planning (MRP) on request..."

Then the very next paragraph states:

"...MPS is the calculation of a master **production** schedule based on actual demand and the demand forecast..."

So, what is it?

Tks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cab5a2e2-4760-d1d5-218b-be5bce80a715
* Version Independent ID: b1a80fd4-85ad-a6c0-37f8-59f20dfe6acf
* Content: [Run Full Planning, MPS, or MRP - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/production-how-to-run-mps-and-mrp)
* Content Source: [business-central/production-how-to-run-mps-and-mrp.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/production-how-to-run-mps-and-mrp.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

Thanks for pointing out the mismatch. It should be "Master Production Schedule." I've updated the article and it'll go live in the near future. I've swept the doc set to find other instances, and it looks like the mistake was only in that one article.
