### ISSUE TITLE
Typo on left content pane 

### ISSUE THREAD

**Issue by ManishKutar** [MicrosoftDocs/dynamics365smb-docs#716]
Hi Team,

Just noticed on typo in content part of document subject of Business Central - Install the Business Central App for Microsoft Teams

The image is below to highlight on spelling mistake that I noticed. May not be a big problem, but thought to provide the feedback.

![image](https://user-images.githubusercontent.com/44708071/161904322-81b5c023-ad85-48e0-92b6-029c8bd6ea8b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e82d09a8-c562-eb3b-5940-42d0cdc54da4
* Version Independent ID: 6b15d2d0-2515-e6d0-294a-5bf30a72305e
* Content: [Install the Business Central app in Microsoft Teams - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-install-app-for-teams#feedback)
* Content Source: [business-central/across-install-app-for-teams.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/across-install-app-for-teams.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
Thanks for the feedback! We've made the fix, and the update will be published soon.
