### ISSUE TITLE
Microsoft Sharepoint Connector Setup

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#718]
Hey there.

there is functionality to connect sharepoint to business central (simply search Sharepoint Connector setup in BC).  I cannot locate any documentation on this function, only oneDrive and usually this relates to onprem systems only.

Where do we locate instructions for the online version of BC and the Sharepoint Connector Setup?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63507777-3b53-79f6-885f-da0b0c530475
* Version Independent ID: 385e61aa-adc9-c1ed-5c32-ce8b85205c18
* Content: [Opening Business Central Files in OneDrive - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/across-share-onedrive)
* Content Source: [business-central/across-share-onedrive.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/across-share-onedrive.md)
* Service: **dynamics365-business-central**
* GitHub Login: @brentholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hi Chris,

The SharePoint Connection Setup page will be deprecated: https://docs.microsoft.com/en-us/dynamics365/business-central/admin-onedrive-faq#should-i-use-the-sharepoint-connection-setup-page-to-connect-to-sharepoint

For more information, see https://docs.microsoft.com/en-us/dynamics365/business-central/admin-onedrive-faq#does--online-connect-with-sharepoint-server

**Comment by chris7777au** [comment]
Hmm. Ok.

What’s the latest guidance then on storing documents in Business Central (specifically attachments for Sales and Purchase orders)?  If we simply store them into BC won’t that blow up our storage limit?  I have terabytes of online SharePoint storage… I’m not sure the BC liscence has opened up a little space for this or what – can you point me in the right direction if the sharepoint connection has been depreciated?

Chris Pope
Pacsource Pty ltd
Unit 84, 1470 Ferntree Gully Road
Knoxfield, Victoria 3180, Australia
T. +61.3.9763.4500
M. +61.447.888.777
E. ***@***.******@***.***>

Disclaimer ; The information in this email including any attachments is confidential and may be legally privileged. If an addressing or transmission error has misdirected this email please notify the author by replying to this email and destroy the original message. If you are not the intended recipient, any use, disclosure, copying or distributions prohibited and may be unlawful. Distribution of this email to other parties may result in criminal prosecution.


From: Eva Dupont ***@***.***>
Reply to: MicrosoftDocs/dynamics365smb-docs ***@***.***>
Date: Wednesday, 13 April 2022 at 4:21 pm
To: MicrosoftDocs/dynamics365smb-docs ***@***.***>
Cc: Chris Pope ***@***.***>, Author ***@***.***>
Subject: Re: [MicrosoftDocs/dynamics365smb-docs] Microsoft Sharepoint Connector Setup (Issue #718)


Hi Chris,

The SharePoint Connection Setup page will be deprecated: https://docs.microsoft.com/en-us/dynamics365/business-central/admin-onedrive-faq#should-i-use-the-sharepoint-connection-setup-page-to-connect-to-sharepoint

For more information, see https://docs.microsoft.com/en-us/dynamics365/business-central/admin-onedrive-faq#does--online-connect-with-sharepoint-server

**Comment by edupont04** [comment]
Hi @chris7777au 
My apologies for the delay! You might want to us the Data Archive extension: https://docs.microsoft.com/dynamics365/business-central/admin-archive-data
Alternatively, you can move some of the data to Azure Data Lake - we have a little bit of guidance in the migration docs for Dynamics GP here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/migrate-dynamics-gp#lake

**Comment by edupont04** [comment]
Closing as (partially) fixed.
