### ISSUE TITLE
Einheiten nicht Maßeinheiten

### ISSUE THREAD

**Issue by Peter-Steffek** [MicrosoftDocs/dynamics365smb-docs#719]
Maßeinheiten gibt es nicht mehr es heißt jetzt nur noch Einheiten in der Suche

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 915a6d7c-d5ca-1826-ecac-8d2e392d511e
* Version Independent ID: 5042b726-bace-220a-ef68-0cd429cce24c
* Content: [So geht's: Artikeleinheiten einrichten - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/inventory-how-setup-units-of-measure)
* Content Source: [business-central/inventory-how-setup-units-of-measure.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/inventory-how-setup-units-of-measure.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! This has been reported to our translation team, and it will be fixed in the next translation update.
