### ISSUE TITLE
Upgrade to BC 17.17

### ISSUE THREAD

**Issue by averied** [MicrosoftDocs/dynamics365smb-docs#720]
I belive there is a bug in the update to BC 17.17 (https://support.microsoft.com/es-es/topic/actualizaci%C3%B3n-17-17-para-microsoft-dynamics-365-business-central-2020-release-wave-2-compilaci%C3%B3n-de-aplicaciones-17-17-38111-compilaci%C3%B3n-de-plataforma-17-0-38061-6a88004d-3a03-41f3-bbbb-9166d5113fa2)

As part of the base application upgrade Codeunit, there is a script to update "Report Selections". Basically you are deleting all report selections, so users will not be able to print sales and purch reports, until they are manually set back again.

```
codeunit 104107 "Upg Report Selections"
{
    Subtype = Upgrade;

    trigger OnRun()
    begin
    end;

    trigger OnUpgradePerCompany()
    begin
        UpdateReportSelections;
    end;

    local procedure UpdateReportSelections()
    var
        ReportSelections: Record "Report Selections";
        TempReportSelections: Record "Report Selections";  //NOT SET TO TEMPORARY
        UpgradeTag: Codeunit "Upgrade Tag";
        UpgradeTagDefCountry: Codeunit "Upgrade Tag Def - Country";
    begin
        IF UpgradeTag.HasUpgradeTag(UpgradeTagDefCountry.GetUpdateReportSelectionsTag) THEN
            EXIT;

        TempReportSelections.DeleteAll(); //ALL MY REPORT SELECTIONS ARE DELETED WHEN UPGRADING!!
```

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).

**Comment by averied** [comment]
Sure..maybe you should state in the documentation that installing 17.17 update will delete all your report selections.. coz I did not read this will happen in the installation guide
