### ISSUE TITLE
Personalize page instructions are incorrect in BC V20 

### ISSUE THREAD

**Issue by eyestone57** [MicrosoftDocs/dynamics365smb-docs#723]
Hi:
The video indicates that I can personalize the page to add the Drop Ship field, however that field is not an option. I had to Design the Page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f773c52d-84a2-eac7-00a9-b8c24f5dffb7
* Version Independent ID: 5afdc112-18e8-7984-e382-d9b1a3858fa8
* Content: [Make Drop Shipments (contains video) - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-drop-shipment)
* Content Source: [business-central/sales-how-drop-shipment.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/sales-how-drop-shipment.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

Thanks, but it looks like the article is correct. I just tested the Sales Order and Purchase Order pages in 2022 release wave 1, and the field is available when I personalize those pages. The trick is to select the section of the page that contains the lines when you're in personalization mode. The fields that you can add through personalization change, depending on the section of the page that's chosen. 

There was a different mistake in the article though. It mentioned a **Choose Columns** function, which is not correct. I've removed that, and added an alert that clarifies how to add the field. We'll publish the update in the very near future.

On a side note, I've also contacted our subject matter expert to ask why we've hidden the Drop Shipment field in the first place. Seems to me like that would be something that people do frequently.

**Comment by eyestone57** [comment]
Hi Brent - well, egg on my face, you are absolutely right. Rookie mistake. I agree with your other point that on hiding that field, what did not duplicate the Purchasing Code option?

Thanks,

Jim


Jim Augenstein
Customer Engagement Specialist
Office: +1 800-834-7700
Direct: +1 949-203-5885


For Support, please call +1 855-856-8764 or email ***@***.***

**Comment by brentholtorf** [comment]
Hi Jim,

Just closing the loop on why the Drop Ship field is hidden by default. It was a simple matter of a lack of real estate on the page. There are a lot of fields, and this one was down prioritized when deciding what to show.
