### ISSUE TITLE
Automatic Sync of contacts to Office 365

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#727]
Hi.

This page states.:

Synchronise Contacts
 If you are used to working with contacts in Business Central, then you will find it easy to start the synchronisation manually whenever it suits you from the Contacts list. Simply choose the Sync with Microsoft 365 action, and then decide if you want to change the filter that you have set up. When you choose the OK button, the synchronisation starts immediately, and the latest changes are applied to your contacts in Outlook.

this is a little oblique - can you ONLY synchronise manually or is there an automatic option?  If there is an automated option, how is this setup and how regularly does it synchronise?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be2a9cdb-ccff-0083-16af-6eaa309416f4
* Version Independent ID: 2897af77-749b-da01-ec4d-54976ed10bcc
* Content: [Share contacts between Business Central and Outlook - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/admin-synchronize-outlook-contacts)
* Content Source: [business-central/admin-synchronize-outlook-contacts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/admin-synchronize-outlook-contacts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

Thanks for pointing this out. I agree that the article is rather vague about automated sync. I've created a task in our backlog to clarify that, and you can expect an update in the near future.

In the meantime, yes, after you set up your Exchange contact sync, you can automate synchronization by setting up a job queue entry and scheduling it to run whenever it suits you. The key settings on the job queue entry are to choose Codeunit in the Object Type to Run field, and then codeunit 6700 in the Object ID to Run field. The caption for codeunit 6700 is O365 Sync. Management.

The article is correct in that you can only sync data from Business Central to Exchange. Sync is not bi-directional.

Something worth mentioning is that sync is not designed for large sets of contacts. It'll take some investigation to figure out where exactly the limit is though, so I can't provide it here. Sorry about that, but we'll include the limit when we update the article.  

On a side note, the contact sync capability hasn't had much attention for a while. It would be great if you'd visit our [Ideas](https://experience.dynamics.com/ideas/categories/?forum=e288ef32-82ed-e611-8101-5065f38b21f1&forumName=Dynamics%20365%20Business%20Central)) page and suggest that we add bi-directional sync.
