### ISSUE TITLE
HTML Description

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#737]
Hello There Eva.

This page 'should' provide either information about all sections/parts/fields on the item card, or links out to other pages talking where we can get information about fields on the page.

In the right hand "information" block, in the details section is a block called HTML Description.  Is there any information about this block?  What does it do?  How is it Used?  The functionality is there for a purpose... I just can't figure out what that purpose is and there's nothing on the Item Card page that provides any guidance about it.  Is there information about this elsewhere (I've googled it and I can't find anything at all, even from 3rd parties discussing NAV Items), so I'm wondering if you could either add to the existing page, or provide some kind of link out to where this functionality is described.

Cheers

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37d63058-5104-f4c6-dd07-21caf3a4a4a8
* Version Independent ID: 6c3e166d-bdc9-b823-dfc4-62957f5aa385
* Content: [Create Item Cards for Goods or Services (contains video) - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/inventory-how-register-new-items)
* Content Source: [business-central/inventory-how-register-new-items.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/inventory-how-register-new-items.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi there, Chris!
Generally speaking, we refer to so-called tooltips for field descriptions as part of our user assistance model. But in this particular case, I am not familiar with the user interface element that you are wondering about. I don't see a part called HTML Description in my own tenant, so I assume that it might have been added by an app, perhaps?

**Comment by edupont04** [comment]
Closing as (partially) answered.
