### ISSUE TITLE
page different from version 16 of business central

### ISSUE THREAD

**Issue by albgen** [MicrosoftDocs/dynamics365smb-docs#739]
only v 20 of business central is like described on the document.
Other version are very different

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba9829c4-83a6-e278-adf3-b95b262b9255
* Version Independent ID: f40af485-bb95-0e4c-16f8-2871d7f38c7e
* Content: [How to Set Up a Document Exchange Service - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-how-to-set-up-a-document-exchange-service)
* Content Source: [business-central/across-how-to-set-up-a-document-exchange-service.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/across-how-to-set-up-a-document-exchange-service.md)
* Service: **dynamics365-business-central**
* GitHub Login: @brentholtorf
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! The content on Docs.microsoft.com generally reflects the latest version of Dynamics 365 Business Central unless a different version is explicitly specified. If you're using Business Central on-premises, then your partner might have set up a website for you with a copy of our content from the time of the version that you're using. That process is described here: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/configure-help#on-premises-deployments
