### ISSUE TITLE
Dokumentation on webservice

### ISSUE THREAD

**Issue by ERPgruppenMW** [MicrosoftDocs/dynamics365smb-docs#74]
We would like to know how to set up our own document exchange service - is it possible to get a hold of that information?
At first it should be used for PEOPPL invoice/credit note documents. Thanks

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: ba9829c4-83a6-e278-adf3-b95b262b9255
* Version Independent ID: f40af485-bb95-0e4c-16f8-2871d7f38c7e
* Content: [Sådan konfigureres en dokumentudvekslingstjeneste - Business Central](https://docs.microsoft.com/da-dk/dynamics365/business-central/across-how-to-set-up-a-document-exchange-service)
* Content Source: [business-central/across-how-to-set-up-a-document-exchange-service.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/across-how-to-set-up-a-document-exchange-service.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by ERPgruppenMW** [comment]
Hi Søren,

Thanks for reply.

We want to set up our own exchange service like Tradeshift. I cannot find information on requirements on that?

Med venlig hilsen / Kind regards

Mads Westen

Direktør/Manager, ERPgruppen Kolding |D: + 45 78 79 41 51 | mw@erpgruppen.dk

[ERPgruppen]<http://www.erpgruppen.dk/>

Hovednr.
Support
Website

+ 45 78 79 40 40
+ 45 70 70 70 66
www.erpgruppen.dk

ERPgruppen
Kolding, Aarhus, Horsens, Slagelse, Hellerup
Læs mere om ERPgruppen her<http://erpgruppen.dk/profil/>

Få support på C5, NAV, Dynamics 365 og Stackss - man.-tors. kl. 8.00 - 22.00 (fre. til kl. 15.00)     [Få hurtig hjælp fra supportafdelingen]


[Se åbningstider her]<https://t.xink.io/Tracking/Index/s8YBAM8rAADFQAUA0>

Hold dig godt opdateret - tilmeld dig ERPgruppens nyhedsbrev<https://t.xink.io/Tracking/Index/pcYBAM8rAADFQAUA0>


Fra: Søren Groes-Petersen <notifications@github.com>
Sendt: 5. december 2018 14:45
Til: MicrosoftDocs/dynamics365smb-docs <dynamics365smb-docs@noreply.github.com>
Cc: Mads Westen <mw@erpgruppen.dk>; Author <author@noreply.github.com>
Emne: Re: [MicrosoftDocs/dynamics365smb-docs] Dokumentation on webservice (#74)


Have you studied this topic?: https://docs.microsoft.com/da-dk/dynamics365/business-central/across-how-to-set-up-data-exchange-definitions

**Comment by SorenGP** [comment]
Here comes the answer from Development:
You can duplicate and customize the setup and authentication code of the existing Tradeshift service and then call out the code for PEPPOL generation.

The setup of Tradeshift is done on the Document Exchange Service Setup page (URLs, credentials, and tokens). This page is bound to the concepts that are used for authentication with the Tradeshift service.

The codeunit that handles integration with Tradeshift is 1410 Doc. Exch. Service Mgt.

The data exchange definition for importing PEPPOL invoices and credit memos can be seen on the Data Exchange Definitions page. The involved codes are PEPPOLINVOICE and PEPPOLCREDITMEMO.
