### ISSUE TITLE
missing carrage return

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#740]
On this section under Sales Value is there a missing Carriage Return?

This is how the columns look
Percentage of Completion = Usage Total Costs / Budget Total Costs
Invoiced % = Billable Invoiced Price

Should it look like this
Percentage of Completion = Usage Total Costs / Budget Total Costs

Invoiced % = Billable Invoiced Price
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 090f04ae-5bfb-d1a2-c89e-6efd90447c4a
* Version Independent ID: cb9bc313-f0f0-9986-77c5-f2f40d5982b3
* Content: [WIP Methods for Calculating and Recording Job Progress - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/projects-understanding-wip)
* Content Source: [business-central/projects-understanding-wip.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/projects-understanding-wip.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Ben,

Thank you for your feedback! If you mean the second-to-last method under "Cost value" rather than "Sales value", then yes, we're missing a line break. This will be fixed in the next doc update.
