### ISSUE TITLE
Specifics of the Unit Cost on the item card

### ISSUE THREAD

**Issue by hholmin** [MicrosoftDocs/dynamics365smb-docs#742]
I was trying to find the documentation regarding when the average Unit cost of the units on hand actually is zero and the Unit Cost on the Item card keeps the previous known Unit Cost instead of being zero, In NAV 2016 doc we had a Note about it: https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/hh169034%28v=nav.90%29

I think that Note from NAV 2016 doc shall be added, perhaps this page as it describes the Unit Cost calculation.

Thanks,
Helene

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 059d2db1-1236-6674-15e5-1d850d82db80
* Version Independent ID: ce2612e5-da1b-180a-5692-43de0c1eea5e
* Content: [Manually Adjust the Costs of Items - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/inventory-how-adjust-item-costs)
* Content Source: [business-central/inventory-how-adjust-item-costs.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/inventory-how-adjust-item-costs.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Helene,
Our vendor writer has ported the note.
