### ISSUE TITLE
Incoming Documents Overview

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#743]
For the uninitiated, this 'overview' is pretty vague on the overall process.  It tends to direct people to the fact that 'incoming documents' relate to General Ledger transactions (i.e. the setup requires GL batch info), but within BC itself there's a number of areas where incoming documents are referenced (i.e. sales order & purchase order).

What is unclear in this overview is the various 'pathways' into incoming documents.  

For example:

- Can I email an incoming SALES ORDER document directly into BC?  If so how and to what address?  Is there a different address for sales documents vs purchase documents?
- Are Incoming Documents ONLY sent to General Ledger Journals or can they be used to create sales orders and purchase invoices?  (I don't think this is the case, but it's unclear)
- If my incoming document is a PDF in TEXT format (i.e. it's already 'readable') does an incoming document need to go through the OCR pathway or is there an alternative?

Seems like a really great feature, to be able to 'receive' incoming documents into an inbox and then either automatically or manually process these, but the implementation steps outlined on this page (and the 'setup incoming documents' page) don't really establish an easy pathway.  Most people are going to want to ingest via email.  Given you can ingest by taking a photo - surely email is an option (or is it not?). 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e0acd95-5498-9acf-1d97-698e76d99d7d
* Version Independent ID: 55e87498-2992-45cb-2956-53ddbec08d7e
* Content: [Work with Incoming Documents - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/across-income-documents)
* Content Source: [business-central/across-income-documents.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/across-income-documents.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Chris,

Thank you for your feedback! This particular feature is not well described in the docs, I admit, but unless you make changes to it, it's designed to process OCR documents, very specifically. It is not intended to support email or other ways of sharing content. You can get some more information about that here: https://docs.microsoft.com/dynamics365/business-central/across-how-use-ocr-pdf-images-files. 
This process starts with connecting to a service that can scan artifacts and turn them into OCR documents. You can use the feature to convert G/L journal lines ("incoming documents") into purchase invoices, for example: https://docs.microsoft.com/dynamics365/business-central/purchasing-how-to-receive-and-convert-electronic-documents
You can exchange documents with the OCR service provider by email if they support that.

I agree that there is no easy pathway with this feature. The docs don't really help either, I'll admit. I'll ask someone to consolidating the content and maybe even find someone who can help with core scenarios later this year. I know that's not what you're asking for, but it's the best I can offer at this time.....

You can get an overview of the different ways the base application can process electronic data here: https://docs.microsoft.com/dynamics365/business-central/across-exchange-data
But in many cases, you might want to take a look at sharing documents and other files using OneDrive: https://docs.microsoft.com/dynamics365/business-central/across-onedrive-overview

**Comment by edupont04** [comment]
Well, in all fairness, you rarely need to scan sales documents because you generate those yourself in whatever format you need. It's then, at least conceptually, up to your customers to convert your sales documents into purchase documents on their side. And if they use Business Central, then they can use this feature to do that for them.

Anyway, you might want to ask the community for tips on how to support your scenarios. For example, you could use Power Automate flows to create sales documents based on received purchase orders, which becomes even easier with the May update (20.1).

I'm closing this Issue, not because it's resolved, but because the docs do (kind of) say what is supported out-of-the-box, and you need other scenarios that are not covered.

**Comment by edupont04** [comment]
@chris7777au I've talked to one of our product owners, and they suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
