### ISSUE TITLE
Wrong tables in inbound advanced warehouse configuration diagram

### ISSUE THREAD

**Issue by f0ffee** [MicrosoftDocs/dynamics365smb-docs#746]
Hi,

in the following diagram https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/media/design_details_warehouse_management_inbound_advanced_flow.png

included in the following page https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-inbound-warehouse-flow

the wrong tables are listed in the first step (top left).

The tables should be "Purchase Order", "Transfer Order", "Sales Return Order" instead, since the posted documents are the result of the step 4 (top right).

**Comment by brentholtorf** [comment]
Hello,

You're absolutely correct, and thanks for bring this bug to our attention. A fix is in the works and will be published in the near future.
