### ISSUE TITLE
Entering @-Sign with German Keyboard

### ISSUE THREAD

**Issue by Lilithyan** [MicrosoftDocs/dynamics365smb-docs#75]
Hello,

since the shortcut ALT + Q (also ALT GR + Q and any other key with those two) is reserved for "Tell me what you want to do", how can a user with a German Keyboard enter an @-sign in a field (e.g. the Email in Company Information). As this requires the exact same shortcut entering the sign currently seems to be only possible either via copy & paste or through ASCII-Code combination. This does not seem to be have thought through...

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: d96fd662-e905-9df6-60f5-c709f92077c1
* Version Independent ID: 172fd943-0f5c-6d4c-b764-ced7fd077a96
* Content: [Tastenkombinationen - Business Central](https://docs.microsoft.com/de-de/dynamics365/business-central/keyboard-shortcuts)
* Content Source: [business-central/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/keyboard-shortcuts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hello Lilithyan,
Thank you for your feedback! You are not the first person to run into this problem, unfortunately, so the upcoming December update of Business Central includes a fix for it. If your Business Central has not yet been updated, then it will be updated within a few days, I am told.
If you are using Business Central on-premises, then your administrator can apply the cumulative update manually.
