### ISSUE TITLE
Creating marketing documents 

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#750]
This area of business Central is a bit of a dark art, there are many fantastic features in here that are not being shared.
the ability to communicate with clients and how to use templates would be a great start.
please elaborate on how a word document or a PDF can be attached to a interaction and The effort and cost associated can be logged against a particular opportunity, that would be very helpful for people still learning
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34006406-dbcf-6317-16f0-fbf6e5482609
* Version Independent ID: 79ef7f6c-4407-64cb-eabe-92addde16443
* Content: [Manage Interactions With Your Contacts - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/marketing-interactions)
* Content Source: [business-central/marketing-interactions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/marketing-interactions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by brentholtorf** [comment]
Hello,

These are definitely some areas that could use some attention. Thanks for taking the time to point out some specific areas that we can improve. That's a big help for us. I've created a task in our backlog for updating the content.
