### ISSUE TITLE
Wrong/Missing column documentation and Invalid help link from the BC Pages.

### ISSUE THREAD

**Issue by matthewmartin-nvg** [MicrosoftDocs/dynamics365smb-docs#753]
Within the "https://docs.microsoft.com/en-gb/dynamics365/business-central/across-how-to-set-up-data-exchange-definitions#to-map-columns-in-the-data-file-to-fields-in-prod_short" part:
- The table in "To map columns in the data file to fields in Business Central" point 3 (Field Mapping FastTab) needs ...
  1. For the following fields either to not mention them or state that they must be added by design if wanted = "Target Table ID", "Target Table Caption", "Target Field ID" & "Target Field Caption".
  2. For the following fields they must have a description added herein, which I have suggested:
    - "Transformation Rule" field = "See the section directly below here for details of how/why to use this".
    - "Multiplier" field = "Only used for numeric data (this column can be added through personalisation), to add/remove decimals and/or to reverse the sign".

Help link needs to be to "https://docs.microsoft.com/en-gb/dynamics365/business-central/across-how-to-set-up-data-exchange-definitions" (with the relevant # suffix) from pages 1210, 1214, 1215, 1216 & 1217.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 350ad27c-dd1c-fde6-27a3-faaf9c0c3da1
* Version Independent ID: 704d9728-05d0-c21a-9d68-d23af8fc6457
* Content: [Define how data is exchanged electronically - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/across-how-to-set-up-data-exchange-definitions)
* Content Source: [business-central/across-how-to-set-up-data-exchange-definitions.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/across-how-to-set-up-data-exchange-definitions.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! We've added your suggestions to our backlog, and I expect someone to pick it up in a few weeks.

**Comment by edupont04** [comment]
Now live.
