### ISSUE TITLE
Low Value Pool Assets

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#754]
Can Low Value Pool assets be added to the Australian Localisation?

https://www.ato.gov.au/Business/Depreciation-and-capital-expenses-and-allowances/General-depreciation-rules---capital-allowances/Low-value-assets-(pool)/

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1fd6e96-76f1-6d75-570d-1d1cd571be0d
* Version Independent ID: 4647bb84-b1ce-abac-5aa3-41df2134d40e
* Content: [Australia Local Functionality - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/australia/australia-local-functionality)
* Content Source: [business-central/LocalFunctionality/Australia/australia-local-functionality.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/Australia/australia-local-functionality.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you submit a feature request here: [https://aka.ms/businesscentralfeedback](https://aka.ms/businesscentralfeedback)
