### ISSUE TITLE
Stale check function is not working in BC

### ISSUE THREAD

**Issue by akash1shukla** [MicrosoftDocs/dynamics365smb-docs#756]
Hi Team,

When i am going to post a transaction related to stale cheque, then i found that it's not working as per the details written below. Stale cheque expiry date is not auto populated in **check ledger entry**. 
![image](https://user-images.githubusercontent.com/107189508/172840831-e64d8079-deb7-4827-a9af-fd3535db956f.png)
![image](https://user-images.githubusercontent.com/107189508/172840932-360188f2-e3f1-4e16-87cd-e9064471fa27.png)

When i am going to click on stale check function then it's also not working it's give license error, but i have appropriate license. Please into this.  
![image](https://user-images.githubusercontent.com/107189508/172841095-a79ef747-d778-4a7f-bbd1-3b3c1340fe36.png)
![image](https://user-images.githubusercontent.com/107189508/172841144-0704ee0b-4fa8-4bac-860b-3034047ad3de.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb1ae757-a2b0-5ead-4dae-423949fe2186
* Version Independent ID: 85d19143-d151-c930-ecfd-c2469707bb05
* Content: [Setting up and how to stale check - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/india/stale-check)
* Content Source: [business-central/LocalFunctionality/India/Stale-Check.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/India/Stale-Check.md)
* Service: **dynamics365-business-central**
* GitHub Login: @v-debapd
* Microsoft Alias: **v-debapd**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you contact technical support. For more information, see [Report a Problem](https://docs.microsoft.com/en-us/dynamics365/business-central/product-help-and-support#report-a-problem).
