### ISSUE TITLE
Making Tax Digital - VAT Returns submission

### ISSUE THREAD

**Issue by ryancairnsy** [MicrosoftDocs/dynamics365smb-docs#76]
Can you advise when this documentation will be available? The updates have been released but we don't know how to set it up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7dcf603-9deb-1715-9e2f-9afbd791498e
* Version Independent ID: 955ab2fc-93cc-3e63-b7c9-e5b34f944642
* Content: [United Kingdom Local Functionality - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedkingdom/united-kingdom-local-functionality)
* Content Source: [business-central/LocalFunctionality/UnitedKingdom/united-kingdom-local-functionality.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/UnitedKingdom/united-kingdom-local-functionality.md)
* Service: **dynamics365-business-central**
* GitHub Login: @sorenfriisalexandersen
* Microsoft Alias: **soalex**

**Comment by sorenfriisalexandersen** [comment]
Thank you for the feedback. Could you contact me on email on soalex (at) microsoft.com

**Comment by stevennettleship** [comment]
Not the only one waiting for this.

**Comment by edupont04** [comment]
Hi everyone, 
The docs have been updated accordingly (currently only available in English US, though):
https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedkingdom/making-tax-digital-submit-vat-return
