### ISSUE TITLE
Works Order v Production Order

### ISSUE THREAD

**Issue by nickgoddard777** [MicrosoftDocs/dynamics365smb-docs#760]
In the system, the term Production Order is used and there is no reference (that I have seen)  but the help calls them Works Orders.  This may be because I come from an IT background and not a manufacturing background, but using a totally different term in the help is very confusing.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07941e74-a84a-a44e-d80b-50b050e95a91
* Version Independent ID: ebf2793e-4ed3-3abb-ce76-04aa51cd1b42
* Content: [About Works Orders - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/production-about-production-orders)
* Content Source: [business-central/production-about-production-orders.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/production-about-production-orders.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! It sounds like there is a mismatch between how the product and the docs refer to this feature in English (UK). I've reported it to our translation team, and it will be fixed in the next translation update, as appropriate.

**Comment by edupont04** [comment]
Now live.
