### ISSUE TITLE
Numbered list broken

### ISSUE THREAD

**Issue by nickgoddard777** [MicrosoftDocs/dynamics365smb-docs#761]
The numbered list in this article breaks at point 4.  This means that points 5 and 6 are just one big paragraph.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfd52d34-7cf1-ebb9-ad9c-efcacac8bd09
* Version Independent ID: be48dc99-4575-83df-d542-206f2b526de3
* Content: [Create Works Order Headers - Business Central](https://docs.microsoft.com/en-gb/dynamics365/business-central/production-how-to-create-production-orders)
* Content Source: [business-central/production-how-to-create-production-orders.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/production-how-to-create-production-orders.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello, 
Thank you for your feedback! This will be fixed in the next doc update.
