### ISSUE TITLE
D365 Finance reference

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#766]
There is a tip on this page that talks about d365 Finance I think it is miss labelled.

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4498087-0e7f-079a-c371-7543c7d771d7
* Version Independent ID: e6e5ffe6-3e2c-b821-2992-ac9b01b3ebc3
* Content: [Consolidate Data from Multiple Companies - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/finance-consolidated-company-reporting)
* Content Source: [business-central/finance-consolidated-company-reporting.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/finance-consolidated-company-reporting.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Ben,
No, that's not a mistake at all. The point of the tip is that if you use Business Central in a company that is a subsidiary of an organization that uses Dynamics 365 Finance as the software to manage the books, then this capability will also support that scenario.
In other words, use the same steps, regardless of whether the parent organization uses Business Central or Finance.
