### ISSUE TITLE
text file

### ISSUE THREAD

**Issue by gnlcmrcl** [MicrosoftDocs/dynamics365smb-docs#769]
Hi, 
in step 4, please precise that the file (downloaded from the SIX Interbank Clearing website) that need to be imported is .txt and not .xls.
Thank you and best regards,
Gianluca

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b3ce50-4818-a005-8c29-dbd9706747d4
* Version Independent ID: 4155aeb4-0010-7ef1-bc37-2e4a127cdc5e
* Content: [Import Swiss Bank Clearing Numbers \[CH\] - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/switzerland/how-to-import-swiss-bank-clearing-numbers)
* Content Source: [business-central/LocalFunctionality/Switzerland/how-to-import-swiss-bank-clearing-numbers.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/Switzerland/how-to-import-swiss-bank-clearing-numbers.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! We're currently investigating and will update the article soon.

**Comment by edupont04** [comment]
This is now fixed in English and will be updated in the supported languages for Switzerland in the next translation update (August).
https://docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/switzerland/how-to-import-swiss-bank-clearing-numbers
