### ISSUE TITLE
Why are Query APIs not mentioned on this page?

### ISSUE THREAD

**Issue by srenders** [MicrosoftDocs/dynamics365smb-docs#770]
Query APIs (and web services) can aggregate data (group by, subtotals) and therefore create smaller datasets. Query objects are the ideal source for Power BI, because in Power BI data is typically imported and aggregated, so aggregating at the source is much more performant. On top if that, Query object can, more easily, combine multiple tables (using different types of joins).

So I wonder why Query APIs/Web Services are not mentiond on this docs page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f0d4b2d-e2f5-a8bb-27bb-3a6975169dc0
* Version Independent ID: a23bba5a-ee49-8910-b84b-c23f479caec6
* Content: [Enabling Power BI Integration With Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-powerbi-setup#exposedata)
* Content Source: [business-central/admin-powerbi-setup.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/admin-powerbi-setup.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hello Steven,
Thank you for your feedback! I take your question as in "why only mention page API and not query API?", and if I understood you correctly, then it's a good question. I've forwarded it to some people on the team, and the article will be updated if appropriate.

**Comment by edupont04** [comment]
Well, that was quick. It's confirmed that query API is also supported, and we'll make that clear in the next doc update.

**Comment by edupont04** [comment]
Now live.
