### ISSUE TITLE
Shipping Advice

### ISSUE THREAD

**Issue by chris7777au** [MicrosoftDocs/dynamics365smb-docs#772]
On the Sales Order Page (42), there's a field Shipping Advice (5750).  The help link take me to this document page, but there's nothing relating to shipping advice.  Is it possible to either direct the link to the correct page, include a link on this page to the page that provides the information or add the info to this page.

Seems like a good feature... just no documentation on what it does.

Cheers
Chris.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e2a85cc-ce94-3c69-1a6f-e362bdc1ffe1
* Version Independent ID: 2e6fcee3-cc00-7902-c275-363e7c87aadd
* Content: [Invoice Sales - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/sales-how-invoice-sales)
* Content Source: [business-central/sales-how-invoice-sales.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/sales-how-invoice-sales.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by otherjoel** [comment]
This is a consistent problem throughout BC. More generally, every individual set of related fields on every single document should have their own page in the docs, and the “Learn More” tooltip link for each field should lead to that page. These pages should describe each individual field: what value it expects, what is affected by its value, and whether it might be indirectly updated by another field/process.

Even if these pages were stubbed out with minimal content in only a single language, it would make it possible for users to contribute this kind of content through pull requests.

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! I have added the very reasonable request for porting content about partial shipments and the weirdly named field Shipping Advice to our backlog. I hope a team member will be able to pick up the work within too long.

As for the frustration about the effect of the Learn More link on tooltips, then that is something the team is looking into improving. Our original plan was that the link would go to an article that would describe how that field fits into a task or larger context. But also that the article would have a bunch of links to other articles describing the many different processes that each document can be part of. We'll never have field-specific articles again, but we're currently porting legacy content in a prioritized way.

**Comment by chris7777au** [comment]
Thanks Eva,

Thank you!  I actually think the idea of field linking to help is brilliant – but relies on the vendor explaining the fields they include.  Personally I don’t quite understand the rationale behind adding new features (some of which may be brilliant) but not telling customers how to use these new features seems a bit counter intuitive!

Appreciate your efforts internally to get things ported over.


From: Eva Dupont ***@***.***>
Reply to: MicrosoftDocs/dynamics365smb-docs ***@***.***>
Date: Wednesday, 3 August 2022 at 10:14 pm
To: MicrosoftDocs/dynamics365smb-docs ***@***.***>
Cc: Chris Pope ***@***.***>, Author ***@***.***>
Subject: Re: [MicrosoftDocs/dynamics365smb-docs] Shipping Advice (Issue #772)


Hello,
Thank you for your feedback! I have added the very reasonable request for porting content about partial shipments and the weirdly named field Shipping Advice to our backlog. I hope a team member will be able to pick up the work within too long.

As for the frustration about the effect of the Learn More link on tooltips, then that is something the team is looking into improving. Our original plan was that the link would go to an article that would describe how that field fits into a task or larger context. But also that the article would have a bunch of links to other articles describing the many different processes that each document can be part of. We'll never have field-specific articles again, but we're currently porting legacy content in a prioritized way.

**Comment by edupont04** [comment]
We published a new article that will be available in your language in about 2 weeks from now but curently only available in English: https://docs.microsoft.com/en-us/dynamics365/business-central/sales-how-send-partial-shipments
