### ISSUE TITLE
Best Practice regarding customizing your Profile

### ISSUE THREAD

**Issue by Waseemdk** [MicrosoftDocs/dynamics365smb-docs#773]
I have now gone through most of the "Profiles" documentation on your docs.microsoft.com. I have not been able to find any answer that describes what is the **best practice** regarding customization of "Profiles".
Is it possible to adapt existing "Profiles" (Business Manager, Base Application), the answer is yes.
What will happen to this profile when one of the monthly updates (BC SAAS) from Microsoft arrives. Will changes be overwritten? Please write something about it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbc54780-19ba-4d44-cd54-3435966b1293
* Version Independent ID: 1417b68c-68fd-9f06-fafa-854edc3c1e75
* Content: [Manage users and roles - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-users-profiles-roles)
* Content Source: [business-central/admin-users-profiles-roles.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/admin-users-profiles-roles.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

Profile customizations aren't affected by upgrade. We keep customizations in dedicated tables and store the deltas between the customized and standard profiles. I've created a task to add a note to the article to mention that.

**Comment by Waseemdk** [comment]
Hi,
Thanks for your reply.

Den man. 7. nov. 2022 kl. 15.09 skrev Brent Holtorf <
***@***.***>:
