### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by McSap** [MicrosoftDocs/dynamics365smb-docs#774]
In the row "No Inventario" in several columns (eg. "Salida de ensamblado", "Salida de producción", "Transferencia de ubicación", etc) have the value "N.º". In English version they have "No".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea248ae7-d4ca-5879-0785-d097f3250b5a
* Version Independent ID: adefc344-0777-caa6-7052-416302d9dbb8
* Content: [Understanding Item Types - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/inventory-about-item-types)
* Content Source: [business-central/inventory-about-item-types.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/inventory-about-item-types.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! This has been reported to our translation team, and I expect it to be fixed in the next translation update (August).
