### ISSUE TITLE
Expand on Blocked Options

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#776]
There are 3 setting for blocked

Here is the help text
_Specifies that the related record is blocked from being posted in transactions, for example a customer that is declared insolvent or an item that is placed in quarantine._
Here are the 3 options
Blank
Posting 
All

Can we please get an expansion on this component?

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0224b54f-4603-1014-fc83-4a4341b47867
* Version Independent ID: 77836692-5a29-390c-7176-387e849bfda3
* Content: [Create a Job Card for a Job and Specify Tasks - Business Central](https://docs.microsoft.com/en-AU/dynamics365/business-central/projects-how-create-jobs)
* Content Source: [business-central/projects-how-create-jobs.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/projects-how-create-jobs.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for your feedback! We never explained this particularly well, but we will in the next doc update.

<table>
<colgroup>
<col style="width: 50%" />
<col style="width: 50%" />
</colgroup>
<thead>
<tr class="header">
<th>Option</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><p><strong>&lt;Blank&gt;</strong></p></td>
<td><p>All actions are allowed.</p></td>
</tr>
<tr class="even">
<td><p><strong>Posting</strong></p></td>
<td><p>You can work with planning lines, but the job is blocked for posting. Choosing this option means that you cannot post any usage or sale on the job.</p></td>
</tr>
<tr class="odd">
<td><p><strong>All</strong></p></td>
<td><p>All actions are blocked.</p></td>
</tr>
</tbody>
</table>

**Comment by edupont04** [comment]
Now live.
