### ISSUE TITLE
Misleading Sentence

### ISSUE THREAD

**Issue by Castanle** [MicrosoftDocs/dynamics365smb-docs#777]
This sentence (If you want to invoice more than one purchase receipt at a time, you can use the Combine Receipts function.) is misleading because there isn't an actual "Combine Receipts" function.  You have to go to the line level which is explained in the doc further down.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44c4fe80-4e37-08cf-c436-451c658ea9eb
* Version Independent ID: f0c2e419-d6bc-4bae-e0a6-f83f98cacf2e
* Content: [Combine Receipts on a Single Invoice - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/purchasing-how-to-combine-receipts)
* Content Source: [business-central/purchasing-how-to-combine-receipts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/purchasing-how-to-combine-receipts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.

**Comment by edupont04** [comment]
Now live.
