### ISSUE TITLE
Vendor Posting Direct Cost Applied Account

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#778]
Can you share more on this process

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae49cb5f-62a1-2c2c-455c-5062fb5f9ae1
* Version Independent ID: 9229c603-465e-a779-4b4b-1cd60cfb20b7
* Content: [Posting Group Setup - Business Central](https://docs.microsoft.com/en-au/dynamics365/business-central/finance-posting-groups)
* Content Source: [business-central/finance-posting-groups.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/finance-posting-groups.md)
* Service: **dynamics365-business-central**
* GitHub Login: @brentholtorf
* Microsoft Alias: **bholtorf**

**Comment by edupont04** [comment]
Hello Ben,
I'm not sure I understand your question. Are you asking about how to set up a posting group for direct cost of vendors?

**Comment by makdaddy8888** [comment]
Hi Eva

I think my question relates to non inventory items vs inventory item and how direct cost applied account works depending on item type. There’s been some confusion as to the benefits of having a purchase variance account which seems to be related here. Apologies if that’s not 100% clear.

Kind Regards
Ben

**Comment by edupont04** [comment]
My apologies for the delay in getting back to you. For this particular scenario, I recommend you reach out to the greater community. You can start with this one: https://community.dynamics.com/business

**Comment by makdaddy8888** [comment]
Hi Eva I think this is the issue Non Stock Items vs Inventory Items If you are selling a Non inventory item there is no option to adjust when received purchase orders get posted too, they hit the item journal and you can filter the purchase order page to show “received not invoiced <> 0”. For this customer they would like this open/received po to be a liability and hit a G/L. If on the other hand you were doing the same item using Inventory Items then the direct cost applied account is used. These guys don’t hold stock at all just want to account for when a Purchase order has been submitted and received but not invoiced. Regards  Ben Opit From: Eva DupontSent: Wednesday, 3 August 2022 11:37 PMTo: MicrosoftDocs/dynamics365smb-docsCc: BenO; AuthorSubject: Re: [MicrosoftDocs/dynamics365smb-docs] Vendor Posting Direct Cost Applied Account (Issue #778) Hello Ben,I'm not sure I understand your question. Are you asking about how to set up a posting group for direct cost of vendors?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
