### ISSUE TITLE
Example – Fixed Application in Purchase Return

### ISSUE THREAD

**Issue by NoOneLt** [MicrosoftDocs/dynamics365smb-docs#78]
Example – Fixed Application in Purchase Return
Shouldn't inbound entry no. be 2 in the example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d637fa6f-a440-1f1b-ed97-1a2d7f9e8bb5
* Version Independent ID: c32b25eb-3691-dec7-2eae-3dbbac6f05cf
* Content: [Design Details - Item Application - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-item-application)
* Content Source: [business-central/design-details-item-application.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-item-application.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thanks for spotting this. The topic is updated and will be available within one week.
