### ISSUE TITLE
Expense Management

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#782]
How can the job module allocate expenses relating to the job for example some travel expense relating to the job which need to be reimbursed back to the employee
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 090f04ae-5bfb-d1a2-c89e-6efd90447c4a
* Version Independent ID: cb9bc313-f0f0-9986-77c5-f2f40d5982b3
* Content: [WIP Methods for Calculating and Recording Job Progress - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/projects-understanding-wip)
* Content Source: [business-central/projects-understanding-wip.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/projects-understanding-wip.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,
The project management capability was originally created to help people track time. But you can also track expenses. For more information, see this article: https://docs.microsoft.com/dynamics365/business-central/projects-how-manage-project-supplies
