### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by richardmayo** [MicrosoftDocs/dynamics365smb-docs#784]
Hi,

This page suggests that the "Document Layouts" is under the "Action" heading on the customer page. However its actually under the "Related/Customer" section.

Thanks 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33db86c4-87ac-ed6e-f9d6-2367df3d98b2
* Version Independent ID: 2fa3dfce-59b7-bc97-294e-d276cace34f4
* Content: [Assign Document Layouts to Customers or Vendors - Business Central](https://docs.microsoft.com/en-nz/dynamics365/business-central/ui-define-customer-vendor-document-layouts)
* Content Source: [business-central/ui-define-customer-vendor-document-layouts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-define-customer-vendor-document-layouts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! Actions, meaning icons or text you can click on in the different pages, can be moved around as part of personalization. That is why, we don't usually say exactly where a certain action is. We usually write that you must "choose the XYZ action.", in this case the Document Layouts action. That action can then be under the menu item of Actions, or it can be in another section of the action bar.
We accept that you read that information in a different way than we mean it, but that's how things are, sometimes.  For more information about personalization, see this article: https://docs.microsoft.com/dynamics365/business-central/ui-personalization-user
