### ISSUE TITLE
Wrong italian label: "Impostare i metodi di pagamento"

### ISSUE THREAD

**Issue by mpierno** [MicrosoftDocs/dynamics365smb-docs#786]
The correct label may be "Impostare i metodi di spedizione".
The address link is OK.
Thanks.
---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 8a25308e-e0c0-c326-c000-083a7383deeb
* Version Independent ID: 0a150274-2e5e-280e-09c1-d4930d65887e
* Content: [Panoramica dei task per la configurazione dei processi di vendita - Business Central](https://docs.microsoft.com/it-it/dynamics365/business-central/sales-setup-sales)
* Content Source: [business-central/sales-setup-sales.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/sales-setup-sales.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! This has been reported to our translation team, and it will be fixed in the next translation update.
