### ISSUE TITLE
How do i filter on dates?

### ISSUE THREAD

**Issue by klauskaan** [MicrosoftDocs/dynamics365smb-docs#787]
[Enter feedback here]
Can i filter on dates, if so: How? Can i use date formulas to filter on dates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 802c5ab2-6384-9f67-586f-8de66cd361cc
* Version Independent ID: 12fb39ec-1f3c-e49b-de9c-7d9d09b29fc4
* Content: [Sorting, Searching, and Filtering Lists - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-enter-criteria-filters)
* Content Source: [business-central/ui-enter-criteria-filters.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-enter-criteria-filters.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. You can filter by date, and you can filter by date formula. Learn more at https://docs.microsoft.com/en-us/dynamics365/business-central/ui-enter-criteria-filters#-filter-criteria-and-operators

**Comment by klauskaan** [comment]
Thanks for the answer :)
I think the article could benefit from an example with filtering on a date range that might even include a date formula.
