### ISSUE TITLE
Is there an automated way to retry a coupling when a dependent coupling fails (or the record is not yet present in BC)?

### ISSUE THREAD

**Issue by grantbrimhall** [MicrosoftDocs/dynamics365smb-docs#790]
Hi:

is there a page you can link to, or can you provide instruction on this page, that give more detail behind the a dependency coupling? You mention a manual solution, but is there an automated one?

for example you list an item for which the unit of measure is not coupled ... we are having the same problem with Dataverse inserting purchase orders into BC when a vendor is not yet coupled ... your solution is to first couple the dependent record, and then retry the coupling. How can this be accomplished automatically?

We are fine that BC reports an error when trying to create a new Purchase Order when it can't find the vendor -- that's what it should do; but within a few minutes, vendor will run, and it will be inserted/coupled into BC. How can we setup the Purchase Order Integration Mapping so that it automatically retries this kind of dependency failure without users having to intervene?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5924a9c-ef42-2343-d799-3574f8e63a25
* Version Independent ID: 5d67e63f-5602-5e25-289d-301147857279
* Content: [Troubleshooting Synchronization Errors - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-troubleshoot-sales-synchronization)
* Content Source: [business-central/admin-troubleshoot-sales-synchronization.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/admin-troubleshoot-sales-synchronization.md)
* Service: **dynamics365-business-central**
* GitHub Login: @brentholtorf
* Microsoft Alias: **bholtorf**

**Comment by rubenseishima** [comment]
Hello,

After consulting with an expert in Dataverse integration, failed couplings should be automatically retried by the scheduled job queue, following the [synchronization frequency set for the integration mapping](https://docs.microsoft.com/en-us/dynamics365/business-central/admin-synchronizing-business-central-and-sales).
