### ISSUE TITLE
Not quite enough

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-docs#791]
We are used to formatting date fields in RDLC layouts using VB code. There seems to be extensive formatting control available in Word templates as well, as documented [on this website:](http://www.gmayor.com/formatting_word_fields.htm)

However, we notice that when we insert formatting into a Word content control as described in the above document, it does not seem to survive the Import of the layout back into Business Central (when we Export, the formatting is gone). 

It would be extremely helpful if this doc page referenced the use of built-in Word formatting, and whether it can in fact be used in Business Central custom report layouts (and if so, how). 

It is quite frustrating to find this documentation page but find it makes no mention one way or the other of the use of this kind of formatting for such a commonly-used function (formatting date-time strings).

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4eb792f3-7edc-76bd-235b-39f412d1c990
* Version Independent ID: a3a8442a-f3d9-7c4e-a70a-86b3133d562c
* Content: [How to Add Fields to a Word Report Layout - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-add-fields-word-report-layout)
* Content Source: [business-central/ui-how-add-fields-word-report-layout.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-how-add-fields-word-report-layout.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by rubenseishima** [comment]
Hello,

Word report layouts in Business Central follow a specific syntax that is not compatible with the Word Field Codes described in the linked page. To insert dates in Word report layouts, you need to use the XML Mapping fields available for each specific report as described in the [Adding data fields](https://docs.microsoft.com/dynamics365/business-central/ui-how-add-fields-word-report-layout#adding-data-fields) section.

**Comment by rubenseishima** [comment]
Hi,

After talking to a specialist, he mentioned that option is only available through [code personalization](https://learn.microsoft.com/dynamics365/business-central/dev-itpro/developer/devenv-programming-in-al), by setting how the system formats dates when the Word layout XML field calls for one when a report is generated.
At this time, I cannot promise you an article covering that particular customization, but you can always reach for the community for additional information: https://community.dynamics.com/business

Sorry I couldn't be of more help.

**Comment by edupont04** [comment]
Closing as answered.
