### ISSUE TITLE
What does released mean? 

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#793]
I cannot find where the term released is explained

can you please add some context to what Released means.

Thank you
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79ad74cc-aba8-7c05-93c2-da28efdbf375
* Version Independent ID: 2f07a9a9-4cf3-c835-29d0-aab1c830277c
* Content: [FAQ About Using Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/across-faq)
* Content Source: [business-central/across-faq.yml](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/across-faq.yml)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello Ben,
I assume you're talking about the value of the Status field on documents such as a sales order. As the field description for that field says, the field "specifies whether the document is open, waiting to be approved, has been invoiced for prepayment, or has been **released** to the next stage of processing."


We also had this additional info in the old days - would adding that text answer your question?
"The document has been released to the next stage of processing and you cannot make changes to lines of type Item and Fixed Asset. You can reopen a released document if you want to make changes to its contents. To move the adjusted document to the next stage of processing, you must once again release the document."

**Comment by makdaddy8888** [comment]
You got it :)People are not clear what released means …There should also be additional status like partially invoices or partially shipped but that’s just an opinion :)Kind RegardsBen OpitOn 14 Sep 2022, at 12:28 am, Eva Dupont ***@***.***> wrote:﻿
Hello Ben,
I assume you're talking about the value of the Status field on documents such as a sales order. As the field description for that field says, the field "specifies whether the document is open, waiting to be approved, has been invoiced for prepayment, or has been released to the next stage of processing."
We also had this additional info in the old days - would adding that text answer your question?
"The document has been released to the next stage of processing and you cannot make changes to lines of type Item and Fixed Asset. You can reopen a released document if you want to make changes to its contents. To move the adjusted document to the next stage of processing, you must once again release the document."

**Comment by edupont04** [comment]
Ok, I added a work item to the backlog to port an article we used to have. I expect it to live as part of our next major release in 2 weeks' time.

**Comment by edupont04** [comment]
Now live.
