### ISSUE TITLE
Where can I find the documentation for Copy Inv. No. To Pmt. Ref.

### ISSUE THREAD

**Issue by misterede** [MicrosoftDocs/dynamics365smb-docs#798]
Hi, 
where can I find the documentation for the field Copy Inv. No. To Pmt. Ref. (59, Boolean) in the table Purchases & Payables Setup (312)?
/Eduard Schäfer

**Comment by edupont04** [comment]
Hello, 
Thank you for your feedback! Field descriptions are available as "tooltips" that show when you hover over or select a field caption. 
In this case, the field description reveals this text:
**Copy Invoice No. To Payment Reference**
Specifies if the value of the Vendor Invoice No. field must be copied to the Payment Reference field during posting unless the Payment Reference field is not blank.

Learn more here: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/user-assistance#help-users-get-unblocked

**Comment by misterede** [comment]
Hello,
I saw the tooltip. I was looking for further information about the origin and the effect of this property. After posting the information is stored in the vendor ledger entries.
What is the business case? When was it introduced?
Is this relevant for the payment module?


Kind Regards

Eduard Schäfer
Head of Customer Service

Phone +49 5241 9217-332

Microsoft Teams: Chatten Sie mit ***@***.***>

***@***.******@***.***>







MODUS Consult GmbHJames Watt Strasse 6
D-33334 Gütersloh

Telefon: +49 5241 9217-0

***@***.***
www.modusconsult.de

Geschäftsführung: Bernhard Alsdorf, Birgit Merschmann, Stefan Sagowski, Klaus Wagner

Handelsregister beim Amtsgericht Gütersloh, HRB 11619
USt-IdNr.: DE 257988856

Entdecken Sie unsere Webinare für Business-IT und treffen Sie uns live vor Ort: https://www.modusconsult.de/unternehmen/modus-consult-live
Bleiben Sie auf dem aktuellsten Stand und erhalten Sie mit unserem Newsletter alle Neuigkeiten aus unserem Unternehmen: https://www.modusconsult.de/unternehmen/newsletter
Haben Sie Lust auf eine neue Herausforderung? https://www.modus-karriere.de

Wir nehmen das Thema Datenschutz sehr ernst. Deswegen informieren wir Sie über die Verarbeitung Ihrer personenbezogenen Daten durch die MODUS Consult GmbH und die Ihnen nach dem Datenschutzrecht zustehenden Rechte auf https://www.modusconsult.de/datenschutz.

Die 1995 gegründete MODUS Consult GmbH bietet integrative, ganzheitliche Leistungen aus einer Hand. Von ERP und CRM über DMS und BI bis zu Systemberatung und -technik basieren unsere Lösungen und unser Know-how auf der Erfahrung von 25 Jahren erfolgreicher Zusammenarbeit mit über 1.000 Kunden. Mit unseren zertifizierten Branchenlösungen auf Basis von Microsoft Dynamics setzen wir als Microsoft Gold Partner höchste Qualitätsansprüche an uns und an die gemeinsam mit unseren Partnern geschaffenen Lösungen.

Die MODUS Consult GmbH ist ein Unternehmen der Bechtle-Gruppe.


Von: Eva Dupont ***@***.***>
Gesendet: Dienstag, 20. September 2022 14:29
An: MicrosoftDocs/dynamics365smb-docs ***@***.***>
Cc: Schäfer, Eduard ***@***.***>; Author ***@***.***>
Betreff: Re: [MicrosoftDocs/dynamics365smb-docs] Where can I find the documentation for Copy Inv. No. To Pmt. Ref. (Issue #798)


Hello,
Thank you for your feedback! Field descriptions are available as "tooltips" that show when you hover over or select a field caption.
In this case, the field description reveals this text:
Copy Invoice No. To Payment Reference
Specifies if the value of the Vendor Invoice No. field must be copied to the Payment Reference field during posting unless the Payment Reference field is not blank.

Learn more here: Protected link<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmailportal.modusconsult.de%2FenQsig%2Flink%3Fid%3DBCAAAABGd7m3lfMOLOIhx3uNR_1Qav4Ffx8-jQB0torD82ts_NIAAABc_YM4F6SeDDhSDoZ2cPP4aE4efK9VpugOlQUXj3uu-eV8-_Zv2vqNwhy_37vHDJYhsuog4Hecx316rm6TYEt4e4JgtMp_cW55-WSCmxZTCojrmCBDZdTMygZQ8Gmp4I2t4th6y8z9AE0o01oHRoOIkZZ0KC74jA--KRxcw3eoS4JGw3plnt-uM_MmUswY5U1sTS0ykfvg4z7CC0S8p8u1espK7_IVuvJtFXTzT7Pl6LGESTBe8fPz5W_TziPbn7pY6Cb_m3pHl7j23NPLu32LY_A1&data=05%7C01%7CEduard.Schaefer%40modusconsult.de%7C2849bfb50eed4f9d098e08da9b03b9d1%7C81a9a075535e4ade862061bf93d53491%7C1%7C0%7C637992737547645928%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eg%2FWZ%2F61mNE49Jd3lIaYb62s%2BDyclJQ7hhfCrcgB8lc%3D&reserved=0>

-
