### ISSUE TITLE
Typo Error in the section "Calculating without a requested delivery date"

### ISSUE THREAD

**Issue by Slominski-q** [MicrosoftDocs/dynamics365smb-docs#800]
it is written  "Calculating without a requested **delivery** date" 
it should be "Calculating without a requested **receipt** date"
and further, in the text of the article, it also should be replaced

the author of the original article is mr. @brentholtorf

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0b4f3fd5-03e2-c8c6-9a05-23ce8893b834
* Version Independent ID: 95b969fb-97c9-9d9d-2a69-9f692683a585
* Content: [Calculate Dates for Purchases - Business Central](https://learn.microsoft.com/en-gb/dynamics365/business-central/purchasing-date-calculation-for-purchases)
* Content Source: [business-central/purchasing-date-calculation-for-purchases.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/purchasing-date-calculation-for-purchases.md)
* Service: **dynamics365-business-central**
* GitHub Login: @brentholtorf
* Microsoft Alias: **bholtorf**

**Comment by brentholtorf** [comment]
Hello,

Thanks for calling that out. We'll update and republish the article asap.

**Comment by Slominski-q** [comment]
Thanks, guys.
