### ISSUE TITLE
Payment Terms only in Italy?

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-docs#801]
How is it that the setup of Payment Terms is only described (as far as I can tell) in the Italian version? If this is in fact the only place it is described, maybe include a note to that effect to ward off fruitless searches for a US or Canadian version?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5f0109b5-e9f8-5537-d13d-5f3c6f9cb8cf
* Version Independent ID: 669e2224-0f43-e744-d313-ff1d72d4fff2
* Content: [Set Up Payment Terms (IT) - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/localfunctionality/italy/how-to-set-up-payment-terms)
* Content Source: [business-central/LocalFunctionality/Italy/how-to-set-up-payment-terms.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/LocalFunctionality/Italy/how-to-set-up-payment-terms.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello, 

We do have an article about payment terms in the US and CA versions. Here's a link to the US article:

https://learn.microsoft.com/en-us/dynamics365/business-central/finance-payment-terms

**Comment by buzzwick** [comment]
Fabulous. Thanks very much.
