### ISSUE TITLE
Falscher Link

### ISSUE THREAD

**Issue by ThomasBrockmann** [MicrosoftDocs/dynamics365smb-docs#805]
Die Suche in der Lupe nach "Geplante Prod. Aufträge" liefert keine Ergebnisse. Richtig wäre: "Geplante FA"

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er wird für die Verknüpfung von learn.microsoft.com zum GitHub-Issue benötigt.*

* ID: dfd52d34-7cf1-ebb9-ad9c-efcacac8bd09
* Version Independent ID: be48dc99-4575-83df-d542-206f2b526de3
* Content: [Fertigungsauftragsköpfe erstellen - Business Central](https://learn.microsoft.com/de-de/dynamics365/business-central/production-how-to-create-production-orders)
* Content Source: [business-central/production-how-to-create-production-orders.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/production-how-to-create-production-orders.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

Sorry that I can't reply in German, but I translated your question. I tested the steps in the article, and it seems to be correct. "Geplante Prod. Aufträge" translates to "Planned Prod. Orders," which is what the article mentions.
