### ISSUE TITLE
Updated Supported countries for the Pagero Extension BC E-invoicing

### ISSUE THREAD

**Issue by Menerback** [MicrosoftDocs/dynamics365smb-docs#806]
Hi, the supported countries of the Pagero extension have been updated, additions to the ones listed are: 

- Luxemburg
- Italy
- (Kingdom of) Saudi Arabia
- Belgium
- Singapore
- USA

Thank you! 

/Mattias Enerbäck
Pagero

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1001680f-3464-f355-903c-d753ce203d44
* Version Independent ID: 5dac4461-4875-e797-471b-ea7ee66b2b23
* Content: [Electronic invoicing FAQ - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/faq-electronic-invoicing)
* Content Source: [business-central/faq-electronic-invoicing.yml](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/faq-electronic-invoicing.yml)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04

**Comment by edupont04** [comment]
Thank you for your feedback! This will be fixed in the next doc update.
