### ISSUE TITLE
"Report Layout" doesn't exist

### ISSUE THREAD

**Issue by JMA1972** [MicrosoftDocs/dynamics365smb-docs#807]
[Enter feedback here]
The starting point of the documentation is the list "Report Layout" that doesn't exist in BC19 or BC20. Similar named lists don't have the actions mentioned here or don't have the full list of built-in layouts.
You should phrase exactly what the list is called and what version of Business Central do you refer to.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 359150dd-afe0-f05e-c2e0-970db6832ef0
* Version Independent ID: 359150dd-afe0-f05e-c2e0-970db6832ef0
* Content: [Get Started Creating Layouts - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/ui-get-started-layouts?tabs=copy)
* Content Source: [business-central/ui-get-started-layouts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-get-started-layouts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by brentholtorf** [comment]
Hello,

Thanks for the feedback, but I can't reproduce this issue. When I use TellMe (ALT+Q) to search for "Report Layouts," I can open the Report Layouts page and a list of layouts is available. For the product version, the docs are always based on the latest, so we don't do versioning.
