### ISSUE TITLE
What does Blocked "Payment" mean

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#810]
This document disucsses Blocked but there is another field called Payment

can this page get updated please?
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aea4ada6-bbd8-fbeb-5707-50988d0dbddf
* Version Independent ID: 7840c42d-efd6-eff9-6c74-53ebc8f23380
* Content: [How to Block Items from Sales or Purchasing - Business Central](https://learn.microsoft.com/en-au/dynamics365/business-central/inventory-how-block-items)
* Content Source: [business-central/inventory-how-block-items.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/inventory-how-block-items.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Hello,

There isn't a Payment field on items, however, you can block a vendor so that people can't make payments to them. Is that what you're looking for? If so, check out [Block Vendors](https://learn.microsoft.com/en-us/dynamics365/business-central/payables-how-block-vendors)
