### ISSUE TITLE
"See related Microsoft training" is of little value on this topic

### ISSUE THREAD

**Issue by lvanvugt** [MicrosoftDocs/dynamics365smb-docs#813]
"See related Microsoft training" is of little value on this topic as the MS lern topc behind does not discuss the use of Excel layout in reports.
My suggestion is to either remove the link or get MS learn updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 71cd93a1-9e26-530c-5d77-c5c58f423d15
* Version Independent ID: 71cd93a1-9e26-530c-5d77-c5c58f423d15
* Content: [Working with Excel Layouts - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/ui-excel-report-layouts?tabs=any-report&source=docs)
* Content Source: [business-central/ui-excel-report-layouts.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-excel-report-layouts.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by brentholtorf** [comment]
Hello,

Thanks for pointing this out. We'll remove the link from the article, but more importantly, we'll create a task for the Learning team to create a module that describes the functionality. I found [this learning path](https://learn.microsoft.com/training/paths/build-reports/), but it doesn't mention Excel layouts.

**Comment by lvanvugt** [comment]
Yep, found the same.
