### ISSUE TITLE
QBO import- This app no longer meets our guidelines and standards

### ISSUE THREAD

**Issue by KeithDownieErthos** [MicrosoftDocs/dynamics365smb-docs#815]
The connector is broken.  Intuit site says: This app no longer meets our guidelines and standards. It's no longer available and you can't connect to it. Reach out to the app developer for support.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b52fd22f-b904-40f3-85c6-46ece79ea03d
* Version Independent ID: 16f1126b-14a4-2815-98e4-52e7becc6c22
* Content: [QuickBooks Online Data Migration Extension - Business Central](https://learn.microsoft.com/en-gb/dynamics365/business-central/ui-extensions-quickbooks-online-data-migration)
* Content Source: [business-central/ui-extensions-quickbooks-online-data-migration.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-extensions-quickbooks-online-data-migration.md)
* Service: **dynamics365-business-central**
* GitHub Login: @brentholtorf
* Microsoft Alias: **bholtorf**

**Comment by brentholtorf** [comment]
I reached out to the dev team who owns the QuickBooks data migration features and fortunately they've already fixed the issue. Everything should be working fine now.
