### ISSUE TITLE
lacking explanation

### ISSUE THREAD

**Issue by joemarselo** [MicrosoftDocs/dynamics365smb-docs#82]
this section about consolidation is lack of explanation about elimination, as appear in:
https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/hh168815(v=nav.90)

Setting up Consolidation company:
https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/hh168815(v=nav.90)#setting-up-the-consolidation-company

Processing Consolidation Eliminations:
https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/hh168815(v=nav.90)#processing-consolidation-eliminations
After you have consolidated all the companies, you must make elimination entries to remove transactions that are recorded across more than one company or remove entries involving intercompany transactions.

To process consolidation eliminations

1. Manually calculate the eliminations.
2. Enter the amounts in a general journal.
3. Post the journal.

Before you post the eliminations, you can verify the effect on the trial balance of the consolidated company by using the G/L Consolidation Eliminations report. The report displays a tentative trial balance. It shows the consequences of eliminating the entries by comparing the entries in the consolidated company with the eliminations that have been entered in the general journal. Calculating the eliminations is a time-consuming manual process that may be aided by setting up specific intercompany accounts, intercompany customers/vendors, and intercompany posting groups.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4498087-0e7f-079a-c371-7543c7d771d7
* Version Independent ID: e6e5ffe6-3e2c-b821-2992-ac9b01b3ebc3
* Content: [Consolidate Data from Multiple Companies - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-consolidated-company-reporting)
* Content Source: [business-central/finance-consolidated-company-reporting.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-consolidated-company-reporting.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by SorenGP** [comment]
Thank you for the feedback. The topic has been updated with the "To eliminate repeated transactions" section.
