### ISSUE TITLE
Wrong Business Central page referenced

### ISSUE THREAD

**Issue by KevinRosendaal** [MicrosoftDocs/dynamics365smb-docs#820]
"(represented by the SEPA CAMT code on the **_Posting_** Exchange Definitions page)"

Most likely has to be "Data Exchange Definitions page".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6d3b6f57-f301-4ad2-a530-495bd59de8b1
* Version Independent ID: a862f3ef-6672-14b7-581f-131fdfa2088a
* Content: [Field Mapping When Importing SEPA CAMT Files - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/across-field-mapping-when-importing-sepa-camt-files)
* Content Source: [business-central/across-field-mapping-when-importing-sepa-camt-files.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/across-field-mapping-when-importing-sepa-camt-files.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by brentholtorf** [comment]
Nice catch, and thanks for reporting the issue. It should definitely be "Data Exchange Definitions." I've created a work item to update the article and we'll publish the correction soon.
