### ISSUE TITLE
Set up reusable email texts and layouts

### ISSUE THREAD

**Issue by JennReinhardt** [MicrosoftDocs/dynamics365smb-docs#822]
In the section "Set up reusable email texts and layouts" on this page number 6 says:

"To view or edit the layout that the email text is based on, select the layout on the Custom Report Layouts page, and then choose the Update Layout action."

That is incorrect, the Update Layout action doesn't allow you to view or edit the layout, all it does is updates the report to any changes that have incurred in the dataset.  Instead, the user should choose Export Layout. This will open the layout up in Word and allow edits to be made. The layout can then be imported to incorporate those changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0171dfbc-61f2-e62e-f4a3-bb641b15c3e2
* Version Independent ID: 51deab1e-0243-3178-7640-01bb91591fca
* Content: [Set up email in Business Central (contains video) - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/admin-how-setup-email)
* Content Source: [business-central/admin-how-setup-email.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/admin-how-setup-email.md)
* Service: **dynamics365-business-central**
![1](https://user-images.githubusercontent.com/22746878/207973414-778b6f5e-6fef-4753-8d5b-568660426479.png)

* GitHub Login: @brentholtorf
* Microsoft Alias: **bholtorf**

**Comment by brentholtorf** [comment]
Thanks for pointing this out. I've created a work item to update the article.
