### ISSUE TITLE
Incorrect Link

### ISSUE THREAD

**Issue by bbsparkrock** [MicrosoftDocs/dynamics365smb-docs#828]
The link to Manage Sessions in https://learn.microsoft.com/en-ca/dynamics365/business-central/admin-setup-and-administration and https://learn.microsoft.com/en-ca/dynamics365/business-central/admin-users-profiles-roles should link to: https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-manage-sessions

**Comment by brentholtorf** [comment]
Hello,

Thanks for pointing these out. I've created a work item to get them updated asap.
