### ISSUE TITLE
lacking explanation on Adjust Exchange Rates ... batch job

### ISSUE THREAD

**Issue by joemarselo** [MicrosoftDocs/dynamics365smb-docs#83]
this content is lacking explanation about Adjust Exchange Rates batch job - with 'Adjust G/L Account for Add.-Reporting Currency - checked.
as appear here: https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/hh167698%28v%3dnav.90%29

this content is lacking explanation about How to: Set Up the Additional Reporting Currency
https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/hh169189%28v%3dnav.90%29

About Using Additional Reporting Currencies: https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/hh168995%28v%3dnav.90%29

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91e359ab-a5f2-1fe6-1b91-a1a07244c9c8
* Version Independent ID: 02824859-6365-784b-e7d0-173b9e10553c
* Content: [Setting Up Additional Currencies - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-how-setup-additional-currencies)
* Content Source: [business-central/finance-how-setup-additional-currencies.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-how-setup-additional-currencies.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
This is now described in the "To activate the additional reporting currency" section in this topic: https://docs.microsoft.com/en-us/dynamics365/business-central/finance-how-setup-additional-currencies.
