### ISSUE TITLE
this content is lacking information about Adjust Add. Reporting Currency Batch Job

### ISSUE THREAD

**Issue by joemarselo** [MicrosoftDocs/dynamics365smb-docs#84]
as appear here:
Adjust Add. Reporting Currency Batch Job
https://docs.microsoft.com/en-us/previous-versions/dynamicsnav-2016/hh167698(v%3dnav.90)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cbd815c-4e94-b21d-dbfa-411885d4a5dd
* Version Independent ID: f4aced3d-7e1c-6486-f8dc-7749cc9ddd12
* Content: [Updating Currency Exchange Rates - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-how-update-currencies)
* Content Source: [business-central/finance-how-update-currencies.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-how-update-currencies.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
This new topic was added recently: https://docs.microsoft.com/en-us/dynamics365/business-central/finance-how-setup-additional-currencies

It can also be accessed by choosing the "Set Up an Additional Reporting Currency" link in the discussed topic.
