### ISSUE TITLE
Create addtional environment in your tenancy

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/dynamics365smb-docs#842]
can you please link to the article that how's partners how to create additional environments with deferent localisations?
Eg AU Tenancy hosts 2 environments, 1 is AU localistion and the other is W1

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 203baec6-0fa8-b294-a7ee-5b5a4c153fde
* Version Independent ID: 8f2c2fc3-f5e5-7c15-56c6-9a5fbc1a577a
* Content: [Local functionality and localization strategy - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/about-localization)
* Content Source: [business-central/about-localization.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/about-localization.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by jswymer** [comment]
Thanks for the feedback, We've added a link to [this article](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/tenant-admin-center-environments) about creating environments. We hope this helps. The update will be published soon.
