### ISSUE TITLE
The title of this page is incorrect

### ISSUE THREAD

**Issue by dirkree** [MicrosoftDocs/dynamics365smb-docs#85]
The title is "Set Up Multiple Interest Rates" but should be "Set Up Reverse Charges on VAT"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e7f2fb3-10db-763b-c1dd-e9d8e3ec0070
* Version Independent ID: c7cdf2cb-38fe-8eeb-d9fb-cfeb79acc5e6
* Content: [How to Set Up Reverse Charges on VAT - Business Central](https://review.docs.microsoft.com/en-us/dynamics365/business-central/localfunctionality/unitedkingdom/how-to-set-up-reverse-charges-on-vat)
* Content Source: [business-central/LocalFunctionality/UnitedKingdom/how-to-set-up-reverse-charges-on-vat.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/LocalFunctionality/UnitedKingdom/how-to-set-up-reverse-charges-on-vat.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hi Dirk,

Oops, you're right! It's actually had the wrong title for a very long time, but I'll get it fixed.
