### ISSUE TITLE
Update name of user group ...

### ISSUE THREAD

**Issue by grantbrimhall** [MicrosoftDocs/dynamics365smb-docs#850]
Please update this paragraph:

To install or uninstall apps from AppSource or add per-tenant apps, you must have the right permissions. You must either be a member of the EXTEND. MGT. - ADMIN user group or you must have the EXTEND. MGT. - ADMIN permission set.

>> the user group is D365 EXTENSION MGT.

Thx...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18ef22cd-6149-41b4-1743-df71dcb66d21
* Version Independent ID: a7c6922c-ccce-fb75-9ada-a4ff7def845c
* Content: [Install and Uninstall Apps - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/ui-extensions-install-uninstall)
* Content Source: [business-central/ui-extensions-install-uninstall.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ui-extensions-install-uninstall.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by brentholtorf** [comment]
Hello,

Thanks for pointing this out. We've corrected the name of the user group and will publish an update soon.
