### ISSUE TITLE
Incorrect instructions on Set Up Intercompany Transactions

### ISSUE THREAD

**Issue by alexwiley** [MicrosoftDocs/dynamics365smb-docs#851]
In the subsection "Set up the intercompany charts of accounts", it instructs to go to **Intercompany Setup** then "Choose the IC Chart of Accounts action." There is no action to navigate to the Intercompany Chart of Accounts from this page:

![IC_Setup](https://user-images.githubusercontent.com/39127479/231521466-c6c81191-983b-4e02-86f4-49fee38189cd.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c748d8ad-0f5e-126e-0555-b047af1e8c96
* Version Independent ID: beb88306-1c4e-3e69-cb6d-06d62ddd71a6
* Content: [Set Up Intercompany Transaction Posting - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/intercompany-how-setup#set-up-the-intercompany-charts-of-accounts)
* Content Source: [business-central/intercompany-how-setup.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/intercompany-how-setup.md)
* Service: **dynamics365-business-central**
* GitHub Login: @brentholtorf
* Microsoft Alias: **bholtorf**

**Comment by brentholtorf** [comment]
Hello,

I just verified that the button is available on the page, as the article describes. My guess is that your tenant hadn't been updated yet at the time you raised this issue. 

If the button still isn't available, check whether your tenant has been updated to the latest version of Business Central. If you have, consider contacting support.
