### ISSUE TITLE
Typo : Warejpise 

### ISSUE THREAD

**Issue by fvet** [MicrosoftDocs/dynamics365smb-docs#852]
The Movement Worksheet , Warehouse Internal Pick, and Warejpise Internal Put-away pages

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86d0ec80-99f3-35c5-1484-9b6ced2b0ec9
* Version Independent ID: 905989a9-0635-a944-ab7c-8244ce465e11
* Content: [Move Items in Warehouses That Use Directed Put-away and Pick - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/warehouse-how-to-move-items-in-advanced-warehousing)
* Content Source: [business-central/warehouse-how-to-move-items-in-advanced-warehousing.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/warehouse-how-to-move-items-in-advanced-warehousing.md)
* Service: **dynamics365-business-central**
* GitHub Login: @brentholtorf
* Microsoft Alias: **bholtorf**

**Comment by brentholtorf** [comment]
Hello,

Thanks for pointing this out. We've corrected the typo and will publish the updated article soon.
