### ISSUE TITLE
Notification Entry Type correction - "due data" should be "due date"

### ISSUE THREAD

**Issue by ian-scho** [MicrosoftDocs/dynamics365smb-docs#853]
The following:
"Notification Entry Type | Specify if the workflow notification is triggered by a record change, an approval request, or passed due data."
Should probably read as:
"Notification Entry Type | Specify if the workflow notification is triggered by a record change, an approval request, or passed due **date**."

Cheers, Ian

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cca7d126-fb60-435b-0e57-07e84be35c24
* Version Independent ID: 6b113e2a-c524-65b7-32c9-fc9b257a9ef2
* Content: [Create Approval Workflows to Connect Tasks - Business Central](https://learn.microsoft.com/en-gb/dynamics365/business-central/across-how-to-create-workflows)
* Content Source: [business-central/across-how-to-create-workflows.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/across-how-to-create-workflows.md)
* Service: **dynamics365-business-central**
* GitHub Login: @brentholtorf
* Microsoft Alias: **bholtorf**

**Comment by brentholtorf** [comment]
Hello,

Thanks for pointing this out. We've corrected the typo and will soon publish an update.
