### ISSUE TITLE
The word "Learn" more is misspelled 

### ISSUE THREAD

**Issue by Castanle** [MicrosoftDocs/dynamics365smb-docs#857]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84ddff91-f250-6168-265d-fbe6ffd41a5c
* Version Independent ID: e58801fd-14cc-77b5-4aaf-ccb7bbc9ff78
* Content: [Managing Inventory - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/inventory-manage-inventory)
* Content Source: [business-central/inventory-manage-inventory.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/inventory-manage-inventory.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **edupont**

**Comment by jswymer** [comment]
We've fixed the spelling. An update will be published soon. Thanks!
