### ISSUE TITLE
Typo: custeomer

### ISSUE THREAD

**Issue by abarberenaCPDS** [MicrosoftDocs/dynamics365smb-docs#861]
Bullted point should read, **customer**; punctuation also needs a simple fix.

> - You must be using Business Central online version 22 or later (if you're an existing custeomer) or a trial. .

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6b9c4b8c-845f-bde1-c4b6-f5eeabf2f23a
* Version Independent ID: 6b9c4b8c-845f-bde1-c4b6-f5eeabf2f23a
* Content: [AI-powered item marketing text (preview) with Copilot FAQ - Business Central](https://learn.microsoft.com/en-us/dynamics365/business-central/ai-faq?tabs=general)
* Content Source: [business-central/ai-faq.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/ai-faq.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by jswymer** [comment]
We've fixed the article. An update will be published soon. Thanks!
