### ISSUE TITLE
I don't think this is how the QuickBooks Payroll File Import Extension works

### ISSUE THREAD

**Issue by DaveBoehmPBSI** [MicrosoftDocs/dynamics365smb-docs#87]
I wish it actually worked as described on this page, but I don't believe it does.  The "QuickBooks Payroll File Import Extension" doesn't actually import anything from QuickBooks.  That's a real shame.  Actually, it allows you to import an "IFF" file of payroll G/L entries into BC in the same manner that you would import that file into QuickBooks.  As an example, if I use PayChex as my Payroll provider, I can export the result of my payments from PayChex to an IIF file.  This is the format used to import data into QuickBooks.  Instead of importing this IIF file into QuickBooks, I can use this extension to import that same IIF file into BC.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5eee77f4-8ea1-039c-86a4-8c083e4acd25
* Version Independent ID: 2a89fa84-9cf7-00ad-a543-9992ecd031ac
* Content: [Using the Quickbooks Payroll File Import Extension - Business Central](https://docs.microsoft.com/en-US/dynamics365/business-central/ui-extensions-quickbooks-payroll)
* Content Source: [business-central/ui-extensions-quickbooks-payroll.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-extensions-quickbooks-payroll.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **SorenGP**

**Comment by brentholtorf** [comment]
.IIF is the format that QuickBooks supports for data import and export, which is why this extension uses that format. After you export your payroll data from QuickBooks to a .IIF file, you can use the extension to import the file in Business Central.

**Comment by DaveBoehmPBSI** [comment]
I was never able to find a way to export my QuickBooks P/R data from QuickBooks.  Are you absolutely sure this can be done?

I remember having this discussion with Chris Bulson about 1 1/2 years ago.  When I couldn't find a way to export P/R data from QuickBooks, I asked him how this was to be done.  He indicated that the extension wasn't designed to import data that was exported from QuickBooks.  Instead, it was designed to import the same sort of IIF file that is typically exported from a third-party payroll provider.

Once again, are you sure you can export QuickBooks P/R data from QuickBooks?  Over the past 20 years, I've exported other sorts of data from QuickBooks, but I've never seen a P/R export capability.


--Dave--


David Boehm, CPA

PBSI

www.pbsisoftware.com<http://www.pbsisoftware.com/>

Bookings page: https://outlook.office365.com/owa/calendar/ProfessionalBusinessSoftwareInc@pbsisoftware.com/bookings/

Office: 817.752.3352<http://tel.:8177523352>

Cell: 214.392.4797<tel:214.392.4797>

***********************************************************

This communication, along with any documents, files or attachments, is intended only for the use of the addressee and may contain legally privileged and confidential information. If you are not the intended recipient, you are hereby notified that any dissemination, distribution or copying of any information contained in or attached to this communication is strictly prohibited. If you have received this message in error, please notify the sender immediately and destroy the original communication and its attachments without reading, printing or saving in any manner. Thank you.


________________________________

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback! Our apologies for the very long wait for an answer!

A member of our team has at long last reviewed your feedback. We defer to the QuickBooks docs to explain how to export from QuickBooks.
