### ISSUE TITLE
I'm having a problem trying to add a record to the output journals.

### ISSUE THREAD

**Issue by CRIS-117** [MicrosoftDocs/dynamics365smb-docs#883]
I have a problem creating an output journal record. In Dynamics 365 Business Central, I have no problem, but in the flow created in Power Automate I first got an error that was the following: "You can not insert item number 00256583 because it is not produced on released production order"
Then I saw that I had to add the "OrderType" field in my api, I add it but without filling the field and I get the following: "You cannot change Order No. when Order Type is ." When I saw the table in Dynamics, I saw that it had to have "Production" as the value. I add it in the flow in English, in Spanish and from the api and I get this error: "Production gets the error that Order Type is OnlyRead"
For the API I am using: AL Language extension for Microsoft Dynamics 365 Business Central.
<img width="947" alt="image" src="https://github.com/MicrosoftDocs/dynamics365smb-docs/assets/90110151/c97eca22-ab87-479a-8f25-6ba97cd7f900">
<img width="895" alt="image" src="https://github.com/MicrosoftDocs/dynamics365smb-docs/assets/90110151/9a352345-2f8a-426a-92c8-2c0388783d87">

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para learn.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: c9d77e62-2a31-9769-4dd1-eaf45dccee2d
* Version Independent ID: 0b2dcdcf-3ebf-c192-47fe-3b98c0c66f5e
* Content: [Recursos de ayuda y soporte técnico - Business Central](https://learn.microsoft.com/es-MX/dynamics365/business-central/product-help-and-support?wt.mc_id=d365bc_inproduct_helppane)
* Content Source: [business-central/product-help-and-support.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/main/business-central/product-help-and-support.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello,
Thank you for your feedback. Since your question is not about the Help, we suggest that you either ask the community at [Business Central forum](https://community.dynamics.com/forums/thread/?partialUrl=business) or contact [technical support](https://learn.microsoft.com/dynamics365/business-central/product-help-and-support#report-a-problem).
