### ISSUE TITLE
Missing detail

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-docs#89]
Documentation directs user to the Contact Card to create a new Contact. A note is made pointing out that certain information from "the company" may be copied to the Contact. At no point does the documentation describe how this Contact is associated with any Company. Presumably there would have to be an association between a Company and "persons within that company" in order for Inheritance information to be copied.  How is that association established for a new Person Contact?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac596c7b-491c-b518-d018-ab39d998a287
* Version Independent ID: fbca2993-1c03-b2b2-52e6-bbdd7e552cd0
* Content: [Create Contact Persons - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/marketing-create-contact-persons)
* Content Source: [business-central/marketing-create-contact-persons.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/marketing-create-contact-persons.md)
* Service: **dynamics365-business-central**
* GitHub Login: @jswymer
* Microsoft Alias: **jswymer**

**Comment by SorenGP** [comment]
Thank you for the feedback. Having two topics for contacts of type Person and Company respectively was unnecessary and confusing. The relationship between the two types is now explained clearly in this single topic: https://docs.microsoft.com/en-us/dynamics365/business-central/marketing-create-contact-companies
