### ISSUE TITLE
IC versus Intercompany

### ISSUE THREAD

**Issue by hldavids** [MicrosoftDocs/dynamics365smb-docs#9]
It appears in the latest release of business central that the objects have intercompany spelled out; therefore, if you do any of the above searches for IC you will get no results.

E.G.  IC Chart of Accounts is Intercompany Chart of Accounts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c748d8ad-0f5e-126e-0555-b047af1e8c96
* Version Independent ID: beb88306-1c4e-3e69-cb6d-06d62ddd71a6
* Content: [Set Up Intercompany Transaction Posting - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/intercompany-how-setup)
* Content Source: [business-central/intercompany-how-setup.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/intercompany-how-setup.md)
* Service: **dynamics365-business-central**
* Product: **unspecified**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by edupont04** [comment]
Thank you for catching this. We'll get this improved - and yes, fortunately our user interface strings are getting easier to understand :-)

**Comment by edupont04** [comment]
Fix ready for the weekly update on Monday.
