### ISSUE TITLE
Item Tracking in the Warehouse

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-docs#90]
The link https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-item-tracking-in-the-warehouse contains the exact same information as https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-item-tracking-availability
Do you have a specific topic covering WMS Tracking? (T6550, P6550, etc.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1a698ba-2728-420d-ce1d-518e6543ce41
* Version Independent ID: ad7063c6-a2c7-5e56-4423-e5bc8438ff1b
* Content: [Design Details - Item Tracking - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/design-details-item-tracking)
* Content Source: [business-central/design-details-item-tracking.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/design-details-item-tracking.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback. The topic has been updated and will be available within one week.
