### ISSUE TITLE
Is this ONLY for Azure Active Directory?

### ISSUE THREAD

**Issue by TormDK** [MicrosoftDocs/dynamics365smb-docs#92]
Hello team.

Just to confirm, you write this part; "The accountant's email address must be a work address that is based an Active Directory. If the accountant uses another type of email, then the invitation cannot be sent." - but what you mean is;

"The accountant's email address must be a work address that is based an Azure Active Directory. If the accountant uses another type of email, then the invitation cannot be sent.

Aka, the external accountant MUST have an Azure AD with an Exchange Online attached? The reason for the question is that SharePoint can invite Microsoft accounts as guest users, as can Teams.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff78214b-7557-66ed-e80e-4483fd784fc8
* Version Independent ID: b8b374d6-b93f-c09d-4ef8-2b44908123b8
* Content: [Add your external accountant to your Business Central - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-invite-external-accountant)
* Content Source: [business-central/finance-invite-external-accountant.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-invite-external-accountant.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by edupont04** [comment]
Hello TormDK,

Thanks for asking for clarification. Currently, the accountant's email must be Azure Active Directory so that it can be added to your Azure Active Directory and be assigned the External Accountant license. An update will be made to the content later today.
