### ISSUE TITLE
Small grammatical error

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-docs#93]
"By assigning as much data as possible about a specific company ensures efficient communication."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c7058a5-84a4-97e0-8bbd-cba40a0a2c88
* Version Independent ID: 2b299373-73fb-0d62-5cab-4044e15b4e60
* Content: [Create Contact Companies - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/marketing-create-contact-companies)
* Content Source: [business-central/marketing-create-contact-companies.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/marketing-create-contact-companies.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by SorenGP** [comment]
Fixed
