### ISSUE TITLE
Show me

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-docs#94]
I have spent the last several weeks trying to reverse-engineer the Contact and Contact Business Relation relationships, in order to bulk import Vendors and related Contacts. Reading through this page, I am struck by how difficult it is for a developer to visualize and understand the described relationships through description alone--largely because of the ambiguous and repetitive references. I now have mastered the actual relationships sufficiently to manage the bulk import, but the doc is still almost incomprehensible. I would strongly recommend that some simple diagrams be included, to illustrate exactly the relationships being referred to in any given section of the doc. Please.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c7058a5-84a4-97e0-8bbd-cba40a0a2c88
* Version Independent ID: 2b299373-73fb-0d62-5cab-4044e15b4e60
* Content: [Create Contact Companies - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/marketing-create-contact-companies)
* Content Source: [business-central/marketing-create-contact-companies.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/marketing-create-contact-companies.md)
* Service: **dynamics365-business-central**
* GitHub Login: @edupont04
* Microsoft Alias: **edupont**

**Comment by SorenGP** [comment]
Thank you for the feedback. 
This and surrounding topics have been simplified and restructured. It will be available within one week. 
For reasons related to the translation process, we cannot use illustrations in this help library.
