### ISSUE TITLE
Bin.Dedicated

### ISSUE THREAD

**Issue by Bleika** [MicrosoftDocs/dynamics365smb-docs#97]
Step 4 says "Fill in the fields as necessary. Hover over a field to read a short description."
Can you please explain the use for the new field (41) Dedicated? 
(It's not very clear from the ToolTip)
Thankyou

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82e1125d-38df-9d50-7054-95d0f2822266
* Version Independent ID: 722323c1-f3fc-4e5f-36bd-461fb0cfcbc7
* Content: [How to Create Bins - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/warehouse-how-to-create-individual-bins)
* Content Source: [business-central/warehouse-how-to-create-individual-bins.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/warehouse-how-to-create-individual-bins.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SorenGP
* Microsoft Alias: **sgroespe**

**Comment by SorenGP** [comment]
Thank you for the feedback. The topic has been updated and is now live.
