### ISSUE TITLE
Trying to add extended text to inventory item description

### ISSUE THREAD

**Issue by Deeptnt** [MicrosoftDocs/dynamics365smb-docs#98]
There is no "Extended Text action" to choose from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6b18849-5bc8-3415-274e-403072387bab
* Version Independent ID: cd9c8b7a-1c90-867e-b9e2-b8e03007fae6
* Content: [Add Extra Lines to Define Extended Item Descriptions - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/ui-how-define-ext-text)
* Content Source: [business-central/ui-how-define-ext-text.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/ui-how-define-ext-text.md)
* Service: **dynamics365-business-central**
* GitHub Login: @SusanneWindfeldPedersen
* Microsoft Alias: **solsen**

**Comment by SorenGP** [comment]
Thank you for the feedback. The topic has been updated and will be available within one week.
