### ISSUE TITLE
Confusing or incomplete

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/dynamics365smb-docs#99]
Customer Posting Groups
If Customer Posting Groups "Define the accounts to use when you post accounts receivable transactions", then why is there a reference to "If you use inventory with receivables, the general business posting group assigned to your customer, and the general product posting group assigned to the inventory item determine the accounts the sales order lines post to."?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae49cb5f-62a1-2c2c-455c-5062fb5f9ae1
* Version Independent ID: 9229c603-465e-a779-4b4b-1cd60cfb20b7
* Content: [Posting Group Setup - Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/finance-posting-groups)
* Content Source: [business-central/finance-posting-groups.md](https://github.com/MicrosoftDocs/dynamics365smb-docs/blob/live/business-central/finance-posting-groups.md)
* Service: **dynamics365-business-central**
* GitHub Login: @bholtorf
* Microsoft Alias: **bholtorf**

**Comment by SorenGP** [comment]
Thank you for the feedback. The paragraph has been updated as follows:
"Define the accounts to use when you post accounts receivable transactions. If you use inventory with receivables, the general business posting group assigned to your customer, and the general product posting group assigned to the inventory item determine the accounts that the sales order lines post to. See "General Business Posting Groups" and "General Product Posting Groups" under General Posting Groups above. Set these up on the Customer Posting Groups page."
The update will be available within one week.
